(define (problem problema1)

    (:domain SeriesPelisExt4)
    
    (:objects 
        divergente insurgente tmsc1 tmsc2 tmsc3 hola a1 monja a2 a3 conj adeu cmbyn mujercitas love_actually after buenas noches 
    )
    
    (:init
        (predecesor divergente insurgente)
        (predecesor tmsc1 tmsc2)
        (predecesor tmsc2 tmsc3)
        (paralela a1 a2)(paralela a2 a1)(paralela monja a1)(paralela monja a2)(paralela a1 monja)(paralela a2 monja)
        (predecesor a1 conj)
        (predecesor a2 conj)
        (predecesor a3 conj)
        (predecesor noches buenas)
        (predecesor monja conj)
        (paralela a1 a3)(paralela a2 a3)(paralela monja a3)(paralela a3 a1)(paralela a3 a2)(paralela a3 monja) 
        (paralela a1 buenas)(paralela a2 buenas)(paralela monja buenas)(paralela buenas a1)(paralela buenas a2)(paralela buenas monja) 
        (paralela a3 buenas)(paralela buenas a3)
        (no_paralela insurgente)
        (no_paralela divergente)
        (no_paralela tmsc1)
        (no_paralela tmsc2)
        (no_paralela tmsc3)
        (no_paralela hola)
        (no_paralela adeu)
        (no_paralela conj)
        (no_paralela love_actually)
        (no_paralela after)
        (no_paralela cmbyn)
        (no_paralela mujercitas)
        (no_paralela noches)
        (paralelas_ok)
		(= (minutos_vistos) 0)
		(= (minutos_contenido divergente) 139)
		(= (minutos_contenido insurgente) 140)
		(= (minutos_contenido tmsc1) 118)
		(= (minutos_contenido tmsc2) 120)
		(= (minutos_contenido tmsc3) 122)
		(= (minutos_contenido hola) 10)
		(= (minutos_contenido a1) 99)
		(= (minutos_contenido a2) 120)
		(= (minutos_contenido a3) 100)
		(= (minutos_contenido monja) 56)
		(= (minutos_contenido conj) 112)
		(= (minutos_contenido adeu) 12)
		(= (minutos_contenido cmbyn) 11)
		(= (minutos_contenido after) 132)
		(= (minutos_contenido mujercitas) 109)
		(= (minutos_contenido love_actually) 112)
		(= (minutos_contenido buenas) 23)
		(= (minutos_contenido noches) 114)
    )
    
    (:goal 
        (forall (?c) (visto ?c))
    )
)


