(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25
    )

    (:init
        (paralela contenido_6 contenido_15)
        (paralela contenido_15 contenido_6)
        (paralela contenido_6 contenido_17)
        (paralela contenido_17 contenido_6)
        (paralela contenido_6 contenido_1)
        (paralela contenido_1 contenido_6)
        (paralela contenido_15 contenido_17)
        (paralela contenido_17 contenido_15)
        (paralela contenido_15 contenido_1)
        (paralela contenido_1 contenido_15)
        (paralela contenido_17 contenido_1)
        (paralela contenido_1 contenido_17)
        (paralela contenido_16 contenido_13)
        (paralela contenido_13 contenido_16)
        (paralela contenido_16 contenido_9)
        (paralela contenido_9 contenido_16)
        (paralela contenido_16 contenido_7)
        (paralela contenido_7 contenido_16)
        (paralela contenido_13 contenido_9)
        (paralela contenido_9 contenido_13)
        (paralela contenido_13 contenido_7)
        (paralela contenido_7 contenido_13)
        (paralela contenido_9 contenido_7)
        (paralela contenido_7 contenido_9)
        (paralela contenido_5 contenido_25)
        (paralela contenido_25 contenido_5)
        (paralela contenido_5 contenido_20)
        (paralela contenido_20 contenido_5)
        (paralela contenido_5 contenido_11)
        (paralela contenido_11 contenido_5)
        (paralela contenido_25 contenido_20)
        (paralela contenido_20 contenido_25)
        (paralela contenido_25 contenido_11)
        (paralela contenido_11 contenido_25)
        (paralela contenido_20 contenido_11)
        (paralela contenido_11 contenido_20)
        (paralela contenido_21 contenido_22)
        (paralela contenido_22 contenido_21)
        (paralela contenido_21 contenido_23)
        (paralela contenido_23 contenido_21)
        (paralela contenido_21 contenido_12)
        (paralela contenido_12 contenido_21)
        (paralela contenido_22 contenido_23)
        (paralela contenido_23 contenido_22)
        (paralela contenido_22 contenido_12)
        (paralela contenido_12 contenido_22)
        (paralela contenido_23 contenido_12)
        (paralela contenido_12 contenido_23)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_19)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_6)
        (final contenido_2)
        (final contenido_3)
        (final contenido_4)
        (final contenido_8)
        (final contenido_10)
        (final contenido_14)
        (final contenido_18)
        (final contenido_19)
        (final contenido_24)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
