(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20
    )

    (:init
        (paralela contenido_9 contenido_13)
        (paralela contenido_13 contenido_9)
        (paralela contenido_9 contenido_14)
        (paralela contenido_14 contenido_9)
        (paralela contenido_9 contenido_1)
        (paralela contenido_1 contenido_9)
        (paralela contenido_13 contenido_14)
        (paralela contenido_14 contenido_13)
        (paralela contenido_13 contenido_1)
        (paralela contenido_1 contenido_13)
        (paralela contenido_14 contenido_1)
        (paralela contenido_1 contenido_14)
        (paralela contenido_11 contenido_19)
        (paralela contenido_19 contenido_11)
        (paralela contenido_11 contenido_3)
        (paralela contenido_3 contenido_11)
        (paralela contenido_11 contenido_8)
        (paralela contenido_8 contenido_11)
        (paralela contenido_19 contenido_3)
        (paralela contenido_3 contenido_19)
        (paralela contenido_19 contenido_8)
        (paralela contenido_8 contenido_19)
        (paralela contenido_3 contenido_8)
        (paralela contenido_8 contenido_3)
        (paralela contenido_10 contenido_12)
        (paralela contenido_12 contenido_10)
        (paralela contenido_10 contenido_6)
        (paralela contenido_6 contenido_10)
        (paralela contenido_10 contenido_5)
        (paralela contenido_5 contenido_10)
        (paralela contenido_12 contenido_6)
        (paralela contenido_6 contenido_12)
        (paralela contenido_12 contenido_5)
        (paralela contenido_5 contenido_12)
        (paralela contenido_6 contenido_5)
        (paralela contenido_5 contenido_6)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_16)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_4)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_8)
        (final contenido_2)
        (final contenido_4)
        (final contenido_7)
        (final contenido_15)
        (final contenido_16)
        (final contenido_17)
        (final contenido_18)
        (final contenido_20)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
