(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40
    )

    (:init
        (paralela contenido_36 contenido_29)
        (paralela contenido_29 contenido_36)
        (paralela contenido_36 contenido_4)
        (paralela contenido_4 contenido_36)
        (paralela contenido_36 contenido_24)
        (paralela contenido_24 contenido_36)
        (paralela contenido_29 contenido_4)
        (paralela contenido_4 contenido_29)
        (paralela contenido_29 contenido_24)
        (paralela contenido_24 contenido_29)
        (paralela contenido_4 contenido_24)
        (paralela contenido_24 contenido_4)
        (paralela contenido_21 contenido_10)
        (paralela contenido_10 contenido_21)
        (paralela contenido_21 contenido_39)
        (paralela contenido_39 contenido_21)
        (paralela contenido_21 contenido_32)
        (paralela contenido_32 contenido_21)
        (paralela contenido_10 contenido_39)
        (paralela contenido_39 contenido_10)
        (paralela contenido_10 contenido_32)
        (paralela contenido_32 contenido_10)
        (paralela contenido_39 contenido_32)
        (paralela contenido_32 contenido_39)
        (paralela contenido_6 contenido_13)
        (paralela contenido_13 contenido_6)
        (paralela contenido_6 contenido_8)
        (paralela contenido_8 contenido_6)
        (paralela contenido_6 contenido_40)
        (paralela contenido_40 contenido_6)
        (paralela contenido_13 contenido_8)
        (paralela contenido_8 contenido_13)
        (paralela contenido_13 contenido_40)
        (paralela contenido_40 contenido_13)
        (paralela contenido_8 contenido_40)
        (paralela contenido_40 contenido_8)
        (paralela contenido_2 contenido_30)
        (paralela contenido_30 contenido_2)
        (paralela contenido_2 contenido_28)
        (paralela contenido_28 contenido_2)
        (paralela contenido_2 contenido_22)
        (paralela contenido_22 contenido_2)
        (paralela contenido_30 contenido_28)
        (paralela contenido_28 contenido_30)
        (paralela contenido_30 contenido_22)
        (paralela contenido_22 contenido_30)
        (paralela contenido_28 contenido_22)
        (paralela contenido_22 contenido_28)
        (paralela contenido_25 contenido_3)
        (paralela contenido_3 contenido_25)
        (paralela contenido_25 contenido_5)
        (paralela contenido_5 contenido_25)
        (paralela contenido_25 contenido_27)
        (paralela contenido_27 contenido_25)
        (paralela contenido_3 contenido_5)
        (paralela contenido_5 contenido_3)
        (paralela contenido_3 contenido_27)
        (paralela contenido_27 contenido_3)
        (paralela contenido_5 contenido_27)
        (paralela contenido_27 contenido_5)
        (paralela contenido_35 contenido_23)
        (paralela contenido_23 contenido_35)
        (paralela contenido_35 contenido_18)
        (paralela contenido_18 contenido_35)
        (paralela contenido_35 contenido_33)
        (paralela contenido_33 contenido_35)
        (paralela contenido_23 contenido_18)
        (paralela contenido_18 contenido_23)
        (paralela contenido_23 contenido_33)
        (paralela contenido_33 contenido_23)
        (paralela contenido_18 contenido_33)
        (paralela contenido_33 contenido_18)
        (paralela contenido_37 contenido_7)
        (paralela contenido_7 contenido_37)
        (paralela contenido_37 contenido_15)
        (paralela contenido_15 contenido_37)
        (paralela contenido_37 contenido_31)
        (paralela contenido_31 contenido_37)
        (paralela contenido_7 contenido_15)
        (paralela contenido_15 contenido_7)
        (paralela contenido_7 contenido_31)
        (paralela contenido_31 contenido_7)
        (paralela contenido_15 contenido_31)
        (paralela contenido_31 contenido_15)
        (paralela contenido_12 contenido_11)
        (paralela contenido_11 contenido_12)
        (paralela contenido_12 contenido_38)
        (paralela contenido_38 contenido_12)
        (paralela contenido_12 contenido_34)
        (paralela contenido_34 contenido_12)
        (paralela contenido_11 contenido_38)
        (paralela contenido_38 contenido_11)
        (paralela contenido_11 contenido_34)
        (paralela contenido_34 contenido_11)
        (paralela contenido_38 contenido_34)
        (paralela contenido_34 contenido_38)
        (paralela contenido_19 contenido_26)
        (paralela contenido_26 contenido_19)
        (paralela contenido_19 contenido_9)
        (paralela contenido_9 contenido_19)
        (paralela contenido_19 contenido_17)
        (paralela contenido_17 contenido_19)
        (paralela contenido_26 contenido_9)
        (paralela contenido_9 contenido_26)
        (paralela contenido_26 contenido_17)
        (paralela contenido_17 contenido_26)
        (paralela contenido_9 contenido_17)
        (paralela contenido_17 contenido_9)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_16)
        (paralelas_vistas contenido_14)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_39)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_36)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_38)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_35)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_37)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_14)
        (final contenido_1)
        (final contenido_14)
        (final contenido_16)
        (final contenido_20)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
