(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125 contenido_126 contenido_127 contenido_128 contenido_129 contenido_130 contenido_131 contenido_132 contenido_133 contenido_134 contenido_135 contenido_136 contenido_137 contenido_138 contenido_139 contenido_140 contenido_141 contenido_142 contenido_143 contenido_144 contenido_145 contenido_146 contenido_147 contenido_148 contenido_149 contenido_150
    )

    (:init
        (paralela contenido_58 contenido_135)
        (paralela contenido_135 contenido_58)
        (paralela contenido_58 contenido_96)
        (paralela contenido_96 contenido_58)
        (paralela contenido_58 contenido_123)
        (paralela contenido_123 contenido_58)
        (paralela contenido_135 contenido_96)
        (paralela contenido_96 contenido_135)
        (paralela contenido_135 contenido_123)
        (paralela contenido_123 contenido_135)
        (paralela contenido_96 contenido_123)
        (paralela contenido_123 contenido_96)
        (paralela contenido_81 contenido_112)
        (paralela contenido_112 contenido_81)
        (paralela contenido_81 contenido_113)
        (paralela contenido_113 contenido_81)
        (paralela contenido_81 contenido_69)
        (paralela contenido_69 contenido_81)
        (paralela contenido_112 contenido_113)
        (paralela contenido_113 contenido_112)
        (paralela contenido_112 contenido_69)
        (paralela contenido_69 contenido_112)
        (paralela contenido_113 contenido_69)
        (paralela contenido_69 contenido_113)
        (paralela contenido_127 contenido_27)
        (paralela contenido_27 contenido_127)
        (paralela contenido_127 contenido_50)
        (paralela contenido_50 contenido_127)
        (paralela contenido_127 contenido_59)
        (paralela contenido_59 contenido_127)
        (paralela contenido_27 contenido_50)
        (paralela contenido_50 contenido_27)
        (paralela contenido_27 contenido_59)
        (paralela contenido_59 contenido_27)
        (paralela contenido_50 contenido_59)
        (paralela contenido_59 contenido_50)
        (paralela contenido_75 contenido_57)
        (paralela contenido_57 contenido_75)
        (paralela contenido_75 contenido_107)
        (paralela contenido_107 contenido_75)
        (paralela contenido_75 contenido_35)
        (paralela contenido_35 contenido_75)
        (paralela contenido_57 contenido_107)
        (paralela contenido_107 contenido_57)
        (paralela contenido_57 contenido_35)
        (paralela contenido_35 contenido_57)
        (paralela contenido_107 contenido_35)
        (paralela contenido_35 contenido_107)
        (paralela contenido_39 contenido_91)
        (paralela contenido_91 contenido_39)
        (paralela contenido_39 contenido_10)
        (paralela contenido_10 contenido_39)
        (paralela contenido_39 contenido_48)
        (paralela contenido_48 contenido_39)
        (paralela contenido_91 contenido_10)
        (paralela contenido_10 contenido_91)
        (paralela contenido_91 contenido_48)
        (paralela contenido_48 contenido_91)
        (paralela contenido_10 contenido_48)
        (paralela contenido_48 contenido_10)
        (paralela contenido_74 contenido_137)
        (paralela contenido_137 contenido_74)
        (paralela contenido_74 contenido_54)
        (paralela contenido_54 contenido_74)
        (paralela contenido_74 contenido_1)
        (paralela contenido_1 contenido_74)
        (paralela contenido_137 contenido_54)
        (paralela contenido_54 contenido_137)
        (paralela contenido_137 contenido_1)
        (paralela contenido_1 contenido_137)
        (paralela contenido_54 contenido_1)
        (paralela contenido_1 contenido_54)
        (paralela contenido_29 contenido_34)
        (paralela contenido_34 contenido_29)
        (paralela contenido_29 contenido_21)
        (paralela contenido_21 contenido_29)
        (paralela contenido_29 contenido_6)
        (paralela contenido_6 contenido_29)
        (paralela contenido_34 contenido_21)
        (paralela contenido_21 contenido_34)
        (paralela contenido_34 contenido_6)
        (paralela contenido_6 contenido_34)
        (paralela contenido_21 contenido_6)
        (paralela contenido_6 contenido_21)
        (paralela contenido_77 contenido_149)
        (paralela contenido_149 contenido_77)
        (paralela contenido_77 contenido_32)
        (paralela contenido_32 contenido_77)
        (paralela contenido_77 contenido_147)
        (paralela contenido_147 contenido_77)
        (paralela contenido_149 contenido_32)
        (paralela contenido_32 contenido_149)
        (paralela contenido_149 contenido_147)
        (paralela contenido_147 contenido_149)
        (paralela contenido_32 contenido_147)
        (paralela contenido_147 contenido_32)
        (paralela contenido_103 contenido_92)
        (paralela contenido_92 contenido_103)
        (paralela contenido_103 contenido_14)
        (paralela contenido_14 contenido_103)
        (paralela contenido_103 contenido_56)
        (paralela contenido_56 contenido_103)
        (paralela contenido_92 contenido_14)
        (paralela contenido_14 contenido_92)
        (paralela contenido_92 contenido_56)
        (paralela contenido_56 contenido_92)
        (paralela contenido_14 contenido_56)
        (paralela contenido_56 contenido_14)
        (paralela contenido_118 contenido_83)
        (paralela contenido_83 contenido_118)
        (paralela contenido_118 contenido_98)
        (paralela contenido_98 contenido_118)
        (paralela contenido_118 contenido_115)
        (paralela contenido_115 contenido_118)
        (paralela contenido_83 contenido_98)
        (paralela contenido_98 contenido_83)
        (paralela contenido_83 contenido_115)
        (paralela contenido_115 contenido_83)
        (paralela contenido_98 contenido_115)
        (paralela contenido_115 contenido_98)
        (paralela contenido_105 contenido_138)
        (paralela contenido_138 contenido_105)
        (paralela contenido_105 contenido_16)
        (paralela contenido_16 contenido_105)
        (paralela contenido_105 contenido_134)
        (paralela contenido_134 contenido_105)
        (paralela contenido_138 contenido_16)
        (paralela contenido_16 contenido_138)
        (paralela contenido_138 contenido_134)
        (paralela contenido_134 contenido_138)
        (paralela contenido_16 contenido_134)
        (paralela contenido_134 contenido_16)
        (paralela contenido_43 contenido_64)
        (paralela contenido_64 contenido_43)
        (paralela contenido_43 contenido_80)
        (paralela contenido_80 contenido_43)
        (paralela contenido_43 contenido_150)
        (paralela contenido_150 contenido_43)
        (paralela contenido_64 contenido_80)
        (paralela contenido_80 contenido_64)
        (paralela contenido_64 contenido_150)
        (paralela contenido_150 contenido_64)
        (paralela contenido_80 contenido_150)
        (paralela contenido_150 contenido_80)
        (paralela contenido_124 contenido_40)
        (paralela contenido_40 contenido_124)
        (paralela contenido_124 contenido_28)
        (paralela contenido_28 contenido_124)
        (paralela contenido_124 contenido_100)
        (paralela contenido_100 contenido_124)
        (paralela contenido_40 contenido_28)
        (paralela contenido_28 contenido_40)
        (paralela contenido_40 contenido_100)
        (paralela contenido_100 contenido_40)
        (paralela contenido_28 contenido_100)
        (paralela contenido_100 contenido_28)
        (paralela contenido_110 contenido_126)
        (paralela contenido_126 contenido_110)
        (paralela contenido_110 contenido_125)
        (paralela contenido_125 contenido_110)
        (paralela contenido_110 contenido_2)
        (paralela contenido_2 contenido_110)
        (paralela contenido_126 contenido_125)
        (paralela contenido_125 contenido_126)
        (paralela contenido_126 contenido_2)
        (paralela contenido_2 contenido_126)
        (paralela contenido_125 contenido_2)
        (paralela contenido_2 contenido_125)
        (paralela contenido_61 contenido_44)
        (paralela contenido_44 contenido_61)
        (paralela contenido_61 contenido_41)
        (paralela contenido_41 contenido_61)
        (paralela contenido_61 contenido_84)
        (paralela contenido_84 contenido_61)
        (paralela contenido_44 contenido_41)
        (paralela contenido_41 contenido_44)
        (paralela contenido_44 contenido_84)
        (paralela contenido_84 contenido_44)
        (paralela contenido_41 contenido_84)
        (paralela contenido_84 contenido_41)
        (paralela contenido_82 contenido_146)
        (paralela contenido_146 contenido_82)
        (paralela contenido_82 contenido_9)
        (paralela contenido_9 contenido_82)
        (paralela contenido_82 contenido_114)
        (paralela contenido_114 contenido_82)
        (paralela contenido_146 contenido_9)
        (paralela contenido_9 contenido_146)
        (paralela contenido_146 contenido_114)
        (paralela contenido_114 contenido_146)
        (paralela contenido_9 contenido_114)
        (paralela contenido_114 contenido_9)
        (paralela contenido_129 contenido_132)
        (paralela contenido_132 contenido_129)
        (paralela contenido_129 contenido_17)
        (paralela contenido_17 contenido_129)
        (paralela contenido_129 contenido_63)
        (paralela contenido_63 contenido_129)
        (paralela contenido_132 contenido_17)
        (paralela contenido_17 contenido_132)
        (paralela contenido_132 contenido_63)
        (paralela contenido_63 contenido_132)
        (paralela contenido_17 contenido_63)
        (paralela contenido_63 contenido_17)
        (paralela contenido_22 contenido_87)
        (paralela contenido_87 contenido_22)
        (paralela contenido_22 contenido_89)
        (paralela contenido_89 contenido_22)
        (paralela contenido_22 contenido_121)
        (paralela contenido_121 contenido_22)
        (paralela contenido_87 contenido_89)
        (paralela contenido_89 contenido_87)
        (paralela contenido_87 contenido_121)
        (paralela contenido_121 contenido_87)
        (paralela contenido_89 contenido_121)
        (paralela contenido_121 contenido_89)
        (paralela contenido_122 contenido_106)
        (paralela contenido_106 contenido_122)
        (paralela contenido_122 contenido_76)
        (paralela contenido_76 contenido_122)
        (paralela contenido_122 contenido_26)
        (paralela contenido_26 contenido_122)
        (paralela contenido_106 contenido_76)
        (paralela contenido_76 contenido_106)
        (paralela contenido_106 contenido_26)
        (paralela contenido_26 contenido_106)
        (paralela contenido_76 contenido_26)
        (paralela contenido_26 contenido_76)
        (paralela contenido_67 contenido_7)
        (paralela contenido_7 contenido_67)
        (paralela contenido_67 contenido_31)
        (paralela contenido_31 contenido_67)
        (paralela contenido_67 contenido_13)
        (paralela contenido_13 contenido_67)
        (paralela contenido_7 contenido_31)
        (paralela contenido_31 contenido_7)
        (paralela contenido_7 contenido_13)
        (paralela contenido_13 contenido_7)
        (paralela contenido_31 contenido_13)
        (paralela contenido_13 contenido_31)
        (paralela contenido_78 contenido_30)
        (paralela contenido_30 contenido_78)
        (paralela contenido_78 contenido_90)
        (paralela contenido_90 contenido_78)
        (paralela contenido_78 contenido_45)
        (paralela contenido_45 contenido_78)
        (paralela contenido_30 contenido_90)
        (paralela contenido_90 contenido_30)
        (paralela contenido_30 contenido_45)
        (paralela contenido_45 contenido_30)
        (paralela contenido_90 contenido_45)
        (paralela contenido_45 contenido_90)
        (paralela contenido_97 contenido_37)
        (paralela contenido_37 contenido_97)
        (paralela contenido_97 contenido_111)
        (paralela contenido_111 contenido_97)
        (paralela contenido_97 contenido_70)
        (paralela contenido_70 contenido_97)
        (paralela contenido_37 contenido_111)
        (paralela contenido_111 contenido_37)
        (paralela contenido_37 contenido_70)
        (paralela contenido_70 contenido_37)
        (paralela contenido_111 contenido_70)
        (paralela contenido_70 contenido_111)
        (paralela contenido_94 contenido_33)
        (paralela contenido_33 contenido_94)
        (paralela contenido_94 contenido_55)
        (paralela contenido_55 contenido_94)
        (paralela contenido_94 contenido_104)
        (paralela contenido_104 contenido_94)
        (paralela contenido_33 contenido_55)
        (paralela contenido_55 contenido_33)
        (paralela contenido_33 contenido_104)
        (paralela contenido_104 contenido_33)
        (paralela contenido_55 contenido_104)
        (paralela contenido_104 contenido_55)
        (paralela contenido_3 contenido_19)
        (paralela contenido_19 contenido_3)
        (paralela contenido_3 contenido_11)
        (paralela contenido_11 contenido_3)
        (paralela contenido_3 contenido_42)
        (paralela contenido_42 contenido_3)
        (paralela contenido_19 contenido_11)
        (paralela contenido_11 contenido_19)
        (paralela contenido_19 contenido_42)
        (paralela contenido_42 contenido_19)
        (paralela contenido_11 contenido_42)
        (paralela contenido_42 contenido_11)
        (paralela contenido_145 contenido_25)
        (paralela contenido_25 contenido_145)
        (paralela contenido_145 contenido_140)
        (paralela contenido_140 contenido_145)
        (paralela contenido_145 contenido_65)
        (paralela contenido_65 contenido_145)
        (paralela contenido_25 contenido_140)
        (paralela contenido_140 contenido_25)
        (paralela contenido_25 contenido_65)
        (paralela contenido_65 contenido_25)
        (paralela contenido_140 contenido_65)
        (paralela contenido_65 contenido_140)
        (paralela contenido_128 contenido_18)
        (paralela contenido_18 contenido_128)
        (paralela contenido_128 contenido_49)
        (paralela contenido_49 contenido_128)
        (paralela contenido_128 contenido_93)
        (paralela contenido_93 contenido_128)
        (paralela contenido_18 contenido_49)
        (paralela contenido_49 contenido_18)
        (paralela contenido_18 contenido_93)
        (paralela contenido_93 contenido_18)
        (paralela contenido_49 contenido_93)
        (paralela contenido_93 contenido_49)
        (paralela contenido_46 contenido_143)
        (paralela contenido_143 contenido_46)
        (paralela contenido_46 contenido_144)
        (paralela contenido_144 contenido_46)
        (paralela contenido_46 contenido_36)
        (paralela contenido_36 contenido_46)
        (paralela contenido_143 contenido_144)
        (paralela contenido_144 contenido_143)
        (paralela contenido_143 contenido_36)
        (paralela contenido_36 contenido_143)
        (paralela contenido_144 contenido_36)
        (paralela contenido_36 contenido_144)
        (paralela contenido_72 contenido_142)
        (paralela contenido_142 contenido_72)
        (paralela contenido_72 contenido_51)
        (paralela contenido_51 contenido_72)
        (paralela contenido_72 contenido_148)
        (paralela contenido_148 contenido_72)
        (paralela contenido_142 contenido_51)
        (paralela contenido_51 contenido_142)
        (paralela contenido_142 contenido_148)
        (paralela contenido_148 contenido_142)
        (paralela contenido_51 contenido_148)
        (paralela contenido_148 contenido_51)
        (paralela contenido_73 contenido_141)
        (paralela contenido_141 contenido_73)
        (paralela contenido_73 contenido_12)
        (paralela contenido_12 contenido_73)
        (paralela contenido_73 contenido_66)
        (paralela contenido_66 contenido_73)
        (paralela contenido_141 contenido_12)
        (paralela contenido_12 contenido_141)
        (paralela contenido_141 contenido_66)
        (paralela contenido_66 contenido_141)
        (paralela contenido_12 contenido_66)
        (paralela contenido_66 contenido_12)
        (paralela contenido_53 contenido_8)
        (paralela contenido_8 contenido_53)
        (paralela contenido_53 contenido_99)
        (paralela contenido_99 contenido_53)
        (paralela contenido_53 contenido_23)
        (paralela contenido_23 contenido_53)
        (paralela contenido_8 contenido_99)
        (paralela contenido_99 contenido_8)
        (paralela contenido_8 contenido_23)
        (paralela contenido_23 contenido_8)
        (paralela contenido_99 contenido_23)
        (paralela contenido_23 contenido_99)
        (paralela contenido_116 contenido_130)
        (paralela contenido_130 contenido_116)
        (paralela contenido_116 contenido_71)
        (paralela contenido_71 contenido_116)
        (paralela contenido_116 contenido_136)
        (paralela contenido_136 contenido_116)
        (paralela contenido_130 contenido_71)
        (paralela contenido_71 contenido_130)
        (paralela contenido_130 contenido_136)
        (paralela contenido_136 contenido_130)
        (paralela contenido_71 contenido_136)
        (paralela contenido_136 contenido_71)
        (paralela contenido_88 contenido_117)
        (paralela contenido_117 contenido_88)
        (paralela contenido_88 contenido_85)
        (paralela contenido_85 contenido_88)
        (paralela contenido_88 contenido_131)
        (paralela contenido_131 contenido_88)
        (paralela contenido_117 contenido_85)
        (paralela contenido_85 contenido_117)
        (paralela contenido_117 contenido_131)
        (paralela contenido_131 contenido_117)
        (paralela contenido_85 contenido_131)
        (paralela contenido_131 contenido_85)
        (paralela contenido_119 contenido_120)
        (paralela contenido_120 contenido_119)
        (paralela contenido_119 contenido_47)
        (paralela contenido_47 contenido_119)
        (paralela contenido_119 contenido_79)
        (paralela contenido_79 contenido_119)
        (paralela contenido_120 contenido_47)
        (paralela contenido_47 contenido_120)
        (paralela contenido_120 contenido_79)
        (paralela contenido_79 contenido_120)
        (paralela contenido_47 contenido_79)
        (paralela contenido_79 contenido_47)
        (paralela contenido_15 contenido_20)
        (paralela contenido_20 contenido_15)
        (paralela contenido_15 contenido_139)
        (paralela contenido_139 contenido_15)
        (paralela contenido_15 contenido_133)
        (paralela contenido_133 contenido_15)
        (paralela contenido_20 contenido_139)
        (paralela contenido_139 contenido_20)
        (paralela contenido_20 contenido_133)
        (paralela contenido_133 contenido_20)
        (paralela contenido_139 contenido_133)
        (paralela contenido_133 contenido_139)
        (paralela contenido_68 contenido_86)
        (paralela contenido_86 contenido_68)
        (paralela contenido_68 contenido_38)
        (paralela contenido_38 contenido_68)
        (paralela contenido_68 contenido_62)
        (paralela contenido_62 contenido_68)
        (paralela contenido_86 contenido_38)
        (paralela contenido_38 contenido_86)
        (paralela contenido_86 contenido_62)
        (paralela contenido_62 contenido_86)
        (paralela contenido_38 contenido_62)
        (paralela contenido_62 contenido_38)
        (paralela contenido_4 contenido_60)
        (paralela contenido_60 contenido_4)
        (paralela contenido_4 contenido_52)
        (paralela contenido_52 contenido_4)
        (paralela contenido_4 contenido_24)
        (paralela contenido_24 contenido_4)
        (paralela contenido_60 contenido_52)
        (paralela contenido_52 contenido_60)
        (paralela contenido_60 contenido_24)
        (paralela contenido_24 contenido_60)
        (paralela contenido_52 contenido_24)
        (paralela contenido_24 contenido_52)
        (paralela contenido_108 contenido_101)
        (paralela contenido_101 contenido_108)
        (paralela contenido_108 contenido_109)
        (paralela contenido_109 contenido_108)
        (paralela contenido_108 contenido_5)
        (paralela contenido_5 contenido_108)
        (paralela contenido_101 contenido_109)
        (paralela contenido_109 contenido_101)
        (paralela contenido_101 contenido_5)
        (paralela contenido_5 contenido_101)
        (paralela contenido_109 contenido_5)
        (paralela contenido_5 contenido_109)
        (paralela contenido_102 contenido_95)
        (paralela contenido_95 contenido_102)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_96)
        (predecesores_vistos contenido_101)
        (predecesores_vistos contenido_150)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_119)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_50)
        (predecesores_vistos contenido_81)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_52)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_47)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_41)
        (predecesores_vistos contenido_76)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_54)
        (predecesores_vistos contenido_112)
        (predecesores_vistos contenido_123)
        (predecesores_vistos contenido_84)
        (predecesores_vistos contenido_45)
        (predecesores_vistos contenido_114)
        (predecesores_vistos contenido_113)
        (predecesores_vistos contenido_136)
        (predecesores_vistos contenido_135)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_35)
        (predecesores_vistos contenido_73)
        (predecesores_vistos contenido_144)
        (predecesores_vistos contenido_51)
        (predecesores_vistos contenido_99)
        (predecesores_vistos contenido_110)
        (predecesores_vistos contenido_87)
        (predecesores_vistos contenido_91)
        (predecesores_vistos contenido_140)
        (predecesores_vistos contenido_38)
        (predecesores_vistos contenido_134)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_36)
        (predecesores_vistos contenido_107)
        (predecesores_vistos contenido_121)
        (predecesores_vistos contenido_138)
        (predecesores_vistos contenido_147)
        (predecesores_vistos contenido_139)
        (predecesores_vistos contenido_71)
        (predecesores_vistos contenido_105)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_120)
        (predecesores_vistos contenido_78)
        (predecesores_vistos contenido_39)
        (predecesores_vistos contenido_118)
        (predecesores_vistos contenido_53)
        (predecesores_vistos contenido_132)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_143)
        (predecesores_vistos contenido_46)
        (predecesores_vistos contenido_109)
        (predecesores_vistos contenido_115)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_127)
        (predecesores_vistos contenido_66)
        (predecesores_vistos contenido_100)
        (predecesores_vistos contenido_117)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_68)
        (predecesores_vistos contenido_79)
        (predecesores_vistos contenido_131)
        (predecesores_vistos contenido_55)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_67)
        (predecesores_vistos contenido_137)
        (predecesores_vistos contenido_104)
        (predecesores_vistos contenido_61)
        (predecesores_vistos contenido_65)
        (predecesores_vistos contenido_122)
        (predecesores_vistos contenido_83)
        (predecesores_vistos contenido_77)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_108)
        (predecesores_vistos contenido_43)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_93)
        (predecesores_vistos contenido_116)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_69)
        (predecesores_vistos contenido_149)
        (predecesores_vistos contenido_59)
        (predecesores_vistos contenido_92)
        (predecesores_vistos contenido_94)
        (predecesores_vistos contenido_125)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_64)
        (predecesores_vistos contenido_124)
        (predecesores_vistos contenido_142)
        (predecesores_vistos contenido_49)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_70)
        (predecesores_vistos contenido_56)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_37)
        (predecesores_vistos contenido_146)
        (predecesores_vistos contenido_58)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_60)
        (predecesores_vistos contenido_95)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_106)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_97)
        (predecesores_vistos contenido_148)
        (predecesores_vistos contenido_86)
        (predecesores_vistos contenido_80)
        (predecesores_vistos contenido_141)
        (predecesores_vistos contenido_89)
        (predecesores_vistos contenido_129)
        (predecesores_vistos contenido_82)
        (predecesores_vistos contenido_102)
        (predecesores_vistos contenido_62)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_57)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_90)
        (predecesores_vistos contenido_103)
        (predecesores_vistos contenido_88)
        (predecesores_vistos contenido_75)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_133)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_126)
        (predecesores_vistos contenido_128)
        (predecesores_vistos contenido_85)
        (predecesores_vistos contenido_98)
        (predecesores_vistos contenido_74)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_130)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_111)
        (predecesores_vistos contenido_145)
        (predecesores_vistos contenido_18)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
