(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32
    )

    (:init
        (paralela contenido_23 contenido_2)
        (paralela contenido_2 contenido_23)
        (paralela contenido_23 contenido_6)
        (paralela contenido_6 contenido_23)
        (paralela contenido_23 contenido_3)
        (paralela contenido_3 contenido_23)
        (paralela contenido_2 contenido_6)
        (paralela contenido_6 contenido_2)
        (paralela contenido_2 contenido_3)
        (paralela contenido_3 contenido_2)
        (paralela contenido_6 contenido_3)
        (paralela contenido_3 contenido_6)
        (paralela contenido_22 contenido_27)
        (paralela contenido_27 contenido_22)
        (paralela contenido_22 contenido_30)
        (paralela contenido_30 contenido_22)
        (paralela contenido_22 contenido_5)
        (paralela contenido_5 contenido_22)
        (paralela contenido_27 contenido_30)
        (paralela contenido_30 contenido_27)
        (paralela contenido_27 contenido_5)
        (paralela contenido_5 contenido_27)
        (paralela contenido_30 contenido_5)
        (paralela contenido_5 contenido_30)
        (paralela contenido_9 contenido_1)
        (paralela contenido_1 contenido_9)
        (paralela contenido_9 contenido_12)
        (paralela contenido_12 contenido_9)
        (paralela contenido_9 contenido_14)
        (paralela contenido_14 contenido_9)
        (paralela contenido_1 contenido_12)
        (paralela contenido_12 contenido_1)
        (paralela contenido_1 contenido_14)
        (paralela contenido_14 contenido_1)
        (paralela contenido_12 contenido_14)
        (paralela contenido_14 contenido_12)
        (paralela contenido_19 contenido_8)
        (paralela contenido_8 contenido_19)
        (paralela contenido_19 contenido_29)
        (paralela contenido_29 contenido_19)
        (paralela contenido_19 contenido_25)
        (paralela contenido_25 contenido_19)
        (paralela contenido_8 contenido_29)
        (paralela contenido_29 contenido_8)
        (paralela contenido_8 contenido_25)
        (paralela contenido_25 contenido_8)
        (paralela contenido_29 contenido_25)
        (paralela contenido_25 contenido_29)
        (paralela contenido_21 contenido_26)
        (paralela contenido_26 contenido_21)
        (paralela contenido_21 contenido_31)
        (paralela contenido_31 contenido_21)
        (paralela contenido_21 contenido_16)
        (paralela contenido_16 contenido_21)
        (paralela contenido_26 contenido_31)
        (paralela contenido_31 contenido_26)
        (paralela contenido_26 contenido_16)
        (paralela contenido_16 contenido_26)
        (paralela contenido_31 contenido_16)
        (paralela contenido_16 contenido_31)
        (paralela contenido_20 contenido_28)
        (paralela contenido_28 contenido_20)
        (paralela contenido_20 contenido_32)
        (paralela contenido_32 contenido_20)
        (paralela contenido_20 contenido_13)
        (paralela contenido_13 contenido_20)
        (paralela contenido_28 contenido_32)
        (paralela contenido_32 contenido_28)
        (paralela contenido_28 contenido_13)
        (paralela contenido_13 contenido_28)
        (paralela contenido_32 contenido_13)
        (paralela contenido_13 contenido_32)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_11)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_15)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_15)
        (final contenido_4)
        (final contenido_7)
        (final contenido_10)
        (final contenido_11)
        (final contenido_15)
        (final contenido_17)
        (final contenido_18)
        (final contenido_24)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
