(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30
    )

    (:init
        (paralela contenido_10 contenido_5)
        (paralela contenido_5 contenido_10)
        (paralela contenido_10 contenido_20)
        (paralela contenido_20 contenido_10)
        (paralela contenido_10 contenido_25)
        (paralela contenido_25 contenido_10)
        (paralela contenido_5 contenido_20)
        (paralela contenido_20 contenido_5)
        (paralela contenido_5 contenido_25)
        (paralela contenido_25 contenido_5)
        (paralela contenido_20 contenido_25)
        (paralela contenido_25 contenido_20)
        (paralela contenido_22 contenido_15)
        (paralela contenido_15 contenido_22)
        (paralela contenido_22 contenido_30)
        (paralela contenido_30 contenido_22)
        (paralela contenido_22 contenido_16)
        (paralela contenido_16 contenido_22)
        (paralela contenido_15 contenido_30)
        (paralela contenido_30 contenido_15)
        (paralela contenido_15 contenido_16)
        (paralela contenido_16 contenido_15)
        (paralela contenido_30 contenido_16)
        (paralela contenido_16 contenido_30)
        (paralela contenido_12 contenido_17)
        (paralela contenido_17 contenido_12)
        (paralela contenido_12 contenido_13)
        (paralela contenido_13 contenido_12)
        (paralela contenido_12 contenido_8)
        (paralela contenido_8 contenido_12)
        (paralela contenido_17 contenido_13)
        (paralela contenido_13 contenido_17)
        (paralela contenido_17 contenido_8)
        (paralela contenido_8 contenido_17)
        (paralela contenido_13 contenido_8)
        (paralela contenido_8 contenido_13)
        (paralela contenido_19 contenido_1)
        (paralela contenido_1 contenido_19)
        (paralela contenido_19 contenido_4)
        (paralela contenido_4 contenido_19)
        (paralela contenido_19 contenido_7)
        (paralela contenido_7 contenido_19)
        (paralela contenido_1 contenido_4)
        (paralela contenido_4 contenido_1)
        (paralela contenido_1 contenido_7)
        (paralela contenido_7 contenido_1)
        (paralela contenido_4 contenido_7)
        (paralela contenido_7 contenido_4)
        (paralela contenido_29 contenido_11)
        (paralela contenido_11 contenido_29)
        (paralela contenido_29 contenido_2)
        (paralela contenido_2 contenido_29)
        (paralela contenido_29 contenido_18)
        (paralela contenido_18 contenido_29)
        (paralela contenido_11 contenido_2)
        (paralela contenido_2 contenido_11)
        (paralela contenido_11 contenido_18)
        (paralela contenido_18 contenido_11)
        (paralela contenido_2 contenido_18)
        (paralela contenido_18 contenido_2)
        (paralelas_vistas contenido_27)
        (paralelas_vistas contenido_9)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_28)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_26)
        (paralelas_vistas contenido_6)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_15)
        (final contenido_3)
        (final contenido_6)
        (final contenido_9)
        (final contenido_14)
        (final contenido_21)
        (final contenido_23)
        (final contenido_24)
        (final contenido_26)
        (final contenido_27)
        (final contenido_28)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
