(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80
    )

    (:init
        (paralela contenido_55 contenido_68)
        (paralela contenido_68 contenido_55)
        (paralela contenido_55 contenido_49)
        (paralela contenido_49 contenido_55)
        (paralela contenido_55 contenido_6)
        (paralela contenido_6 contenido_55)
        (paralela contenido_68 contenido_49)
        (paralela contenido_49 contenido_68)
        (paralela contenido_68 contenido_6)
        (paralela contenido_6 contenido_68)
        (paralela contenido_49 contenido_6)
        (paralela contenido_6 contenido_49)
        (paralela contenido_44 contenido_32)
        (paralela contenido_32 contenido_44)
        (paralela contenido_44 contenido_45)
        (paralela contenido_45 contenido_44)
        (paralela contenido_44 contenido_73)
        (paralela contenido_73 contenido_44)
        (paralela contenido_32 contenido_45)
        (paralela contenido_45 contenido_32)
        (paralela contenido_32 contenido_73)
        (paralela contenido_73 contenido_32)
        (paralela contenido_45 contenido_73)
        (paralela contenido_73 contenido_45)
        (paralela contenido_15 contenido_52)
        (paralela contenido_52 contenido_15)
        (paralela contenido_15 contenido_69)
        (paralela contenido_69 contenido_15)
        (paralela contenido_15 contenido_65)
        (paralela contenido_65 contenido_15)
        (paralela contenido_52 contenido_69)
        (paralela contenido_69 contenido_52)
        (paralela contenido_52 contenido_65)
        (paralela contenido_65 contenido_52)
        (paralela contenido_69 contenido_65)
        (paralela contenido_65 contenido_69)
        (paralela contenido_25 contenido_5)
        (paralela contenido_5 contenido_25)
        (paralela contenido_25 contenido_40)
        (paralela contenido_40 contenido_25)
        (paralela contenido_25 contenido_50)
        (paralela contenido_50 contenido_25)
        (paralela contenido_5 contenido_40)
        (paralela contenido_40 contenido_5)
        (paralela contenido_5 contenido_50)
        (paralela contenido_50 contenido_5)
        (paralela contenido_40 contenido_50)
        (paralela contenido_50 contenido_40)
        (paralela contenido_21 contenido_79)
        (paralela contenido_79 contenido_21)
        (paralela contenido_21 contenido_61)
        (paralela contenido_61 contenido_21)
        (paralela contenido_21 contenido_42)
        (paralela contenido_42 contenido_21)
        (paralela contenido_79 contenido_61)
        (paralela contenido_61 contenido_79)
        (paralela contenido_79 contenido_42)
        (paralela contenido_42 contenido_79)
        (paralela contenido_61 contenido_42)
        (paralela contenido_42 contenido_61)
        (paralela contenido_29 contenido_30)
        (paralela contenido_30 contenido_29)
        (paralela contenido_29 contenido_28)
        (paralela contenido_28 contenido_29)
        (paralela contenido_29 contenido_60)
        (paralela contenido_60 contenido_29)
        (paralela contenido_30 contenido_28)
        (paralela contenido_28 contenido_30)
        (paralela contenido_30 contenido_60)
        (paralela contenido_60 contenido_30)
        (paralela contenido_28 contenido_60)
        (paralela contenido_60 contenido_28)
        (paralela contenido_56 contenido_77)
        (paralela contenido_77 contenido_56)
        (paralela contenido_56 contenido_74)
        (paralela contenido_74 contenido_56)
        (paralela contenido_56 contenido_58)
        (paralela contenido_58 contenido_56)
        (paralela contenido_77 contenido_74)
        (paralela contenido_74 contenido_77)
        (paralela contenido_77 contenido_58)
        (paralela contenido_58 contenido_77)
        (paralela contenido_74 contenido_58)
        (paralela contenido_58 contenido_74)
        (paralela contenido_57 contenido_43)
        (paralela contenido_43 contenido_57)
        (paralela contenido_57 contenido_1)
        (paralela contenido_1 contenido_57)
        (paralela contenido_57 contenido_17)
        (paralela contenido_17 contenido_57)
        (paralela contenido_43 contenido_1)
        (paralela contenido_1 contenido_43)
        (paralela contenido_43 contenido_17)
        (paralela contenido_17 contenido_43)
        (paralela contenido_1 contenido_17)
        (paralela contenido_17 contenido_1)
        (paralela contenido_54 contenido_59)
        (paralela contenido_59 contenido_54)
        (paralela contenido_54 contenido_76)
        (paralela contenido_76 contenido_54)
        (paralela contenido_54 contenido_11)
        (paralela contenido_11 contenido_54)
        (paralela contenido_59 contenido_76)
        (paralela contenido_76 contenido_59)
        (paralela contenido_59 contenido_11)
        (paralela contenido_11 contenido_59)
        (paralela contenido_76 contenido_11)
        (paralela contenido_11 contenido_76)
        (paralela contenido_64 contenido_70)
        (paralela contenido_70 contenido_64)
        (paralela contenido_64 contenido_9)
        (paralela contenido_9 contenido_64)
        (paralela contenido_64 contenido_24)
        (paralela contenido_24 contenido_64)
        (paralela contenido_70 contenido_9)
        (paralela contenido_9 contenido_70)
        (paralela contenido_70 contenido_24)
        (paralela contenido_24 contenido_70)
        (paralela contenido_9 contenido_24)
        (paralela contenido_24 contenido_9)
        (paralela contenido_46 contenido_22)
        (paralela contenido_22 contenido_46)
        (paralela contenido_46 contenido_47)
        (paralela contenido_47 contenido_46)
        (paralela contenido_46 contenido_8)
        (paralela contenido_8 contenido_46)
        (paralela contenido_22 contenido_47)
        (paralela contenido_47 contenido_22)
        (paralela contenido_22 contenido_8)
        (paralela contenido_8 contenido_22)
        (paralela contenido_47 contenido_8)
        (paralela contenido_8 contenido_47)
        (paralela contenido_66 contenido_2)
        (paralela contenido_2 contenido_66)
        (paralela contenido_66 contenido_26)
        (paralela contenido_26 contenido_66)
        (paralela contenido_66 contenido_3)
        (paralela contenido_3 contenido_66)
        (paralela contenido_2 contenido_26)
        (paralela contenido_26 contenido_2)
        (paralela contenido_2 contenido_3)
        (paralela contenido_3 contenido_2)
        (paralela contenido_26 contenido_3)
        (paralela contenido_3 contenido_26)
        (paralela contenido_75 contenido_20)
        (paralela contenido_20 contenido_75)
        (paralela contenido_75 contenido_78)
        (paralela contenido_78 contenido_75)
        (paralela contenido_75 contenido_37)
        (paralela contenido_37 contenido_75)
        (paralela contenido_20 contenido_78)
        (paralela contenido_78 contenido_20)
        (paralela contenido_20 contenido_37)
        (paralela contenido_37 contenido_20)
        (paralela contenido_78 contenido_37)
        (paralela contenido_37 contenido_78)
        (paralela contenido_34 contenido_63)
        (paralela contenido_63 contenido_34)
        (paralela contenido_34 contenido_67)
        (paralela contenido_67 contenido_34)
        (paralela contenido_34 contenido_4)
        (paralela contenido_4 contenido_34)
        (paralela contenido_63 contenido_67)
        (paralela contenido_67 contenido_63)
        (paralela contenido_63 contenido_4)
        (paralela contenido_4 contenido_63)
        (paralela contenido_67 contenido_4)
        (paralela contenido_4 contenido_67)
        (paralela contenido_7 contenido_51)
        (paralela contenido_51 contenido_7)
        (paralela contenido_7 contenido_72)
        (paralela contenido_72 contenido_7)
        (paralela contenido_7 contenido_10)
        (paralela contenido_10 contenido_7)
        (paralela contenido_51 contenido_72)
        (paralela contenido_72 contenido_51)
        (paralela contenido_51 contenido_10)
        (paralela contenido_10 contenido_51)
        (paralela contenido_72 contenido_10)
        (paralela contenido_10 contenido_72)
        (paralela contenido_31 contenido_80)
        (paralela contenido_80 contenido_31)
        (paralela contenido_31 contenido_41)
        (paralela contenido_41 contenido_31)
        (paralela contenido_31 contenido_18)
        (paralela contenido_18 contenido_31)
        (paralela contenido_80 contenido_41)
        (paralela contenido_41 contenido_80)
        (paralela contenido_80 contenido_18)
        (paralela contenido_18 contenido_80)
        (paralela contenido_41 contenido_18)
        (paralela contenido_18 contenido_41)
        (paralela contenido_53 contenido_27)
        (paralela contenido_27 contenido_53)
        (paralela contenido_53 contenido_14)
        (paralela contenido_14 contenido_53)
        (paralela contenido_53 contenido_16)
        (paralela contenido_16 contenido_53)
        (paralela contenido_27 contenido_14)
        (paralela contenido_14 contenido_27)
        (paralela contenido_27 contenido_16)
        (paralela contenido_16 contenido_27)
        (paralela contenido_14 contenido_16)
        (paralela contenido_16 contenido_14)
        (paralela contenido_38 contenido_39)
        (paralela contenido_39 contenido_38)
        (paralela contenido_38 contenido_12)
        (paralela contenido_12 contenido_38)
        (paralela contenido_38 contenido_62)
        (paralela contenido_62 contenido_38)
        (paralela contenido_39 contenido_12)
        (paralela contenido_12 contenido_39)
        (paralela contenido_39 contenido_62)
        (paralela contenido_62 contenido_39)
        (paralela contenido_12 contenido_62)
        (paralela contenido_62 contenido_12)
        (paralela contenido_35 contenido_19)
        (paralela contenido_19 contenido_35)
        (paralela contenido_35 contenido_36)
        (paralela contenido_36 contenido_35)
        (paralela contenido_35 contenido_13)
        (paralela contenido_13 contenido_35)
        (paralela contenido_19 contenido_36)
        (paralela contenido_36 contenido_19)
        (paralela contenido_19 contenido_13)
        (paralela contenido_13 contenido_19)
        (paralela contenido_36 contenido_13)
        (paralela contenido_13 contenido_36)
        (paralela contenido_23 contenido_33)
        (paralela contenido_33 contenido_23)
        (paralela contenido_23 contenido_48)
        (paralela contenido_48 contenido_23)
        (paralela contenido_23 contenido_71)
        (paralela contenido_71 contenido_23)
        (paralela contenido_33 contenido_48)
        (paralela contenido_48 contenido_33)
        (paralela contenido_33 contenido_71)
        (paralela contenido_71 contenido_33)
        (paralela contenido_48 contenido_71)
        (paralela contenido_71 contenido_48)
        (predecesores_vistos contenido_49)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_78)
        (predecesores_vistos contenido_69)
        (predecesores_vistos contenido_65)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_75)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_77)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_45)
        (predecesores_vistos contenido_43)
        (predecesores_vistos contenido_68)
        (predecesores_vistos contenido_73)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_54)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_79)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_51)
        (predecesores_vistos contenido_56)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_38)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_61)
        (predecesores_vistos contenido_41)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_66)
        (predecesores_vistos contenido_52)
        (predecesores_vistos contenido_64)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_53)
        (predecesores_vistos contenido_46)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_47)
        (predecesores_vistos contenido_60)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_67)
        (predecesores_vistos contenido_57)
        (predecesores_vistos contenido_62)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_58)
        (predecesores_vistos contenido_37)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_36)
        (predecesores_vistos contenido_55)
        (predecesores_vistos contenido_59)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_39)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_74)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_76)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_70)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_80)
        (predecesores_vistos contenido_50)
        (predecesores_vistos contenido_71)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_35)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
