(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15
    )

    (:init
        (paralela contenido_5 contenido_6)
        (paralela contenido_6 contenido_5)
        (paralela contenido_5 contenido_4)
        (paralela contenido_4 contenido_5)
        (paralela contenido_5 contenido_9)
        (paralela contenido_9 contenido_5)
        (paralela contenido_6 contenido_4)
        (paralela contenido_4 contenido_6)
        (paralela contenido_6 contenido_9)
        (paralela contenido_9 contenido_6)
        (paralela contenido_4 contenido_9)
        (paralela contenido_9 contenido_4)
        (paralela contenido_11 contenido_10)
        (paralela contenido_10 contenido_11)
        (paralela contenido_11 contenido_12)
        (paralela contenido_12 contenido_11)
        (paralela contenido_11 contenido_13)
        (paralela contenido_13 contenido_11)
        (paralela contenido_10 contenido_12)
        (paralela contenido_12 contenido_10)
        (paralela contenido_10 contenido_13)
        (paralela contenido_13 contenido_10)
        (paralela contenido_12 contenido_13)
        (paralela contenido_13 contenido_12)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_14)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_13)
        (final contenido_1)
        (final contenido_2)
        (final contenido_3)
        (final contenido_7)
        (final contenido_8)
        (final contenido_14)
        (final contenido_15)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
