(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37
    )

    (:init
        (paralela contenido_17 contenido_27)
        (paralela contenido_27 contenido_17)
        (paralela contenido_17 contenido_14)
        (paralela contenido_14 contenido_17)
        (paralela contenido_17 contenido_25)
        (paralela contenido_25 contenido_17)
        (paralela contenido_27 contenido_14)
        (paralela contenido_14 contenido_27)
        (paralela contenido_27 contenido_25)
        (paralela contenido_25 contenido_27)
        (paralela contenido_14 contenido_25)
        (paralela contenido_25 contenido_14)
        (paralela contenido_13 contenido_7)
        (paralela contenido_7 contenido_13)
        (paralela contenido_13 contenido_16)
        (paralela contenido_16 contenido_13)
        (paralela contenido_13 contenido_9)
        (paralela contenido_9 contenido_13)
        (paralela contenido_7 contenido_16)
        (paralela contenido_16 contenido_7)
        (paralela contenido_7 contenido_9)
        (paralela contenido_9 contenido_7)
        (paralela contenido_16 contenido_9)
        (paralela contenido_9 contenido_16)
        (paralela contenido_19 contenido_2)
        (paralela contenido_2 contenido_19)
        (paralela contenido_19 contenido_35)
        (paralela contenido_35 contenido_19)
        (paralela contenido_19 contenido_1)
        (paralela contenido_1 contenido_19)
        (paralela contenido_2 contenido_35)
        (paralela contenido_35 contenido_2)
        (paralela contenido_2 contenido_1)
        (paralela contenido_1 contenido_2)
        (paralela contenido_35 contenido_1)
        (paralela contenido_1 contenido_35)
        (paralela contenido_29 contenido_37)
        (paralela contenido_37 contenido_29)
        (paralela contenido_29 contenido_5)
        (paralela contenido_5 contenido_29)
        (paralela contenido_29 contenido_8)
        (paralela contenido_8 contenido_29)
        (paralela contenido_37 contenido_5)
        (paralela contenido_5 contenido_37)
        (paralela contenido_37 contenido_8)
        (paralela contenido_8 contenido_37)
        (paralela contenido_5 contenido_8)
        (paralela contenido_8 contenido_5)
        (paralela contenido_24 contenido_30)
        (paralela contenido_30 contenido_24)
        (paralela contenido_24 contenido_21)
        (paralela contenido_21 contenido_24)
        (paralela contenido_24 contenido_11)
        (paralela contenido_11 contenido_24)
        (paralela contenido_30 contenido_21)
        (paralela contenido_21 contenido_30)
        (paralela contenido_30 contenido_11)
        (paralela contenido_11 contenido_30)
        (paralela contenido_21 contenido_11)
        (paralela contenido_11 contenido_21)
        (paralela contenido_23 contenido_36)
        (paralela contenido_36 contenido_23)
        (paralela contenido_23 contenido_15)
        (paralela contenido_15 contenido_23)
        (paralela contenido_23 contenido_3)
        (paralela contenido_3 contenido_23)
        (paralela contenido_36 contenido_15)
        (paralela contenido_15 contenido_36)
        (paralela contenido_36 contenido_3)
        (paralela contenido_3 contenido_36)
        (paralela contenido_15 contenido_3)
        (paralela contenido_3 contenido_15)
        (paralela contenido_4 contenido_31)
        (paralela contenido_31 contenido_4)
        (paralela contenido_4 contenido_32)
        (paralela contenido_32 contenido_4)
        (paralela contenido_4 contenido_34)
        (paralela contenido_34 contenido_4)
        (paralela contenido_31 contenido_32)
        (paralela contenido_32 contenido_31)
        (paralela contenido_31 contenido_34)
        (paralela contenido_34 contenido_31)
        (paralela contenido_32 contenido_34)
        (paralela contenido_34 contenido_32)
        (paralela contenido_26 contenido_28)
        (paralela contenido_28 contenido_26)
        (paralela contenido_26 contenido_22)
        (paralela contenido_22 contenido_26)
        (paralela contenido_26 contenido_18)
        (paralela contenido_18 contenido_26)
        (paralela contenido_28 contenido_22)
        (paralela contenido_22 contenido_28)
        (paralela contenido_28 contenido_18)
        (paralela contenido_18 contenido_28)
        (paralela contenido_22 contenido_18)
        (paralela contenido_18 contenido_22)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_6)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_37)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_35)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_36)
        (predecesores_vistos contenido_28)
        (final contenido_6)
        (final contenido_10)
        (final contenido_12)
        (final contenido_20)
        (final contenido_33)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
