(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125 contenido_126 contenido_127 contenido_128 contenido_129 contenido_130 contenido_131 contenido_132 contenido_133 contenido_134 contenido_135 contenido_136 contenido_137 contenido_138 contenido_139 contenido_140 contenido_141 contenido_142 contenido_143 contenido_144 contenido_145 contenido_146 contenido_147 contenido_148 contenido_149 contenido_150 contenido_151 contenido_152 contenido_153 contenido_154 contenido_155 contenido_156 contenido_157 contenido_158 contenido_159 contenido_160 contenido_161 contenido_162 contenido_163 contenido_164 contenido_165 contenido_166 contenido_167 contenido_168 contenido_169 contenido_170 contenido_171 contenido_172 contenido_173 contenido_174 contenido_175 contenido_176 contenido_177 contenido_178 contenido_179 contenido_180 contenido_181 contenido_182 contenido_183 contenido_184 contenido_185 contenido_186 contenido_187 contenido_188 contenido_189 contenido_190 contenido_191 contenido_192 contenido_193 contenido_194 contenido_195 contenido_196 contenido_197 contenido_198 contenido_199 contenido_200
    )

    (:init
        (predecesor contenido_44 contenido_107)
        (predecesor contenido_69 contenido_113)
        (predecesor contenido_71 contenido_87)
        (predecesor contenido_38 contenido_168)
        (predecesor contenido_128 contenido_188)
        (predecesor contenido_83 contenido_187)
        (predecesor contenido_45 contenido_144)
        (predecesor contenido_44 contenido_86)
        (predecesor contenido_40 contenido_127)
        (predecesor contenido_35 contenido_117)
        (predecesor contenido_2 contenido_154)
        (predecesor contenido_23 contenido_173)
        (predecesor contenido_49 contenido_100)
        (predecesor contenido_93 contenido_172)
        (predecesor contenido_145 contenido_147)
        (predecesor contenido_91 contenido_142)
        (predecesor contenido_15 contenido_39)
        (predecesor contenido_27 contenido_114)
        (predecesor contenido_23 contenido_197)
        (predecesor contenido_27 contenido_140)
        (predecesor contenido_98 contenido_138)
        (predecesor contenido_53 contenido_156)
        (predecesor contenido_65 contenido_73)
        (predecesor contenido_66 contenido_91)
        (predecesor contenido_4 contenido_102)
        (predecesor contenido_50 contenido_78)
        (predecesor contenido_16 contenido_146)
        (predecesor contenido_32 contenido_118)
        (predecesor contenido_18 contenido_76)
        (predecesor contenido_15 contenido_195)
        (predecesor contenido_91 contenido_182)
        (predecesor contenido_69 contenido_145)
        (predecesor contenido_48 contenido_78)
        (predecesor contenido_9 contenido_26)
        (predecesor contenido_3 contenido_106)
        (predecesor contenido_13 contenido_47)
        (predecesor contenido_8 contenido_41)
        (predecesor contenido_10 contenido_63)
        (predecesor contenido_101 contenido_105)
        (predecesor contenido_157 contenido_163)
        (predecesor contenido_68 contenido_121)
        (predecesor contenido_87 contenido_144)
        (predecesor contenido_120 contenido_147)
        (predecesor contenido_127 contenido_188)
        (predecesor contenido_15 contenido_141)
        (predecesor contenido_58 contenido_107)
        (predecesor contenido_5 contenido_49)
        (predecesor contenido_22 contenido_88)
        (predecesor contenido_117 contenido_172)
        (predecesor contenido_127 contenido_196)
        (predecesor contenido_17 contenido_131)
        (predecesor contenido_34 contenido_123)
        (predecesor contenido_70 contenido_130)
        (predecesor contenido_35 contenido_50)
        (predecesor contenido_101 contenido_144)
        (predecesor contenido_14 contenido_69)
        (predecesor contenido_2 contenido_42)
        (predecesor contenido_60 contenido_140)
        (predecesor contenido_37 contenido_84)
        (predecesor contenido_28 contenido_159)
        (predecesor contenido_162 contenido_185)
        (predecesor contenido_28 contenido_33)
        (predecesor contenido_1 contenido_112)
        (predecesor contenido_22 contenido_125)
        (predecesor contenido_61 contenido_191)
        (predecesor contenido_18 contenido_163)
        (predecesor contenido_119 contenido_130)
        (predecesor contenido_129 contenido_155)
        (predecesor contenido_58 contenido_73)
        (predecesor contenido_10 contenido_197)
        (predecesor contenido_110 contenido_170)
        (predecesor contenido_29 contenido_73)
        (predecesor contenido_55 contenido_62)
        (predecesor contenido_121 contenido_139)
        (predecesor contenido_11 contenido_64)
        (predecesor contenido_87 contenido_142)
        (predecesor contenido_52 contenido_170)
        (predecesor contenido_8 contenido_66)
        (predecesor contenido_50 contenido_134)
        (predecesor contenido_35 contenido_137)
        (predecesor contenido_129 contenido_148)
        (predecesor contenido_112 contenido_163)
        (predecesor contenido_36 contenido_122)
        (predecesor contenido_40 contenido_138)
        (predecesor contenido_4 contenido_91)
        (predecesor contenido_17 contenido_184)
        (predecesor contenido_152 contenido_171)
        (predecesor contenido_52 contenido_195)
        (predecesor contenido_111 contenido_195)
        (predecesor contenido_5 contenido_50)
        (predecesor contenido_88 contenido_129)
        (predecesor contenido_47 contenido_186)
        (predecesor contenido_23 contenido_85)
        (predecesor contenido_102 contenido_199)
        (predecesor contenido_22 contenido_200)
        (predecesor contenido_69 contenido_135)
        (predecesor contenido_79 contenido_88)
        (predecesor contenido_59 contenido_104)
        (predecesor contenido_6 contenido_90)
        (predecesor contenido_35 contenido_172)
        (predecesor contenido_35 contenido_124)
        (predecesor contenido_3 contenido_75)
        (predecesor contenido_93 contenido_118)
        (predecesor contenido_32 contenido_68)
        (predecesor contenido_38 contenido_57)
        (predecesor contenido_21 contenido_161)
        (predecesor contenido_116 contenido_190)
        (predecesor contenido_75 contenido_111)
        (predecesor contenido_12 contenido_24)
        (predecesor contenido_84 contenido_189)
        (predecesor contenido_17 contenido_29)
        (predecesor contenido_100 contenido_147)
        (predecesor contenido_51 contenido_130)
        (predecesor contenido_58 contenido_146)
        (predecesor contenido_74 contenido_181)
        (predecesor contenido_40 contenido_120)
        (predecesor contenido_110 contenido_199)
        (predecesor contenido_86 contenido_180)
        (predecesor contenido_43 contenido_196)
        (predecesor contenido_4 contenido_128)
        (predecesor contenido_57 contenido_131)
        (predecesor contenido_114 contenido_134)
        (predecesor contenido_164 contenido_171)
        (predecesor contenido_28 contenido_131)
        (predecesor contenido_92 contenido_109)
        (predecesor contenido_19 contenido_140)
        (predecesor contenido_88 contenido_193)
        (predecesor contenido_81 contenido_188)
        (predecesor contenido_96 contenido_172)
        (predecesor contenido_20 contenido_128)
        (predecesor contenido_11 contenido_92)
        (predecesor contenido_84 contenido_172)
        (predecesor contenido_86 contenido_107)
        (predecesor contenido_88 contenido_179)
        (predecesor contenido_12 contenido_156)
        (predecesor contenido_42 contenido_108)
        (predecesor contenido_154 contenido_199)
        (predecesor contenido_134 contenido_172)
        (predecesor contenido_30 contenido_119)
        (predecesor contenido_11 contenido_74)
        (paralela contenido_21 contenido_169)
        (paralela contenido_169 contenido_21)
        (paralela contenido_21 contenido_11)
        (paralela contenido_11 contenido_21)
        (paralela contenido_21 contenido_93)
        (paralela contenido_93 contenido_21)
        (paralela contenido_169 contenido_11)
        (paralela contenido_11 contenido_169)
        (paralela contenido_169 contenido_93)
        (paralela contenido_93 contenido_169)
        (paralela contenido_11 contenido_93)
        (paralela contenido_93 contenido_11)
        (= (minutos_contenido contenido_21) 149)
        (= (minutos_contenido contenido_169) 51)
        (= (minutos_contenido contenido_11) 109)
        (= (minutos_contenido contenido_93) 16)
        (paralela contenido_16 contenido_40)
        (paralela contenido_40 contenido_16)
        (paralela contenido_16 contenido_157)
        (paralela contenido_157 contenido_16)
        (paralela contenido_16 contenido_12)
        (paralela contenido_12 contenido_16)
        (paralela contenido_40 contenido_157)
        (paralela contenido_157 contenido_40)
        (paralela contenido_40 contenido_12)
        (paralela contenido_12 contenido_40)
        (paralela contenido_157 contenido_12)
        (paralela contenido_12 contenido_157)
        (= (minutos_contenido contenido_16) 57)
        (= (minutos_contenido contenido_40) 35)
        (= (minutos_contenido contenido_157) 44)
        (= (minutos_contenido contenido_12) 192)
        (paralela contenido_54 contenido_174)
        (paralela contenido_174 contenido_54)
        (paralela contenido_54 contenido_82)
        (paralela contenido_82 contenido_54)
        (paralela contenido_54 contenido_94)
        (paralela contenido_94 contenido_54)
        (paralela contenido_174 contenido_82)
        (paralela contenido_82 contenido_174)
        (paralela contenido_174 contenido_94)
        (paralela contenido_94 contenido_174)
        (paralela contenido_82 contenido_94)
        (paralela contenido_94 contenido_82)
        (= (minutos_contenido contenido_54) 164)
        (= (minutos_contenido contenido_174) 35)
        (= (minutos_contenido contenido_82) 79)
        (= (minutos_contenido contenido_94) 41)
        (paralela contenido_136 contenido_65)
        (paralela contenido_65 contenido_136)
        (paralela contenido_136 contenido_166)
        (paralela contenido_166 contenido_136)
        (paralela contenido_136 contenido_133)
        (paralela contenido_133 contenido_136)
        (paralela contenido_65 contenido_166)
        (paralela contenido_166 contenido_65)
        (paralela contenido_65 contenido_133)
        (paralela contenido_133 contenido_65)
        (paralela contenido_166 contenido_133)
        (paralela contenido_133 contenido_166)
        (= (minutos_contenido contenido_136) 28)
        (= (minutos_contenido contenido_65) 102)
        (= (minutos_contenido contenido_166) 24)
        (= (minutos_contenido contenido_133) 75)
        (paralela contenido_183 contenido_132)
        (paralela contenido_132 contenido_183)
        (paralela contenido_183 contenido_95)
        (paralela contenido_95 contenido_183)
        (paralela contenido_183 contenido_116)
        (paralela contenido_116 contenido_183)
        (paralela contenido_132 contenido_95)
        (paralela contenido_95 contenido_132)
        (paralela contenido_132 contenido_116)
        (paralela contenido_116 contenido_132)
        (paralela contenido_95 contenido_116)
        (paralela contenido_116 contenido_95)
        (= (minutos_contenido contenido_183) 102)
        (= (minutos_contenido contenido_132) 43)
        (= (minutos_contenido contenido_95) 74)
        (= (minutos_contenido contenido_116) 115)
        (paralela contenido_96 contenido_43)
        (paralela contenido_43 contenido_96)
        (paralela contenido_96 contenido_58)
        (paralela contenido_58 contenido_96)
        (paralela contenido_96 contenido_17)
        (paralela contenido_17 contenido_96)
        (paralela contenido_43 contenido_58)
        (paralela contenido_58 contenido_43)
        (paralela contenido_43 contenido_17)
        (paralela contenido_17 contenido_43)
        (paralela contenido_58 contenido_17)
        (paralela contenido_17 contenido_58)
        (= (minutos_contenido contenido_96) 11)
        (= (minutos_contenido contenido_43) 33)
        (= (minutos_contenido contenido_58) 38)
        (= (minutos_contenido contenido_17) 168)
        (paralela contenido_30 contenido_28)
        (paralela contenido_28 contenido_30)
        (paralela contenido_30 contenido_2)
        (paralela contenido_2 contenido_30)
        (paralela contenido_30 contenido_52)
        (paralela contenido_52 contenido_30)
        (paralela contenido_28 contenido_2)
        (paralela contenido_2 contenido_28)
        (paralela contenido_28 contenido_52)
        (paralela contenido_52 contenido_28)
        (paralela contenido_2 contenido_52)
        (paralela contenido_52 contenido_2)
        (= (minutos_contenido contenido_30) 10)
        (= (minutos_contenido contenido_28) 116)
        (= (minutos_contenido contenido_2) 63)
        (= (minutos_contenido contenido_52) 71)
        (paralela contenido_37 contenido_167)
        (paralela contenido_167 contenido_37)
        (paralela contenido_37 contenido_192)
        (paralela contenido_192 contenido_37)
        (paralela contenido_37 contenido_1)
        (paralela contenido_1 contenido_37)
        (paralela contenido_167 contenido_192)
        (paralela contenido_192 contenido_167)
        (paralela contenido_167 contenido_1)
        (paralela contenido_1 contenido_167)
        (paralela contenido_192 contenido_1)
        (paralela contenido_1 contenido_192)
        (= (minutos_contenido contenido_37) 11)
        (= (minutos_contenido contenido_167) 116)
        (= (minutos_contenido contenido_192) 43)
        (= (minutos_contenido contenido_1) 31)
        (paralela contenido_9 contenido_149)
        (paralela contenido_149 contenido_9)
        (paralela contenido_9 contenido_178)
        (paralela contenido_178 contenido_9)
        (paralela contenido_9 contenido_79)
        (paralela contenido_79 contenido_9)
        (paralela contenido_149 contenido_178)
        (paralela contenido_178 contenido_149)
        (paralela contenido_149 contenido_79)
        (paralela contenido_79 contenido_149)
        (paralela contenido_178 contenido_79)
        (paralela contenido_79 contenido_178)
        (= (minutos_contenido contenido_9) 53)
        (= (minutos_contenido contenido_149) 109)
        (= (minutos_contenido contenido_178) 88)
        (= (minutos_contenido contenido_79) 26)
        (paralela contenido_175 contenido_18)
        (paralela contenido_18 contenido_175)
        (paralela contenido_175 contenido_19)
        (paralela contenido_19 contenido_175)
        (paralela contenido_175 contenido_53)
        (paralela contenido_53 contenido_175)
        (paralela contenido_18 contenido_19)
        (paralela contenido_19 contenido_18)
        (paralela contenido_18 contenido_53)
        (paralela contenido_53 contenido_18)
        (paralela contenido_19 contenido_53)
        (paralela contenido_53 contenido_19)
        (= (minutos_contenido contenido_175) 16)
        (= (minutos_contenido contenido_18) 41)
        (= (minutos_contenido contenido_19) 155)
        (= (minutos_contenido contenido_53) 110)
        (paralelas_vistas contenido_146)
        (no_paralela contenido_146)
        (paralelas_vistas contenido_45)
        (no_paralela contenido_45)
        (paralelas_vistas contenido_33)
        (no_paralela contenido_33)
        (paralelas_vistas contenido_90)
        (no_paralela contenido_90)
        (paralelas_vistas contenido_123)
        (no_paralela contenido_123)
        (paralelas_vistas contenido_8)
        (no_paralela contenido_8)
        (paralelas_vistas contenido_121)
        (no_paralela contenido_121)
        (paralelas_vistas contenido_158)
        (no_paralela contenido_158)
        (paralelas_vistas contenido_103)
        (no_paralela contenido_103)
        (paralelas_vistas contenido_31)
        (no_paralela contenido_31)
        (paralelas_vistas contenido_137)
        (no_paralela contenido_137)
        (paralelas_vistas contenido_125)
        (no_paralela contenido_125)
        (paralelas_vistas contenido_141)
        (no_paralela contenido_141)
        (paralelas_vistas contenido_160)
        (no_paralela contenido_160)
        (paralelas_vistas contenido_69)
        (no_paralela contenido_69)
        (paralelas_vistas contenido_110)
        (no_paralela contenido_110)
        (paralelas_vistas contenido_47)
        (no_paralela contenido_47)
        (paralelas_vistas contenido_115)
        (no_paralela contenido_115)
        (paralelas_vistas contenido_120)
        (no_paralela contenido_120)
        (paralelas_vistas contenido_118)
        (no_paralela contenido_118)
        (paralelas_vistas contenido_152)
        (no_paralela contenido_152)
        (paralelas_vistas contenido_63)
        (no_paralela contenido_63)
        (paralelas_vistas contenido_114)
        (no_paralela contenido_114)
        (paralelas_vistas contenido_176)
        (no_paralela contenido_176)
        (paralelas_vistas contenido_85)
        (no_paralela contenido_85)
        (paralelas_vistas contenido_186)
        (no_paralela contenido_186)
        (paralelas_vistas contenido_14)
        (no_paralela contenido_14)
        (paralelas_vistas contenido_60)
        (no_paralela contenido_60)
        (paralelas_vistas contenido_184)
        (no_paralela contenido_184)
        (paralelas_vistas contenido_148)
        (no_paralela contenido_148)
        (paralelas_vistas contenido_151)
        (no_paralela contenido_151)
        (paralelas_vistas contenido_80)
        (no_paralela contenido_80)
        (paralelas_vistas contenido_200)
        (no_paralela contenido_200)
        (paralelas_vistas contenido_153)
        (no_paralela contenido_153)
        (paralelas_vistas contenido_154)
        (no_paralela contenido_154)
        (paralelas_vistas contenido_6)
        (no_paralela contenido_6)
        (paralelas_vistas contenido_100)
        (no_paralela contenido_100)
        (paralelas_vistas contenido_48)
        (no_paralela contenido_48)
        (paralelas_vistas contenido_122)
        (no_paralela contenido_122)
        (paralelas_vistas contenido_126)
        (no_paralela contenido_126)
        (paralelas_vistas contenido_83)
        (no_paralela contenido_83)
        (paralelas_vistas contenido_138)
        (no_paralela contenido_138)
        (paralelas_vistas contenido_164)
        (no_paralela contenido_164)
        (paralelas_vistas contenido_27)
        (no_paralela contenido_27)
        (paralelas_vistas contenido_73)
        (no_paralela contenido_73)
        (paralelas_vistas contenido_190)
        (no_paralela contenido_190)
        (paralelas_vistas contenido_128)
        (no_paralela contenido_128)
        (paralelas_vistas contenido_56)
        (no_paralela contenido_56)
        (paralelas_vistas contenido_181)
        (no_paralela contenido_181)
        (paralelas_vistas contenido_41)
        (no_paralela contenido_41)
        (paralelas_vistas contenido_194)
        (no_paralela contenido_194)
        (paralelas_vistas contenido_4)
        (no_paralela contenido_4)
        (paralelas_vistas contenido_46)
        (no_paralela contenido_46)
        (paralelas_vistas contenido_62)
        (no_paralela contenido_62)
        (paralelas_vistas contenido_113)
        (no_paralela contenido_113)
        (paralelas_vistas contenido_81)
        (no_paralela contenido_81)
        (paralelas_vistas contenido_59)
        (no_paralela contenido_59)
        (paralelas_vistas contenido_191)
        (no_paralela contenido_191)
        (paralelas_vistas contenido_91)
        (no_paralela contenido_91)
        (paralelas_vistas contenido_173)
        (no_paralela contenido_173)
        (paralelas_vistas contenido_61)
        (no_paralela contenido_61)
        (paralelas_vistas contenido_156)
        (no_paralela contenido_156)
        (paralelas_vistas contenido_84)
        (no_paralela contenido_84)
        (paralelas_vistas contenido_25)
        (no_paralela contenido_25)
        (paralelas_vistas contenido_168)
        (no_paralela contenido_168)
        (paralelas_vistas contenido_57)
        (no_paralela contenido_57)
        (paralelas_vistas contenido_44)
        (no_paralela contenido_44)
        (paralelas_vistas contenido_49)
        (no_paralela contenido_49)
        (paralelas_vistas contenido_22)
        (no_paralela contenido_22)
        (paralelas_vistas contenido_86)
        (no_paralela contenido_86)
        (paralelas_vistas contenido_142)
        (no_paralela contenido_142)
        (paralelas_vistas contenido_38)
        (no_paralela contenido_38)
        (paralelas_vistas contenido_64)
        (no_paralela contenido_64)
        (paralelas_vistas contenido_145)
        (no_paralela contenido_145)
        (paralelas_vistas contenido_5)
        (no_paralela contenido_5)
        (paralelas_vistas contenido_182)
        (no_paralela contenido_182)
        (paralelas_vistas contenido_129)
        (no_paralela contenido_129)
        (paralelas_vistas contenido_67)
        (no_paralela contenido_67)
        (paralelas_vistas contenido_72)
        (no_paralela contenido_72)
        (paralelas_vistas contenido_187)
        (no_paralela contenido_187)
        (paralelas_vistas contenido_140)
        (no_paralela contenido_140)
        (paralelas_vistas contenido_193)
        (no_paralela contenido_193)
        (paralelas_vistas contenido_131)
        (no_paralela contenido_131)
        (paralelas_vistas contenido_179)
        (no_paralela contenido_179)
        (paralelas_vistas contenido_102)
        (no_paralela contenido_102)
        (paralelas_vistas contenido_36)
        (no_paralela contenido_36)
        (paralelas_vistas contenido_15)
        (no_paralela contenido_15)
        (paralelas_vistas contenido_3)
        (no_paralela contenido_3)
        (paralelas_vistas contenido_23)
        (no_paralela contenido_23)
        (paralelas_vistas contenido_124)
        (no_paralela contenido_124)
        (paralelas_vistas contenido_35)
        (no_paralela contenido_35)
        (paralelas_vistas contenido_107)
        (no_paralela contenido_107)
        (paralelas_vistas contenido_13)
        (no_paralela contenido_13)
        (paralelas_vistas contenido_77)
        (no_paralela contenido_77)
        (paralelas_vistas contenido_10)
        (no_paralela contenido_10)
        (paralelas_vistas contenido_66)
        (no_paralela contenido_66)
        (paralelas_vistas contenido_159)
        (no_paralela contenido_159)
        (paralelas_vistas contenido_68)
        (no_paralela contenido_68)
        (paralelas_vistas contenido_127)
        (no_paralela contenido_127)
        (paralelas_vistas contenido_39)
        (no_paralela contenido_39)
        (paralelas_vistas contenido_104)
        (no_paralela contenido_104)
        (paralelas_vistas contenido_75)
        (no_paralela contenido_75)
        (paralelas_vistas contenido_139)
        (no_paralela contenido_139)
        (paralelas_vistas contenido_20)
        (no_paralela contenido_20)
        (paralelas_vistas contenido_7)
        (no_paralela contenido_7)
        (paralelas_vistas contenido_34)
        (no_paralela contenido_34)
        (paralelas_vistas contenido_144)
        (no_paralela contenido_144)
        (paralelas_vistas contenido_24)
        (no_paralela contenido_24)
        (paralelas_vistas contenido_197)
        (no_paralela contenido_197)
        (paralelas_vistas contenido_108)
        (no_paralela contenido_108)
        (paralelas_vistas contenido_134)
        (no_paralela contenido_134)
        (paralelas_vistas contenido_92)
        (no_paralela contenido_92)
        (paralelas_vistas contenido_143)
        (no_paralela contenido_143)
        (paralelas_vistas contenido_119)
        (no_paralela contenido_119)
        (paralelas_vistas contenido_50)
        (no_paralela contenido_50)
        (paralelas_vistas contenido_89)
        (no_paralela contenido_89)
        (paralelas_vistas contenido_99)
        (no_paralela contenido_99)
        (paralelas_vistas contenido_97)
        (no_paralela contenido_97)
        (paralelas_vistas contenido_150)
        (no_paralela contenido_150)
        (paralelas_vistas contenido_161)
        (no_paralela contenido_161)
        (paralelas_vistas contenido_88)
        (no_paralela contenido_88)
        (paralelas_vistas contenido_172)
        (no_paralela contenido_172)
        (paralelas_vistas contenido_135)
        (no_paralela contenido_135)
        (paralelas_vistas contenido_198)
        (no_paralela contenido_198)
        (paralelas_vistas contenido_32)
        (no_paralela contenido_32)
        (paralelas_vistas contenido_162)
        (no_paralela contenido_162)
        (paralelas_vistas contenido_155)
        (no_paralela contenido_155)
        (paralelas_vistas contenido_29)
        (no_paralela contenido_29)
        (paralelas_vistas contenido_109)
        (no_paralela contenido_109)
        (paralelas_vistas contenido_171)
        (no_paralela contenido_171)
        (paralelas_vistas contenido_188)
        (no_paralela contenido_188)
        (paralelas_vistas contenido_74)
        (no_paralela contenido_74)
        (paralelas_vistas contenido_106)
        (no_paralela contenido_106)
        (paralelas_vistas contenido_26)
        (no_paralela contenido_26)
        (paralelas_vistas contenido_71)
        (no_paralela contenido_71)
        (paralelas_vistas contenido_195)
        (no_paralela contenido_195)
        (paralelas_vistas contenido_130)
        (no_paralela contenido_130)
        (paralelas_vistas contenido_165)
        (no_paralela contenido_165)
        (paralelas_vistas contenido_177)
        (no_paralela contenido_177)
        (paralelas_vistas contenido_101)
        (no_paralela contenido_101)
        (paralelas_vistas contenido_189)
        (no_paralela contenido_189)
        (paralelas_vistas contenido_196)
        (no_paralela contenido_196)
        (paralelas_vistas contenido_112)
        (no_paralela contenido_112)
        (paralelas_vistas contenido_42)
        (no_paralela contenido_42)
        (paralelas_vistas contenido_70)
        (no_paralela contenido_70)
        (paralelas_vistas contenido_98)
        (no_paralela contenido_98)
        (paralelas_vistas contenido_111)
        (no_paralela contenido_111)
        (paralelas_vistas contenido_147)
        (no_paralela contenido_147)
        (paralelas_vistas contenido_185)
        (no_paralela contenido_185)
        (paralelas_vistas contenido_163)
        (no_paralela contenido_163)
        (paralelas_vistas contenido_55)
        (no_paralela contenido_55)
        (paralelas_vistas contenido_180)
        (no_paralela contenido_180)
        (paralelas_vistas contenido_51)
        (no_paralela contenido_51)
        (paralelas_vistas contenido_199)
        (no_paralela contenido_199)
        (paralelas_vistas contenido_87)
        (no_paralela contenido_87)
        (paralelas_vistas contenido_76)
        (no_paralela contenido_76)
        (paralelas_vistas contenido_78)
        (no_paralela contenido_78)
        (paralelas_vistas contenido_105)
        (no_paralela contenido_105)
        (paralelas_vistas contenido_170)
        (no_paralela contenido_170)
        (paralelas_vistas contenido_117)
        (no_paralela contenido_117)
        (predecesores_vistos contenido_45)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_158)
        (predecesores_vistos contenido_103)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_160)
        (predecesores_vistos contenido_110)
        (predecesores_vistos contenido_115)
        (predecesores_vistos contenido_152)
        (predecesores_vistos contenido_176)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_60)
        (predecesores_vistos contenido_151)
        (predecesores_vistos contenido_80)
        (predecesores_vistos contenido_153)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_126)
        (predecesores_vistos contenido_83)
        (predecesores_vistos contenido_164)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_56)
        (predecesores_vistos contenido_194)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_46)
        (predecesores_vistos contenido_81)
        (predecesores_vistos contenido_59)
        (predecesores_vistos contenido_61)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_38)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_67)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_36)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_35)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_77)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_143)
        (predecesores_vistos contenido_89)
        (predecesores_vistos contenido_99)
        (predecesores_vistos contenido_97)
        (predecesores_vistos contenido_150)
        (predecesores_vistos contenido_198)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_162)
        (predecesores_vistos contenido_71)
        (predecesores_vistos contenido_165)
        (predecesores_vistos contenido_177)
        (predecesores_vistos contenido_101)
        (predecesores_vistos contenido_70)
        (predecesores_vistos contenido_98)
        (predecesores_vistos contenido_55)
        (predecesores_vistos contenido_51)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
