(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75
    )

    (:init
        (predecesor contenido_43 contenido_44)
        (predecesor contenido_68 contenido_73)
        (predecesor contenido_8 contenido_37)
        (predecesor contenido_44 contenido_51)
        (predecesor contenido_51 contenido_66)
        (predecesor contenido_18 contenido_44)
        (predecesor contenido_7 contenido_35)
        (predecesor contenido_49 contenido_60)
        (predecesor contenido_9 contenido_38)
        (predecesor contenido_5 contenido_49)
        (predecesor contenido_29 contenido_73)
        (predecesor contenido_56 contenido_69)
        (predecesor contenido_3 contenido_25)
        (predecesor contenido_8 contenido_49)
        (predecesor contenido_38 contenido_56)
        (predecesor contenido_35 contenido_56)
        (predecesor contenido_8 contenido_67)
        (predecesor contenido_63 contenido_67)
        (predecesor contenido_4 contenido_21)
        (predecesor contenido_3 contenido_45)
        (predecesor contenido_60 contenido_74)
        (predecesor contenido_23 contenido_72)
        (predecesor contenido_41 contenido_58)
        (predecesor contenido_12 contenido_47)
        (predecesor contenido_18 contenido_69)
        (predecesor contenido_29 contenido_65)
        (predecesor contenido_11 contenido_41)
        (predecesor contenido_19 contenido_48)
        (predecesor contenido_42 contenido_67)
        (predecesor contenido_10 contenido_70)
        (predecesor contenido_5 contenido_40)
        (predecesor contenido_44 contenido_67)
        (predecesor contenido_44 contenido_71)
        (predecesor contenido_18 contenido_59)
        (predecesor contenido_25 contenido_35)
        (predecesor contenido_7 contenido_50)
        (predecesor contenido_18 contenido_62)
        (predecesor contenido_4 contenido_33)
        (predecesor contenido_57 contenido_73)
        (predecesor contenido_7 contenido_21)
        (predecesor contenido_69 contenido_72)
        (predecesor contenido_22 contenido_50)
        (predecesor contenido_7 contenido_47)
        (predecesor contenido_16 contenido_34)
        (predecesor contenido_50 contenido_69)
        (predecesor contenido_35 contenido_65)
        (predecesor contenido_1 contenido_56)
        (predecesor contenido_34 contenido_61)
        (predecesor contenido_21 contenido_67)
        (predecesor contenido_66 contenido_72)
        (predecesor contenido_12 contenido_53)
        (predecesor contenido_12 contenido_49)
        (predecesor contenido_30 contenido_52)
        (predecesor contenido_22 contenido_43)
        (predecesor contenido_11 contenido_44)
        (predecesor contenido_12 contenido_19)
        (predecesor contenido_2 contenido_46)
        (predecesor contenido_38 contenido_50)
        (predecesor contenido_26 contenido_65)
        (predecesor contenido_33 contenido_46)
        (paralela contenido_36 contenido_17)
        (paralela contenido_17 contenido_36)
        (paralela contenido_36 contenido_4)
        (paralela contenido_4 contenido_36)
        (paralela contenido_36 contenido_32)
        (paralela contenido_32 contenido_36)
        (paralela contenido_17 contenido_4)
        (paralela contenido_4 contenido_17)
        (paralela contenido_17 contenido_32)
        (paralela contenido_32 contenido_17)
        (paralela contenido_4 contenido_32)
        (paralela contenido_32 contenido_4)
        (= (minutos_contenido contenido_36) 186)
        (= (minutos_contenido contenido_17) 26)
        (= (minutos_contenido contenido_4) 74)
        (= (minutos_contenido contenido_32) 82)
        (paralela contenido_2 contenido_55)
        (paralela contenido_55 contenido_2)
        (paralela contenido_2 contenido_30)
        (paralela contenido_30 contenido_2)
        (paralela contenido_2 contenido_27)
        (paralela contenido_27 contenido_2)
        (paralela contenido_55 contenido_30)
        (paralela contenido_30 contenido_55)
        (paralela contenido_55 contenido_27)
        (paralela contenido_27 contenido_55)
        (paralela contenido_30 contenido_27)
        (paralela contenido_27 contenido_30)
        (= (minutos_contenido contenido_2) 21)
        (= (minutos_contenido contenido_55) 165)
        (= (minutos_contenido contenido_30) 13)
        (= (minutos_contenido contenido_27) 137)
        (paralela contenido_10 contenido_12)
        (paralela contenido_12 contenido_10)
        (paralela contenido_10 contenido_8)
        (paralela contenido_8 contenido_10)
        (paralela contenido_10 contenido_24)
        (paralela contenido_24 contenido_10)
        (paralela contenido_12 contenido_8)
        (paralela contenido_8 contenido_12)
        (paralela contenido_12 contenido_24)
        (paralela contenido_24 contenido_12)
        (paralela contenido_8 contenido_24)
        (paralela contenido_24 contenido_8)
        (= (minutos_contenido contenido_10) 182)
        (= (minutos_contenido contenido_12) 52)
        (= (minutos_contenido contenido_8) 60)
        (= (minutos_contenido contenido_24) 21)
        (paralela contenido_31 contenido_5)
        (paralela contenido_5 contenido_31)
        (paralela contenido_31 contenido_20)
        (paralela contenido_20 contenido_31)
        (paralela contenido_31 contenido_64)
        (paralela contenido_64 contenido_31)
        (paralela contenido_5 contenido_20)
        (paralela contenido_20 contenido_5)
        (paralela contenido_5 contenido_64)
        (paralela contenido_64 contenido_5)
        (paralela contenido_20 contenido_64)
        (paralela contenido_64 contenido_20)
        (= (minutos_contenido contenido_31) 33)
        (= (minutos_contenido contenido_5) 36)
        (= (minutos_contenido contenido_20) 123)
        (= (minutos_contenido contenido_64) 166)
        (paralela contenido_29 contenido_39)
        (paralela contenido_39 contenido_29)
        (paralela contenido_29 contenido_18)
        (paralela contenido_18 contenido_29)
        (paralela contenido_29 contenido_1)
        (paralela contenido_1 contenido_29)
        (paralela contenido_39 contenido_18)
        (paralela contenido_18 contenido_39)
        (paralela contenido_39 contenido_1)
        (paralela contenido_1 contenido_39)
        (paralela contenido_18 contenido_1)
        (paralela contenido_1 contenido_18)
        (= (minutos_contenido contenido_29) 114)
        (= (minutos_contenido contenido_39) 124)
        (= (minutos_contenido contenido_18) 38)
        (= (minutos_contenido contenido_1) 25)
        (paralelas_vistas contenido_38)
        (no_paralela contenido_38)
        (paralelas_vistas contenido_58)
        (no_paralela contenido_58)
        (paralelas_vistas contenido_63)
        (no_paralela contenido_63)
        (paralelas_vistas contenido_74)
        (no_paralela contenido_74)
        (paralelas_vistas contenido_66)
        (no_paralela contenido_66)
        (paralelas_vistas contenido_37)
        (no_paralela contenido_37)
        (paralelas_vistas contenido_23)
        (no_paralela contenido_23)
        (paralelas_vistas contenido_48)
        (no_paralela contenido_48)
        (paralelas_vistas contenido_41)
        (no_paralela contenido_41)
        (paralelas_vistas contenido_40)
        (no_paralela contenido_40)
        (paralelas_vistas contenido_45)
        (no_paralela contenido_45)
        (paralelas_vistas contenido_53)
        (no_paralela contenido_53)
        (paralelas_vistas contenido_67)
        (no_paralela contenido_67)
        (paralelas_vistas contenido_22)
        (no_paralela contenido_22)
        (paralelas_vistas contenido_51)
        (no_paralela contenido_51)
        (paralelas_vistas contenido_75)
        (no_paralela contenido_75)
        (paralelas_vistas contenido_60)
        (no_paralela contenido_60)
        (paralelas_vistas contenido_71)
        (no_paralela contenido_71)
        (paralelas_vistas contenido_28)
        (no_paralela contenido_28)
        (paralelas_vistas contenido_49)
        (no_paralela contenido_49)
        (paralelas_vistas contenido_42)
        (no_paralela contenido_42)
        (paralelas_vistas contenido_68)
        (no_paralela contenido_68)
        (paralelas_vistas contenido_65)
        (no_paralela contenido_65)
        (paralelas_vistas contenido_19)
        (no_paralela contenido_19)
        (paralelas_vistas contenido_13)
        (no_paralela contenido_13)
        (paralelas_vistas contenido_59)
        (no_paralela contenido_59)
        (paralelas_vistas contenido_26)
        (no_paralela contenido_26)
        (paralelas_vistas contenido_14)
        (no_paralela contenido_14)
        (paralelas_vistas contenido_46)
        (no_paralela contenido_46)
        (paralelas_vistas contenido_52)
        (no_paralela contenido_52)
        (paralelas_vistas contenido_34)
        (no_paralela contenido_34)
        (paralelas_vistas contenido_73)
        (no_paralela contenido_73)
        (paralelas_vistas contenido_70)
        (no_paralela contenido_70)
        (paralelas_vistas contenido_72)
        (no_paralela contenido_72)
        (paralelas_vistas contenido_43)
        (no_paralela contenido_43)
        (paralelas_vistas contenido_11)
        (no_paralela contenido_11)
        (paralelas_vistas contenido_6)
        (no_paralela contenido_6)
        (paralelas_vistas contenido_9)
        (no_paralela contenido_9)
        (paralelas_vistas contenido_25)
        (no_paralela contenido_25)
        (paralelas_vistas contenido_62)
        (no_paralela contenido_62)
        (paralelas_vistas contenido_69)
        (no_paralela contenido_69)
        (paralelas_vistas contenido_35)
        (no_paralela contenido_35)
        (paralelas_vistas contenido_3)
        (no_paralela contenido_3)
        (paralelas_vistas contenido_21)
        (no_paralela contenido_21)
        (paralelas_vistas contenido_15)
        (no_paralela contenido_15)
        (paralelas_vistas contenido_16)
        (no_paralela contenido_16)
        (paralelas_vistas contenido_61)
        (no_paralela contenido_61)
        (paralelas_vistas contenido_57)
        (no_paralela contenido_57)
        (paralelas_vistas contenido_54)
        (no_paralela contenido_54)
        (paralelas_vistas contenido_47)
        (no_paralela contenido_47)
        (paralelas_vistas contenido_50)
        (no_paralela contenido_50)
        (paralelas_vistas contenido_56)
        (no_paralela contenido_56)
        (paralelas_vistas contenido_7)
        (no_paralela contenido_7)
        (paralelas_vistas contenido_44)
        (no_paralela contenido_44)
        (paralelas_vistas contenido_33)
        (no_paralela contenido_33)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_75)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_68)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_57)
        (predecesores_vistos contenido_54)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_14)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
