(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125 contenido_126 contenido_127 contenido_128 contenido_129 contenido_130 contenido_131 contenido_132 contenido_133 contenido_134 contenido_135 contenido_136 contenido_137 contenido_138 contenido_139 contenido_140 contenido_141 contenido_142 contenido_143 contenido_144 contenido_145 contenido_146 contenido_147 contenido_148 contenido_149 contenido_150 contenido_151 contenido_152 contenido_153 contenido_154 contenido_155 contenido_156 contenido_157 contenido_158 contenido_159 contenido_160 contenido_161 contenido_162 contenido_163 contenido_164 contenido_165 contenido_166 contenido_167 contenido_168 contenido_169 contenido_170 contenido_171 contenido_172 contenido_173 contenido_174 contenido_175 contenido_176 contenido_177 contenido_178 contenido_179 contenido_180 contenido_181 contenido_182 contenido_183 contenido_184 contenido_185 contenido_186 contenido_187 contenido_188 contenido_189 contenido_190 contenido_191 contenido_192 contenido_193 contenido_194 contenido_195 contenido_196 contenido_197 contenido_198 contenido_199 contenido_200 contenido_201 contenido_202 contenido_203 contenido_204 contenido_205 contenido_206 contenido_207 contenido_208 contenido_209 contenido_210 contenido_211 contenido_212 contenido_213 contenido_214 contenido_215 contenido_216 contenido_217 contenido_218 contenido_219 contenido_220 contenido_221 contenido_222 contenido_223 contenido_224 contenido_225 contenido_226 contenido_227 contenido_228 contenido_229 contenido_230 contenido_231 contenido_232 contenido_233 contenido_234 contenido_235 contenido_236 contenido_237 contenido_238 contenido_239 contenido_240 contenido_241 contenido_242 contenido_243 contenido_244 contenido_245 contenido_246 contenido_247 contenido_248 contenido_249 contenido_250 contenido_251 contenido_252 contenido_253 contenido_254 contenido_255 contenido_256 contenido_257 contenido_258 contenido_259 contenido_260 contenido_261 contenido_262 contenido_263 contenido_264 contenido_265 contenido_266 contenido_267 contenido_268 contenido_269 contenido_270 contenido_271 contenido_272 contenido_273 contenido_274 contenido_275 contenido_276 contenido_277 contenido_278 contenido_279 contenido_280 contenido_281 contenido_282 contenido_283 contenido_284 contenido_285 contenido_286 contenido_287 contenido_288 contenido_289 contenido_290 contenido_291 contenido_292 contenido_293 contenido_294 contenido_295 contenido_296 contenido_297 contenido_298 contenido_299 contenido_300 contenido_301 contenido_302 contenido_303 contenido_304 contenido_305 contenido_306 contenido_307 contenido_308 contenido_309 contenido_310 contenido_311 contenido_312 contenido_313 contenido_314 contenido_315 contenido_316 contenido_317 contenido_318 contenido_319 contenido_320 contenido_321 contenido_322 contenido_323 contenido_324 contenido_325 contenido_326 contenido_327 contenido_328 contenido_329 contenido_330 contenido_331 contenido_332 contenido_333 contenido_334 contenido_335 contenido_336 contenido_337 contenido_338 contenido_339 contenido_340 contenido_341 contenido_342 contenido_343 contenido_344 contenido_345 contenido_346 contenido_347 contenido_348 contenido_349 contenido_350 contenido_351 contenido_352 contenido_353 contenido_354 contenido_355 contenido_356 contenido_357 contenido_358 contenido_359 contenido_360 contenido_361 contenido_362 contenido_363 contenido_364 contenido_365 contenido_366 contenido_367 contenido_368 contenido_369 contenido_370 contenido_371 contenido_372 contenido_373 contenido_374 contenido_375 contenido_376 contenido_377 contenido_378 contenido_379 contenido_380 contenido_381 contenido_382 contenido_383 contenido_384 contenido_385 contenido_386 contenido_387 contenido_388 contenido_389 contenido_390 contenido_391 contenido_392 contenido_393 contenido_394 contenido_395 contenido_396 contenido_397 contenido_398 contenido_399 contenido_400
    )

    (:init
        (predecesor contenido_304 contenido_341)
        (predecesor contenido_79 contenido_239)
        (predecesor contenido_167 contenido_377)
        (predecesor contenido_68 contenido_245)
        (predecesor contenido_30 contenido_131)
        (predecesor contenido_108 contenido_123)
        (predecesor contenido_150 contenido_221)
        (predecesor contenido_75 contenido_113)
        (predecesor contenido_22 contenido_127)
        (predecesor contenido_204 contenido_398)
        (predecesor contenido_109 contenido_124)
        (predecesor contenido_223 contenido_325)
        (predecesor contenido_118 contenido_208)
        (predecesor contenido_106 contenido_312)
        (predecesor contenido_54 contenido_280)
        (predecesor contenido_116 contenido_292)
        (predecesor contenido_7 contenido_255)
        (predecesor contenido_55 contenido_261)
        (predecesor contenido_176 contenido_357)
        (predecesor contenido_25 contenido_282)
        (predecesor contenido_54 contenido_337)
        (predecesor contenido_6 contenido_212)
        (predecesor contenido_5 contenido_150)
        (predecesor contenido_97 contenido_159)
        (predecesor contenido_260 contenido_389)
        (predecesor contenido_185 contenido_236)
        (predecesor contenido_80 contenido_330)
        (predecesor contenido_45 contenido_170)
        (predecesor contenido_90 contenido_275)
        (predecesor contenido_187 contenido_262)
        (predecesor contenido_33 contenido_262)
        (predecesor contenido_2 contenido_180)
        (predecesor contenido_306 contenido_340)
        (predecesor contenido_54 contenido_376)
        (predecesor contenido_38 contenido_280)
        (predecesor contenido_69 contenido_100)
        (predecesor contenido_337 contenido_349)
        (predecesor contenido_186 contenido_343)
        (predecesor contenido_128 contenido_148)
        (predecesor contenido_115 contenido_145)
        (predecesor contenido_173 contenido_284)
        (predecesor contenido_281 contenido_339)
        (predecesor contenido_260 contenido_348)
        (predecesor contenido_85 contenido_392)
        (predecesor contenido_233 contenido_343)
        (predecesor contenido_11 contenido_179)
        (predecesor contenido_36 contenido_152)
        (predecesor contenido_88 contenido_342)
        (predecesor contenido_72 contenido_76)
        (predecesor contenido_323 contenido_369)
        (predecesor contenido_2 contenido_332)
        (predecesor contenido_160 contenido_306)
        (predecesor contenido_120 contenido_279)
        (predecesor contenido_19 contenido_394)
        (predecesor contenido_58 contenido_145)
        (predecesor contenido_332 contenido_379)
        (predecesor contenido_83 contenido_400)
        (predecesor contenido_219 contenido_399)
        (predecesor contenido_158 contenido_226)
        (predecesor contenido_43 contenido_175)
        (predecesor contenido_321 contenido_345)
        (predecesor contenido_160 contenido_360)
        (predecesor contenido_119 contenido_294)
        (predecesor contenido_46 contenido_225)
        (predecesor contenido_84 contenido_215)
        (predecesor contenido_230 contenido_297)
        (predecesor contenido_34 contenido_57)
        (predecesor contenido_351 contenido_352)
        (predecesor contenido_220 contenido_397)
        (predecesor contenido_214 contenido_391)
        (predecesor contenido_238 contenido_259)
        (predecesor contenido_138 contenido_269)
        (predecesor contenido_140 contenido_260)
        (predecesor contenido_48 contenido_58)
        (predecesor contenido_181 contenido_283)
        (predecesor contenido_63 contenido_136)
        (predecesor contenido_136 contenido_241)
        (predecesor contenido_30 contenido_282)
        (predecesor contenido_279 contenido_366)
        (predecesor contenido_157 contenido_176)
        (predecesor contenido_308 contenido_397)
        (predecesor contenido_267 contenido_343)
        (predecesor contenido_68 contenido_199)
        (predecesor contenido_176 contenido_257)
        (predecesor contenido_289 contenido_293)
        (predecesor contenido_30 contenido_389)
        (predecesor contenido_267 contenido_389)
        (predecesor contenido_16 contenido_107)
        (predecesor contenido_38 contenido_185)
        (predecesor contenido_261 contenido_335)
        (predecesor contenido_195 contenido_275)
        (predecesor contenido_327 contenido_342)
        (predecesor contenido_87 contenido_214)
        (predecesor contenido_146 contenido_276)
        (predecesor contenido_258 contenido_310)
        (predecesor contenido_99 contenido_188)
        (predecesor contenido_92 contenido_395)
        (predecesor contenido_138 contenido_290)
        (predecesor contenido_17 contenido_51)
        (predecesor contenido_265 contenido_365)
        (predecesor contenido_24 contenido_217)
        (predecesor contenido_161 contenido_354)
        (predecesor contenido_220 contenido_339)
        (predecesor contenido_3 contenido_214)
        (predecesor contenido_9 contenido_100)
        (predecesor contenido_116 contenido_213)
        (predecesor contenido_109 contenido_255)
        (predecesor contenido_4 contenido_308)
        (predecesor contenido_257 contenido_295)
        (predecesor contenido_134 contenido_266)
        (predecesor contenido_313 contenido_326)
        (predecesor contenido_137 contenido_216)
        (predecesor contenido_176 contenido_386)
        (predecesor contenido_97 contenido_200)
        (predecesor contenido_23 contenido_111)
        (predecesor contenido_119 contenido_322)
        (predecesor contenido_7 contenido_181)
        (predecesor contenido_222 contenido_390)
        (predecesor contenido_79 contenido_275)
        (predecesor contenido_167 contenido_228)
        (predecesor contenido_134 contenido_374)
        (predecesor contenido_45 contenido_394)
        (predecesor contenido_148 contenido_362)
        (predecesor contenido_100 contenido_156)
        (predecesor contenido_67 contenido_214)
        (predecesor contenido_149 contenido_180)
        (predecesor contenido_135 contenido_216)
        (predecesor contenido_48 contenido_318)
        (predecesor contenido_39 contenido_111)
        (predecesor contenido_242 contenido_316)
        (predecesor contenido_15 contenido_132)
        (predecesor contenido_233 contenido_336)
        (predecesor contenido_130 contenido_211)
        (predecesor contenido_31 contenido_292)
        (predecesor contenido_93 contenido_372)
        (predecesor contenido_63 contenido_236)
        (predecesor contenido_231 contenido_379)
        (predecesor contenido_53 contenido_227)
        (predecesor contenido_103 contenido_339)
        (predecesor contenido_249 contenido_257)
        (predecesor contenido_22 contenido_184)
        (predecesor contenido_205 contenido_326)
        (predecesor contenido_1 contenido_213)
        (predecesor contenido_121 contenido_381)
        (predecesor contenido_56 contenido_317)
        (predecesor contenido_194 contenido_369)
        (predecesor contenido_41 contenido_322)
        (predecesor contenido_239 contenido_294)
        (predecesor contenido_70 contenido_366)
        (predecesor contenido_216 contenido_362)
        (predecesor contenido_172 contenido_213)
        (predecesor contenido_90 contenido_287)
        (predecesor contenido_184 contenido_218)
        (predecesor contenido_79 contenido_253)
        (predecesor contenido_228 contenido_267)
        (predecesor contenido_27 contenido_138)
        (predecesor contenido_147 contenido_327)
        (predecesor contenido_100 contenido_267)
        (predecesor contenido_29 contenido_78)
        (predecesor contenido_73 contenido_167)
        (predecesor contenido_270 contenido_388)
        (predecesor contenido_255 contenido_376)
        (predecesor contenido_135 contenido_146)
        (predecesor contenido_63 contenido_292)
        (predecesor contenido_223 contenido_365)
        (predecesor contenido_70 contenido_248)
        (predecesor contenido_306 contenido_382)
        (predecesor contenido_141 contenido_173)
        (predecesor contenido_25 contenido_94)
        (predecesor contenido_191 contenido_343)
        (predecesor contenido_46 contenido_346)
        (predecesor contenido_33 contenido_368)
        (predecesor contenido_182 contenido_363)
        (predecesor contenido_43 contenido_400)
        (predecesor contenido_310 contenido_393)
        (predecesor contenido_87 contenido_399)
        (predecesor contenido_22 contenido_147)
        (predecesor contenido_173 contenido_288)
        (predecesor contenido_99 contenido_106)
        (predecesor contenido_201 contenido_287)
        (predecesor contenido_98 contenido_206)
        (predecesor contenido_22 contenido_274)
        (predecesor contenido_69 contenido_274)
        (predecesor contenido_62 contenido_169)
        (predecesor contenido_7 contenido_204)
        (predecesor contenido_211 contenido_375)
        (predecesor contenido_103 contenido_219)
        (predecesor contenido_34 contenido_79)
        (predecesor contenido_16 contenido_392)
        (predecesor contenido_101 contenido_259)
        (predecesor contenido_23 contenido_311)
        (predecesor contenido_94 contenido_396)
        (predecesor contenido_298 contenido_310)
        (predecesor contenido_114 contenido_262)
        (predecesor contenido_173 contenido_347)
        (predecesor contenido_15 contenido_82)
        (predecesor contenido_18 contenido_309)
        (predecesor contenido_96 contenido_156)
        (predecesor contenido_254 contenido_392)
        (predecesor contenido_152 contenido_386)
        (predecesor contenido_301 contenido_334)
        (predecesor contenido_88 contenido_172)
        (predecesor contenido_59 contenido_237)
        (predecesor contenido_95 contenido_313)
        (predecesor contenido_3 contenido_84)
        (predecesor contenido_327 contenido_346)
        (predecesor contenido_40 contenido_255)
        (predecesor contenido_132 contenido_181)
        (predecesor contenido_103 contenido_389)
        (predecesor contenido_190 contenido_321)
        (predecesor contenido_292 contenido_368)
        (predecesor contenido_78 contenido_337)
        (predecesor contenido_75 contenido_336)
        (predecesor contenido_205 contenido_382)
        (predecesor contenido_199 contenido_294)
        (predecesor contenido_72 contenido_244)
        (predecesor contenido_253 contenido_375)
        (predecesor contenido_23 contenido_48)
        (predecesor contenido_241 contenido_278)
        (predecesor contenido_168 contenido_343)
        (predecesor contenido_28 contenido_354)
        (predecesor contenido_137 contenido_225)
        (predecesor contenido_1 contenido_224)
        (predecesor contenido_208 contenido_220)
        (predecesor contenido_9 contenido_97)
        (predecesor contenido_69 contenido_234)
        (predecesor contenido_330 contenido_337)
        (predecesor contenido_16 contenido_191)
        (predecesor contenido_20 contenido_126)
        (predecesor contenido_130 contenido_146)
        (predecesor contenido_69 contenido_343)
        (predecesor contenido_171 contenido_360)
        (predecesor contenido_201 contenido_209)
        (predecesor contenido_127 contenido_321)
        (predecesor contenido_310 contenido_324)
        (predecesor contenido_162 contenido_375)
        (predecesor contenido_55 contenido_65)
        (predecesor contenido_165 contenido_374)
        (predecesor contenido_43 contenido_250)
        (predecesor contenido_35 contenido_326)
        (paralela contenido_166 contenido_54)
        (paralela contenido_54 contenido_166)
        (paralela contenido_166 contenido_39)
        (paralela contenido_39 contenido_166)
        (paralela contenido_166 contenido_20)
        (paralela contenido_20 contenido_166)
        (paralela contenido_54 contenido_39)
        (paralela contenido_39 contenido_54)
        (paralela contenido_54 contenido_20)
        (paralela contenido_20 contenido_54)
        (paralela contenido_39 contenido_20)
        (paralela contenido_20 contenido_39)
        (= (minutos_contenido contenido_166) 54)
        (= (minutos_contenido contenido_54) 58)
        (= (minutos_contenido contenido_39) 31)
        (= (minutos_contenido contenido_20) 26)
        (paralela contenido_353 contenido_222)
        (paralela contenido_222 contenido_353)
        (paralela contenido_353 contenido_194)
        (paralela contenido_194 contenido_353)
        (paralela contenido_353 contenido_99)
        (paralela contenido_99 contenido_353)
        (paralela contenido_222 contenido_194)
        (paralela contenido_194 contenido_222)
        (paralela contenido_222 contenido_99)
        (paralela contenido_99 contenido_222)
        (paralela contenido_194 contenido_99)
        (paralela contenido_99 contenido_194)
        (= (minutos_contenido contenido_353) 20)
        (= (minutos_contenido contenido_222) 116)
        (= (minutos_contenido contenido_194) 23)
        (= (minutos_contenido contenido_99) 34)
        (paralela contenido_10 contenido_153)
        (paralela contenido_153 contenido_10)
        (paralela contenido_10 contenido_193)
        (paralela contenido_193 contenido_10)
        (paralela contenido_10 contenido_15)
        (paralela contenido_15 contenido_10)
        (paralela contenido_153 contenido_193)
        (paralela contenido_193 contenido_153)
        (paralela contenido_153 contenido_15)
        (paralela contenido_15 contenido_153)
        (paralela contenido_193 contenido_15)
        (paralela contenido_15 contenido_193)
        (= (minutos_contenido contenido_10) 26)
        (= (minutos_contenido contenido_153) 95)
        (= (minutos_contenido contenido_193) 165)
        (= (minutos_contenido contenido_15) 57)
        (paralela contenido_109 contenido_93)
        (paralela contenido_93 contenido_109)
        (paralela contenido_109 contenido_210)
        (paralela contenido_210 contenido_109)
        (paralela contenido_109 contenido_189)
        (paralela contenido_189 contenido_109)
        (paralela contenido_93 contenido_210)
        (paralela contenido_210 contenido_93)
        (paralela contenido_93 contenido_189)
        (paralela contenido_189 contenido_93)
        (paralela contenido_210 contenido_189)
        (paralela contenido_189 contenido_210)
        (= (minutos_contenido contenido_109) 40)
        (= (minutos_contenido contenido_93) 16)
        (= (minutos_contenido contenido_210) 123)
        (= (minutos_contenido contenido_189) 110)
        (paralela contenido_247 contenido_203)
        (paralela contenido_203 contenido_247)
        (paralela contenido_247 contenido_265)
        (paralela contenido_265 contenido_247)
        (paralela contenido_247 contenido_351)
        (paralela contenido_351 contenido_247)
        (paralela contenido_203 contenido_265)
        (paralela contenido_265 contenido_203)
        (paralela contenido_203 contenido_351)
        (paralela contenido_351 contenido_203)
        (paralela contenido_265 contenido_351)
        (paralela contenido_351 contenido_265)
        (= (minutos_contenido contenido_247) 138)
        (= (minutos_contenido contenido_203) 92)
        (= (minutos_contenido contenido_265) 18)
        (= (minutos_contenido contenido_351) 62)
        (paralela contenido_102 contenido_40)
        (paralela contenido_40 contenido_102)
        (paralela contenido_102 contenido_384)
        (paralela contenido_384 contenido_102)
        (paralela contenido_102 contenido_186)
        (paralela contenido_186 contenido_102)
        (paralela contenido_40 contenido_384)
        (paralela contenido_384 contenido_40)
        (paralela contenido_40 contenido_186)
        (paralela contenido_186 contenido_40)
        (paralela contenido_384 contenido_186)
        (paralela contenido_186 contenido_384)
        (= (minutos_contenido contenido_102) 102)
        (= (minutos_contenido contenido_40) 67)
        (= (minutos_contenido contenido_384) 146)
        (= (minutos_contenido contenido_186) 18)
        (paralela contenido_338 contenido_251)
        (paralela contenido_251 contenido_338)
        (paralela contenido_338 contenido_328)
        (paralela contenido_328 contenido_338)
        (paralela contenido_338 contenido_47)
        (paralela contenido_47 contenido_338)
        (paralela contenido_251 contenido_328)
        (paralela contenido_328 contenido_251)
        (paralela contenido_251 contenido_47)
        (paralela contenido_47 contenido_251)
        (paralela contenido_328 contenido_47)
        (paralela contenido_47 contenido_328)
        (= (minutos_contenido contenido_338) 43)
        (= (minutos_contenido contenido_251) 69)
        (= (minutos_contenido contenido_328) 24)
        (= (minutos_contenido contenido_47) 51)
        (paralela contenido_252 contenido_46)
        (paralela contenido_46 contenido_252)
        (paralela contenido_252 contenido_201)
        (paralela contenido_201 contenido_252)
        (paralela contenido_252 contenido_121)
        (paralela contenido_121 contenido_252)
        (paralela contenido_46 contenido_201)
        (paralela contenido_201 contenido_46)
        (paralela contenido_46 contenido_121)
        (paralela contenido_121 contenido_46)
        (paralela contenido_201 contenido_121)
        (paralela contenido_121 contenido_201)
        (= (minutos_contenido contenido_252) 70)
        (= (minutos_contenido contenido_46) 84)
        (= (minutos_contenido contenido_201) 54)
        (= (minutos_contenido contenido_121) 143)
        (paralela contenido_230 contenido_9)
        (paralela contenido_9 contenido_230)
        (paralela contenido_230 contenido_108)
        (paralela contenido_108 contenido_230)
        (paralela contenido_230 contenido_301)
        (paralela contenido_301 contenido_230)
        (paralela contenido_9 contenido_108)
        (paralela contenido_108 contenido_9)
        (paralela contenido_9 contenido_301)
        (paralela contenido_301 contenido_9)
        (paralela contenido_108 contenido_301)
        (paralela contenido_301 contenido_108)
        (= (minutos_contenido contenido_230) 171)
        (= (minutos_contenido contenido_9) 44)
        (= (minutos_contenido contenido_108) 53)
        (= (minutos_contenido contenido_301) 98)
        (paralela contenido_14 contenido_77)
        (paralela contenido_77 contenido_14)
        (paralela contenido_14 contenido_315)
        (paralela contenido_315 contenido_14)
        (paralela contenido_14 contenido_27)
        (paralela contenido_27 contenido_14)
        (paralela contenido_77 contenido_315)
        (paralela contenido_315 contenido_77)
        (paralela contenido_77 contenido_27)
        (paralela contenido_27 contenido_77)
        (paralela contenido_315 contenido_27)
        (paralela contenido_27 contenido_315)
        (= (minutos_contenido contenido_14) 87)
        (= (minutos_contenido contenido_77) 116)
        (= (minutos_contenido contenido_315) 49)
        (= (minutos_contenido contenido_27) 51)
        (paralela contenido_28 contenido_302)
        (paralela contenido_302 contenido_28)
        (paralela contenido_28 contenido_350)
        (paralela contenido_350 contenido_28)
        (paralela contenido_28 contenido_296)
        (paralela contenido_296 contenido_28)
        (paralela contenido_302 contenido_350)
        (paralela contenido_350 contenido_302)
        (paralela contenido_302 contenido_296)
        (paralela contenido_296 contenido_302)
        (paralela contenido_350 contenido_296)
        (paralela contenido_296 contenido_350)
        (= (minutos_contenido contenido_28) 59)
        (= (minutos_contenido contenido_302) 166)
        (= (minutos_contenido contenido_350) 124)
        (= (minutos_contenido contenido_296) 16)
        (paralela contenido_19 contenido_285)
        (paralela contenido_285 contenido_19)
        (paralela contenido_19 contenido_16)
        (paralela contenido_16 contenido_19)
        (paralela contenido_19 contenido_59)
        (paralela contenido_59 contenido_19)
        (paralela contenido_285 contenido_16)
        (paralela contenido_16 contenido_285)
        (paralela contenido_285 contenido_59)
        (paralela contenido_59 contenido_285)
        (paralela contenido_16 contenido_59)
        (paralela contenido_59 contenido_16)
        (= (minutos_contenido contenido_19) 180)
        (= (minutos_contenido contenido_285) 51)
        (= (minutos_contenido contenido_16) 93)
        (= (minutos_contenido contenido_59) 20)
        (paralela contenido_74 contenido_133)
        (paralela contenido_133 contenido_74)
        (paralela contenido_74 contenido_3)
        (paralela contenido_3 contenido_74)
        (paralela contenido_74 contenido_378)
        (paralela contenido_378 contenido_74)
        (paralela contenido_133 contenido_3)
        (paralela contenido_3 contenido_133)
        (paralela contenido_133 contenido_378)
        (paralela contenido_378 contenido_133)
        (paralela contenido_3 contenido_378)
        (paralela contenido_378 contenido_3)
        (= (minutos_contenido contenido_74) 35)
        (= (minutos_contenido contenido_133) 72)
        (= (minutos_contenido contenido_3) 20)
        (= (minutos_contenido contenido_378) 98)
        (paralela contenido_157 contenido_60)
        (paralela contenido_60 contenido_157)
        (paralela contenido_157 contenido_263)
        (paralela contenido_263 contenido_157)
        (paralela contenido_157 contenido_30)
        (paralela contenido_30 contenido_157)
        (paralela contenido_60 contenido_263)
        (paralela contenido_263 contenido_60)
        (paralela contenido_60 contenido_30)
        (paralela contenido_30 contenido_60)
        (paralela contenido_263 contenido_30)
        (paralela contenido_30 contenido_263)
        (= (minutos_contenido contenido_157) 65)
        (= (minutos_contenido contenido_60) 31)
        (= (minutos_contenido contenido_263) 54)
        (= (minutos_contenido contenido_30) 128)
        (paralela contenido_380 contenido_83)
        (paralela contenido_83 contenido_380)
        (paralela contenido_380 contenido_320)
        (paralela contenido_320 contenido_380)
        (paralela contenido_380 contenido_356)
        (paralela contenido_356 contenido_380)
        (paralela contenido_83 contenido_320)
        (paralela contenido_320 contenido_83)
        (paralela contenido_83 contenido_356)
        (paralela contenido_356 contenido_83)
        (paralela contenido_320 contenido_356)
        (paralela contenido_356 contenido_320)
        (= (minutos_contenido contenido_380) 121)
        (= (minutos_contenido contenido_83) 54)
        (= (minutos_contenido contenido_320) 34)
        (= (minutos_contenido contenido_356) 152)
        (paralela contenido_298 contenido_197)
        (paralela contenido_197 contenido_298)
        (paralela contenido_298 contenido_33)
        (paralela contenido_33 contenido_298)
        (paralela contenido_298 contenido_56)
        (paralela contenido_56 contenido_298)
        (paralela contenido_197 contenido_33)
        (paralela contenido_33 contenido_197)
        (paralela contenido_197 contenido_56)
        (paralela contenido_56 contenido_197)
        (paralela contenido_33 contenido_56)
        (paralela contenido_56 contenido_33)
        (= (minutos_contenido contenido_298) 53)
        (= (minutos_contenido contenido_197) 125)
        (= (minutos_contenido contenido_33) 42)
        (= (minutos_contenido contenido_56) 158)
        (paralela contenido_98 contenido_81)
        (paralela contenido_81 contenido_98)
        (paralela contenido_98 contenido_17)
        (paralela contenido_17 contenido_98)
        (paralela contenido_98 contenido_96)
        (paralela contenido_96 contenido_98)
        (paralela contenido_81 contenido_17)
        (paralela contenido_17 contenido_81)
        (paralela contenido_81 contenido_96)
        (paralela contenido_96 contenido_81)
        (paralela contenido_17 contenido_96)
        (paralela contenido_96 contenido_17)
        (= (minutos_contenido contenido_98) 155)
        (= (minutos_contenido contenido_81) 46)
        (= (minutos_contenido contenido_17) 59)
        (= (minutos_contenido contenido_96) 68)
        (paralela contenido_103 contenido_12)
        (paralela contenido_12 contenido_103)
        (paralela contenido_103 contenido_117)
        (paralela contenido_117 contenido_103)
        (paralela contenido_103 contenido_307)
        (paralela contenido_307 contenido_103)
        (paralela contenido_12 contenido_117)
        (paralela contenido_117 contenido_12)
        (paralela contenido_12 contenido_307)
        (paralela contenido_307 contenido_12)
        (paralela contenido_117 contenido_307)
        (paralela contenido_307 contenido_117)
        (= (minutos_contenido contenido_103) 40)
        (= (minutos_contenido contenido_12) 34)
        (= (minutos_contenido contenido_117) 87)
        (= (minutos_contenido contenido_307) 170)
        (paralela contenido_90 contenido_135)
        (paralela contenido_135 contenido_90)
        (paralela contenido_90 contenido_254)
        (paralela contenido_254 contenido_90)
        (paralela contenido_90 contenido_32)
        (paralela contenido_32 contenido_90)
        (paralela contenido_135 contenido_254)
        (paralela contenido_254 contenido_135)
        (paralela contenido_135 contenido_32)
        (paralela contenido_32 contenido_135)
        (paralela contenido_254 contenido_32)
        (paralela contenido_32 contenido_254)
        (= (minutos_contenido contenido_90) 78)
        (= (minutos_contenido contenido_135) 70)
        (= (minutos_contenido contenido_254) 48)
        (= (minutos_contenido contenido_32) 168)
        (paralela contenido_43 contenido_63)
        (paralela contenido_63 contenido_43)
        (paralela contenido_43 contenido_31)
        (paralela contenido_31 contenido_43)
        (paralela contenido_43 contenido_29)
        (paralela contenido_29 contenido_43)
        (paralela contenido_63 contenido_31)
        (paralela contenido_31 contenido_63)
        (paralela contenido_63 contenido_29)
        (paralela contenido_29 contenido_63)
        (paralela contenido_31 contenido_29)
        (paralela contenido_29 contenido_31)
        (= (minutos_contenido contenido_43) 62)
        (= (minutos_contenido contenido_63) 58)
        (= (minutos_contenido contenido_31) 12)
        (= (minutos_contenido contenido_29) 179)
        (paralela contenido_115 contenido_319)
        (paralela contenido_319 contenido_115)
        (paralela contenido_115 contenido_242)
        (paralela contenido_242 contenido_115)
        (paralela contenido_115 contenido_161)
        (paralela contenido_161 contenido_115)
        (paralela contenido_319 contenido_242)
        (paralela contenido_242 contenido_319)
        (paralela contenido_319 contenido_161)
        (paralela contenido_161 contenido_319)
        (paralela contenido_242 contenido_161)
        (paralela contenido_161 contenido_242)
        (= (minutos_contenido contenido_115) 87)
        (= (minutos_contenido contenido_319) 134)
        (= (minutos_contenido contenido_242) 28)
        (= (minutos_contenido contenido_161) 57)
        (paralela contenido_207 contenido_205)
        (paralela contenido_205 contenido_207)
        (paralela contenido_207 contenido_118)
        (paralela contenido_118 contenido_207)
        (paralela contenido_207 contenido_53)
        (paralela contenido_53 contenido_207)
        (paralela contenido_205 contenido_118)
        (paralela contenido_118 contenido_205)
        (paralela contenido_205 contenido_53)
        (paralela contenido_53 contenido_205)
        (paralela contenido_118 contenido_53)
        (paralela contenido_53 contenido_118)
        (= (minutos_contenido contenido_207) 125)
        (= (minutos_contenido contenido_205) 173)
        (= (minutos_contenido contenido_118) 16)
        (= (minutos_contenido contenido_53) 46)
        (paralela contenido_1 contenido_52)
        (paralela contenido_52 contenido_1)
        (paralela contenido_1 contenido_355)
        (paralela contenido_355 contenido_1)
        (paralela contenido_1 contenido_5)
        (paralela contenido_5 contenido_1)
        (paralela contenido_52 contenido_355)
        (paralela contenido_355 contenido_52)
        (paralela contenido_52 contenido_5)
        (paralela contenido_5 contenido_52)
        (paralela contenido_355 contenido_5)
        (paralela contenido_5 contenido_355)
        (= (minutos_contenido contenido_1) 77)
        (= (minutos_contenido contenido_52) 95)
        (= (minutos_contenido contenido_355) 42)
        (= (minutos_contenido contenido_5) 122)
        (paralela contenido_68 contenido_331)
        (paralela contenido_331 contenido_68)
        (paralela contenido_68 contenido_183)
        (paralela contenido_183 contenido_68)
        (paralela contenido_68 contenido_139)
        (paralela contenido_139 contenido_68)
        (paralela contenido_331 contenido_183)
        (paralela contenido_183 contenido_331)
        (paralela contenido_331 contenido_139)
        (paralela contenido_139 contenido_331)
        (paralela contenido_183 contenido_139)
        (paralela contenido_139 contenido_183)
        (= (minutos_contenido contenido_68) 105)
        (= (minutos_contenido contenido_331) 41)
        (= (minutos_contenido contenido_183) 69)
        (= (minutos_contenido contenido_139) 101)
        (paralela contenido_272 contenido_273)
        (paralela contenido_273 contenido_272)
        (paralela contenido_272 contenido_36)
        (paralela contenido_36 contenido_272)
        (paralela contenido_272 contenido_168)
        (paralela contenido_168 contenido_272)
        (paralela contenido_273 contenido_36)
        (paralela contenido_36 contenido_273)
        (paralela contenido_273 contenido_168)
        (paralela contenido_168 contenido_273)
        (paralela contenido_36 contenido_168)
        (paralela contenido_168 contenido_36)
        (= (minutos_contenido contenido_272) 144)
        (= (minutos_contenido contenido_273) 33)
        (= (minutos_contenido contenido_36) 36)
        (= (minutos_contenido contenido_168) 12)
        (paralelas_vistas contenido_66)
        (no_paralela contenido_66)
        (paralelas_vistas contenido_260)
        (no_paralela contenido_260)
        (paralelas_vistas contenido_177)
        (no_paralela contenido_177)
        (paralelas_vistas contenido_288)
        (no_paralela contenido_288)
        (paralelas_vistas contenido_146)
        (no_paralela contenido_146)
        (paralelas_vistas contenido_114)
        (no_paralela contenido_114)
        (paralelas_vistas contenido_233)
        (no_paralela contenido_233)
        (paralelas_vistas contenido_229)
        (no_paralela contenido_229)
        (paralelas_vistas contenido_211)
        (no_paralela contenido_211)
        (paralelas_vistas contenido_58)
        (no_paralela contenido_58)
        (paralelas_vistas contenido_120)
        (no_paralela contenido_120)
        (paralelas_vistas contenido_330)
        (no_paralela contenido_330)
        (paralelas_vistas contenido_78)
        (no_paralela contenido_78)
        (paralelas_vistas contenido_219)
        (no_paralela contenido_219)
        (paralelas_vistas contenido_123)
        (no_paralela contenido_123)
        (paralelas_vistas contenido_23)
        (no_paralela contenido_23)
        (paralelas_vistas contenido_340)
        (no_paralela contenido_340)
        (paralelas_vistas contenido_173)
        (no_paralela contenido_173)
        (paralelas_vistas contenido_261)
        (no_paralela contenido_261)
        (paralelas_vistas contenido_181)
        (no_paralela contenido_181)
        (paralelas_vistas contenido_208)
        (no_paralela contenido_208)
        (paralelas_vistas contenido_300)
        (no_paralela contenido_300)
        (paralelas_vistas contenido_287)
        (no_paralela contenido_287)
        (paralelas_vistas contenido_95)
        (no_paralela contenido_95)
        (paralelas_vistas contenido_343)
        (no_paralela contenido_343)
        (paralelas_vistas contenido_206)
        (no_paralela contenido_206)
        (paralelas_vistas contenido_192)
        (no_paralela contenido_192)
        (paralelas_vistas contenido_112)
        (no_paralela contenido_112)
        (paralelas_vistas contenido_171)
        (no_paralela contenido_171)
        (paralelas_vistas contenido_267)
        (no_paralela contenido_267)
        (paralelas_vistas contenido_138)
        (no_paralela contenido_138)
        (paralelas_vistas contenido_344)
        (no_paralela contenido_344)
        (paralelas_vistas contenido_209)
        (no_paralela contenido_209)
        (paralelas_vistas contenido_304)
        (no_paralela contenido_304)
        (paralelas_vistas contenido_134)
        (no_paralela contenido_134)
        (paralelas_vistas contenido_281)
        (no_paralela contenido_281)
        (paralelas_vistas contenido_140)
        (no_paralela contenido_140)
        (paralelas_vistas contenido_397)
        (no_paralela contenido_397)
        (paralelas_vistas contenido_367)
        (no_paralela contenido_367)
        (paralelas_vistas contenido_310)
        (no_paralela contenido_310)
        (paralelas_vistas contenido_67)
        (no_paralela contenido_67)
        (paralelas_vistas contenido_100)
        (no_paralela contenido_100)
        (paralelas_vistas contenido_231)
        (no_paralela contenido_231)
        (paralelas_vistas contenido_169)
        (no_paralela contenido_169)
        (paralelas_vistas contenido_270)
        (no_paralela contenido_270)
        (paralelas_vistas contenido_322)
        (no_paralela contenido_322)
        (paralelas_vistas contenido_126)
        (no_paralela contenido_126)
        (paralelas_vistas contenido_337)
        (no_paralela contenido_337)
        (paralelas_vistas contenido_283)
        (no_paralela contenido_283)
        (paralelas_vistas contenido_325)
        (no_paralela contenido_325)
        (paralelas_vistas contenido_365)
        (no_paralela contenido_365)
        (paralelas_vistas contenido_369)
        (no_paralela contenido_369)
        (paralelas_vistas contenido_314)
        (no_paralela contenido_314)
        (paralelas_vistas contenido_370)
        (no_paralela contenido_370)
        (paralelas_vistas contenido_345)
        (no_paralela contenido_345)
        (paralelas_vistas contenido_88)
        (no_paralela contenido_88)
        (paralelas_vistas contenido_11)
        (no_paralela contenido_11)
        (paralelas_vistas contenido_172)
        (no_paralela contenido_172)
        (paralelas_vistas contenido_125)
        (no_paralela contenido_125)
        (paralelas_vistas contenido_151)
        (no_paralela contenido_151)
        (paralelas_vistas contenido_85)
        (no_paralela contenido_85)
        (paralelas_vistas contenido_8)
        (no_paralela contenido_8)
        (paralelas_vistas contenido_4)
        (no_paralela contenido_4)
        (paralelas_vistas contenido_75)
        (no_paralela contenido_75)
        (paralelas_vistas contenido_309)
        (no_paralela contenido_309)
        (paralelas_vistas contenido_400)
        (no_paralela contenido_400)
        (paralelas_vistas contenido_62)
        (no_paralela contenido_62)
        (paralelas_vistas contenido_198)
        (no_paralela contenido_198)
        (paralelas_vistas contenido_199)
        (no_paralela contenido_199)
        (paralelas_vistas contenido_253)
        (no_paralela contenido_253)
        (paralelas_vistas contenido_187)
        (no_paralela contenido_187)
        (paralelas_vistas contenido_227)
        (no_paralela contenido_227)
        (paralelas_vistas contenido_271)
        (no_paralela contenido_271)
        (paralelas_vistas contenido_92)
        (no_paralela contenido_92)
        (paralelas_vistas contenido_158)
        (no_paralela contenido_158)
        (paralelas_vistas contenido_360)
        (no_paralela contenido_360)
        (paralelas_vistas contenido_42)
        (no_paralela contenido_42)
        (paralelas_vistas contenido_377)
        (no_paralela contenido_377)
        (paralelas_vistas contenido_129)
        (no_paralela contenido_129)
        (paralelas_vistas contenido_393)
        (no_paralela contenido_393)
        (paralelas_vistas contenido_293)
        (no_paralela contenido_293)
        (paralelas_vistas contenido_238)
        (no_paralela contenido_238)
        (paralelas_vistas contenido_216)
        (no_paralela contenido_216)
        (paralelas_vistas contenido_312)
        (no_paralela contenido_312)
        (paralelas_vistas contenido_256)
        (no_paralela contenido_256)
        (paralelas_vistas contenido_257)
        (no_paralela contenido_257)
        (paralelas_vistas contenido_297)
        (no_paralela contenido_297)
        (paralelas_vistas contenido_7)
        (no_paralela contenido_7)
        (paralelas_vistas contenido_73)
        (no_paralela contenido_73)
        (paralelas_vistas contenido_34)
        (no_paralela contenido_34)
        (paralelas_vistas contenido_243)
        (no_paralela contenido_243)
        (paralelas_vistas contenido_44)
        (no_paralela contenido_44)
        (paralelas_vistas contenido_264)
        (no_paralela contenido_264)
        (paralelas_vistas contenido_372)
        (no_paralela contenido_372)
        (paralelas_vistas contenido_342)
        (no_paralela contenido_342)
        (paralelas_vistas contenido_49)
        (no_paralela contenido_49)
        (paralelas_vistas contenido_55)
        (no_paralela contenido_55)
        (paralelas_vistas contenido_24)
        (no_paralela contenido_24)
        (paralelas_vistas contenido_51)
        (no_paralela contenido_51)
        (paralelas_vistas contenido_13)
        (no_paralela contenido_13)
        (paralelas_vistas contenido_97)
        (no_paralela contenido_97)
        (paralelas_vistas contenido_106)
        (no_paralela contenido_106)
        (paralelas_vistas contenido_182)
        (no_paralela contenido_182)
        (paralelas_vistas contenido_184)
        (no_paralela contenido_184)
        (paralelas_vistas contenido_305)
        (no_paralela contenido_305)
        (paralelas_vistas contenido_269)
        (no_paralela contenido_269)
        (paralelas_vistas contenido_137)
        (no_paralela contenido_137)
        (paralelas_vistas contenido_156)
        (no_paralela contenido_156)
        (paralelas_vistas contenido_165)
        (no_paralela contenido_165)
        (paralelas_vistas contenido_65)
        (no_paralela contenido_65)
        (paralelas_vistas contenido_383)
        (no_paralela contenido_383)
        (paralelas_vistas contenido_224)
        (no_paralela contenido_224)
        (paralelas_vistas contenido_376)
        (no_paralela contenido_376)
        (paralelas_vistas contenido_87)
        (no_paralela contenido_87)
        (paralelas_vistas contenido_239)
        (no_paralela contenido_239)
        (paralelas_vistas contenido_326)
        (no_paralela contenido_326)
        (paralelas_vistas contenido_352)
        (no_paralela contenido_352)
        (paralelas_vistas contenido_379)
        (no_paralela contenido_379)
        (paralelas_vistas contenido_41)
        (no_paralela contenido_41)
        (paralelas_vistas contenido_79)
        (no_paralela contenido_79)
        (paralelas_vistas contenido_144)
        (no_paralela contenido_144)
        (paralelas_vistas contenido_145)
        (no_paralela contenido_145)
        (paralelas_vistas contenido_311)
        (no_paralela contenido_311)
        (paralelas_vistas contenido_130)
        (no_paralela contenido_130)
        (paralelas_vistas contenido_2)
        (no_paralela contenido_2)
        (paralelas_vistas contenido_89)
        (no_paralela contenido_89)
        (paralelas_vistas contenido_195)
        (no_paralela contenido_195)
        (paralelas_vistas contenido_226)
        (no_paralela contenido_226)
        (paralelas_vistas contenido_368)
        (no_paralela contenido_368)
        (paralelas_vistas contenido_107)
        (no_paralela contenido_107)
        (paralelas_vistas contenido_57)
        (no_paralela contenido_57)
        (paralelas_vistas contenido_18)
        (no_paralela contenido_18)
        (paralelas_vistas contenido_381)
        (no_paralela contenido_381)
        (paralelas_vistas contenido_162)
        (no_paralela contenido_162)
        (paralelas_vistas contenido_110)
        (no_paralela contenido_110)
        (paralelas_vistas contenido_308)
        (no_paralela contenido_308)
        (paralelas_vistas contenido_128)
        (no_paralela contenido_128)
        (paralelas_vistas contenido_101)
        (no_paralela contenido_101)
        (paralelas_vistas contenido_374)
        (no_paralela contenido_374)
        (paralelas_vistas contenido_104)
        (no_paralela contenido_104)
        (paralelas_vistas contenido_217)
        (no_paralela contenido_217)
        (paralelas_vistas contenido_327)
        (no_paralela contenido_327)
        (paralelas_vistas contenido_225)
        (no_paralela contenido_225)
        (paralelas_vistas contenido_354)
        (no_paralela contenido_354)
        (paralelas_vistas contenido_148)
        (no_paralela contenido_148)
        (paralelas_vistas contenido_386)
        (no_paralela contenido_386)
        (paralelas_vistas contenido_392)
        (no_paralela contenido_392)
        (paralelas_vistas contenido_84)
        (no_paralela contenido_84)
        (paralelas_vistas contenido_278)
        (no_paralela contenido_278)
        (paralelas_vistas contenido_346)
        (no_paralela contenido_346)
        (paralelas_vistas contenido_70)
        (no_paralela contenido_70)
        (paralelas_vistas contenido_335)
        (no_paralela contenido_335)
        (paralelas_vistas contenido_174)
        (no_paralela contenido_174)
        (paralelas_vistas contenido_282)
        (no_paralela contenido_282)
        (paralelas_vistas contenido_25)
        (no_paralela contenido_25)
        (paralelas_vistas contenido_175)
        (no_paralela contenido_175)
        (paralelas_vistas contenido_232)
        (no_paralela contenido_232)
        (paralelas_vistas contenido_266)
        (no_paralela contenido_266)
        (paralelas_vistas contenido_22)
        (no_paralela contenido_22)
        (paralelas_vistas contenido_21)
        (no_paralela contenido_21)
        (paralelas_vistas contenido_303)
        (no_paralela contenido_303)
        (paralelas_vistas contenido_80)
        (no_paralela contenido_80)
        (paralelas_vistas contenido_371)
        (no_paralela contenido_371)
        (paralelas_vistas contenido_35)
        (no_paralela contenido_35)
        (paralelas_vistas contenido_284)
        (no_paralela contenido_284)
        (paralelas_vistas contenido_366)
        (no_paralela contenido_366)
        (paralelas_vistas contenido_277)
        (no_paralela contenido_277)
        (paralelas_vistas contenido_223)
        (no_paralela contenido_223)
        (paralelas_vistas contenido_399)
        (no_paralela contenido_399)
        (paralelas_vistas contenido_329)
        (no_paralela contenido_329)
        (paralelas_vistas contenido_359)
        (no_paralela contenido_359)
        (paralelas_vistas contenido_86)
        (no_paralela contenido_86)
        (paralelas_vistas contenido_179)
        (no_paralela contenido_179)
        (paralelas_vistas contenido_294)
        (no_paralela contenido_294)
        (paralelas_vistas contenido_159)
        (no_paralela contenido_159)
        (paralelas_vistas contenido_188)
        (no_paralela contenido_188)
        (paralelas_vistas contenido_248)
        (no_paralela contenido_248)
        (paralelas_vistas contenido_347)
        (no_paralela contenido_347)
        (paralelas_vistas contenido_76)
        (no_paralela contenido_76)
        (paralelas_vistas contenido_334)
        (no_paralela contenido_334)
        (paralelas_vistas contenido_387)
        (no_paralela contenido_387)
        (paralelas_vistas contenido_142)
        (no_paralela contenido_142)
        (paralelas_vistas contenido_274)
        (no_paralela contenido_274)
        (paralelas_vistas contenido_220)
        (no_paralela contenido_220)
        (paralelas_vistas contenido_94)
        (no_paralela contenido_94)
        (paralelas_vistas contenido_45)
        (no_paralela contenido_45)
        (paralelas_vistas contenido_127)
        (no_paralela contenido_127)
        (paralelas_vistas contenido_167)
        (no_paralela contenido_167)
        (paralelas_vistas contenido_105)
        (no_paralela contenido_105)
        (paralelas_vistas contenido_246)
        (no_paralela contenido_246)
        (paralelas_vistas contenido_339)
        (no_paralela contenido_339)
        (paralelas_vistas contenido_348)
        (no_paralela contenido_348)
        (paralelas_vistas contenido_50)
        (no_paralela contenido_50)
        (paralelas_vistas contenido_26)
        (no_paralela contenido_26)
        (paralelas_vistas contenido_132)
        (no_paralela contenido_132)
        (paralelas_vistas contenido_295)
        (no_paralela contenido_295)
        (paralelas_vistas contenido_116)
        (no_paralela contenido_116)
        (paralelas_vistas contenido_358)
        (no_paralela contenido_358)
        (paralelas_vistas contenido_388)
        (no_paralela contenido_388)
        (paralelas_vistas contenido_375)
        (no_paralela contenido_375)
        (paralelas_vistas contenido_200)
        (no_paralela contenido_200)
        (paralelas_vistas contenido_149)
        (no_paralela contenido_149)
        (paralelas_vistas contenido_155)
        (no_paralela contenido_155)
        (paralelas_vistas contenido_236)
        (no_paralela contenido_236)
        (paralelas_vistas contenido_237)
        (no_paralela contenido_237)
        (paralelas_vistas contenido_361)
        (no_paralela contenido_361)
        (paralelas_vistas contenido_48)
        (no_paralela contenido_48)
        (paralelas_vistas contenido_235)
        (no_paralela contenido_235)
        (paralelas_vistas contenido_394)
        (no_paralela contenido_394)
        (paralelas_vistas contenido_396)
        (no_paralela contenido_396)
        (paralelas_vistas contenido_349)
        (no_paralela contenido_349)
        (paralelas_vistas contenido_141)
        (no_paralela contenido_141)
        (paralelas_vistas contenido_276)
        (no_paralela contenido_276)
        (paralelas_vistas contenido_124)
        (no_paralela contenido_124)
        (paralelas_vistas contenido_91)
        (no_paralela contenido_91)
        (paralelas_vistas contenido_204)
        (no_paralela contenido_204)
        (paralelas_vistas contenido_389)
        (no_paralela contenido_389)
        (paralelas_vistas contenido_154)
        (no_paralela contenido_154)
        (paralelas_vistas contenido_71)
        (no_paralela contenido_71)
        (paralelas_vistas contenido_72)
        (no_paralela contenido_72)
        (paralelas_vistas contenido_363)
        (no_paralela contenido_363)
        (paralelas_vistas contenido_136)
        (no_paralela contenido_136)
        (paralelas_vistas contenido_61)
        (no_paralela contenido_61)
        (paralelas_vistas contenido_180)
        (no_paralela contenido_180)
        (paralelas_vistas contenido_318)
        (no_paralela contenido_318)
        (paralelas_vistas contenido_131)
        (no_paralela contenido_131)
        (paralelas_vistas contenido_218)
        (no_paralela contenido_218)
        (paralelas_vistas contenido_289)
        (no_paralela contenido_289)
        (paralelas_vistas contenido_324)
        (no_paralela contenido_324)
        (paralelas_vistas contenido_362)
        (no_paralela contenido_362)
        (paralelas_vistas contenido_163)
        (no_paralela contenido_163)
        (paralelas_vistas contenido_176)
        (no_paralela contenido_176)
        (paralelas_vistas contenido_178)
        (no_paralela contenido_178)
        (paralelas_vistas contenido_364)
        (no_paralela contenido_364)
        (paralelas_vistas contenido_391)
        (no_paralela contenido_391)
        (paralelas_vistas contenido_147)
        (no_paralela contenido_147)
        (paralelas_vistas contenido_262)
        (no_paralela contenido_262)
        (paralelas_vistas contenido_292)
        (no_paralela contenido_292)
        (paralelas_vistas contenido_190)
        (no_paralela contenido_190)
        (paralelas_vistas contenido_280)
        (no_paralela contenido_280)
        (paralelas_vistas contenido_215)
        (no_paralela contenido_215)
        (paralelas_vistas contenido_38)
        (no_paralela contenido_38)
        (paralelas_vistas contenido_291)
        (no_paralela contenido_291)
        (paralelas_vistas contenido_286)
        (no_paralela contenido_286)
        (paralelas_vistas contenido_390)
        (no_paralela contenido_390)
        (paralelas_vistas contenido_213)
        (no_paralela contenido_213)
        (paralelas_vistas contenido_306)
        (no_paralela contenido_306)
        (paralelas_vistas contenido_185)
        (no_paralela contenido_185)
        (paralelas_vistas contenido_313)
        (no_paralela contenido_313)
        (paralelas_vistas contenido_332)
        (no_paralela contenido_332)
        (paralelas_vistas contenido_37)
        (no_paralela contenido_37)
        (paralelas_vistas contenido_268)
        (no_paralela contenido_268)
        (paralelas_vistas contenido_290)
        (no_paralela contenido_290)
        (paralelas_vistas contenido_385)
        (no_paralela contenido_385)
        (paralelas_vistas contenido_170)
        (no_paralela contenido_170)
        (paralelas_vistas contenido_164)
        (no_paralela contenido_164)
        (paralelas_vistas contenido_64)
        (no_paralela contenido_64)
        (paralelas_vistas contenido_150)
        (no_paralela contenido_150)
        (paralelas_vistas contenido_202)
        (no_paralela contenido_202)
        (paralelas_vistas contenido_299)
        (no_paralela contenido_299)
        (paralelas_vistas contenido_111)
        (no_paralela contenido_111)
        (paralelas_vistas contenido_321)
        (no_paralela contenido_321)
        (paralelas_vistas contenido_382)
        (no_paralela contenido_382)
        (paralelas_vistas contenido_191)
        (no_paralela contenido_191)
        (paralelas_vistas contenido_258)
        (no_paralela contenido_258)
        (paralelas_vistas contenido_122)
        (no_paralela contenido_122)
        (paralelas_vistas contenido_245)
        (no_paralela contenido_245)
        (paralelas_vistas contenido_249)
        (no_paralela contenido_249)
        (paralelas_vistas contenido_244)
        (no_paralela contenido_244)
        (paralelas_vistas contenido_395)
        (no_paralela contenido_395)
        (paralelas_vistas contenido_275)
        (no_paralela contenido_275)
        (paralelas_vistas contenido_250)
        (no_paralela contenido_250)
        (paralelas_vistas contenido_119)
        (no_paralela contenido_119)
        (paralelas_vistas contenido_357)
        (no_paralela contenido_357)
        (paralelas_vistas contenido_212)
        (no_paralela contenido_212)
        (paralelas_vistas contenido_317)
        (no_paralela contenido_317)
        (paralelas_vistas contenido_196)
        (no_paralela contenido_196)
        (paralelas_vistas contenido_316)
        (no_paralela contenido_316)
        (paralelas_vistas contenido_341)
        (no_paralela contenido_341)
        (paralelas_vistas contenido_221)
        (no_paralela contenido_221)
        (paralelas_vistas contenido_82)
        (no_paralela contenido_82)
        (paralelas_vistas contenido_69)
        (no_paralela contenido_69)
        (paralelas_vistas contenido_228)
        (no_paralela contenido_228)
        (paralelas_vistas contenido_259)
        (no_paralela contenido_259)
        (paralelas_vistas contenido_240)
        (no_paralela contenido_240)
        (paralelas_vistas contenido_279)
        (no_paralela contenido_279)
        (paralelas_vistas contenido_336)
        (no_paralela contenido_336)
        (paralelas_vistas contenido_373)
        (no_paralela contenido_373)
        (paralelas_vistas contenido_6)
        (no_paralela contenido_6)
        (paralelas_vistas contenido_234)
        (no_paralela contenido_234)
        (paralelas_vistas contenido_255)
        (no_paralela contenido_255)
        (paralelas_vistas contenido_241)
        (no_paralela contenido_241)
        (paralelas_vistas contenido_143)
        (no_paralela contenido_143)
        (paralelas_vistas contenido_160)
        (no_paralela contenido_160)
        (paralelas_vistas contenido_333)
        (no_paralela contenido_333)
        (paralelas_vistas contenido_398)
        (no_paralela contenido_398)
        (paralelas_vistas contenido_152)
        (no_paralela contenido_152)
        (paralelas_vistas contenido_214)
        (no_paralela contenido_214)
        (paralelas_vistas contenido_323)
        (no_paralela contenido_323)
        (paralelas_vistas contenido_113)
        (no_paralela contenido_113)
        (predecesores_vistos contenido_66)
        (predecesores_vistos contenido_177)
        (predecesores_vistos contenido_233)
        (predecesores_vistos contenido_114)
        (predecesores_vistos contenido_229)
        (predecesores_vistos contenido_120)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_300)
        (predecesores_vistos contenido_95)
        (predecesores_vistos contenido_192)
        (predecesores_vistos contenido_112)
        (predecesores_vistos contenido_171)
        (predecesores_vistos contenido_344)
        (predecesores_vistos contenido_304)
        (predecesores_vistos contenido_134)
        (predecesores_vistos contenido_281)
        (predecesores_vistos contenido_140)
        (predecesores_vistos contenido_367)
        (predecesores_vistos contenido_67)
        (predecesores_vistos contenido_231)
        (predecesores_vistos contenido_270)
        (predecesores_vistos contenido_370)
        (predecesores_vistos contenido_314)
        (predecesores_vistos contenido_88)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_125)
        (predecesores_vistos contenido_85)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_75)
        (predecesores_vistos contenido_151)
        (predecesores_vistos contenido_62)
        (predecesores_vistos contenido_198)
        (predecesores_vistos contenido_187)
        (predecesores_vistos contenido_271)
        (predecesores_vistos contenido_92)
        (predecesores_vistos contenido_158)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_129)
        (predecesores_vistos contenido_238)
        (predecesores_vistos contenido_256)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_73)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_243)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_264)
        (predecesores_vistos contenido_49)
        (predecesores_vistos contenido_55)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_182)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_305)
        (predecesores_vistos contenido_137)
        (predecesores_vistos contenido_165)
        (predecesores_vistos contenido_383)
        (predecesores_vistos contenido_87)
        (predecesores_vistos contenido_41)
        (predecesores_vistos contenido_144)
        (predecesores_vistos contenido_130)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_89)
        (predecesores_vistos contenido_195)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_162)
        (predecesores_vistos contenido_110)
        (predecesores_vistos contenido_128)
        (predecesores_vistos contenido_101)
        (predecesores_vistos contenido_104)
        (predecesores_vistos contenido_70)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_174)
        (predecesores_vistos contenido_232)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_303)
        (predecesores_vistos contenido_80)
        (predecesores_vistos contenido_35)
        (predecesores_vistos contenido_371)
        (predecesores_vistos contenido_277)
        (predecesores_vistos contenido_223)
        (predecesores_vistos contenido_329)
        (predecesores_vistos contenido_86)
        (predecesores_vistos contenido_359)
        (predecesores_vistos contenido_387)
        (predecesores_vistos contenido_142)
        (predecesores_vistos contenido_45)
        (predecesores_vistos contenido_105)
        (predecesores_vistos contenido_246)
        (predecesores_vistos contenido_50)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_116)
        (predecesores_vistos contenido_358)
        (predecesores_vistos contenido_149)
        (predecesores_vistos contenido_155)
        (predecesores_vistos contenido_361)
        (predecesores_vistos contenido_235)
        (predecesores_vistos contenido_141)
        (predecesores_vistos contenido_91)
        (predecesores_vistos contenido_154)
        (predecesores_vistos contenido_71)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_61)
        (predecesores_vistos contenido_289)
        (predecesores_vistos contenido_163)
        (predecesores_vistos contenido_178)
        (predecesores_vistos contenido_364)
        (predecesores_vistos contenido_190)
        (predecesores_vistos contenido_38)
        (predecesores_vistos contenido_291)
        (predecesores_vistos contenido_286)
        (predecesores_vistos contenido_37)
        (predecesores_vistos contenido_268)
        (predecesores_vistos contenido_385)
        (predecesores_vistos contenido_164)
        (predecesores_vistos contenido_64)
        (predecesores_vistos contenido_202)
        (predecesores_vistos contenido_299)
        (predecesores_vistos contenido_258)
        (predecesores_vistos contenido_122)
        (predecesores_vistos contenido_249)
        (predecesores_vistos contenido_119)
        (predecesores_vistos contenido_196)
        (predecesores_vistos contenido_69)
        (predecesores_vistos contenido_240)
        (predecesores_vistos contenido_373)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_143)
        (predecesores_vistos contenido_160)
        (predecesores_vistos contenido_333)
        (predecesores_vistos contenido_323)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
