(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100
    )

    (:init
        (predecesor contenido_8 contenido_95)
        (predecesor contenido_51 contenido_100)
        (predecesor contenido_73 contenido_74)
        (predecesor contenido_38 contenido_100)
        (predecesor contenido_50 contenido_74)
        (predecesor contenido_7 contenido_24)
        (predecesor contenido_11 contenido_63)
        (predecesor contenido_38 contenido_56)
        (predecesor contenido_56 contenido_82)
        (predecesor contenido_82 contenido_86)
        (predecesor contenido_22 contenido_43)
        (predecesor contenido_9 contenido_38)
        (predecesor contenido_4 contenido_21)
        (predecesor contenido_17 contenido_69)
        (predecesor contenido_35 contenido_65)
        (predecesor contenido_44 contenido_90)
        (predecesor contenido_11 contenido_44)
        (predecesor contenido_41 contenido_94)
        (predecesor contenido_22 contenido_76)
        (predecesor contenido_35 contenido_73)
        (predecesor contenido_18 contenido_59)
        (predecesor contenido_1 contenido_56)
        (predecesor contenido_18 contenido_62)
        (predecesor contenido_35 contenido_57)
        (predecesor contenido_64 contenido_98)
        (predecesor contenido_14 contenido_70)
        (predecesor contenido_50 contenido_56)
        (predecesor contenido_4 contenido_33)
        (predecesor contenido_16 contenido_34)
        (predecesor contenido_44 contenido_67)
        (predecesor contenido_2 contenido_46)
        (predecesor contenido_79 contenido_82)
        (predecesor contenido_2 contenido_51)
        (predecesor contenido_64 contenido_94)
        (predecesor contenido_84 contenido_99)
        (predecesor contenido_10 contenido_70)
        (predecesor contenido_1 contenido_77)
        (predecesor contenido_29 contenido_73)
        (predecesor contenido_6 contenido_12)
        (predecesor contenido_47 contenido_59)
        (predecesor contenido_46 contenido_91)
        (predecesor contenido_27 contenido_78)
        (predecesor contenido_7 contenido_35)
        (predecesor contenido_24 contenido_93)
        (predecesor contenido_36 contenido_44)
        (predecesor contenido_50 contenido_69)
        (predecesor contenido_18 contenido_69)
        (predecesor contenido_16 contenido_81)
        (predecesor contenido_44 contenido_71)
        (predecesor contenido_30 contenido_52)
        (predecesor contenido_81 contenido_93)
        (predecesor contenido_44 contenido_97)
        (predecesor contenido_67 contenido_86)
        (predecesor contenido_30 contenido_70)
        (predecesor contenido_44 contenido_72)
        (predecesor contenido_44 contenido_65)
        (predecesor contenido_34 contenido_61)
        (predecesor contenido_5 contenido_99)
        (predecesor contenido_60 contenido_74)
        (predecesor contenido_33 contenido_46)
        (predecesor contenido_55 contenido_85)
        (predecesor contenido_65 contenido_78)
        (predecesor contenido_26 contenido_98)
        (predecesor contenido_40 contenido_44)
        (predecesor contenido_3 contenido_25)
        (predecesor contenido_43 contenido_54)
        (predecesor contenido_26 contenido_65)
        (predecesor contenido_55 contenido_100)
        (predecesor contenido_65 contenido_74)
        (predecesor contenido_47 contenido_86)
        (predecesor contenido_43 contenido_90)
        (predecesor contenido_19 contenido_48)
        (predecesor contenido_45 contenido_58)
        (predecesor contenido_49 contenido_69)
        (predecesor contenido_20 contenido_69)
        (predecesor contenido_14 contenido_80)
        (predecesor contenido_17 contenido_62)
        (predecesor contenido_23 contenido_72)
        (predecesor contenido_12 contenido_99)
        (predecesor contenido_9 contenido_66)
        (paralela contenido_19 contenido_32)
        (paralela contenido_32 contenido_19)
        (paralela contenido_19 contenido_53)
        (paralela contenido_53 contenido_19)
        (paralela contenido_19 contenido_7)
        (paralela contenido_7 contenido_19)
        (paralela contenido_32 contenido_53)
        (paralela contenido_53 contenido_32)
        (paralela contenido_32 contenido_7)
        (paralela contenido_7 contenido_32)
        (paralela contenido_53 contenido_7)
        (paralela contenido_7 contenido_53)
        (= (minutos_contenido contenido_19) 118)
        (= (minutos_contenido contenido_32) 21)
        (= (minutos_contenido contenido_53) 165)
        (= (minutos_contenido contenido_7) 13)
        (paralela contenido_17 contenido_30)
        (paralela contenido_30 contenido_17)
        (paralela contenido_17 contenido_20)
        (paralela contenido_20 contenido_17)
        (paralela contenido_17 contenido_55)
        (paralela contenido_55 contenido_17)
        (paralela contenido_30 contenido_20)
        (paralela contenido_20 contenido_30)
        (paralela contenido_30 contenido_55)
        (paralela contenido_55 contenido_30)
        (paralela contenido_20 contenido_55)
        (paralela contenido_55 contenido_20)
        (= (minutos_contenido contenido_17) 21)
        (= (minutos_contenido contenido_30) 78)
        (= (minutos_contenido contenido_20) 144)
        (= (minutos_contenido contenido_55) 52)
        (paralela contenido_42 contenido_6)
        (paralela contenido_6 contenido_42)
        (paralela contenido_42 contenido_37)
        (paralela contenido_37 contenido_42)
        (paralela contenido_42 contenido_16)
        (paralela contenido_16 contenido_42)
        (paralela contenido_6 contenido_37)
        (paralela contenido_37 contenido_6)
        (paralela contenido_6 contenido_16)
        (paralela contenido_16 contenido_6)
        (paralela contenido_37 contenido_16)
        (paralela contenido_16 contenido_37)
        (= (minutos_contenido contenido_42) 145)
        (= (minutos_contenido contenido_6) 33)
        (= (minutos_contenido contenido_37) 36)
        (= (minutos_contenido contenido_16) 123)
        (paralela contenido_47 contenido_11)
        (paralela contenido_11 contenido_47)
        (paralela contenido_47 contenido_23)
        (paralela contenido_23 contenido_47)
        (paralela contenido_47 contenido_84)
        (paralela contenido_84 contenido_47)
        (paralela contenido_11 contenido_23)
        (paralela contenido_23 contenido_11)
        (paralela contenido_11 contenido_84)
        (paralela contenido_84 contenido_11)
        (paralela contenido_23 contenido_84)
        (paralela contenido_84 contenido_23)
        (= (minutos_contenido contenido_47) 136)
        (= (minutos_contenido contenido_11) 44)
        (= (minutos_contenido contenido_23) 59)
        (= (minutos_contenido contenido_84) 64)
        (paralela contenido_92 contenido_64)
        (paralela contenido_64 contenido_92)
        (paralela contenido_92 contenido_45)
        (paralela contenido_45 contenido_92)
        (paralela contenido_92 contenido_14)
        (paralela contenido_14 contenido_92)
        (paralela contenido_64 contenido_45)
        (paralela contenido_45 contenido_64)
        (paralela contenido_64 contenido_14)
        (paralela contenido_14 contenido_64)
        (paralela contenido_45 contenido_14)
        (paralela contenido_14 contenido_45)
        (= (minutos_contenido contenido_92) 71)
        (= (minutos_contenido contenido_64) 19)
        (= (minutos_contenido contenido_45) 72)
        (= (minutos_contenido contenido_14) 63)
        (paralela contenido_41 contenido_36)
        (paralela contenido_36 contenido_41)
        (paralela contenido_41 contenido_5)
        (paralela contenido_5 contenido_41)
        (paralela contenido_41 contenido_60)
        (paralela contenido_60 contenido_41)
        (paralela contenido_36 contenido_5)
        (paralela contenido_5 contenido_36)
        (paralela contenido_36 contenido_60)
        (paralela contenido_60 contenido_36)
        (paralela contenido_5 contenido_60)
        (paralela contenido_60 contenido_5)
        (= (minutos_contenido contenido_41) 28)
        (= (minutos_contenido contenido_36) 113)
        (= (minutos_contenido contenido_5) 16)
        (= (minutos_contenido contenido_60) 12)
        (paralelas_vistas contenido_13)
        (no_paralela contenido_13)
        (paralelas_vistas contenido_95)
        (no_paralela contenido_95)
        (paralelas_vistas contenido_99)
        (no_paralela contenido_99)
        (paralelas_vistas contenido_87)
        (no_paralela contenido_87)
        (paralelas_vistas contenido_9)
        (no_paralela contenido_9)
        (paralelas_vistas contenido_57)
        (no_paralela contenido_57)
        (paralelas_vistas contenido_58)
        (no_paralela contenido_58)
        (paralelas_vistas contenido_29)
        (no_paralela contenido_29)
        (paralelas_vistas contenido_68)
        (no_paralela contenido_68)
        (paralelas_vistas contenido_93)
        (no_paralela contenido_93)
        (paralelas_vistas contenido_21)
        (no_paralela contenido_21)
        (paralelas_vistas contenido_81)
        (no_paralela contenido_81)
        (paralelas_vistas contenido_34)
        (no_paralela contenido_34)
        (paralelas_vistas contenido_2)
        (no_paralela contenido_2)
        (paralelas_vistas contenido_25)
        (no_paralela contenido_25)
        (paralelas_vistas contenido_35)
        (no_paralela contenido_35)
        (paralelas_vistas contenido_75)
        (no_paralela contenido_75)
        (paralelas_vistas contenido_18)
        (no_paralela contenido_18)
        (paralelas_vistas contenido_83)
        (no_paralela contenido_83)
        (paralelas_vistas contenido_70)
        (no_paralela contenido_70)
        (paralelas_vistas contenido_27)
        (no_paralela contenido_27)
        (paralelas_vistas contenido_71)
        (no_paralela contenido_71)
        (paralelas_vistas contenido_85)
        (no_paralela contenido_85)
        (paralelas_vistas contenido_22)
        (no_paralela contenido_22)
        (paralelas_vistas contenido_43)
        (no_paralela contenido_43)
        (paralelas_vistas contenido_50)
        (no_paralela contenido_50)
        (paralelas_vistas contenido_51)
        (no_paralela contenido_51)
        (paralelas_vistas contenido_77)
        (no_paralela contenido_77)
        (paralelas_vistas contenido_39)
        (no_paralela contenido_39)
        (paralelas_vistas contenido_54)
        (no_paralela contenido_54)
        (paralelas_vistas contenido_98)
        (no_paralela contenido_98)
        (paralelas_vistas contenido_90)
        (no_paralela contenido_90)
        (paralelas_vistas contenido_26)
        (no_paralela contenido_26)
        (paralelas_vistas contenido_78)
        (no_paralela contenido_78)
        (paralelas_vistas contenido_91)
        (no_paralela contenido_91)
        (paralelas_vistas contenido_66)
        (no_paralela contenido_66)
        (paralelas_vistas contenido_59)
        (no_paralela contenido_59)
        (paralelas_vistas contenido_52)
        (no_paralela contenido_52)
        (paralelas_vistas contenido_15)
        (no_paralela contenido_15)
        (paralelas_vistas contenido_40)
        (no_paralela contenido_40)
        (paralelas_vistas contenido_56)
        (no_paralela contenido_56)
        (paralelas_vistas contenido_65)
        (no_paralela contenido_65)
        (paralelas_vistas contenido_88)
        (no_paralela contenido_88)
        (paralelas_vistas contenido_46)
        (no_paralela contenido_46)
        (paralelas_vistas contenido_10)
        (no_paralela contenido_10)
        (paralelas_vistas contenido_12)
        (no_paralela contenido_12)
        (paralelas_vistas contenido_49)
        (no_paralela contenido_49)
        (paralelas_vistas contenido_63)
        (no_paralela contenido_63)
        (paralelas_vistas contenido_69)
        (no_paralela contenido_69)
        (paralelas_vistas contenido_73)
        (no_paralela contenido_73)
        (paralelas_vistas contenido_61)
        (no_paralela contenido_61)
        (paralelas_vistas contenido_80)
        (no_paralela contenido_80)
        (paralelas_vistas contenido_44)
        (no_paralela contenido_44)
        (paralelas_vistas contenido_94)
        (no_paralela contenido_94)
        (paralelas_vistas contenido_96)
        (no_paralela contenido_96)
        (paralelas_vistas contenido_97)
        (no_paralela contenido_97)
        (paralelas_vistas contenido_28)
        (no_paralela contenido_28)
        (paralelas_vistas contenido_48)
        (no_paralela contenido_48)
        (paralelas_vistas contenido_74)
        (no_paralela contenido_74)
        (paralelas_vistas contenido_82)
        (no_paralela contenido_82)
        (paralelas_vistas contenido_89)
        (no_paralela contenido_89)
        (paralelas_vistas contenido_76)
        (no_paralela contenido_76)
        (paralelas_vistas contenido_8)
        (no_paralela contenido_8)
        (paralelas_vistas contenido_1)
        (no_paralela contenido_1)
        (paralelas_vistas contenido_86)
        (no_paralela contenido_86)
        (paralelas_vistas contenido_31)
        (no_paralela contenido_31)
        (paralelas_vistas contenido_38)
        (no_paralela contenido_38)
        (paralelas_vistas contenido_4)
        (no_paralela contenido_4)
        (paralelas_vistas contenido_72)
        (no_paralela contenido_72)
        (paralelas_vistas contenido_79)
        (no_paralela contenido_79)
        (paralelas_vistas contenido_3)
        (no_paralela contenido_3)
        (paralelas_vistas contenido_100)
        (no_paralela contenido_100)
        (paralelas_vistas contenido_62)
        (no_paralela contenido_62)
        (paralelas_vistas contenido_24)
        (no_paralela contenido_24)
        (paralelas_vistas contenido_67)
        (no_paralela contenido_67)
        (paralelas_vistas contenido_33)
        (no_paralela contenido_33)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_87)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_68)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_75)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_83)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_50)
        (predecesores_vistos contenido_39)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_88)
        (predecesores_vistos contenido_49)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_96)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_89)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_79)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_4)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
