(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125
    )

    (:init
        (predecesor contenido_12 contenido_35)
        (predecesor contenido_10 contenido_70)
        (predecesor contenido_101 contenido_116)
        (predecesor contenido_50 contenido_69)
        (predecesor contenido_2 contenido_102)
        (predecesor contenido_98 contenido_115)
        (predecesor contenido_44 contenido_72)
        (predecesor contenido_20 contenido_69)
        (predecesor contenido_1 contenido_116)
        (predecesor contenido_52 contenido_69)
        (predecesor contenido_34 contenido_51)
        (predecesor contenido_56 contenido_100)
        (predecesor contenido_78 contenido_82)
        (predecesor contenido_106 contenido_113)
        (predecesor contenido_43 contenido_90)
        (predecesor contenido_41 contenido_94)
        (predecesor contenido_18 contenido_59)
        (predecesor contenido_33 contenido_92)
        (predecesor contenido_7 contenido_35)
        (predecesor contenido_38 contenido_100)
        (predecesor contenido_33 contenido_103)
        (predecesor contenido_5 contenido_109)
        (predecesor contenido_56 contenido_115)
        (predecesor contenido_12 contenido_99)
        (predecesor contenido_16 contenido_81)
        (predecesor contenido_68 contenido_73)
        (predecesor contenido_10 contenido_93)
        (predecesor contenido_19 contenido_48)
        (predecesor contenido_63 contenido_67)
        (predecesor contenido_5 contenido_97)
        (predecesor contenido_25 contenido_76)
        (predecesor contenido_69 contenido_125)
        (predecesor contenido_21 contenido_114)
        (predecesor contenido_99 contenido_118)
        (predecesor contenido_24 contenido_93)
        (predecesor contenido_12 contenido_107)
        (predecesor contenido_46 contenido_88)
        (predecesor contenido_44 contenido_65)
        (predecesor contenido_104 contenido_123)
        (predecesor contenido_44 contenido_51)
        (predecesor contenido_51 contenido_115)
        (predecesor contenido_8 contenido_82)
        (predecesor contenido_104 contenido_120)
        (predecesor contenido_12 contenido_113)
        (predecesor contenido_22 contenido_103)
        (predecesor contenido_82 contenido_102)
        (predecesor contenido_3 contenido_45)
        (predecesor contenido_48 contenido_66)
        (predecesor contenido_102 contenido_117)
        (predecesor contenido_2 contenido_115)
        (predecesor contenido_65 contenido_93)
        (predecesor contenido_11 contenido_77)
        (predecesor contenido_14 contenido_80)
        (predecesor contenido_35 contenido_123)
        (predecesor contenido_30 contenido_70)
        (predecesor contenido_9 contenido_92)
        (predecesor contenido_51 contenido_114)
        (predecesor contenido_62 contenido_64)
        (predecesor contenido_22 contenido_43)
        (predecesor contenido_37 contenido_64)
        (predecesor contenido_34 contenido_61)
        (predecesor contenido_3 contenido_38)
        (predecesor contenido_69 contenido_72)
        (predecesor contenido_82 contenido_125)
        (predecesor contenido_74 contenido_100)
        (predecesor contenido_106 contenido_117)
        (predecesor contenido_59 contenido_86)
        (predecesor contenido_44 contenido_67)
        (predecesor contenido_56 contenido_82)
        (predecesor contenido_25 contenido_35)
        (predecesor contenido_14 contenido_70)
        (predecesor contenido_44 contenido_71)
        (predecesor contenido_14 contenido_108)
        (predecesor contenido_29 contenido_115)
        (predecesor contenido_81 contenido_93)
        (predecesor contenido_12 contenido_86)
        (predecesor contenido_5 contenido_49)
        (predecesor contenido_21 contenido_67)
        (predecesor contenido_55 contenido_102)
        (predecesor contenido_4 contenido_82)
        (predecesor contenido_58 contenido_112)
        (predecesor contenido_27 contenido_106)
        (predecesor contenido_46 contenido_91)
        (predecesor contenido_9 contenido_66)
        (predecesor contenido_42 contenido_112)
        (predecesor contenido_6 contenido_121)
        (predecesor contenido_43 contenido_44)
        (paralela contenido_50 contenido_5)
        (paralela contenido_5 contenido_50)
        (paralela contenido_50 contenido_75)
        (paralela contenido_75 contenido_50)
        (paralela contenido_50 contenido_40)
        (paralela contenido_40 contenido_50)
        (paralela contenido_5 contenido_75)
        (paralela contenido_75 contenido_5)
        (paralela contenido_5 contenido_40)
        (paralela contenido_40 contenido_5)
        (paralela contenido_75 contenido_40)
        (paralela contenido_40 contenido_75)
        (= (minutos_contenido contenido_50) 104)
        (= (minutos_contenido contenido_5) 27)
        (= (minutos_contenido contenido_75) 85)
        (= (minutos_contenido contenido_40) 41)
        (paralela contenido_60 contenido_110)
        (paralela contenido_110 contenido_60)
        (paralela contenido_60 contenido_21)
        (paralela contenido_21 contenido_60)
        (paralela contenido_60 contenido_20)
        (paralela contenido_20 contenido_60)
        (paralela contenido_110 contenido_21)
        (paralela contenido_21 contenido_110)
        (paralela contenido_110 contenido_20)
        (paralela contenido_20 contenido_110)
        (paralela contenido_21 contenido_20)
        (paralela contenido_20 contenido_21)
        (= (minutos_contenido contenido_60) 24)
        (= (minutos_contenido contenido_110) 107)
        (= (minutos_contenido contenido_21) 23)
        (= (minutos_contenido contenido_20) 160)
        (paralela contenido_14 contenido_29)
        (paralela contenido_29 contenido_14)
        (paralela contenido_14 contenido_124)
        (paralela contenido_124 contenido_14)
        (paralela contenido_14 contenido_24)
        (paralela contenido_24 contenido_14)
        (paralela contenido_29 contenido_124)
        (paralela contenido_124 contenido_29)
        (paralela contenido_29 contenido_24)
        (paralela contenido_24 contenido_29)
        (paralela contenido_124 contenido_24)
        (paralela contenido_24 contenido_124)
        (= (minutos_contenido contenido_14) 109)
        (= (minutos_contenido contenido_29) 86)
        (= (minutos_contenido contenido_124) 37)
        (= (minutos_contenido contenido_24) 129)
        (paralela contenido_3 contenido_55)
        (paralela contenido_55 contenido_3)
        (paralela contenido_3 contenido_18)
        (paralela contenido_18 contenido_3)
        (paralela contenido_3 contenido_39)
        (paralela contenido_39 contenido_3)
        (paralela contenido_55 contenido_18)
        (paralela contenido_18 contenido_55)
        (paralela contenido_55 contenido_39)
        (paralela contenido_39 contenido_55)
        (paralela contenido_18 contenido_39)
        (paralela contenido_39 contenido_18)
        (= (minutos_contenido contenido_3) 80)
        (= (minutos_contenido contenido_55) 96)
        (= (minutos_contenido contenido_18) 22)
        (= (minutos_contenido contenido_39) 56)
        (paralela contenido_42 contenido_56)
        (paralela contenido_56 contenido_42)
        (paralela contenido_42 contenido_41)
        (paralela contenido_41 contenido_42)
        (paralela contenido_42 contenido_1)
        (paralela contenido_1 contenido_42)
        (paralela contenido_56 contenido_41)
        (paralela contenido_41 contenido_56)
        (paralela contenido_56 contenido_1)
        (paralela contenido_1 contenido_56)
        (paralela contenido_41 contenido_1)
        (paralela contenido_1 contenido_41)
        (= (minutos_contenido contenido_42) 41)
        (= (minutos_contenido contenido_56) 15)
        (= (minutos_contenido contenido_41) 119)
        (= (minutos_contenido contenido_1) 179)
        (paralela contenido_79 contenido_53)
        (paralela contenido_53 contenido_79)
        (paralela contenido_79 contenido_98)
        (paralela contenido_98 contenido_79)
        (paralela contenido_79 contenido_31)
        (paralela contenido_31 contenido_79)
        (paralela contenido_53 contenido_98)
        (paralela contenido_98 contenido_53)
        (paralela contenido_53 contenido_31)
        (paralela contenido_31 contenido_53)
        (paralela contenido_98 contenido_31)
        (paralela contenido_31 contenido_98)
        (= (minutos_contenido contenido_79) 46)
        (= (minutos_contenido contenido_53) 93)
        (= (minutos_contenido contenido_98) 104)
        (= (minutos_contenido contenido_31) 66)
        (paralela contenido_58 contenido_23)
        (paralela contenido_23 contenido_58)
        (paralela contenido_58 contenido_7)
        (paralela contenido_7 contenido_58)
        (paralela contenido_58 contenido_26)
        (paralela contenido_26 contenido_58)
        (paralela contenido_23 contenido_7)
        (paralela contenido_7 contenido_23)
        (paralela contenido_23 contenido_26)
        (paralela contenido_26 contenido_23)
        (paralela contenido_7 contenido_26)
        (paralela contenido_26 contenido_7)
        (= (minutos_contenido contenido_58) 68)
        (= (minutos_contenido contenido_23) 186)
        (= (minutos_contenido contenido_7) 26)
        (= (minutos_contenido contenido_26) 74)
        (paralelas_vistas contenido_86)
        (no_paralela contenido_86)
        (paralelas_vistas contenido_59)
        (no_paralela contenido_59)
        (paralelas_vistas contenido_67)
        (no_paralela contenido_67)
        (paralelas_vistas contenido_80)
        (no_paralela contenido_80)
        (paralelas_vistas contenido_113)
        (no_paralela contenido_113)
        (paralelas_vistas contenido_35)
        (no_paralela contenido_35)
        (paralelas_vistas contenido_90)
        (no_paralela contenido_90)
        (paralelas_vistas contenido_27)
        (no_paralela contenido_27)
        (paralelas_vistas contenido_62)
        (no_paralela contenido_62)
        (paralelas_vistas contenido_17)
        (no_paralela contenido_17)
        (paralelas_vistas contenido_65)
        (no_paralela contenido_65)
        (paralelas_vistas contenido_69)
        (no_paralela contenido_69)
        (paralelas_vistas contenido_73)
        (no_paralela contenido_73)
        (paralelas_vistas contenido_11)
        (no_paralela contenido_11)
        (paralelas_vistas contenido_107)
        (no_paralela contenido_107)
        (paralelas_vistas contenido_4)
        (no_paralela contenido_4)
        (paralelas_vistas contenido_28)
        (no_paralela contenido_28)
        (paralelas_vistas contenido_61)
        (no_paralela contenido_61)
        (paralelas_vistas contenido_83)
        (no_paralela contenido_83)
        (paralelas_vistas contenido_99)
        (no_paralela contenido_99)
        (paralelas_vistas contenido_104)
        (no_paralela contenido_104)
        (paralelas_vistas contenido_48)
        (no_paralela contenido_48)
        (paralelas_vistas contenido_36)
        (no_paralela contenido_36)
        (paralelas_vistas contenido_93)
        (no_paralela contenido_93)
        (paralelas_vistas contenido_51)
        (no_paralela contenido_51)
        (paralelas_vistas contenido_66)
        (no_paralela contenido_66)
        (paralelas_vistas contenido_68)
        (no_paralela contenido_68)
        (paralelas_vistas contenido_114)
        (no_paralela contenido_114)
        (paralelas_vistas contenido_117)
        (no_paralela contenido_117)
        (paralelas_vistas contenido_8)
        (no_paralela contenido_8)
        (paralelas_vistas contenido_100)
        (no_paralela contenido_100)
        (paralelas_vistas contenido_47)
        (no_paralela contenido_47)
        (paralelas_vistas contenido_115)
        (no_paralela contenido_115)
        (paralelas_vistas contenido_9)
        (no_paralela contenido_9)
        (paralelas_vistas contenido_22)
        (no_paralela contenido_22)
        (paralelas_vistas contenido_116)
        (no_paralela contenido_116)
        (paralelas_vistas contenido_25)
        (no_paralela contenido_25)
        (paralelas_vistas contenido_46)
        (no_paralela contenido_46)
        (paralelas_vistas contenido_122)
        (no_paralela contenido_122)
        (paralelas_vistas contenido_91)
        (no_paralela contenido_91)
        (paralelas_vistas contenido_43)
        (no_paralela contenido_43)
        (paralelas_vistas contenido_72)
        (no_paralela contenido_72)
        (paralelas_vistas contenido_44)
        (no_paralela contenido_44)
        (paralelas_vistas contenido_125)
        (no_paralela contenido_125)
        (paralelas_vistas contenido_92)
        (no_paralela contenido_92)
        (paralelas_vistas contenido_33)
        (no_paralela contenido_33)
        (paralelas_vistas contenido_38)
        (no_paralela contenido_38)
        (paralelas_vistas contenido_77)
        (no_paralela contenido_77)
        (paralelas_vistas contenido_111)
        (no_paralela contenido_111)
        (paralelas_vistas contenido_112)
        (no_paralela contenido_112)
        (paralelas_vistas contenido_87)
        (no_paralela contenido_87)
        (paralelas_vistas contenido_19)
        (no_paralela contenido_19)
        (paralelas_vistas contenido_102)
        (no_paralela contenido_102)
        (paralelas_vistas contenido_30)
        (no_paralela contenido_30)
        (paralelas_vistas contenido_94)
        (no_paralela contenido_94)
        (paralelas_vistas contenido_12)
        (no_paralela contenido_12)
        (paralelas_vistas contenido_15)
        (no_paralela contenido_15)
        (paralelas_vistas contenido_6)
        (no_paralela contenido_6)
        (paralelas_vistas contenido_101)
        (no_paralela contenido_101)
        (paralelas_vistas contenido_121)
        (no_paralela contenido_121)
        (paralelas_vistas contenido_89)
        (no_paralela contenido_89)
        (paralelas_vistas contenido_82)
        (no_paralela contenido_82)
        (paralelas_vistas contenido_2)
        (no_paralela contenido_2)
        (paralelas_vistas contenido_37)
        (no_paralela contenido_37)
        (paralelas_vistas contenido_13)
        (no_paralela contenido_13)
        (paralelas_vistas contenido_10)
        (no_paralela contenido_10)
        (paralelas_vistas contenido_84)
        (no_paralela contenido_84)
        (paralelas_vistas contenido_96)
        (no_paralela contenido_96)
        (paralelas_vistas contenido_54)
        (no_paralela contenido_54)
        (paralelas_vistas contenido_76)
        (no_paralela contenido_76)
        (paralelas_vistas contenido_70)
        (no_paralela contenido_70)
        (paralelas_vistas contenido_74)
        (no_paralela contenido_74)
        (paralelas_vistas contenido_105)
        (no_paralela contenido_105)
        (paralelas_vistas contenido_106)
        (no_paralela contenido_106)
        (paralelas_vistas contenido_81)
        (no_paralela contenido_81)
        (paralelas_vistas contenido_123)
        (no_paralela contenido_123)
        (paralelas_vistas contenido_109)
        (no_paralela contenido_109)
        (paralelas_vistas contenido_34)
        (no_paralela contenido_34)
        (paralelas_vistas contenido_71)
        (no_paralela contenido_71)
        (paralelas_vistas contenido_85)
        (no_paralela contenido_85)
        (paralelas_vistas contenido_120)
        (no_paralela contenido_120)
        (paralelas_vistas contenido_78)
        (no_paralela contenido_78)
        (paralelas_vistas contenido_32)
        (no_paralela contenido_32)
        (paralelas_vistas contenido_45)
        (no_paralela contenido_45)
        (paralelas_vistas contenido_64)
        (no_paralela contenido_64)
        (paralelas_vistas contenido_119)
        (no_paralela contenido_119)
        (paralelas_vistas contenido_97)
        (no_paralela contenido_97)
        (paralelas_vistas contenido_118)
        (no_paralela contenido_118)
        (paralelas_vistas contenido_16)
        (no_paralela contenido_16)
        (paralelas_vistas contenido_52)
        (no_paralela contenido_52)
        (paralelas_vistas contenido_63)
        (no_paralela contenido_63)
        (paralelas_vistas contenido_49)
        (no_paralela contenido_49)
        (paralelas_vistas contenido_57)
        (no_paralela contenido_57)
        (paralelas_vistas contenido_108)
        (no_paralela contenido_108)
        (paralelas_vistas contenido_88)
        (no_paralela contenido_88)
        (paralelas_vistas contenido_95)
        (no_paralela contenido_95)
        (paralelas_vistas contenido_103)
        (no_paralela contenido_103)
        (predecesores_vistos contenido_74)
        (predecesores_vistos contenido_111)
        (predecesores_vistos contenido_105)
        (predecesores_vistos contenido_87)
        (predecesores_vistos contenido_68)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_47)
        (predecesores_vistos contenido_85)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_101)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_78)
        (predecesores_vistos contenido_89)
        (predecesores_vistos contenido_62)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_37)
        (predecesores_vistos contenido_46)
        (predecesores_vistos contenido_122)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_119)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_52)
        (predecesores_vistos contenido_84)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_96)
        (predecesores_vistos contenido_54)
        (predecesores_vistos contenido_57)
        (predecesores_vistos contenido_83)
        (predecesores_vistos contenido_104)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_95)
        (predecesores_vistos contenido_36)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
