(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50
    )

    (:init
        (predecesor contenido_22 contenido_45)
        (predecesor contenido_1 contenido_23)
        (predecesor contenido_14 contenido_39)
        (predecesor contenido_4 contenido_18)
        (predecesor contenido_17 contenido_31)
        (predecesor contenido_1 contenido_26)
        (predecesor contenido_6 contenido_28)
        (predecesor contenido_41 contenido_47)
        (predecesor contenido_6 contenido_50)
        (predecesor contenido_3 contenido_6)
        (predecesor contenido_34 contenido_43)
        (predecesor contenido_10 contenido_24)
        (predecesor contenido_41 contenido_43)
        (predecesor contenido_35 contenido_45)
        (predecesor contenido_12 contenido_47)
        (predecesor contenido_22 contenido_36)
        (predecesor contenido_10 contenido_35)
        (predecesor contenido_21 contenido_47)
        (predecesor contenido_15 contenido_35)
        (predecesor contenido_32 contenido_49)
        (predecesor contenido_2 contenido_41)
        (predecesor contenido_23 contenido_46)
        (predecesor contenido_3 contenido_49)
        (predecesor contenido_19 contenido_28)
        (predecesor contenido_5 contenido_33)
        (predecesor contenido_17 contenido_23)
        (predecesor contenido_25 contenido_35)
        (predecesor contenido_2 contenido_13)
        (predecesor contenido_1 contenido_35)
        (predecesor contenido_2 contenido_21)
        (predecesor contenido_11 contenido_22)
        (predecesor contenido_28 contenido_41)
        (predecesor contenido_20 contenido_22)
        (predecesor contenido_15 contenido_26)
        (predecesor contenido_7 contenido_40)
        (predecesor contenido_3 contenido_50)
        (predecesor contenido_6 contenido_32)
        (predecesor contenido_25 contenido_37)
        (predecesor contenido_1 contenido_28)
        (predecesor contenido_9 contenido_30)
        (paralela contenido_9 contenido_17)
        (paralela contenido_17 contenido_9)
        (paralela contenido_9 contenido_4)
        (paralela contenido_4 contenido_9)
        (paralela contenido_9 contenido_38)
        (paralela contenido_38 contenido_9)
        (paralela contenido_17 contenido_4)
        (paralela contenido_4 contenido_17)
        (paralela contenido_17 contenido_38)
        (paralela contenido_38 contenido_17)
        (paralela contenido_4 contenido_38)
        (paralela contenido_38 contenido_4)
        (= (minutos_contenido contenido_9) 44)
        (= (minutos_contenido contenido_17) 126)
        (= (minutos_contenido contenido_4) 181)
        (= (minutos_contenido contenido_38) 15)
        (paralela contenido_3 contenido_27)
        (paralela contenido_27 contenido_3)
        (paralela contenido_3 contenido_2)
        (paralela contenido_2 contenido_3)
        (paralela contenido_3 contenido_11)
        (paralela contenido_11 contenido_3)
        (paralela contenido_27 contenido_2)
        (paralela contenido_2 contenido_27)
        (paralela contenido_27 contenido_11)
        (paralela contenido_11 contenido_27)
        (paralela contenido_2 contenido_11)
        (paralela contenido_11 contenido_2)
        (= (minutos_contenido contenido_3) 87)
        (= (minutos_contenido contenido_27) 119)
        (= (minutos_contenido contenido_2) 17)
        (= (minutos_contenido contenido_11) 50)
        (paralela contenido_19 contenido_8)
        (paralela contenido_8 contenido_19)
        (paralela contenido_19 contenido_48)
        (paralela contenido_48 contenido_19)
        (paralela contenido_19 contenido_25)
        (paralela contenido_25 contenido_19)
        (paralela contenido_8 contenido_48)
        (paralela contenido_48 contenido_8)
        (paralela contenido_8 contenido_25)
        (paralela contenido_25 contenido_8)
        (paralela contenido_48 contenido_25)
        (paralela contenido_25 contenido_48)
        (= (minutos_contenido contenido_19) 67)
        (= (minutos_contenido contenido_8) 155)
        (= (minutos_contenido contenido_48) 97)
        (= (minutos_contenido contenido_25) 33)
        (paralela contenido_7 contenido_44)
        (paralela contenido_44 contenido_7)
        (paralela contenido_7 contenido_42)
        (paralela contenido_42 contenido_7)
        (paralela contenido_7 contenido_16)
        (paralela contenido_16 contenido_7)
        (paralela contenido_44 contenido_42)
        (paralela contenido_42 contenido_44)
        (paralela contenido_44 contenido_16)
        (paralela contenido_16 contenido_44)
        (paralela contenido_42 contenido_16)
        (paralela contenido_16 contenido_42)
        (= (minutos_contenido contenido_7) 92)
        (= (minutos_contenido contenido_44) 77)
        (= (minutos_contenido contenido_42) 111)
        (= (minutos_contenido contenido_16) 21)
        (paralelas_vistas contenido_29)
        (no_paralela contenido_29)
        (paralelas_vistas contenido_47)
        (no_paralela contenido_47)
        (paralelas_vistas contenido_37)
        (no_paralela contenido_37)
        (paralelas_vistas contenido_46)
        (no_paralela contenido_46)
        (paralelas_vistas contenido_10)
        (no_paralela contenido_10)
        (paralelas_vistas contenido_12)
        (no_paralela contenido_12)
        (paralelas_vistas contenido_20)
        (no_paralela contenido_20)
        (paralelas_vistas contenido_23)
        (no_paralela contenido_23)
        (paralelas_vistas contenido_13)
        (no_paralela contenido_13)
        (paralelas_vistas contenido_35)
        (no_paralela contenido_35)
        (paralelas_vistas contenido_39)
        (no_paralela contenido_39)
        (paralelas_vistas contenido_40)
        (no_paralela contenido_40)
        (paralelas_vistas contenido_6)
        (no_paralela contenido_6)
        (paralelas_vistas contenido_45)
        (no_paralela contenido_45)
        (paralelas_vistas contenido_30)
        (no_paralela contenido_30)
        (paralelas_vistas contenido_24)
        (no_paralela contenido_24)
        (paralelas_vistas contenido_18)
        (no_paralela contenido_18)
        (paralelas_vistas contenido_5)
        (no_paralela contenido_5)
        (paralelas_vistas contenido_43)
        (no_paralela contenido_43)
        (paralelas_vistas contenido_33)
        (no_paralela contenido_33)
        (paralelas_vistas contenido_26)
        (no_paralela contenido_26)
        (paralelas_vistas contenido_50)
        (no_paralela contenido_50)
        (paralelas_vistas contenido_14)
        (no_paralela contenido_14)
        (paralelas_vistas contenido_34)
        (no_paralela contenido_34)
        (paralelas_vistas contenido_41)
        (no_paralela contenido_41)
        (paralelas_vistas contenido_28)
        (no_paralela contenido_28)
        (paralelas_vistas contenido_22)
        (no_paralela contenido_22)
        (paralelas_vistas contenido_1)
        (no_paralela contenido_1)
        (paralelas_vistas contenido_36)
        (no_paralela contenido_36)
        (paralelas_vistas contenido_21)
        (no_paralela contenido_21)
        (paralelas_vistas contenido_32)
        (no_paralela contenido_32)
        (paralelas_vistas contenido_15)
        (no_paralela contenido_15)
        (paralelas_vistas contenido_31)
        (no_paralela contenido_31)
        (paralelas_vistas contenido_49)
        (no_paralela contenido_49)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_15)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
