(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125 contenido_126 contenido_127 contenido_128 contenido_129 contenido_130 contenido_131 contenido_132 contenido_133 contenido_134 contenido_135 contenido_136 contenido_137 contenido_138 contenido_139 contenido_140 contenido_141 contenido_142 contenido_143 contenido_144 contenido_145 contenido_146 contenido_147 contenido_148 contenido_149 contenido_150
    )

    (:init
        (predecesor contenido_64 contenido_117)
        (predecesor contenido_34 contenido_123)
        (predecesor contenido_9 contenido_119)
        (predecesor contenido_28 contenido_131)
        (predecesor contenido_40 contenido_127)
        (predecesor contenido_9 contenido_26)
        (predecesor contenido_18 contenido_76)
        (predecesor contenido_88 contenido_102)
        (predecesor contenido_111 contenido_112)
        (predecesor contenido_35 contenido_50)
        (predecesor contenido_112 contenido_138)
        (predecesor contenido_23 contenido_85)
        (predecesor contenido_58 contenido_129)
        (predecesor contenido_37 contenido_84)
        (predecesor contenido_44 contenido_86)
        (predecesor contenido_14 contenido_69)
        (predecesor contenido_17 contenido_29)
        (predecesor contenido_88 contenido_134)
        (predecesor contenido_55 contenido_132)
        (predecesor contenido_84 contenido_133)
        (predecesor contenido_135 contenido_145)
        (predecesor contenido_75 contenido_84)
        (predecesor contenido_44 contenido_107)
        (predecesor contenido_24 contenido_37)
        (predecesor contenido_8 contenido_66)
        (predecesor contenido_70 contenido_130)
        (predecesor contenido_87 contenido_142)
        (predecesor contenido_22 contenido_82)
        (predecesor contenido_4 contenido_91)
        (predecesor contenido_6 contenido_90)
        (predecesor contenido_10 contenido_98)
        (predecesor contenido_66 contenido_91)
        (predecesor contenido_16 contenido_146)
        (predecesor contenido_35 contenido_124)
        (predecesor contenido_120 contenido_147)
        (predecesor contenido_114 contenido_134)
        (predecesor contenido_58 contenido_107)
        (predecesor contenido_21 contenido_97)
        (predecesor contenido_58 contenido_146)
        (predecesor contenido_50 contenido_78)
        (predecesor contenido_81 contenido_115)
        (predecesor contenido_113 contenido_145)
        (predecesor contenido_50 contenido_53)
        (predecesor contenido_43 contenido_136)
        (predecesor contenido_35 contenido_137)
        (predecesor contenido_14 contenido_41)
        (predecesor contenido_53 contenido_62)
        (predecesor contenido_10 contenido_63)
        (predecesor contenido_22 contenido_53)
        (predecesor contenido_23 contenido_105)
        (predecesor contenido_58 contenido_73)
        (predecesor contenido_140 contenido_143)
        (predecesor contenido_64 contenido_74)
        (predecesor contenido_86 contenido_88)
        (predecesor contenido_55 contenido_62)
        (predecesor contenido_83 contenido_99)
        (predecesor contenido_2 contenido_42)
        (predecesor contenido_7 contenido_93)
        (predecesor contenido_15 contenido_141)
        (predecesor contenido_69 contenido_135)
        (predecesor contenido_64 contenido_112)
        (predecesor contenido_14 contenido_93)
        (predecesor contenido_68 contenido_121)
        (predecesor contenido_75 contenido_111)
        (predecesor contenido_51 contenido_130)
        (predecesor contenido_129 contenido_148)
        (predecesor contenido_3 contenido_106)
        (predecesor contenido_59 contenido_104)
        (predecesor contenido_1 contenido_112)
        (predecesor contenido_132 contenido_143)
        (predecesor contenido_100 contenido_138)
        (predecesor contenido_65 contenido_73)
        (predecesor contenido_101 contenido_105)
        (predecesor contenido_38 contenido_57)
        (predecesor contenido_36 contenido_88)
        (predecesor contenido_13 contenido_47)
        (predecesor contenido_61 contenido_111)
        (predecesor contenido_25 contenido_84)
        (predecesor contenido_108 contenido_143)
        (predecesor contenido_90 contenido_130)
        (predecesor contenido_125 contenido_134)
        (predecesor contenido_45 contenido_144)
        (predecesor contenido_7 contenido_42)
        (predecesor contenido_71 contenido_87)
        (predecesor contenido_75 contenido_100)
        (predecesor contenido_41 contenido_134)
        (predecesor contenido_92 contenido_109)
        (predecesor contenido_10 contenido_79)
        (predecesor contenido_97 contenido_119)
        (predecesor contenido_40 contenido_120)
        (predecesor contenido_5 contenido_49)
        (predecesor contenido_92 contenido_113)
        (predecesor contenido_102 contenido_132)
        (predecesor contenido_1 contenido_76)
        (predecesor contenido_23 contenido_97)
        (predecesor contenido_43 contenido_99)
        (predecesor contenido_121 contenido_139)
        (predecesor contenido_22 contenido_88)
        (predecesor contenido_14 contenido_100)
        (predecesor contenido_110 contenido_128)
        (predecesor contenido_35 contenido_87)
        (predecesor contenido_15 contenido_98)
        (predecesor contenido_19 contenido_140)
        (predecesor contenido_73 contenido_84)
        (predecesor contenido_57 contenido_131)
        (predecesor contenido_23 contenido_94)
        (predecesor contenido_70 contenido_112)
        (predecesor contenido_37 contenido_96)
        (predecesor contenido_52 contenido_104)
        (predecesor contenido_48 contenido_84)
        (predecesor contenido_16 contenido_74)
        (predecesor contenido_8 contenido_11)
        (predecesor contenido_50 contenido_69)
        (predecesor contenido_15 contenido_133)
        (predecesor contenido_27 contenido_114)
        (predecesor contenido_83 contenido_141)
        (predecesor contenido_75 contenido_90)
        (predecesor contenido_138 contenido_144)
        (predecesor contenido_35 contenido_117)
        (predecesor contenido_32 contenido_68)
        (paralelas_vistas contenido_108)
        (no_paralela contenido_108)
        (paralelas_vistas contenido_69)
        (no_paralela contenido_69)
        (paralelas_vistas contenido_118)
        (no_paralela contenido_118)
        (paralelas_vistas contenido_77)
        (no_paralela contenido_77)
        (paralelas_vistas contenido_81)
        (no_paralela contenido_81)
        (paralelas_vistas contenido_54)
        (no_paralela contenido_54)
        (paralelas_vistas contenido_78)
        (no_paralela contenido_78)
        (paralelas_vistas contenido_97)
        (no_paralela contenido_97)
        (paralelas_vistas contenido_140)
        (no_paralela contenido_140)
        (paralelas_vistas contenido_16)
        (no_paralela contenido_16)
        (paralelas_vistas contenido_123)
        (no_paralela contenido_123)
        (paralelas_vistas contenido_114)
        (no_paralela contenido_114)
        (paralelas_vistas contenido_43)
        (no_paralela contenido_43)
        (paralelas_vistas contenido_136)
        (no_paralela contenido_136)
        (paralelas_vistas contenido_129)
        (no_paralela contenido_129)
        (paralelas_vistas contenido_105)
        (no_paralela contenido_105)
        (paralelas_vistas contenido_131)
        (no_paralela contenido_131)
        (paralelas_vistas contenido_67)
        (no_paralela contenido_67)
        (paralelas_vistas contenido_51)
        (no_paralela contenido_51)
        (paralelas_vistas contenido_20)
        (no_paralela contenido_20)
        (paralelas_vistas contenido_124)
        (no_paralela contenido_124)
        (paralelas_vistas contenido_52)
        (no_paralela contenido_52)
        (paralelas_vistas contenido_87)
        (no_paralela contenido_87)
        (paralelas_vistas contenido_27)
        (no_paralela contenido_27)
        (paralelas_vistas contenido_135)
        (no_paralela contenido_135)
        (paralelas_vistas contenido_73)
        (no_paralela contenido_73)
        (paralelas_vistas contenido_94)
        (no_paralela contenido_94)
        (paralelas_vistas contenido_71)
        (no_paralela contenido_71)
        (paralelas_vistas contenido_132)
        (no_paralela contenido_132)
        (paralelas_vistas contenido_13)
        (no_paralela contenido_13)
        (paralelas_vistas contenido_146)
        (no_paralela contenido_146)
        (paralelas_vistas contenido_35)
        (no_paralela contenido_35)
        (paralelas_vistas contenido_130)
        (no_paralela contenido_130)
        (paralelas_vistas contenido_98)
        (no_paralela contenido_98)
        (paralelas_vistas contenido_23)
        (no_paralela contenido_23)
        (paralelas_vistas contenido_61)
        (no_paralela contenido_61)
        (paralelas_vistas contenido_34)
        (no_paralela contenido_34)
        (paralelas_vistas contenido_99)
        (no_paralela contenido_99)
        (paralelas_vistas contenido_22)
        (no_paralela contenido_22)
        (paralelas_vistas contenido_137)
        (no_paralela contenido_137)
        (paralelas_vistas contenido_120)
        (no_paralela contenido_120)
        (paralelas_vistas contenido_10)
        (no_paralela contenido_10)
        (paralelas_vistas contenido_110)
        (no_paralela contenido_110)
        (paralelas_vistas contenido_32)
        (no_paralela contenido_32)
        (paralelas_vistas contenido_46)
        (no_paralela contenido_46)
        (paralelas_vistas contenido_76)
        (no_paralela contenido_76)
        (paralelas_vistas contenido_100)
        (no_paralela contenido_100)
        (paralelas_vistas contenido_45)
        (no_paralela contenido_45)
        (paralelas_vistas contenido_109)
        (no_paralela contenido_109)
        (paralelas_vistas contenido_50)
        (no_paralela contenido_50)
        (paralelas_vistas contenido_40)
        (no_paralela contenido_40)
        (paralelas_vistas contenido_57)
        (no_paralela contenido_57)
        (paralelas_vistas contenido_66)
        (no_paralela contenido_66)
        (paralelas_vistas contenido_18)
        (no_paralela contenido_18)
        (paralelas_vistas contenido_86)
        (no_paralela contenido_86)
        (paralelas_vistas contenido_102)
        (no_paralela contenido_102)
        (paralelas_vistas contenido_115)
        (no_paralela contenido_115)
        (paralelas_vistas contenido_14)
        (no_paralela contenido_14)
        (paralelas_vistas contenido_68)
        (no_paralela contenido_68)
        (paralelas_vistas contenido_44)
        (no_paralela contenido_44)
        (paralelas_vistas contenido_63)
        (no_paralela contenido_63)
        (paralelas_vistas contenido_6)
        (no_paralela contenido_6)
        (paralelas_vistas contenido_17)
        (no_paralela contenido_17)
        (paralelas_vistas contenido_36)
        (no_paralela contenido_36)
        (paralelas_vistas contenido_83)
        (no_paralela contenido_83)
        (paralelas_vistas contenido_112)
        (no_paralela contenido_112)
        (paralelas_vistas contenido_91)
        (no_paralela contenido_91)
        (paralelas_vistas contenido_49)
        (no_paralela contenido_49)
        (paralelas_vistas contenido_103)
        (no_paralela contenido_103)
        (paralelas_vistas contenido_107)
        (no_paralela contenido_107)
        (paralelas_vistas contenido_25)
        (no_paralela contenido_25)
        (paralelas_vistas contenido_58)
        (no_paralela contenido_58)
        (paralelas_vistas contenido_104)
        (no_paralela contenido_104)
        (paralelas_vistas contenido_95)
        (no_paralela contenido_95)
        (paralelas_vistas contenido_106)
        (no_paralela contenido_106)
        (paralelas_vistas contenido_116)
        (no_paralela contenido_116)
        (paralelas_vistas contenido_59)
        (no_paralela contenido_59)
        (paralelas_vistas contenido_29)
        (no_paralela contenido_29)
        (paralelas_vistas contenido_144)
        (no_paralela contenido_144)
        (paralelas_vistas contenido_37)
        (no_paralela contenido_37)
        (paralelas_vistas contenido_80)
        (no_paralela contenido_80)
        (paralelas_vistas contenido_125)
        (no_paralela contenido_125)
        (paralelas_vistas contenido_145)
        (no_paralela contenido_145)
        (paralelas_vistas contenido_119)
        (no_paralela contenido_119)
        (paralelas_vistas contenido_47)
        (no_paralela contenido_47)
        (paralelas_vistas contenido_139)
        (no_paralela contenido_139)
        (paralelas_vistas contenido_31)
        (no_paralela contenido_31)
        (paralelas_vistas contenido_128)
        (no_paralela contenido_128)
        (paralelas_vistas contenido_84)
        (no_paralela contenido_84)
        (paralelas_vistas contenido_121)
        (no_paralela contenido_121)
        (paralelas_vistas contenido_92)
        (no_paralela contenido_92)
        (paralelas_vistas contenido_74)
        (no_paralela contenido_74)
        (paralelas_vistas contenido_38)
        (no_paralela contenido_38)
        (paralelas_vistas contenido_33)
        (no_paralela contenido_33)
        (paralelas_vistas contenido_1)
        (no_paralela contenido_1)
        (paralelas_vistas contenido_30)
        (no_paralela contenido_30)
        (paralelas_vistas contenido_96)
        (no_paralela contenido_96)
        (paralelas_vistas contenido_48)
        (no_paralela contenido_48)
        (paralelas_vistas contenido_141)
        (no_paralela contenido_141)
        (paralelas_vistas contenido_133)
        (no_paralela contenido_133)
        (paralelas_vistas contenido_7)
        (no_paralela contenido_7)
        (paralelas_vistas contenido_90)
        (no_paralela contenido_90)
        (paralelas_vistas contenido_93)
        (no_paralela contenido_93)
        (paralelas_vistas contenido_4)
        (no_paralela contenido_4)
        (paralelas_vistas contenido_122)
        (no_paralela contenido_122)
        (paralelas_vistas contenido_65)
        (no_paralela contenido_65)
        (paralelas_vistas contenido_138)
        (no_paralela contenido_138)
        (paralelas_vistas contenido_24)
        (no_paralela contenido_24)
        (paralelas_vistas contenido_82)
        (no_paralela contenido_82)
        (paralelas_vistas contenido_142)
        (no_paralela contenido_142)
        (paralelas_vistas contenido_79)
        (no_paralela contenido_79)
        (paralelas_vistas contenido_15)
        (no_paralela contenido_15)
        (paralelas_vistas contenido_127)
        (no_paralela contenido_127)
        (paralelas_vistas contenido_5)
        (no_paralela contenido_5)
        (paralelas_vistas contenido_89)
        (no_paralela contenido_89)
        (paralelas_vistas contenido_70)
        (no_paralela contenido_70)
        (paralelas_vistas contenido_143)
        (no_paralela contenido_143)
        (paralelas_vistas contenido_41)
        (no_paralela contenido_41)
        (paralelas_vistas contenido_3)
        (no_paralela contenido_3)
        (paralelas_vistas contenido_12)
        (no_paralela contenido_12)
        (paralelas_vistas contenido_9)
        (no_paralela contenido_9)
        (paralelas_vistas contenido_150)
        (no_paralela contenido_150)
        (paralelas_vistas contenido_28)
        (no_paralela contenido_28)
        (paralelas_vistas contenido_53)
        (no_paralela contenido_53)
        (paralelas_vistas contenido_72)
        (no_paralela contenido_72)
        (paralelas_vistas contenido_56)
        (no_paralela contenido_56)
        (paralelas_vistas contenido_11)
        (no_paralela contenido_11)
        (paralelas_vistas contenido_117)
        (no_paralela contenido_117)
        (paralelas_vistas contenido_113)
        (no_paralela contenido_113)
        (paralelas_vistas contenido_148)
        (no_paralela contenido_148)
        (paralelas_vistas contenido_21)
        (no_paralela contenido_21)
        (paralelas_vistas contenido_2)
        (no_paralela contenido_2)
        (paralelas_vistas contenido_8)
        (no_paralela contenido_8)
        (paralelas_vistas contenido_60)
        (no_paralela contenido_60)
        (paralelas_vistas contenido_42)
        (no_paralela contenido_42)
        (paralelas_vistas contenido_62)
        (no_paralela contenido_62)
        (paralelas_vistas contenido_55)
        (no_paralela contenido_55)
        (paralelas_vistas contenido_134)
        (no_paralela contenido_134)
        (paralelas_vistas contenido_88)
        (no_paralela contenido_88)
        (paralelas_vistas contenido_64)
        (no_paralela contenido_64)
        (paralelas_vistas contenido_39)
        (no_paralela contenido_39)
        (paralelas_vistas contenido_101)
        (no_paralela contenido_101)
        (paralelas_vistas contenido_26)
        (no_paralela contenido_26)
        (paralelas_vistas contenido_147)
        (no_paralela contenido_147)
        (paralelas_vistas contenido_111)
        (no_paralela contenido_111)
        (paralelas_vistas contenido_19)
        (no_paralela contenido_19)
        (paralelas_vistas contenido_75)
        (no_paralela contenido_75)
        (paralelas_vistas contenido_85)
        (no_paralela contenido_85)
        (paralelas_vistas contenido_149)
        (no_paralela contenido_149)
        (paralelas_vistas contenido_126)
        (no_paralela contenido_126)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_80)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_108)
        (predecesores_vistos contenido_125)
        (predecesores_vistos contenido_118)
        (predecesores_vistos contenido_61)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_77)
        (predecesores_vistos contenido_81)
        (predecesores_vistos contenido_54)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_56)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_126)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_92)
        (predecesores_vistos contenido_110)
        (predecesores_vistos contenido_38)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_150)
        (predecesores_vistos contenido_46)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_60)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_43)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_55)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_45)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_64)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_51)
        (predecesores_vistos contenido_39)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_67)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_52)
        (predecesores_vistos contenido_101)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_36)
        (predecesores_vistos contenido_83)
        (predecesores_vistos contenido_103)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_122)
        (predecesores_vistos contenido_65)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_58)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_95)
        (predecesores_vistos contenido_71)
        (predecesores_vistos contenido_75)
        (predecesores_vistos contenido_89)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_70)
        (predecesores_vistos contenido_116)
        (predecesores_vistos contenido_149)
        (predecesores_vistos contenido_59)
        (predecesores_vistos contenido_35)
        (predecesores_vistos contenido_3)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
