(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50
    )

    (:init
        (predecesor contenido_6 contenido_32)
        (predecesor contenido_15 contenido_26)
        (predecesor contenido_19 contenido_28)
        (predecesor contenido_6 contenido_50)
        (predecesor contenido_28 contenido_41)
        (predecesor contenido_25 contenido_37)
        (predecesor contenido_32 contenido_49)
        (predecesor contenido_7 contenido_40)
        (predecesor contenido_10 contenido_35)
        (predecesor contenido_1 contenido_26)
        (predecesor contenido_22 contenido_45)
        (predecesor contenido_15 contenido_35)
        (predecesor contenido_34 contenido_43)
        (predecesor contenido_2 contenido_21)
        (predecesor contenido_10 contenido_24)
        (predecesor contenido_1 contenido_35)
        (predecesor contenido_23 contenido_46)
        (predecesor contenido_35 contenido_45)
        (predecesor contenido_3 contenido_49)
        (predecesor contenido_14 contenido_39)
        (predecesor contenido_12 contenido_47)
        (predecesor contenido_2 contenido_41)
        (predecesor contenido_4 contenido_18)
        (predecesor contenido_21 contenido_47)
        (predecesor contenido_17 contenido_23)
        (predecesor contenido_41 contenido_47)
        (predecesor contenido_20 contenido_22)
        (predecesor contenido_9 contenido_30)
        (predecesor contenido_6 contenido_28)
        (predecesor contenido_1 contenido_23)
        (predecesor contenido_3 contenido_6)
        (predecesor contenido_11 contenido_22)
        (predecesor contenido_17 contenido_31)
        (predecesor contenido_5 contenido_33)
        (predecesor contenido_22 contenido_36)
        (predecesor contenido_2 contenido_13)
        (predecesor contenido_3 contenido_50)
        (predecesor contenido_41 contenido_43)
        (predecesor contenido_1 contenido_28)
        (predecesor contenido_25 contenido_35)
        (paralelas_vistas contenido_37)
        (no_paralela contenido_37)
        (paralelas_vistas contenido_38)
        (no_paralela contenido_38)
        (paralelas_vistas contenido_50)
        (no_paralela contenido_50)
        (paralelas_vistas contenido_41)
        (no_paralela contenido_41)
        (paralelas_vistas contenido_33)
        (no_paralela contenido_33)
        (paralelas_vistas contenido_6)
        (no_paralela contenido_6)
        (paralelas_vistas contenido_32)
        (no_paralela contenido_32)
        (paralelas_vistas contenido_13)
        (no_paralela contenido_13)
        (paralelas_vistas contenido_28)
        (no_paralela contenido_28)
        (paralelas_vistas contenido_17)
        (no_paralela contenido_17)
        (paralelas_vistas contenido_10)
        (no_paralela contenido_10)
        (paralelas_vistas contenido_35)
        (no_paralela contenido_35)
        (paralelas_vistas contenido_18)
        (no_paralela contenido_18)
        (paralelas_vistas contenido_42)
        (no_paralela contenido_42)
        (paralelas_vistas contenido_1)
        (no_paralela contenido_1)
        (paralelas_vistas contenido_24)
        (no_paralela contenido_24)
        (paralelas_vistas contenido_11)
        (no_paralela contenido_11)
        (paralelas_vistas contenido_49)
        (no_paralela contenido_49)
        (paralelas_vistas contenido_8)
        (no_paralela contenido_8)
        (paralelas_vistas contenido_19)
        (no_paralela contenido_19)
        (paralelas_vistas contenido_30)
        (no_paralela contenido_30)
        (paralelas_vistas contenido_12)
        (no_paralela contenido_12)
        (paralelas_vistas contenido_5)
        (no_paralela contenido_5)
        (paralelas_vistas contenido_26)
        (no_paralela contenido_26)
        (paralelas_vistas contenido_20)
        (no_paralela contenido_20)
        (paralelas_vistas contenido_44)
        (no_paralela contenido_44)
        (paralelas_vistas contenido_15)
        (no_paralela contenido_15)
        (paralelas_vistas contenido_22)
        (no_paralela contenido_22)
        (paralelas_vistas contenido_21)
        (no_paralela contenido_21)
        (paralelas_vistas contenido_40)
        (no_paralela contenido_40)
        (paralelas_vistas contenido_4)
        (no_paralela contenido_4)
        (paralelas_vistas contenido_2)
        (no_paralela contenido_2)
        (paralelas_vistas contenido_36)
        (no_paralela contenido_36)
        (paralelas_vistas contenido_25)
        (no_paralela contenido_25)
        (paralelas_vistas contenido_46)
        (no_paralela contenido_46)
        (paralelas_vistas contenido_3)
        (no_paralela contenido_3)
        (paralelas_vistas contenido_43)
        (no_paralela contenido_43)
        (paralelas_vistas contenido_7)
        (no_paralela contenido_7)
        (paralelas_vistas contenido_27)
        (no_paralela contenido_27)
        (paralelas_vistas contenido_23)
        (no_paralela contenido_23)
        (paralelas_vistas contenido_31)
        (no_paralela contenido_31)
        (paralelas_vistas contenido_39)
        (no_paralela contenido_39)
        (paralelas_vistas contenido_34)
        (no_paralela contenido_34)
        (paralelas_vistas contenido_29)
        (no_paralela contenido_29)
        (paralelas_vistas contenido_9)
        (no_paralela contenido_9)
        (paralelas_vistas contenido_47)
        (no_paralela contenido_47)
        (paralelas_vistas contenido_48)
        (no_paralela contenido_48)
        (paralelas_vistas contenido_16)
        (no_paralela contenido_16)
        (paralelas_vistas contenido_14)
        (no_paralela contenido_14)
        (paralelas_vistas contenido_45)
        (no_paralela contenido_45)
        (predecesores_vistos contenido_38)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_14)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
