(define (problem problema_test_100contenidos)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10
        contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20
        contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30
        contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40
        contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50
        contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60
        contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70
        contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80
        contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90
        contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100
    )

    (:init
		;; ------------------- PREDECESORES ----------------------------
        (predecesor contenido_8 contenido_9)
        (predecesor contenido_9 contenido_1)
        (predecesor contenido_1 contenido_2)
        (predecesor contenido_2 contenido_3)
        (predecesor contenido_3 contenido_4)
        
        (predecesor contenido_10 contenido_11)
        (predecesor contenido_11 contenido_12)
        (predecesor contenido_12 contenido_13)
        (predecesor contenido_13 contenido_14)
        (predecesor contenido_14 contenido_15)
        
        (predecesor contenido_30 contenido_31)
        (predecesor contenido_31 contenido_32)
        (predecesor contenido_32 contenido_33)
        (predecesor contenido_33 contenido_34)
        (predecesor contenido_34 contenido_35)
        (predecesor contenido_35 contenido_36)
        (predecesor contenido_36 contenido_37)
        (predecesor contenido_37 contenido_38)
        
        (predecesor contenido_25 contenido_50)
        (predecesor contenido_10 contenido_50)
        (predecesor contenido_48 contenido_50)
        (predecesor contenido_49 contenido_50)
        
        (predecesor contenido_81 contenido_84)
        (predecesor contenido_82 contenido_84)
        (predecesor contenido_83 contenido_84)
        
        (predecesor contenido_90 contenido_86)
        (predecesor contenido_86 contenido_91)
        
        (predecesor contenido_95 contenido_96)
        (predecesor contenido_96 contenido_97)
        (predecesor contenido_97 contenido_98)
        (predecesor contenido_98 contenido_99)
        (predecesor contenido_99 contenido_100)

		(predecesor contenido_73 contenido_75)
        (predecesor contenido_75 contenido_76)
        (predecesor contenido_76 contenido_77)
        (predecesor contenido_77 contenido_78)
        (predecesor contenido_78 contenido_79)
        (predecesor contenido_79 contenido_80)
        
        ;; ------------------- PREDECESORES VISTOS----------------------
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_25) 
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_39)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_41)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_43)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_45)
        (predecesores_vistos contenido_46)
        (predecesores_vistos contenido_47)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_49) 
        (predecesores_vistos contenido_51)
        (predecesores_vistos contenido_52)
        (predecesores_vistos contenido_53)
        (predecesores_vistos contenido_54)
        (predecesores_vistos contenido_55)
        (predecesores_vistos contenido_56)
        (predecesores_vistos contenido_57)
        (predecesores_vistos contenido_58)
        (predecesores_vistos contenido_59)
        (predecesores_vistos contenido_60)
        (predecesores_vistos contenido_61)
        (predecesores_vistos contenido_62)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_64)
        (predecesores_vistos contenido_65) 
        (predecesores_vistos contenido_66)
        (predecesores_vistos contenido_67)
        (predecesores_vistos contenido_68)
        (predecesores_vistos contenido_69)
        (predecesores_vistos contenido_70)
        (predecesores_vistos contenido_71)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_73)
        (predecesores_vistos contenido_74)
        (predecesores_vistos contenido_81)
        (predecesores_vistos contenido_82)
        (predecesores_vistos contenido_83)
        (predecesores_vistos contenido_85)
        (predecesores_vistos contenido_87)
        (predecesores_vistos contenido_88)
        (predecesores_vistos contenido_89)
        (predecesores_vistos contenido_90)
        (predecesores_vistos contenido_92)
        (predecesores_vistos contenido_93)
        (predecesores_vistos contenido_94)
        (predecesores_vistos contenido_95)

        
		
		;; ------------------- PARALELAS ----------------------------
        (paralela contenido_5 contenido_6)
        (paralela contenido_6 contenido_7)
        (paralela contenido_7 contenido_8)
        (paralela contenido_8 contenido_5)
        (paralela contenido_5 contenido_7)
        (paralela contenido_6 contenido_8)
        (paralela contenido_7 contenido_5)
        (paralela contenido_8 contenido_6)
        (paralela contenido_5 contenido_8)
        (paralela contenido_6 contenido_5)
        (paralela contenido_7 contenido_6)
        (paralela contenido_8 contenido_7)
        
        (paralela contenido_24 contenido_25)
        (paralela contenido_25 contenido_24)
        
        (paralela contenido_32 contenido_40)
        (paralela contenido_40 contenido_41)
        (paralela contenido_41 contenido_32)
        (paralela contenido_32 contenido_41)
        (paralela contenido_40 contenido_32)
        (paralela contenido_41 contenido_40)
        
        (paralela contenido_43 contenido_44)
        (paralela contenido_44 contenido_43)
        
        (paralela contenido_85 contenido_86)
        (paralela contenido_86 contenido_87)
        (paralela contenido_87 contenido_84)
        (paralela contenido_84 contenido_85)
        (paralela contenido_85 contenido_87)
        (paralela contenido_86 contenido_84)
        (paralela contenido_87 contenido_85)
        (paralela contenido_84 contenido_86)
        (paralela contenido_85 contenido_84)
        (paralela contenido_86 contenido_85)
        (paralela contenido_87 contenido_86)
        (paralela contenido_84 contenido_87)
        
        (paralela contenido_70 contenido_71)
        (paralela contenido_70 contenido_72)
        (paralela contenido_70 contenido_73)
        (paralela contenido_70 contenido_74)
        (paralela contenido_71 contenido_70)
        (paralela contenido_71 contenido_72)
        (paralela contenido_71 contenido_73)
        (paralela contenido_71 contenido_74)
        (paralela contenido_72 contenido_70)
        (paralela contenido_72 contenido_71)
        (paralela contenido_72 contenido_73)
        (paralela contenido_72 contenido_74)
        (paralela contenido_73 contenido_70)
        (paralela contenido_73 contenido_71)
        (paralela contenido_73 contenido_72)
        (paralela contenido_73 contenido_74)
        (paralela contenido_74 contenido_70)
        (paralela contenido_74 contenido_71)
        (paralela contenido_74 contenido_72)
        (paralela contenido_74 contenido_73)
        
        ;; ------------------- NO PARALELAS ----------------------------
        (no_paralela contenido_1)
        (no_paralela contenido_2)
        (no_paralela contenido_3)
        (no_paralela contenido_4)
        (no_paralela contenido_9)
        (no_paralela contenido_10)
        (no_paralela contenido_11)
        (no_paralela contenido_12)
        (no_paralela contenido_13)
        (no_paralela contenido_14)
        (no_paralela contenido_15)
        (no_paralela contenido_16)
        (no_paralela contenido_17)
        (no_paralela contenido_18)
        (no_paralela contenido_19)
        (no_paralela contenido_20)
        (no_paralela contenido_21)
        (no_paralela contenido_22)
        (no_paralela contenido_23)
        (no_paralela contenido_26)
        (no_paralela contenido_27)
        (no_paralela contenido_28)
        (no_paralela contenido_29)
        (no_paralela contenido_30)
        (no_paralela contenido_31)
        (no_paralela contenido_33)
        (no_paralela contenido_34)
        (no_paralela contenido_35)
        (no_paralela contenido_36)
        (no_paralela contenido_37)
        (no_paralela contenido_38)
        (no_paralela contenido_39)
        (no_paralela contenido_42)
        (no_paralela contenido_45)
        (no_paralela contenido_46)
        (no_paralela contenido_47)
        (no_paralela contenido_48)
        (no_paralela contenido_49)
        (no_paralela contenido_50)
        (no_paralela contenido_51)
        (no_paralela contenido_52)
        (no_paralela contenido_53)
        (no_paralela contenido_54)
        (no_paralela contenido_55)
        (no_paralela contenido_56)
        (no_paralela contenido_57)
        (no_paralela contenido_58)
        (no_paralela contenido_59)
        (no_paralela contenido_60)
        (no_paralela contenido_61)
        (no_paralela contenido_62)
        (no_paralela contenido_63)
        (no_paralela contenido_64)
        (no_paralela contenido_65)
        (no_paralela contenido_66)
        (no_paralela contenido_67)
        (no_paralela contenido_68)
        (no_paralela contenido_69)
        (no_paralela contenido_75)
        (no_paralela contenido_76)
        (no_paralela contenido_77)
        (no_paralela contenido_78)
        (no_paralela contenido_79)
        (no_paralela contenido_80)
        (no_paralela contenido_81)
        (no_paralela contenido_82)
        (no_paralela contenido_83)
        (no_paralela contenido_88)
        (no_paralela contenido_89)
        (no_paralela contenido_90)
        (no_paralela contenido_91)
        (no_paralela contenido_92)
        (no_paralela contenido_93)
        (no_paralela contenido_94)        
        (no_paralela contenido_95)
        (no_paralela contenido_96)
        (no_paralela contenido_97)
        (no_paralela contenido_98)
        (no_paralela contenido_99)
        (no_paralela contenido_100)
        
       
        ;; ---------------------- MINUTOS ------------------------------        
        (=(minutos_contenido contenido_5) 60)
        (=(minutos_contenido contenido_6) 50)
        (=(minutos_contenido contenido_7) 70)
        (=(minutos_contenido contenido_8) 80)
        
        (=(minutos_contenido contenido_24) 170)
        (=(minutos_contenido contenido_25) 180)
        
        (=(minutos_contenido contenido_32) 70)
        (=(minutos_contenido contenido_40) 50)
        (=(minutos_contenido contenido_41) 80)
        
        (=(minutos_contenido contenido_43) 170)
        (=(minutos_contenido contenido_44) 30)
        
        (=(minutos_contenido contenido_70) 60)
        (=(minutos_contenido contenido_71) 50)
        (=(minutos_contenido contenido_72) 70)
        (=(minutos_contenido contenido_73) 80)       
        (=(minutos_contenido contenido_74) 120)
        
        (=(minutos_contenido contenido_84) 150)
        (=(minutos_contenido contenido_85) 70)
        (=(minutos_contenido contenido_86) 70)
        (=(minutos_contenido contenido_87) 60)
        
        (=(minutos_contenido contenido_1) 60)
        (=(minutos_contenido contenido_2) 50)
        (=(minutos_contenido contenido_3) 70)
        (=(minutos_contenido contenido_4) 80)
        (=(minutos_contenido contenido_9) 80)
        (=(minutos_contenido contenido_10) 95)
        (=(minutos_contenido contenido_11) 102)
        (=(minutos_contenido contenido_12) 93)
        (=(minutos_contenido contenido_13) 88)
        (=(minutos_contenido contenido_14) 75)
        (=(minutos_contenido contenido_15) 66)
        (=(minutos_contenido contenido_16) 81)
        (=(minutos_contenido contenido_17) 62)
        (=(minutos_contenido contenido_18) 94)
        (=(minutos_contenido contenido_19) 76)
        (=(minutos_contenido contenido_20) 91)
        (=(minutos_contenido contenido_21) 102)
        (=(minutos_contenido contenido_22) 93)
        (=(minutos_contenido contenido_23) 80)
        (=(minutos_contenido contenido_26) 81)
        (=(minutos_contenido contenido_27) 62)
        (=(minutos_contenido contenido_28) 94)
        (=(minutos_contenido contenido_29) 10)
        (=(minutos_contenido contenido_30) 95)
        (=(minutos_contenido contenido_31) 102)
        (=(minutos_contenido contenido_33) 102)
        (=(minutos_contenido contenido_34) 70)
        (=(minutos_contenido contenido_35) 80)
        (=(minutos_contenido contenido_36) 65)
        (=(minutos_contenido contenido_37) 90)
        (=(minutos_contenido contenido_38) 95)
        (=(minutos_contenido contenido_39) 100)
        (=(minutos_contenido contenido_42) 90)
        (=(minutos_contenido contenido_45) 80)
        (=(minutos_contenido contenido_46) 77)
        (=(minutos_contenido contenido_47) 92)
        (=(minutos_contenido contenido_48) 79)
        (=(minutos_contenido contenido_49) 85)
        (=(minutos_contenido contenido_50) 65)
        (=(minutos_contenido contenido_51) 60)
        (=(minutos_contenido contenido_52) 50)
        (=(minutos_contenido contenido_53) 70)
        (=(minutos_contenido contenido_54) 80)
        (=(minutos_contenido contenido_55) 80)
        (=(minutos_contenido contenido_56) 77)
        (=(minutos_contenido contenido_57) 92)
        (=(minutos_contenido contenido_58) 79)
        (=(minutos_contenido contenido_59) 85)
        (=(minutos_contenido contenido_60) 95)
        (=(minutos_contenido contenido_61) 102)
        (=(minutos_contenido contenido_62) 93)
        (=(minutos_contenido contenido_63) 88)
        (=(minutos_contenido contenido_64) 75)
        (=(minutos_contenido contenido_65) 66)
        (=(minutos_contenido contenido_66) 81)
        (=(minutos_contenido contenido_67) 62)
        (=(minutos_contenido contenido_68) 94)
        (=(minutos_contenido contenido_69) 76)
        (=(minutos_contenido contenido_75) 80)
        (=(minutos_contenido contenido_76) 81)
        (=(minutos_contenido contenido_77) 62)
        (=(minutos_contenido contenido_78) 94)
        (=(minutos_contenido contenido_79) 10)
        (=(minutos_contenido contenido_80) 95)
        (=(minutos_contenido contenido_81) 102)
        (=(minutos_contenido contenido_83) 102)
        (=(minutos_contenido contenido_88) 95)
        (=(minutos_contenido contenido_89) 100)
        (=(minutos_contenido contenido_90) 95)
        (=(minutos_contenido contenido_91) 102)
        (=(minutos_contenido contenido_92) 90)
        (=(minutos_contenido contenido_93) 88)
        (=(minutos_contenido contenido_94) 75)
        (=(minutos_contenido contenido_95) 80)
        (=(minutos_contenido contenido_96) 77)
        (=(minutos_contenido contenido_97) 92)
        (=(minutos_contenido contenido_98) 79)
        (=(minutos_contenido contenido_99) 85)
        (=(minutos_contenido contenido_100) 65)        

        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
