(define (problem problema_test_50contenidos)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10
        contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20
        contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30
        contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40
        contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50
    )

    (:init
		;; ------------------- PREDECESORES ----------------------------
        (predecesor contenido_8 contenido_9)
        (predecesor contenido_9 contenido_1)
        (predecesor contenido_1 contenido_2)
        (predecesor contenido_2 contenido_3)
        (predecesor contenido_3 contenido_4)
        
        (predecesor contenido_10 contenido_11)
        (predecesor contenido_11 contenido_12)
        (predecesor contenido_12 contenido_13)
        (predecesor contenido_13 contenido_14)
        (predecesor contenido_14 contenido_15)
        
        (predecesor contenido_30 contenido_31)
        (predecesor contenido_31 contenido_32)
        (predecesor contenido_32 contenido_33)
        (predecesor contenido_33 contenido_34)
        (predecesor contenido_34 contenido_35)
        (predecesor contenido_35 contenido_36)
        (predecesor contenido_36 contenido_37)
        (predecesor contenido_37 contenido_38)
        
        (predecesor contenido_25 contenido_50)
        (predecesor contenido_10 contenido_50)
        (predecesor contenido_48 contenido_50)
        (predecesor contenido_49 contenido_50)
        
        
        ;; ------------------- PREDECESORES VISTOS----------------------
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_23)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_25) 
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_39)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_41)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_43)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_45)
        (predecesores_vistos contenido_46)
        (predecesores_vistos contenido_47)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_49) 
        
		
		;; ------------------- PARALELAS ----------------------------
        (paralela contenido_5 contenido_6)
        (paralela contenido_6 contenido_7)
        (paralela contenido_7 contenido_8)
        (paralela contenido_8 contenido_5)
        (paralela contenido_5 contenido_7)
        (paralela contenido_6 contenido_8)
        (paralela contenido_7 contenido_5)
        (paralela contenido_8 contenido_6)
        (paralela contenido_5 contenido_8)
        (paralela contenido_6 contenido_5)
        (paralela contenido_7 contenido_6)
        (paralela contenido_8 contenido_7)
        
        (paralela contenido_24 contenido_25)
        (paralela contenido_25 contenido_24)
        
        (paralela contenido_32 contenido_40)
        (paralela contenido_40 contenido_41)
        (paralela contenido_41 contenido_32)
        (paralela contenido_32 contenido_41)
        (paralela contenido_40 contenido_32)
        (paralela contenido_41 contenido_40)
        
        (paralela contenido_43 contenido_44)
        (paralela contenido_44 contenido_43)
        
        ;; ------------------- NO PARALELAS ----------------------------
        (no_paralela contenido_1)
        (no_paralela contenido_2)
        (no_paralela contenido_3)
        (no_paralela contenido_4)
        (no_paralela contenido_9)
        (no_paralela contenido_10)
        (no_paralela contenido_11)
        (no_paralela contenido_12)
        (no_paralela contenido_13)
        (no_paralela contenido_14)
        (no_paralela contenido_15)
        (no_paralela contenido_16)
        (no_paralela contenido_17)
        (no_paralela contenido_18)
        (no_paralela contenido_19)
        (no_paralela contenido_20)
        (no_paralela contenido_21)
        (no_paralela contenido_22)
        (no_paralela contenido_23)
        (no_paralela contenido_26)
        (no_paralela contenido_27)
        (no_paralela contenido_28)
        (no_paralela contenido_29)
        (no_paralela contenido_30)
        (no_paralela contenido_31)
        (no_paralela contenido_33)
        (no_paralela contenido_34)
        (no_paralela contenido_35)
        (no_paralela contenido_36)
        (no_paralela contenido_37)
        (no_paralela contenido_38)
        (no_paralela contenido_39)
        (no_paralela contenido_42)
        (no_paralela contenido_45)
        (no_paralela contenido_46)
        (no_paralela contenido_47)
        (no_paralela contenido_48)
        (no_paralela contenido_49)
        (no_paralela contenido_50)
        
       
        ;; ---------------------- MINUTOS ------------------------------        
        (=(minutos_contenido contenido_5) 60)
        (=(minutos_contenido contenido_6) 50)
        (=(minutos_contenido contenido_7) 70)
        (=(minutos_contenido contenido_8) 80)
        
        (=(minutos_contenido contenido_24) 170)
        (=(minutos_contenido contenido_25) 180)
        
        (=(minutos_contenido contenido_32) 70)
        (=(minutos_contenido contenido_40) 50)
        (=(minutos_contenido contenido_41) 80)
        
        (=(minutos_contenido contenido_43) 170)
        (=(minutos_contenido contenido_44) 30)
        
        (=(minutos_contenido contenido_1) 60)
        (=(minutos_contenido contenido_2) 50)
        (=(minutos_contenido contenido_3) 70)
        (=(minutos_contenido contenido_4) 80)
        (=(minutos_contenido contenido_9) 80)
        (=(minutos_contenido contenido_10) 95)
        (=(minutos_contenido contenido_11) 102)
        (=(minutos_contenido contenido_12) 93)
        (=(minutos_contenido contenido_13) 88)
        (=(minutos_contenido contenido_14) 75)
        (=(minutos_contenido contenido_15) 66)
        (=(minutos_contenido contenido_16) 81)
        (=(minutos_contenido contenido_17) 62)
        (=(minutos_contenido contenido_18) 94)
        (=(minutos_contenido contenido_19) 76)
        (=(minutos_contenido contenido_20) 91)
        (=(minutos_contenido contenido_21) 102)
        (=(minutos_contenido contenido_22) 93)
        (=(minutos_contenido contenido_23) 80)
        (=(minutos_contenido contenido_26) 81)
        (=(minutos_contenido contenido_27) 62)
        (=(minutos_contenido contenido_28) 94)
        (=(minutos_contenido contenido_29) 10)
        (=(minutos_contenido contenido_30) 95)
        (=(minutos_contenido contenido_31) 102)
        (=(minutos_contenido contenido_33) 102)
        (=(minutos_contenido contenido_34) 70)
        (=(minutos_contenido contenido_35) 80)
        (=(minutos_contenido contenido_36) 65)
        (=(minutos_contenido contenido_37) 90)
        (=(minutos_contenido contenido_38) 95)
        (=(minutos_contenido contenido_39) 100)
        (=(minutos_contenido contenido_42) 90)
        (=(minutos_contenido contenido_45) 80)
        (=(minutos_contenido contenido_46) 77)
        (=(minutos_contenido contenido_47) 92)
        (=(minutos_contenido contenido_48) 79)
        (=(minutos_contenido contenido_49) 85)
        (=(minutos_contenido contenido_50) 65)
        

        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
