(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50
    )

    (:init
        (paralela contenido_47 contenido_21)
        (paralela contenido_21 contenido_47)
        (paralela contenido_47 contenido_30)
        (paralela contenido_30 contenido_47)
        (paralela contenido_47 contenido_16)
        (paralela contenido_16 contenido_47)
        (paralela contenido_21 contenido_30)
        (paralela contenido_30 contenido_21)
        (paralela contenido_21 contenido_16)
        (paralela contenido_16 contenido_21)
        (paralela contenido_30 contenido_16)
        (paralela contenido_16 contenido_30)
        (= (minutos_contenido contenido_47) 156)
        (= (minutos_contenido contenido_21) 96)
        (= (minutos_contenido contenido_30) 14)
        (= (minutos_contenido contenido_16) 58)
        (paralela contenido_9 contenido_31)
        (paralela contenido_31 contenido_9)
        (paralela contenido_9 contenido_2)
        (paralela contenido_2 contenido_9)
        (paralela contenido_9 contenido_28)
        (paralela contenido_28 contenido_9)
        (paralela contenido_31 contenido_2)
        (paralela contenido_2 contenido_31)
        (paralela contenido_31 contenido_28)
        (paralela contenido_28 contenido_31)
        (paralela contenido_2 contenido_28)
        (paralela contenido_28 contenido_2)
        (= (minutos_contenido contenido_9) 13)
        (= (minutos_contenido contenido_31) 100)
        (= (minutos_contenido contenido_2) 68)
        (= (minutos_contenido contenido_28) 113)
        (paralela contenido_38 contenido_34)
        (paralela contenido_34 contenido_38)
        (paralela contenido_38 contenido_23)
        (paralela contenido_23 contenido_38)
        (paralela contenido_38 contenido_25)
        (paralela contenido_25 contenido_38)
        (paralela contenido_34 contenido_23)
        (paralela contenido_23 contenido_34)
        (paralela contenido_34 contenido_25)
        (paralela contenido_25 contenido_34)
        (paralela contenido_23 contenido_25)
        (paralela contenido_25 contenido_23)
        (= (minutos_contenido contenido_38) 55)
        (= (minutos_contenido contenido_34) 49)
        (= (minutos_contenido contenido_23) 147)
        (= (minutos_contenido contenido_25) 123)
        (paralela contenido_50 contenido_45)
        (paralela contenido_45 contenido_50)
        (paralela contenido_50 contenido_42)
        (paralela contenido_42 contenido_50)
        (paralela contenido_50 contenido_8)
        (paralela contenido_8 contenido_50)
        (paralela contenido_45 contenido_42)
        (paralela contenido_42 contenido_45)
        (paralela contenido_45 contenido_8)
        (paralela contenido_8 contenido_45)
        (paralela contenido_42 contenido_8)
        (paralela contenido_8 contenido_42)
        (= (minutos_contenido contenido_50) 106)
        (= (minutos_contenido contenido_45) 128)
        (= (minutos_contenido contenido_42) 21)
        (= (minutos_contenido contenido_8) 12)
        (paralela contenido_3 contenido_11)
        (paralela contenido_11 contenido_3)
        (paralela contenido_3 contenido_18)
        (paralela contenido_18 contenido_3)
        (paralela contenido_3 contenido_26)
        (paralela contenido_26 contenido_3)
        (paralela contenido_11 contenido_18)
        (paralela contenido_18 contenido_11)
        (paralela contenido_11 contenido_26)
        (paralela contenido_26 contenido_11)
        (paralela contenido_18 contenido_26)
        (paralela contenido_26 contenido_18)
        (= (minutos_contenido contenido_3) 44)
        (= (minutos_contenido contenido_11) 126)
        (= (minutos_contenido contenido_18) 59)
        (= (minutos_contenido contenido_26) 15)
        (paralela contenido_32 contenido_36)
        (paralela contenido_36 contenido_32)
        (paralela contenido_32 contenido_49)
        (paralela contenido_49 contenido_32)
        (paralela contenido_32 contenido_48)
        (paralela contenido_48 contenido_32)
        (paralela contenido_36 contenido_49)
        (paralela contenido_49 contenido_36)
        (paralela contenido_36 contenido_48)
        (paralela contenido_48 contenido_36)
        (paralela contenido_49 contenido_48)
        (paralela contenido_48 contenido_49)
        (= (minutos_contenido contenido_32) 37)
        (= (minutos_contenido contenido_36) 168)
        (= (minutos_contenido contenido_49) 26)
        (= (minutos_contenido contenido_48) 140)
        (paralela contenido_4 contenido_40)
        (paralela contenido_40 contenido_4)
        (paralela contenido_4 contenido_22)
        (paralela contenido_22 contenido_4)
        (paralela contenido_4 contenido_39)
        (paralela contenido_39 contenido_4)
        (paralela contenido_40 contenido_22)
        (paralela contenido_22 contenido_40)
        (paralela contenido_40 contenido_39)
        (paralela contenido_39 contenido_40)
        (paralela contenido_22 contenido_39)
        (paralela contenido_39 contenido_22)
        (= (minutos_contenido contenido_4) 100)
        (= (minutos_contenido contenido_40) 191)
        (= (minutos_contenido contenido_22) 32)
        (= (minutos_contenido contenido_39) 31)
        (paralela contenido_7 contenido_43)
        (paralela contenido_43 contenido_7)
        (paralela contenido_7 contenido_17)
        (paralela contenido_17 contenido_7)
        (paralela contenido_7 contenido_27)
        (paralela contenido_27 contenido_7)
        (paralela contenido_43 contenido_17)
        (paralela contenido_17 contenido_43)
        (paralela contenido_43 contenido_27)
        (paralela contenido_27 contenido_43)
        (paralela contenido_17 contenido_27)
        (paralela contenido_27 contenido_17)
        (= (minutos_contenido contenido_7) 113)
        (= (minutos_contenido contenido_43) 17)
        (= (minutos_contenido contenido_17) 92)
        (= (minutos_contenido contenido_27) 77)
        (paralela contenido_35 contenido_33)
        (paralela contenido_33 contenido_35)
        (paralela contenido_35 contenido_44)
        (paralela contenido_44 contenido_35)
        (paralela contenido_35 contenido_15)
        (paralela contenido_15 contenido_35)
        (paralela contenido_33 contenido_44)
        (paralela contenido_44 contenido_33)
        (paralela contenido_33 contenido_15)
        (paralela contenido_15 contenido_33)
        (paralela contenido_44 contenido_15)
        (paralela contenido_15 contenido_44)
        (= (minutos_contenido contenido_35) 172)
        (= (minutos_contenido contenido_33) 51)
        (= (minutos_contenido contenido_44) 117)
        (= (minutos_contenido contenido_15) 26)
        (paralela contenido_14 contenido_1)
        (paralela contenido_1 contenido_14)
        (paralela contenido_14 contenido_29)
        (paralela contenido_29 contenido_14)
        (paralela contenido_14 contenido_10)
        (paralela contenido_10 contenido_14)
        (paralela contenido_1 contenido_29)
        (paralela contenido_29 contenido_1)
        (paralela contenido_1 contenido_10)
        (paralela contenido_10 contenido_1)
        (paralela contenido_29 contenido_10)
        (paralela contenido_10 contenido_29)
        (= (minutos_contenido contenido_14) 84)
        (= (minutos_contenido contenido_1) 109)
        (= (minutos_contenido contenido_29) 104)
        (= (minutos_contenido contenido_10) 42)
        (paralela contenido_12 contenido_19)
        (paralela contenido_19 contenido_12)
        (paralela contenido_12 contenido_24)
        (paralela contenido_24 contenido_12)
        (paralela contenido_12 contenido_5)
        (paralela contenido_5 contenido_12)
        (paralela contenido_19 contenido_24)
        (paralela contenido_24 contenido_19)
        (paralela contenido_19 contenido_5)
        (paralela contenido_5 contenido_19)
        (paralela contenido_24 contenido_5)
        (paralela contenido_5 contenido_24)
        (= (minutos_contenido contenido_12) 120)
        (= (minutos_contenido contenido_19) 25)
        (= (minutos_contenido contenido_24) 199)
        (= (minutos_contenido contenido_5) 44)
        (paralela contenido_6 contenido_46)
        (paralela contenido_46 contenido_6)
        (paralela contenido_6 contenido_41)
        (paralela contenido_41 contenido_6)
        (paralela contenido_6 contenido_20)
        (paralela contenido_20 contenido_6)
        (paralela contenido_46 contenido_41)
        (paralela contenido_41 contenido_46)
        (paralela contenido_46 contenido_20)
        (paralela contenido_20 contenido_46)
        (paralela contenido_41 contenido_20)
        (paralela contenido_20 contenido_41)
        (= (minutos_contenido contenido_6) 119)
        (= (minutos_contenido contenido_46) 17)
        (= (minutos_contenido contenido_41) 50)
        (= (minutos_contenido contenido_20) 143)
        (paralelas_vistas contenido_13)
        (no_paralela contenido_13)
        (paralelas_vistas contenido_37)
        (no_paralela contenido_37)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_37)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
