(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125
    )

    (:init
        (paralela contenido_70 contenido_35)
        (paralela contenido_35 contenido_70)
        (paralela contenido_70 contenido_43)
        (paralela contenido_43 contenido_70)
        (paralela contenido_70 contenido_114)
        (paralela contenido_114 contenido_70)
        (paralela contenido_35 contenido_43)
        (paralela contenido_43 contenido_35)
        (paralela contenido_35 contenido_114)
        (paralela contenido_114 contenido_35)
        (paralela contenido_43 contenido_114)
        (paralela contenido_114 contenido_43)
        (= (minutos_contenido contenido_70) 117)
        (= (minutos_contenido contenido_35) 10)
        (= (minutos_contenido contenido_43) 37)
        (= (minutos_contenido contenido_114) 168)
        (paralela contenido_104 contenido_22)
        (paralela contenido_22 contenido_104)
        (paralela contenido_104 contenido_5)
        (paralela contenido_5 contenido_104)
        (paralela contenido_104 contenido_120)
        (paralela contenido_120 contenido_104)
        (paralela contenido_22 contenido_5)
        (paralela contenido_5 contenido_22)
        (paralela contenido_22 contenido_120)
        (paralela contenido_120 contenido_22)
        (paralela contenido_5 contenido_120)
        (paralela contenido_120 contenido_5)
        (= (minutos_contenido contenido_104) 32)
        (= (minutos_contenido contenido_22) 31)
        (= (minutos_contenido contenido_5) 120)
        (= (minutos_contenido contenido_120) 12)
        (paralela contenido_12 contenido_10)
        (paralela contenido_10 contenido_12)
        (paralela contenido_12 contenido_46)
        (paralela contenido_46 contenido_12)
        (paralela contenido_12 contenido_7)
        (paralela contenido_7 contenido_12)
        (paralela contenido_10 contenido_46)
        (paralela contenido_46 contenido_10)
        (paralela contenido_10 contenido_7)
        (paralela contenido_7 contenido_10)
        (paralela contenido_46 contenido_7)
        (paralela contenido_7 contenido_46)
        (= (minutos_contenido contenido_12) 92)
        (= (minutos_contenido contenido_10) 77)
        (= (minutos_contenido contenido_46) 130)
        (= (minutos_contenido contenido_7) 18)
        (paralela contenido_45 contenido_103)
        (paralela contenido_103 contenido_45)
        (paralela contenido_45 contenido_84)
        (paralela contenido_84 contenido_45)
        (paralela contenido_45 contenido_97)
        (paralela contenido_97 contenido_45)
        (paralela contenido_103 contenido_84)
        (paralela contenido_84 contenido_103)
        (paralela contenido_103 contenido_97)
        (paralela contenido_97 contenido_103)
        (paralela contenido_84 contenido_97)
        (paralela contenido_97 contenido_84)
        (= (minutos_contenido contenido_45) 104)
        (= (minutos_contenido contenido_103) 42)
        (= (minutos_contenido contenido_84) 146)
        (= (minutos_contenido contenido_97) 96)
        (paralela contenido_121 contenido_29)
        (paralela contenido_29 contenido_121)
        (paralela contenido_121 contenido_54)
        (paralela contenido_54 contenido_121)
        (paralela contenido_121 contenido_55)
        (paralela contenido_55 contenido_121)
        (paralela contenido_29 contenido_54)
        (paralela contenido_54 contenido_29)
        (paralela contenido_29 contenido_55)
        (paralela contenido_55 contenido_29)
        (paralela contenido_54 contenido_55)
        (paralela contenido_55 contenido_54)
        (= (minutos_contenido contenido_121) 33)
        (= (minutos_contenido contenido_29) 79)
        (= (minutos_contenido contenido_54) 139)
        (= (minutos_contenido contenido_55) 72)
        (paralela contenido_101 contenido_52)
        (paralela contenido_52 contenido_101)
        (paralela contenido_101 contenido_18)
        (paralela contenido_18 contenido_101)
        (paralela contenido_101 contenido_91)
        (paralela contenido_91 contenido_101)
        (paralela contenido_52 contenido_18)
        (paralela contenido_18 contenido_52)
        (paralela contenido_52 contenido_91)
        (paralela contenido_91 contenido_52)
        (paralela contenido_18 contenido_91)
        (paralela contenido_91 contenido_18)
        (= (minutos_contenido contenido_101) 62)
        (= (minutos_contenido contenido_52) 92)
        (= (minutos_contenido contenido_18) 77)
        (= (minutos_contenido contenido_91) 111)
        (paralela contenido_33 contenido_89)
        (paralela contenido_89 contenido_33)
        (paralela contenido_33 contenido_64)
        (paralela contenido_64 contenido_33)
        (paralela contenido_33 contenido_92)
        (paralela contenido_92 contenido_33)
        (paralela contenido_89 contenido_64)
        (paralela contenido_64 contenido_89)
        (paralela contenido_89 contenido_92)
        (paralela contenido_92 contenido_89)
        (paralela contenido_64 contenido_92)
        (paralela contenido_92 contenido_64)
        (= (minutos_contenido contenido_33) 21)
        (= (minutos_contenido contenido_89) 138)
        (= (minutos_contenido contenido_64) 30)
        (= (minutos_contenido contenido_92) 60)
        (paralela contenido_125 contenido_31)
        (paralela contenido_31 contenido_125)
        (paralela contenido_125 contenido_25)
        (paralela contenido_25 contenido_125)
        (paralela contenido_125 contenido_34)
        (paralela contenido_34 contenido_125)
        (paralela contenido_31 contenido_25)
        (paralela contenido_25 contenido_31)
        (paralela contenido_31 contenido_34)
        (paralela contenido_34 contenido_31)
        (paralela contenido_25 contenido_34)
        (paralela contenido_34 contenido_25)
        (= (minutos_contenido contenido_125) 139)
        (= (minutos_contenido contenido_31) 61)
        (= (minutos_contenido contenido_25) 14)
        (= (minutos_contenido contenido_34) 59)
        (paralela contenido_53 contenido_44)
        (paralela contenido_44 contenido_53)
        (paralela contenido_53 contenido_8)
        (paralela contenido_8 contenido_53)
        (paralela contenido_53 contenido_106)
        (paralela contenido_106 contenido_53)
        (paralela contenido_44 contenido_8)
        (paralela contenido_8 contenido_44)
        (paralela contenido_44 contenido_106)
        (paralela contenido_106 contenido_44)
        (paralela contenido_8 contenido_106)
        (paralela contenido_106 contenido_8)
        (= (minutos_contenido contenido_53) 78)
        (= (minutos_contenido contenido_44) 154)
        (= (minutos_contenido contenido_8) 69)
        (= (minutos_contenido contenido_106) 31)
        (paralela contenido_105 contenido_124)
        (paralela contenido_124 contenido_105)
        (paralela contenido_105 contenido_123)
        (paralela contenido_123 contenido_105)
        (paralela contenido_105 contenido_108)
        (paralela contenido_108 contenido_105)
        (paralela contenido_124 contenido_123)
        (paralela contenido_123 contenido_124)
        (paralela contenido_124 contenido_108)
        (paralela contenido_108 contenido_124)
        (paralela contenido_123 contenido_108)
        (paralela contenido_108 contenido_123)
        (= (minutos_contenido contenido_105) 163)
        (= (minutos_contenido contenido_124) 91)
        (= (minutos_contenido contenido_123) 31)
        (= (minutos_contenido contenido_108) 97)
        (paralela contenido_39 contenido_93)
        (paralela contenido_93 contenido_39)
        (paralela contenido_39 contenido_90)
        (paralela contenido_90 contenido_39)
        (paralela contenido_39 contenido_87)
        (paralela contenido_87 contenido_39)
        (paralela contenido_93 contenido_90)
        (paralela contenido_90 contenido_93)
        (paralela contenido_93 contenido_87)
        (paralela contenido_87 contenido_93)
        (paralela contenido_90 contenido_87)
        (paralela contenido_87 contenido_90)
        (= (minutos_contenido contenido_39) 41)
        (= (minutos_contenido contenido_93) 186)
        (= (minutos_contenido contenido_90) 23)
        (= (minutos_contenido contenido_87) 102)
        (paralela contenido_58 contenido_74)
        (paralela contenido_74 contenido_58)
        (paralela contenido_58 contenido_50)
        (paralela contenido_50 contenido_58)
        (paralela contenido_58 contenido_48)
        (paralela contenido_48 contenido_58)
        (paralela contenido_74 contenido_50)
        (paralela contenido_50 contenido_74)
        (paralela contenido_74 contenido_48)
        (paralela contenido_48 contenido_74)
        (paralela contenido_50 contenido_48)
        (paralela contenido_48 contenido_50)
        (= (minutos_contenido contenido_58) 90)
        (= (minutos_contenido contenido_74) 101)
        (= (minutos_contenido contenido_50) 65)
        (= (minutos_contenido contenido_48) 124)
        (paralela contenido_20 contenido_80)
        (paralela contenido_80 contenido_20)
        (paralela contenido_20 contenido_112)
        (paralela contenido_112 contenido_20)
        (paralela contenido_20 contenido_49)
        (paralela contenido_49 contenido_20)
        (paralela contenido_80 contenido_112)
        (paralela contenido_112 contenido_80)
        (paralela contenido_80 contenido_49)
        (paralela contenido_49 contenido_80)
        (paralela contenido_112 contenido_49)
        (paralela contenido_49 contenido_112)
        (= (minutos_contenido contenido_20) 97)
        (= (minutos_contenido contenido_80) 59)
        (= (minutos_contenido contenido_112) 56)
        (= (minutos_contenido contenido_49) 107)
        (paralela contenido_1 contenido_36)
        (paralela contenido_36 contenido_1)
        (paralela contenido_1 contenido_76)
        (paralela contenido_76 contenido_1)
        (paralela contenido_1 contenido_30)
        (paralela contenido_30 contenido_1)
        (paralela contenido_36 contenido_76)
        (paralela contenido_76 contenido_36)
        (paralela contenido_36 contenido_30)
        (paralela contenido_30 contenido_36)
        (paralela contenido_76 contenido_30)
        (paralela contenido_30 contenido_76)
        (= (minutos_contenido contenido_1) 104)
        (= (minutos_contenido contenido_36) 27)
        (= (minutos_contenido contenido_76) 85)
        (= (minutos_contenido contenido_30) 41)
        (paralela contenido_4 contenido_96)
        (paralela contenido_96 contenido_4)
        (paralela contenido_4 contenido_42)
        (paralela contenido_42 contenido_4)
        (paralela contenido_4 contenido_85)
        (paralela contenido_85 contenido_4)
        (paralela contenido_96 contenido_42)
        (paralela contenido_42 contenido_96)
        (paralela contenido_96 contenido_85)
        (paralela contenido_85 contenido_96)
        (paralela contenido_42 contenido_85)
        (paralela contenido_85 contenido_42)
        (= (minutos_contenido contenido_4) 24)
        (= (minutos_contenido contenido_96) 107)
        (= (minutos_contenido contenido_42) 23)
        (= (minutos_contenido contenido_85) 160)
        (paralela contenido_59 contenido_15)
        (paralela contenido_15 contenido_59)
        (paralela contenido_59 contenido_27)
        (paralela contenido_27 contenido_59)
        (paralela contenido_59 contenido_63)
        (paralela contenido_63 contenido_59)
        (paralela contenido_15 contenido_27)
        (paralela contenido_27 contenido_15)
        (paralela contenido_15 contenido_63)
        (paralela contenido_63 contenido_15)
        (paralela contenido_27 contenido_63)
        (paralela contenido_63 contenido_27)
        (= (minutos_contenido contenido_59) 109)
        (= (minutos_contenido contenido_15) 86)
        (= (minutos_contenido contenido_27) 37)
        (= (minutos_contenido contenido_63) 129)
        (paralela contenido_94 contenido_13)
        (paralela contenido_13 contenido_94)
        (paralela contenido_94 contenido_75)
        (paralela contenido_75 contenido_94)
        (paralela contenido_94 contenido_40)
        (paralela contenido_40 contenido_94)
        (paralela contenido_13 contenido_75)
        (paralela contenido_75 contenido_13)
        (paralela contenido_13 contenido_40)
        (paralela contenido_40 contenido_13)
        (paralela contenido_75 contenido_40)
        (paralela contenido_40 contenido_75)
        (= (minutos_contenido contenido_94) 80)
        (= (minutos_contenido contenido_13) 96)
        (= (minutos_contenido contenido_75) 22)
        (= (minutos_contenido contenido_40) 56)
        (paralela contenido_82 contenido_69)
        (paralela contenido_69 contenido_82)
        (paralela contenido_82 contenido_73)
        (paralela contenido_73 contenido_82)
        (paralela contenido_82 contenido_107)
        (paralela contenido_107 contenido_82)
        (paralela contenido_69 contenido_73)
        (paralela contenido_73 contenido_69)
        (paralela contenido_69 contenido_107)
        (paralela contenido_107 contenido_69)
        (paralela contenido_73 contenido_107)
        (paralela contenido_107 contenido_73)
        (= (minutos_contenido contenido_82) 41)
        (= (minutos_contenido contenido_69) 15)
        (= (minutos_contenido contenido_73) 119)
        (= (minutos_contenido contenido_107) 179)
        (paralela contenido_47 contenido_122)
        (paralela contenido_122 contenido_47)
        (paralela contenido_47 contenido_37)
        (paralela contenido_37 contenido_47)
        (paralela contenido_47 contenido_24)
        (paralela contenido_24 contenido_47)
        (paralela contenido_122 contenido_37)
        (paralela contenido_37 contenido_122)
        (paralela contenido_122 contenido_24)
        (paralela contenido_24 contenido_122)
        (paralela contenido_37 contenido_24)
        (paralela contenido_24 contenido_37)
        (= (minutos_contenido contenido_47) 46)
        (= (minutos_contenido contenido_122) 93)
        (= (minutos_contenido contenido_37) 104)
        (= (minutos_contenido contenido_24) 66)
        (paralela contenido_38 contenido_113)
        (paralela contenido_113 contenido_38)
        (paralela contenido_38 contenido_81)
        (paralela contenido_81 contenido_38)
        (paralela contenido_38 contenido_9)
        (paralela contenido_9 contenido_38)
        (paralela contenido_113 contenido_81)
        (paralela contenido_81 contenido_113)
        (paralela contenido_113 contenido_9)
        (paralela contenido_9 contenido_113)
        (paralela contenido_81 contenido_9)
        (paralela contenido_9 contenido_81)
        (= (minutos_contenido contenido_38) 68)
        (= (minutos_contenido contenido_113) 186)
        (= (minutos_contenido contenido_81) 26)
        (= (minutos_contenido contenido_9) 74)
        (paralela contenido_71 contenido_88)
        (paralela contenido_88 contenido_71)
        (paralela contenido_71 contenido_17)
        (paralela contenido_17 contenido_71)
        (paralela contenido_71 contenido_3)
        (paralela contenido_3 contenido_71)
        (paralela contenido_88 contenido_17)
        (paralela contenido_17 contenido_88)
        (paralela contenido_88 contenido_3)
        (paralela contenido_3 contenido_88)
        (paralela contenido_17 contenido_3)
        (paralela contenido_3 contenido_17)
        (= (minutos_contenido contenido_71) 82)
        (= (minutos_contenido contenido_88) 53)
        (= (minutos_contenido contenido_17) 116)
        (= (minutos_contenido contenido_3) 101)
        (paralela contenido_66 contenido_51)
        (paralela contenido_51 contenido_66)
        (paralela contenido_66 contenido_102)
        (paralela contenido_102 contenido_66)
        (paralela contenido_66 contenido_32)
        (paralela contenido_32 contenido_66)
        (paralela contenido_51 contenido_102)
        (paralela contenido_102 contenido_51)
        (paralela contenido_51 contenido_32)
        (paralela contenido_32 contenido_51)
        (paralela contenido_102 contenido_32)
        (paralela contenido_32 contenido_102)
        (= (minutos_contenido contenido_66) 118)
        (= (minutos_contenido contenido_51) 21)
        (= (minutos_contenido contenido_102) 165)
        (= (minutos_contenido contenido_32) 13)
        (paralela contenido_115 contenido_77)
        (paralela contenido_77 contenido_115)
        (paralela contenido_115 contenido_2)
        (paralela contenido_2 contenido_115)
        (paralela contenido_115 contenido_28)
        (paralela contenido_28 contenido_115)
        (paralela contenido_77 contenido_2)
        (paralela contenido_2 contenido_77)
        (paralela contenido_77 contenido_28)
        (paralela contenido_28 contenido_77)
        (paralela contenido_2 contenido_28)
        (paralela contenido_28 contenido_2)
        (= (minutos_contenido contenido_115) 21)
        (= (minutos_contenido contenido_77) 78)
        (= (minutos_contenido contenido_2) 144)
        (= (minutos_contenido contenido_28) 52)
        (paralela contenido_62 contenido_14)
        (paralela contenido_14 contenido_62)
        (paralela contenido_62 contenido_86)
        (paralela contenido_86 contenido_62)
        (paralela contenido_62 contenido_11)
        (paralela contenido_11 contenido_62)
        (paralela contenido_14 contenido_86)
        (paralela contenido_86 contenido_14)
        (paralela contenido_14 contenido_11)
        (paralela contenido_11 contenido_14)
        (paralela contenido_86 contenido_11)
        (paralela contenido_11 contenido_86)
        (= (minutos_contenido contenido_62) 145)
        (= (minutos_contenido contenido_14) 33)
        (= (minutos_contenido contenido_86) 36)
        (= (minutos_contenido contenido_11) 123)
        (paralela contenido_79 contenido_119)
        (paralela contenido_119 contenido_79)
        (paralela contenido_79 contenido_67)
        (paralela contenido_67 contenido_79)
        (paralela contenido_79 contenido_99)
        (paralela contenido_99 contenido_79)
        (paralela contenido_119 contenido_67)
        (paralela contenido_67 contenido_119)
        (paralela contenido_119 contenido_99)
        (paralela contenido_99 contenido_119)
        (paralela contenido_67 contenido_99)
        (paralela contenido_99 contenido_67)
        (= (minutos_contenido contenido_79) 136)
        (= (minutos_contenido contenido_119) 44)
        (= (minutos_contenido contenido_67) 59)
        (= (minutos_contenido contenido_99) 64)
        (paralela contenido_110 contenido_95)
        (paralela contenido_95 contenido_110)
        (paralela contenido_110 contenido_98)
        (paralela contenido_98 contenido_110)
        (paralela contenido_110 contenido_61)
        (paralela contenido_61 contenido_110)
        (paralela contenido_95 contenido_98)
        (paralela contenido_98 contenido_95)
        (paralela contenido_95 contenido_61)
        (paralela contenido_61 contenido_95)
        (paralela contenido_98 contenido_61)
        (paralela contenido_61 contenido_98)
        (= (minutos_contenido contenido_110) 71)
        (= (minutos_contenido contenido_95) 19)
        (= (minutos_contenido contenido_98) 72)
        (= (minutos_contenido contenido_61) 63)
        (paralela contenido_109 contenido_16)
        (paralela contenido_16 contenido_109)
        (paralela contenido_109 contenido_6)
        (paralela contenido_6 contenido_109)
        (paralela contenido_109 contenido_23)
        (paralela contenido_23 contenido_109)
        (paralela contenido_16 contenido_6)
        (paralela contenido_6 contenido_16)
        (paralela contenido_16 contenido_23)
        (paralela contenido_23 contenido_16)
        (paralela contenido_6 contenido_23)
        (paralela contenido_23 contenido_6)
        (= (minutos_contenido contenido_109) 28)
        (= (minutos_contenido contenido_16) 113)
        (= (minutos_contenido contenido_6) 16)
        (= (minutos_contenido contenido_23) 12)
        (paralela contenido_100 contenido_60)
        (paralela contenido_60 contenido_100)
        (paralela contenido_100 contenido_118)
        (paralela contenido_118 contenido_100)
        (paralela contenido_100 contenido_68)
        (paralela contenido_68 contenido_100)
        (paralela contenido_60 contenido_118)
        (paralela contenido_118 contenido_60)
        (paralela contenido_60 contenido_68)
        (paralela contenido_68 contenido_60)
        (paralela contenido_118 contenido_68)
        (paralela contenido_68 contenido_118)
        (= (minutos_contenido contenido_100) 17)
        (= (minutos_contenido contenido_60) 20)
        (= (minutos_contenido contenido_118) 73)
        (= (minutos_contenido contenido_68) 197)
        (paralela contenido_65 contenido_78)
        (paralela contenido_78 contenido_65)
        (paralela contenido_65 contenido_111)
        (paralela contenido_111 contenido_65)
        (paralela contenido_65 contenido_19)
        (paralela contenido_19 contenido_65)
        (paralela contenido_78 contenido_111)
        (paralela contenido_111 contenido_78)
        (paralela contenido_78 contenido_19)
        (paralela contenido_19 contenido_78)
        (paralela contenido_111 contenido_19)
        (paralela contenido_19 contenido_111)
        (= (minutos_contenido contenido_65) 16)
        (= (minutos_contenido contenido_78) 102)
        (= (minutos_contenido contenido_111) 49)
        (= (minutos_contenido contenido_19) 129)
        (paralela contenido_56 contenido_57)
        (paralela contenido_57 contenido_56)
        (paralela contenido_56 contenido_26)
        (paralela contenido_26 contenido_56)
        (paralela contenido_56 contenido_83)
        (paralela contenido_83 contenido_56)
        (paralela contenido_57 contenido_26)
        (paralela contenido_26 contenido_57)
        (paralela contenido_57 contenido_83)
        (paralela contenido_83 contenido_57)
        (paralela contenido_26 contenido_83)
        (paralela contenido_83 contenido_26)
        (= (minutos_contenido contenido_56) 58)
        (= (minutos_contenido contenido_57) 109)
        (= (minutos_contenido contenido_26) 29)
        (= (minutos_contenido contenido_83) 137)
        (paralelas_vistas contenido_41)
        (no_paralela contenido_41)
        (paralelas_vistas contenido_21)
        (no_paralela contenido_21)
        (paralelas_vistas contenido_72)
        (no_paralela contenido_72)
        (paralelas_vistas contenido_117)
        (no_paralela contenido_117)
        (paralelas_vistas contenido_116)
        (no_paralela contenido_116)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_41)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_116)
        (predecesores_vistos contenido_117)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
