(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75
    )

    (:init
        (paralela contenido_51 contenido_6)
        (paralela contenido_6 contenido_51)
        (paralela contenido_51 contenido_32)
        (paralela contenido_32 contenido_51)
        (paralela contenido_51 contenido_59)
        (paralela contenido_59 contenido_51)
        (paralela contenido_6 contenido_32)
        (paralela contenido_32 contenido_6)
        (paralela contenido_6 contenido_59)
        (paralela contenido_59 contenido_6)
        (paralela contenido_32 contenido_59)
        (paralela contenido_59 contenido_32)
        (= (minutos_contenido contenido_51) 156)
        (= (minutos_contenido contenido_6) 96)
        (= (minutos_contenido contenido_32) 14)
        (= (minutos_contenido contenido_59) 58)
        (paralela contenido_52 contenido_63)
        (paralela contenido_63 contenido_52)
        (paralela contenido_52 contenido_43)
        (paralela contenido_43 contenido_52)
        (paralela contenido_52 contenido_53)
        (paralela contenido_53 contenido_52)
        (paralela contenido_63 contenido_43)
        (paralela contenido_43 contenido_63)
        (paralela contenido_63 contenido_53)
        (paralela contenido_53 contenido_63)
        (paralela contenido_43 contenido_53)
        (paralela contenido_53 contenido_43)
        (= (minutos_contenido contenido_52) 13)
        (= (minutos_contenido contenido_63) 100)
        (= (minutos_contenido contenido_43) 68)
        (= (minutos_contenido contenido_53) 113)
        (paralela contenido_30 contenido_50)
        (paralela contenido_50 contenido_30)
        (paralela contenido_30 contenido_58)
        (paralela contenido_58 contenido_30)
        (paralela contenido_30 contenido_56)
        (paralela contenido_56 contenido_30)
        (paralela contenido_50 contenido_58)
        (paralela contenido_58 contenido_50)
        (paralela contenido_50 contenido_56)
        (paralela contenido_56 contenido_50)
        (paralela contenido_58 contenido_56)
        (paralela contenido_56 contenido_58)
        (= (minutos_contenido contenido_30) 55)
        (= (minutos_contenido contenido_50) 49)
        (= (minutos_contenido contenido_58) 147)
        (= (minutos_contenido contenido_56) 123)
        (paralela contenido_27 contenido_54)
        (paralela contenido_54 contenido_27)
        (paralela contenido_27 contenido_21)
        (paralela contenido_21 contenido_27)
        (paralela contenido_27 contenido_22)
        (paralela contenido_22 contenido_27)
        (paralela contenido_54 contenido_21)
        (paralela contenido_21 contenido_54)
        (paralela contenido_54 contenido_22)
        (paralela contenido_22 contenido_54)
        (paralela contenido_21 contenido_22)
        (paralela contenido_22 contenido_21)
        (= (minutos_contenido contenido_27) 106)
        (= (minutos_contenido contenido_54) 128)
        (= (minutos_contenido contenido_21) 21)
        (= (minutos_contenido contenido_22) 12)
        (paralela contenido_74 contenido_25)
        (paralela contenido_25 contenido_74)
        (paralela contenido_74 contenido_42)
        (paralela contenido_42 contenido_74)
        (paralela contenido_74 contenido_55)
        (paralela contenido_55 contenido_74)
        (paralela contenido_25 contenido_42)
        (paralela contenido_42 contenido_25)
        (paralela contenido_25 contenido_55)
        (paralela contenido_55 contenido_25)
        (paralela contenido_42 contenido_55)
        (paralela contenido_55 contenido_42)
        (= (minutos_contenido contenido_74) 44)
        (= (minutos_contenido contenido_25) 126)
        (= (minutos_contenido contenido_42) 59)
        (= (minutos_contenido contenido_55) 15)
        (paralela contenido_71 contenido_47)
        (paralela contenido_47 contenido_71)
        (paralela contenido_71 contenido_20)
        (paralela contenido_20 contenido_71)
        (paralela contenido_71 contenido_44)
        (paralela contenido_44 contenido_71)
        (paralela contenido_47 contenido_20)
        (paralela contenido_20 contenido_47)
        (paralela contenido_47 contenido_44)
        (paralela contenido_44 contenido_47)
        (paralela contenido_20 contenido_44)
        (paralela contenido_44 contenido_20)
        (= (minutos_contenido contenido_71) 37)
        (= (minutos_contenido contenido_47) 168)
        (= (minutos_contenido contenido_20) 26)
        (= (minutos_contenido contenido_44) 140)
        (paralela contenido_49 contenido_38)
        (paralela contenido_38 contenido_49)
        (paralela contenido_49 contenido_73)
        (paralela contenido_73 contenido_49)
        (paralela contenido_49 contenido_75)
        (paralela contenido_75 contenido_49)
        (paralela contenido_38 contenido_73)
        (paralela contenido_73 contenido_38)
        (paralela contenido_38 contenido_75)
        (paralela contenido_75 contenido_38)
        (paralela contenido_73 contenido_75)
        (paralela contenido_75 contenido_73)
        (= (minutos_contenido contenido_49) 100)
        (= (minutos_contenido contenido_38) 191)
        (= (minutos_contenido contenido_73) 32)
        (= (minutos_contenido contenido_75) 31)
        (paralela contenido_37 contenido_12)
        (paralela contenido_12 contenido_37)
        (paralela contenido_37 contenido_57)
        (paralela contenido_57 contenido_37)
        (paralela contenido_37 contenido_68)
        (paralela contenido_68 contenido_37)
        (paralela contenido_12 contenido_57)
        (paralela contenido_57 contenido_12)
        (paralela contenido_12 contenido_68)
        (paralela contenido_68 contenido_12)
        (paralela contenido_57 contenido_68)
        (paralela contenido_68 contenido_57)
        (= (minutos_contenido contenido_37) 113)
        (= (minutos_contenido contenido_12) 17)
        (= (minutos_contenido contenido_57) 92)
        (= (minutos_contenido contenido_68) 77)
        (paralela contenido_45 contenido_34)
        (paralela contenido_34 contenido_45)
        (paralela contenido_45 contenido_16)
        (paralela contenido_16 contenido_45)
        (paralela contenido_45 contenido_19)
        (paralela contenido_19 contenido_45)
        (paralela contenido_34 contenido_16)
        (paralela contenido_16 contenido_34)
        (paralela contenido_34 contenido_19)
        (paralela contenido_19 contenido_34)
        (paralela contenido_16 contenido_19)
        (paralela contenido_19 contenido_16)
        (= (minutos_contenido contenido_45) 172)
        (= (minutos_contenido contenido_34) 51)
        (= (minutos_contenido contenido_16) 117)
        (= (minutos_contenido contenido_19) 26)
        (paralela contenido_66 contenido_29)
        (paralela contenido_29 contenido_66)
        (paralela contenido_66 contenido_48)
        (paralela contenido_48 contenido_66)
        (paralela contenido_66 contenido_33)
        (paralela contenido_33 contenido_66)
        (paralela contenido_29 contenido_48)
        (paralela contenido_48 contenido_29)
        (paralela contenido_29 contenido_33)
        (paralela contenido_33 contenido_29)
        (paralela contenido_48 contenido_33)
        (paralela contenido_33 contenido_48)
        (= (minutos_contenido contenido_66) 84)
        (= (minutos_contenido contenido_29) 109)
        (= (minutos_contenido contenido_48) 104)
        (= (minutos_contenido contenido_33) 42)
        (paralela contenido_72 contenido_1)
        (paralela contenido_1 contenido_72)
        (paralela contenido_72 contenido_8)
        (paralela contenido_8 contenido_72)
        (paralela contenido_72 contenido_11)
        (paralela contenido_11 contenido_72)
        (paralela contenido_1 contenido_8)
        (paralela contenido_8 contenido_1)
        (paralela contenido_1 contenido_11)
        (paralela contenido_11 contenido_1)
        (paralela contenido_8 contenido_11)
        (paralela contenido_11 contenido_8)
        (= (minutos_contenido contenido_72) 120)
        (= (minutos_contenido contenido_1) 25)
        (= (minutos_contenido contenido_8) 199)
        (= (minutos_contenido contenido_11) 44)
        (paralela contenido_65 contenido_60)
        (paralela contenido_60 contenido_65)
        (paralela contenido_65 contenido_5)
        (paralela contenido_5 contenido_65)
        (paralela contenido_65 contenido_7)
        (paralela contenido_7 contenido_65)
        (paralela contenido_60 contenido_5)
        (paralela contenido_5 contenido_60)
        (paralela contenido_60 contenido_7)
        (paralela contenido_7 contenido_60)
        (paralela contenido_5 contenido_7)
        (paralela contenido_7 contenido_5)
        (= (minutos_contenido contenido_65) 119)
        (= (minutos_contenido contenido_60) 17)
        (= (minutos_contenido contenido_5) 50)
        (= (minutos_contenido contenido_7) 143)
        (paralela contenido_62 contenido_10)
        (paralela contenido_10 contenido_62)
        (paralela contenido_62 contenido_4)
        (paralela contenido_4 contenido_62)
        (paralela contenido_62 contenido_39)
        (paralela contenido_39 contenido_62)
        (paralela contenido_10 contenido_4)
        (paralela contenido_4 contenido_10)
        (paralela contenido_10 contenido_39)
        (paralela contenido_39 contenido_10)
        (paralela contenido_4 contenido_39)
        (paralela contenido_39 contenido_4)
        (= (minutos_contenido contenido_62) 45)
        (= (minutos_contenido contenido_10) 97)
        (= (minutos_contenido contenido_4) 138)
        (= (minutos_contenido contenido_39) 36)
        (paralela contenido_2 contenido_46)
        (paralela contenido_46 contenido_2)
        (paralela contenido_2 contenido_18)
        (paralela contenido_18 contenido_2)
        (paralela contenido_2 contenido_28)
        (paralela contenido_28 contenido_2)
        (paralela contenido_46 contenido_18)
        (paralela contenido_18 contenido_46)
        (paralela contenido_46 contenido_28)
        (paralela contenido_28 contenido_46)
        (paralela contenido_18 contenido_28)
        (paralela contenido_28 contenido_18)
        (= (minutos_contenido contenido_2) 155)
        (= (minutos_contenido contenido_46) 97)
        (= (minutos_contenido contenido_18) 33)
        (= (minutos_contenido contenido_28) 79)
        (paralela contenido_3 contenido_24)
        (paralela contenido_24 contenido_3)
        (paralela contenido_3 contenido_13)
        (paralela contenido_13 contenido_3)
        (paralela contenido_3 contenido_70)
        (paralela contenido_70 contenido_3)
        (paralela contenido_24 contenido_13)
        (paralela contenido_13 contenido_24)
        (paralela contenido_24 contenido_70)
        (paralela contenido_70 contenido_24)
        (paralela contenido_13 contenido_70)
        (paralela contenido_70 contenido_13)
        (= (minutos_contenido contenido_3) 77)
        (= (minutos_contenido contenido_24) 111)
        (= (minutos_contenido contenido_13) 21)
        (= (minutos_contenido contenido_70) 138)
        (paralela contenido_67 contenido_9)
        (paralela contenido_9 contenido_67)
        (paralela contenido_67 contenido_31)
        (paralela contenido_31 contenido_67)
        (paralela contenido_67 contenido_41)
        (paralela contenido_41 contenido_67)
        (paralela contenido_9 contenido_31)
        (paralela contenido_31 contenido_9)
        (paralela contenido_9 contenido_41)
        (paralela contenido_41 contenido_9)
        (paralela contenido_31 contenido_41)
        (paralela contenido_41 contenido_31)
        (= (minutos_contenido contenido_67) 30)
        (= (minutos_contenido contenido_9) 60)
        (= (minutos_contenido contenido_31) 139)
        (= (minutos_contenido contenido_41) 61)
        (paralela contenido_64 contenido_17)
        (paralela contenido_17 contenido_64)
        (paralela contenido_64 contenido_36)
        (paralela contenido_36 contenido_64)
        (paralela contenido_64 contenido_35)
        (paralela contenido_35 contenido_64)
        (paralela contenido_17 contenido_36)
        (paralela contenido_36 contenido_17)
        (paralela contenido_17 contenido_35)
        (paralela contenido_35 contenido_17)
        (paralela contenido_36 contenido_35)
        (paralela contenido_35 contenido_36)
        (= (minutos_contenido contenido_64) 14)
        (= (minutos_contenido contenido_17) 59)
        (= (minutos_contenido contenido_36) 78)
        (= (minutos_contenido contenido_35) 154)
        (paralela contenido_23 contenido_69)
        (paralela contenido_69 contenido_23)
        (paralela contenido_23 contenido_40)
        (paralela contenido_40 contenido_23)
        (paralela contenido_23 contenido_61)
        (paralela contenido_61 contenido_23)
        (paralela contenido_69 contenido_40)
        (paralela contenido_40 contenido_69)
        (paralela contenido_69 contenido_61)
        (paralela contenido_61 contenido_69)
        (paralela contenido_40 contenido_61)
        (paralela contenido_61 contenido_40)
        (= (minutos_contenido contenido_23) 69)
        (= (minutos_contenido contenido_69) 31)
        (= (minutos_contenido contenido_40) 163)
        (= (minutos_contenido contenido_61) 91)
        (paralelas_vistas contenido_15)
        (no_paralela contenido_15)
        (paralelas_vistas contenido_26)
        (no_paralela contenido_26)
        (paralelas_vistas contenido_14)
        (no_paralela contenido_14)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_15)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
