(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100
    )

    (:init
        (paralela contenido_18 contenido_64)
        (paralela contenido_64 contenido_18)
        (paralela contenido_18 contenido_85)
        (paralela contenido_85 contenido_18)
        (paralela contenido_18 contenido_92)
        (paralela contenido_92 contenido_18)
        (paralela contenido_64 contenido_85)
        (paralela contenido_85 contenido_64)
        (paralela contenido_64 contenido_92)
        (paralela contenido_92 contenido_64)
        (paralela contenido_85 contenido_92)
        (paralela contenido_92 contenido_85)
        (= (minutos_contenido contenido_18) 133)
        (= (minutos_contenido contenido_64) 55)
        (= (minutos_contenido contenido_85) 49)
        (= (minutos_contenido contenido_92) 147)
        (paralela contenido_82 contenido_72)
        (paralela contenido_72 contenido_82)
        (paralela contenido_82 contenido_16)
        (paralela contenido_16 contenido_82)
        (paralela contenido_82 contenido_80)
        (paralela contenido_80 contenido_82)
        (paralela contenido_72 contenido_16)
        (paralela contenido_16 contenido_72)
        (paralela contenido_72 contenido_80)
        (paralela contenido_80 contenido_72)
        (paralela contenido_16 contenido_80)
        (paralela contenido_80 contenido_16)
        (= (minutos_contenido contenido_82) 12)
        (= (minutos_contenido contenido_72) 44)
        (= (minutos_contenido contenido_16) 126)
        (= (minutos_contenido contenido_80) 59)
        (paralela contenido_28 contenido_76)
        (paralela contenido_76 contenido_28)
        (paralela contenido_28 contenido_93)
        (paralela contenido_93 contenido_28)
        (paralela contenido_28 contenido_31)
        (paralela contenido_31 contenido_28)
        (paralela contenido_76 contenido_93)
        (paralela contenido_93 contenido_76)
        (paralela contenido_76 contenido_31)
        (paralela contenido_31 contenido_76)
        (paralela contenido_93 contenido_31)
        (paralela contenido_31 contenido_93)
        (= (minutos_contenido contenido_28) 15)
        (= (minutos_contenido contenido_76) 75)
        (= (minutos_contenido contenido_93) 100)
        (= (minutos_contenido contenido_31) 185)
        (paralela contenido_47 contenido_59)
        (paralela contenido_59 contenido_47)
        (paralela contenido_47 contenido_58)
        (paralela contenido_58 contenido_47)
        (paralela contenido_47 contenido_36)
        (paralela contenido_36 contenido_47)
        (paralela contenido_59 contenido_58)
        (paralela contenido_58 contenido_59)
        (paralela contenido_59 contenido_36)
        (paralela contenido_36 contenido_59)
        (paralela contenido_58 contenido_36)
        (paralela contenido_36 contenido_58)
        (= (minutos_contenido contenido_47) 10)
        (= (minutos_contenido contenido_59) 37)
        (= (minutos_contenido contenido_58) 168)
        (= (minutos_contenido contenido_36) 26)
        (paralela contenido_24 contenido_21)
        (paralela contenido_21 contenido_24)
        (paralela contenido_24 contenido_94)
        (paralela contenido_94 contenido_24)
        (paralela contenido_24 contenido_1)
        (paralela contenido_1 contenido_24)
        (paralela contenido_21 contenido_94)
        (paralela contenido_94 contenido_21)
        (paralela contenido_21 contenido_1)
        (paralela contenido_1 contenido_21)
        (paralela contenido_94 contenido_1)
        (paralela contenido_1 contenido_94)
        (= (minutos_contenido contenido_24) 31)
        (= (minutos_contenido contenido_21) 120)
        (= (minutos_contenido contenido_94) 12)
        (= (minutos_contenido contenido_1) 147)
        (paralela contenido_52 contenido_97)
        (paralela contenido_97 contenido_52)
        (paralela contenido_52 contenido_22)
        (paralela contenido_22 contenido_52)
        (paralela contenido_52 contenido_68)
        (paralela contenido_68 contenido_52)
        (paralela contenido_97 contenido_22)
        (paralela contenido_22 contenido_97)
        (paralela contenido_97 contenido_68)
        (paralela contenido_68 contenido_97)
        (paralela contenido_22 contenido_68)
        (paralela contenido_68 contenido_22)
        (= (minutos_contenido contenido_52) 95)
        (= (minutos_contenido contenido_97) 116)
        (= (minutos_contenido contenido_22) 99)
        (= (minutos_contenido contenido_68) 16)
        (paralela contenido_95 contenido_84)
        (paralela contenido_84 contenido_95)
        (paralela contenido_95 contenido_27)
        (paralela contenido_27 contenido_95)
        (paralela contenido_95 contenido_65)
        (paralela contenido_65 contenido_95)
        (paralela contenido_84 contenido_27)
        (paralela contenido_27 contenido_84)
        (paralela contenido_84 contenido_65)
        (paralela contenido_65 contenido_84)
        (paralela contenido_27 contenido_65)
        (paralela contenido_65 contenido_27)
        (= (minutos_contenido contenido_95) 30)
        (= (minutos_contenido contenido_84) 170)
        (= (minutos_contenido contenido_27) 24)
        (= (minutos_contenido contenido_65) 142)
        (paralela contenido_29 contenido_66)
        (paralela contenido_66 contenido_29)
        (paralela contenido_29 contenido_86)
        (paralela contenido_86 contenido_29)
        (paralela contenido_29 contenido_10)
        (paralela contenido_10 contenido_29)
        (paralela contenido_66 contenido_86)
        (paralela contenido_86 contenido_66)
        (paralela contenido_66 contenido_10)
        (paralela contenido_10 contenido_66)
        (paralela contenido_86 contenido_10)
        (paralela contenido_10 contenido_86)
        (= (minutos_contenido contenido_29) 109)
        (= (minutos_contenido contenido_66) 147)
        (= (minutos_contenido contenido_86) 88)
        (= (minutos_contenido contenido_10) 47)
        (paralela contenido_9 contenido_98)
        (paralela contenido_98 contenido_9)
        (paralela contenido_9 contenido_17)
        (paralela contenido_17 contenido_9)
        (paralela contenido_9 contenido_25)
        (paralela contenido_25 contenido_9)
        (paralela contenido_98 contenido_17)
        (paralela contenido_17 contenido_98)
        (paralela contenido_98 contenido_25)
        (paralela contenido_25 contenido_98)
        (paralela contenido_17 contenido_25)
        (paralela contenido_25 contenido_17)
        (= (minutos_contenido contenido_9) 44)
        (= (minutos_contenido contenido_98) 126)
        (= (minutos_contenido contenido_17) 181)
        (= (minutos_contenido contenido_25) 15)
        (paralela contenido_11 contenido_69)
        (paralela contenido_69 contenido_11)
        (paralela contenido_11 contenido_63)
        (paralela contenido_63 contenido_11)
        (paralela contenido_11 contenido_23)
        (paralela contenido_23 contenido_11)
        (paralela contenido_69 contenido_63)
        (paralela contenido_63 contenido_69)
        (paralela contenido_69 contenido_23)
        (paralela contenido_23 contenido_69)
        (paralela contenido_63 contenido_23)
        (paralela contenido_23 contenido_63)
        (= (minutos_contenido contenido_11) 87)
        (= (minutos_contenido contenido_69) 119)
        (= (minutos_contenido contenido_63) 17)
        (= (minutos_contenido contenido_23) 50)
        (paralela contenido_35 contenido_42)
        (paralela contenido_42 contenido_35)
        (paralela contenido_35 contenido_100)
        (paralela contenido_100 contenido_35)
        (paralela contenido_35 contenido_49)
        (paralela contenido_49 contenido_35)
        (paralela contenido_42 contenido_100)
        (paralela contenido_100 contenido_42)
        (paralela contenido_42 contenido_49)
        (paralela contenido_49 contenido_42)
        (paralela contenido_100 contenido_49)
        (paralela contenido_49 contenido_100)
        (= (minutos_contenido contenido_35) 67)
        (= (minutos_contenido contenido_42) 155)
        (= (minutos_contenido contenido_100) 97)
        (= (minutos_contenido contenido_49) 33)
        (paralela contenido_4 contenido_41)
        (paralela contenido_41 contenido_4)
        (paralela contenido_4 contenido_75)
        (paralela contenido_75 contenido_4)
        (paralela contenido_4 contenido_51)
        (paralela contenido_51 contenido_4)
        (paralela contenido_41 contenido_75)
        (paralela contenido_75 contenido_41)
        (paralela contenido_41 contenido_51)
        (paralela contenido_51 contenido_41)
        (paralela contenido_75 contenido_51)
        (paralela contenido_51 contenido_75)
        (= (minutos_contenido contenido_4) 92)
        (= (minutos_contenido contenido_41) 77)
        (= (minutos_contenido contenido_75) 111)
        (= (minutos_contenido contenido_51) 21)
        (paralela contenido_56 contenido_45)
        (paralela contenido_45 contenido_56)
        (paralela contenido_56 contenido_3)
        (paralela contenido_3 contenido_56)
        (paralela contenido_56 contenido_7)
        (paralela contenido_7 contenido_56)
        (paralela contenido_45 contenido_3)
        (paralela contenido_3 contenido_45)
        (paralela contenido_45 contenido_7)
        (paralela contenido_7 contenido_45)
        (paralela contenido_3 contenido_7)
        (paralela contenido_7 contenido_3)
        (= (minutos_contenido contenido_56) 138)
        (= (minutos_contenido contenido_45) 30)
        (= (minutos_contenido contenido_3) 60)
        (= (minutos_contenido contenido_7) 139)
        (paralela contenido_5 contenido_88)
        (paralela contenido_88 contenido_5)
        (paralela contenido_5 contenido_38)
        (paralela contenido_38 contenido_5)
        (paralela contenido_5 contenido_13)
        (paralela contenido_13 contenido_5)
        (paralela contenido_88 contenido_38)
        (paralela contenido_38 contenido_88)
        (paralela contenido_88 contenido_13)
        (paralela contenido_13 contenido_88)
        (paralela contenido_38 contenido_13)
        (paralela contenido_13 contenido_38)
        (= (minutos_contenido contenido_5) 61)
        (= (minutos_contenido contenido_88) 14)
        (= (minutos_contenido contenido_38) 59)
        (= (minutos_contenido contenido_13) 78)
        (paralela contenido_8 contenido_60)
        (paralela contenido_60 contenido_8)
        (paralela contenido_8 contenido_71)
        (paralela contenido_71 contenido_8)
        (paralela contenido_8 contenido_37)
        (paralela contenido_37 contenido_8)
        (paralela contenido_60 contenido_71)
        (paralela contenido_71 contenido_60)
        (paralela contenido_60 contenido_37)
        (paralela contenido_37 contenido_60)
        (paralela contenido_71 contenido_37)
        (paralela contenido_37 contenido_71)
        (= (minutos_contenido contenido_8) 91)
        (= (minutos_contenido contenido_60) 31)
        (= (minutos_contenido contenido_71) 97)
        (= (minutos_contenido contenido_37) 151)
        (paralela contenido_20 contenido_89)
        (paralela contenido_89 contenido_20)
        (paralela contenido_20 contenido_96)
        (paralela contenido_96 contenido_20)
        (paralela contenido_20 contenido_43)
        (paralela contenido_43 contenido_20)
        (paralela contenido_89 contenido_96)
        (paralela contenido_96 contenido_89)
        (paralela contenido_89 contenido_43)
        (paralela contenido_43 contenido_89)
        (paralela contenido_96 contenido_43)
        (paralela contenido_43 contenido_96)
        (= (minutos_contenido contenido_20) 147)
        (= (minutos_contenido contenido_89) 44)
        (= (minutos_contenido contenido_96) 146)
        (= (minutos_contenido contenido_43) 44)
        (paralela contenido_83 contenido_54)
        (paralela contenido_54 contenido_83)
        (paralela contenido_83 contenido_39)
        (paralela contenido_39 contenido_83)
        (paralela contenido_83 contenido_34)
        (paralela contenido_34 contenido_83)
        (paralela contenido_54 contenido_39)
        (paralela contenido_39 contenido_54)
        (paralela contenido_54 contenido_34)
        (paralela contenido_34 contenido_54)
        (paralela contenido_39 contenido_34)
        (paralela contenido_34 contenido_39)
        (= (minutos_contenido contenido_83) 101)
        (= (minutos_contenido contenido_54) 65)
        (= (minutos_contenido contenido_39) 124)
        (= (minutos_contenido contenido_34) 97)
        (paralela contenido_40 contenido_6)
        (paralela contenido_6 contenido_40)
        (paralela contenido_40 contenido_78)
        (paralela contenido_78 contenido_40)
        (paralela contenido_40 contenido_12)
        (paralela contenido_12 contenido_40)
        (paralela contenido_6 contenido_78)
        (paralela contenido_78 contenido_6)
        (paralela contenido_6 contenido_12)
        (paralela contenido_12 contenido_6)
        (paralela contenido_78 contenido_12)
        (paralela contenido_12 contenido_78)
        (= (minutos_contenido contenido_40) 59)
        (= (minutos_contenido contenido_6) 56)
        (= (minutos_contenido contenido_78) 107)
        (= (minutos_contenido contenido_12) 25)
        (paralela contenido_55 contenido_26)
        (paralela contenido_26 contenido_55)
        (paralela contenido_55 contenido_32)
        (paralela contenido_32 contenido_55)
        (paralela contenido_55 contenido_90)
        (paralela contenido_90 contenido_55)
        (paralela contenido_26 contenido_32)
        (paralela contenido_32 contenido_26)
        (paralela contenido_26 contenido_90)
        (paralela contenido_90 contenido_26)
        (paralela contenido_32 contenido_90)
        (paralela contenido_90 contenido_32)
        (= (minutos_contenido contenido_55) 27)
        (= (minutos_contenido contenido_26) 85)
        (= (minutos_contenido contenido_32) 41)
        (= (minutos_contenido contenido_90) 77)
        (paralela contenido_67 contenido_70)
        (paralela contenido_70 contenido_67)
        (paralela contenido_67 contenido_81)
        (paralela contenido_81 contenido_67)
        (paralela contenido_67 contenido_62)
        (paralela contenido_62 contenido_67)
        (paralela contenido_70 contenido_81)
        (paralela contenido_81 contenido_70)
        (paralela contenido_70 contenido_62)
        (paralela contenido_62 contenido_70)
        (paralela contenido_81 contenido_62)
        (paralela contenido_62 contenido_81)
        (= (minutos_contenido contenido_67) 96)
        (= (minutos_contenido contenido_70) 22)
        (= (minutos_contenido contenido_81) 56)
        (= (minutos_contenido contenido_62) 41)
        (paralela contenido_87 contenido_73)
        (paralela contenido_73 contenido_87)
        (paralela contenido_87 contenido_15)
        (paralela contenido_15 contenido_87)
        (paralela contenido_87 contenido_53)
        (paralela contenido_53 contenido_87)
        (paralela contenido_73 contenido_15)
        (paralela contenido_15 contenido_73)
        (paralela contenido_73 contenido_53)
        (paralela contenido_53 contenido_73)
        (paralela contenido_15 contenido_53)
        (paralela contenido_53 contenido_15)
        (= (minutos_contenido contenido_87) 20)
        (= (minutos_contenido contenido_73) 130)
        (= (minutos_contenido contenido_15) 148)
        (= (minutos_contenido contenido_53) 46)
        (paralela contenido_99 contenido_19)
        (paralela contenido_19 contenido_99)
        (paralela contenido_99 contenido_30)
        (paralela contenido_30 contenido_99)
        (paralela contenido_99 contenido_74)
        (paralela contenido_74 contenido_99)
        (paralela contenido_19 contenido_30)
        (paralela contenido_30 contenido_19)
        (paralela contenido_19 contenido_74)
        (paralela contenido_74 contenido_19)
        (paralela contenido_30 contenido_74)
        (paralela contenido_74 contenido_30)
        (= (minutos_contenido contenido_99) 186)
        (= (minutos_contenido contenido_19) 26)
        (= (minutos_contenido contenido_30) 74)
        (= (minutos_contenido contenido_74) 82)
        (paralela contenido_77 contenido_50)
        (paralela contenido_50 contenido_77)
        (paralela contenido_77 contenido_61)
        (paralela contenido_61 contenido_77)
        (paralela contenido_77 contenido_91)
        (paralela contenido_91 contenido_77)
        (paralela contenido_50 contenido_61)
        (paralela contenido_61 contenido_50)
        (paralela contenido_50 contenido_91)
        (paralela contenido_91 contenido_50)
        (paralela contenido_61 contenido_91)
        (paralela contenido_91 contenido_61)
        (= (minutos_contenido contenido_77) 21)
        (= (minutos_contenido contenido_50) 165)
        (= (minutos_contenido contenido_61) 13)
        (= (minutos_contenido contenido_91) 137)
        (paralela contenido_79 contenido_46)
        (paralela contenido_46 contenido_79)
        (paralela contenido_79 contenido_48)
        (paralela contenido_48 contenido_79)
        (paralela contenido_79 contenido_2)
        (paralela contenido_2 contenido_79)
        (paralela contenido_46 contenido_48)
        (paralela contenido_48 contenido_46)
        (paralela contenido_46 contenido_2)
        (paralela contenido_2 contenido_46)
        (paralela contenido_48 contenido_2)
        (paralela contenido_2 contenido_48)
        (= (minutos_contenido contenido_79) 182)
        (= (minutos_contenido contenido_46) 52)
        (= (minutos_contenido contenido_48) 60)
        (= (minutos_contenido contenido_2) 21)
        (paralelas_vistas contenido_57)
        (no_paralela contenido_57)
        (paralelas_vistas contenido_44)
        (no_paralela contenido_44)
        (paralelas_vistas contenido_33)
        (no_paralela contenido_33)
        (paralelas_vistas contenido_14)
        (no_paralela contenido_14)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_57)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
