(define (problem problema_generado)

    (:domain SeriesPelisExt4)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125 contenido_126 contenido_127 contenido_128 contenido_129 contenido_130 contenido_131 contenido_132 contenido_133 contenido_134 contenido_135 contenido_136 contenido_137 contenido_138 contenido_139 contenido_140 contenido_141 contenido_142 contenido_143 contenido_144 contenido_145 contenido_146 contenido_147 contenido_148 contenido_149 contenido_150
    )

    (:init
        (paralela contenido_138 contenido_50)
        (paralela contenido_50 contenido_138)
        (paralela contenido_138 contenido_52)
        (paralela contenido_52 contenido_138)
        (paralela contenido_138 contenido_73)
        (paralela contenido_73 contenido_138)
        (paralela contenido_50 contenido_52)
        (paralela contenido_52 contenido_50)
        (paralela contenido_50 contenido_73)
        (paralela contenido_73 contenido_50)
        (paralela contenido_52 contenido_73)
        (paralela contenido_73 contenido_52)
        (= (minutos_contenido contenido_138) 92)
        (= (minutos_contenido contenido_50) 77)
        (= (minutos_contenido contenido_52) 130)
        (= (minutos_contenido contenido_73) 18)
        (paralela contenido_115 contenido_91)
        (paralela contenido_91 contenido_115)
        (paralela contenido_115 contenido_144)
        (paralela contenido_144 contenido_115)
        (paralela contenido_115 contenido_60)
        (paralela contenido_60 contenido_115)
        (paralela contenido_91 contenido_144)
        (paralela contenido_144 contenido_91)
        (paralela contenido_91 contenido_60)
        (paralela contenido_60 contenido_91)
        (paralela contenido_144 contenido_60)
        (paralela contenido_60 contenido_144)
        (= (minutos_contenido contenido_115) 104)
        (= (minutos_contenido contenido_91) 42)
        (= (minutos_contenido contenido_144) 146)
        (= (minutos_contenido contenido_60) 96)
        (paralela contenido_109 contenido_79)
        (paralela contenido_79 contenido_109)
        (paralela contenido_109 contenido_100)
        (paralela contenido_100 contenido_109)
        (paralela contenido_109 contenido_38)
        (paralela contenido_38 contenido_109)
        (paralela contenido_79 contenido_100)
        (paralela contenido_100 contenido_79)
        (paralela contenido_79 contenido_38)
        (paralela contenido_38 contenido_79)
        (paralela contenido_100 contenido_38)
        (paralela contenido_38 contenido_100)
        (= (minutos_contenido contenido_109) 33)
        (= (minutos_contenido contenido_79) 79)
        (= (minutos_contenido contenido_100) 139)
        (= (minutos_contenido contenido_38) 72)
        (paralela contenido_71 contenido_43)
        (paralela contenido_43 contenido_71)
        (paralela contenido_71 contenido_18)
        (paralela contenido_18 contenido_71)
        (paralela contenido_71 contenido_102)
        (paralela contenido_102 contenido_71)
        (paralela contenido_43 contenido_18)
        (paralela contenido_18 contenido_43)
        (paralela contenido_43 contenido_102)
        (paralela contenido_102 contenido_43)
        (paralela contenido_18 contenido_102)
        (paralela contenido_102 contenido_18)
        (= (minutos_contenido contenido_71) 62)
        (= (minutos_contenido contenido_43) 92)
        (= (minutos_contenido contenido_18) 77)
        (= (minutos_contenido contenido_102) 111)
        (paralela contenido_64 contenido_14)
        (paralela contenido_14 contenido_64)
        (paralela contenido_64 contenido_29)
        (paralela contenido_29 contenido_64)
        (paralela contenido_64 contenido_76)
        (paralela contenido_76 contenido_64)
        (paralela contenido_14 contenido_29)
        (paralela contenido_29 contenido_14)
        (paralela contenido_14 contenido_76)
        (paralela contenido_76 contenido_14)
        (paralela contenido_29 contenido_76)
        (paralela contenido_76 contenido_29)
        (= (minutos_contenido contenido_64) 21)
        (= (minutos_contenido contenido_14) 138)
        (= (minutos_contenido contenido_29) 30)
        (= (minutos_contenido contenido_76) 60)
        (paralela contenido_84 contenido_34)
        (paralela contenido_34 contenido_84)
        (paralela contenido_84 contenido_15)
        (paralela contenido_15 contenido_84)
        (paralela contenido_84 contenido_101)
        (paralela contenido_101 contenido_84)
        (paralela contenido_34 contenido_15)
        (paralela contenido_15 contenido_34)
        (paralela contenido_34 contenido_101)
        (paralela contenido_101 contenido_34)
        (paralela contenido_15 contenido_101)
        (paralela contenido_101 contenido_15)
        (= (minutos_contenido contenido_84) 139)
        (= (minutos_contenido contenido_34) 61)
        (= (minutos_contenido contenido_15) 14)
        (= (minutos_contenido contenido_101) 59)
        (paralela contenido_39 contenido_104)
        (paralela contenido_104 contenido_39)
        (paralela contenido_39 contenido_93)
        (paralela contenido_93 contenido_39)
        (paralela contenido_39 contenido_13)
        (paralela contenido_13 contenido_39)
        (paralela contenido_104 contenido_93)
        (paralela contenido_93 contenido_104)
        (paralela contenido_104 contenido_13)
        (paralela contenido_13 contenido_104)
        (paralela contenido_93 contenido_13)
        (paralela contenido_13 contenido_93)
        (= (minutos_contenido contenido_39) 78)
        (= (minutos_contenido contenido_104) 154)
        (= (minutos_contenido contenido_93) 69)
        (= (minutos_contenido contenido_13) 31)
        (paralela contenido_58 contenido_11)
        (paralela contenido_11 contenido_58)
        (paralela contenido_58 contenido_45)
        (paralela contenido_45 contenido_58)
        (paralela contenido_58 contenido_119)
        (paralela contenido_119 contenido_58)
        (paralela contenido_11 contenido_45)
        (paralela contenido_45 contenido_11)
        (paralela contenido_11 contenido_119)
        (paralela contenido_119 contenido_11)
        (paralela contenido_45 contenido_119)
        (paralela contenido_119 contenido_45)
        (= (minutos_contenido contenido_58) 163)
        (= (minutos_contenido contenido_11) 91)
        (= (minutos_contenido contenido_45) 31)
        (= (minutos_contenido contenido_119) 97)
        (paralela contenido_6 contenido_47)
        (paralela contenido_47 contenido_6)
        (paralela contenido_6 contenido_26)
        (paralela contenido_26 contenido_6)
        (paralela contenido_6 contenido_22)
        (paralela contenido_22 contenido_6)
        (paralela contenido_47 contenido_26)
        (paralela contenido_26 contenido_47)
        (paralela contenido_47 contenido_22)
        (paralela contenido_22 contenido_47)
        (paralela contenido_26 contenido_22)
        (paralela contenido_22 contenido_26)
        (= (minutos_contenido contenido_6) 41)
        (= (minutos_contenido contenido_47) 186)
        (= (minutos_contenido contenido_26) 23)
        (= (minutos_contenido contenido_22) 102)
        (paralela contenido_24 contenido_57)
        (paralela contenido_57 contenido_24)
        (paralela contenido_24 contenido_8)
        (paralela contenido_8 contenido_24)
        (paralela contenido_24 contenido_94)
        (paralela contenido_94 contenido_24)
        (paralela contenido_57 contenido_8)
        (paralela contenido_8 contenido_57)
        (paralela contenido_57 contenido_94)
        (paralela contenido_94 contenido_57)
        (paralela contenido_8 contenido_94)
        (paralela contenido_94 contenido_8)
        (= (minutos_contenido contenido_24) 90)
        (= (minutos_contenido contenido_57) 101)
        (= (minutos_contenido contenido_8) 65)
        (= (minutos_contenido contenido_94) 124)
        (paralela contenido_142 contenido_28)
        (paralela contenido_28 contenido_142)
        (paralela contenido_142 contenido_143)
        (paralela contenido_143 contenido_142)
        (paralela contenido_142 contenido_122)
        (paralela contenido_122 contenido_142)
        (paralela contenido_28 contenido_143)
        (paralela contenido_143 contenido_28)
        (paralela contenido_28 contenido_122)
        (paralela contenido_122 contenido_28)
        (paralela contenido_143 contenido_122)
        (paralela contenido_122 contenido_143)
        (= (minutos_contenido contenido_142) 97)
        (= (minutos_contenido contenido_28) 59)
        (= (minutos_contenido contenido_143) 56)
        (= (minutos_contenido contenido_122) 107)
        (paralela contenido_51 contenido_75)
        (paralela contenido_75 contenido_51)
        (paralela contenido_51 contenido_112)
        (paralela contenido_112 contenido_51)
        (paralela contenido_51 contenido_121)
        (paralela contenido_121 contenido_51)
        (paralela contenido_75 contenido_112)
        (paralela contenido_112 contenido_75)
        (paralela contenido_75 contenido_121)
        (paralela contenido_121 contenido_75)
        (paralela contenido_112 contenido_121)
        (paralela contenido_121 contenido_112)
        (= (minutos_contenido contenido_51) 104)
        (= (minutos_contenido contenido_75) 27)
        (= (minutos_contenido contenido_112) 85)
        (= (minutos_contenido contenido_121) 41)
        (paralela contenido_36 contenido_88)
        (paralela contenido_88 contenido_36)
        (paralela contenido_36 contenido_99)
        (paralela contenido_99 contenido_36)
        (paralela contenido_36 contenido_3)
        (paralela contenido_3 contenido_36)
        (paralela contenido_88 contenido_99)
        (paralela contenido_99 contenido_88)
        (paralela contenido_88 contenido_3)
        (paralela contenido_3 contenido_88)
        (paralela contenido_99 contenido_3)
        (paralela contenido_3 contenido_99)
        (= (minutos_contenido contenido_36) 24)
        (= (minutos_contenido contenido_88) 107)
        (= (minutos_contenido contenido_99) 23)
        (= (minutos_contenido contenido_3) 160)
        (paralela contenido_67 contenido_83)
        (paralela contenido_83 contenido_67)
        (paralela contenido_67 contenido_16)
        (paralela contenido_16 contenido_67)
        (paralela contenido_67 contenido_105)
        (paralela contenido_105 contenido_67)
        (paralela contenido_83 contenido_16)
        (paralela contenido_16 contenido_83)
        (paralela contenido_83 contenido_105)
        (paralela contenido_105 contenido_83)
        (paralela contenido_16 contenido_105)
        (paralela contenido_105 contenido_16)
        (= (minutos_contenido contenido_67) 109)
        (= (minutos_contenido contenido_83) 86)
        (= (minutos_contenido contenido_16) 37)
        (= (minutos_contenido contenido_105) 129)
        (paralela contenido_86 contenido_72)
        (paralela contenido_72 contenido_86)
        (paralela contenido_86 contenido_95)
        (paralela contenido_95 contenido_86)
        (paralela contenido_86 contenido_49)
        (paralela contenido_49 contenido_86)
        (paralela contenido_72 contenido_95)
        (paralela contenido_95 contenido_72)
        (paralela contenido_72 contenido_49)
        (paralela contenido_49 contenido_72)
        (paralela contenido_95 contenido_49)
        (paralela contenido_49 contenido_95)
        (= (minutos_contenido contenido_86) 80)
        (= (minutos_contenido contenido_72) 96)
        (= (minutos_contenido contenido_95) 22)
        (= (minutos_contenido contenido_49) 56)
        (paralela contenido_55 contenido_35)
        (paralela contenido_35 contenido_55)
        (paralela contenido_55 contenido_32)
        (paralela contenido_32 contenido_55)
        (paralela contenido_55 contenido_19)
        (paralela contenido_19 contenido_55)
        (paralela contenido_35 contenido_32)
        (paralela contenido_32 contenido_35)
        (paralela contenido_35 contenido_19)
        (paralela contenido_19 contenido_35)
        (paralela contenido_32 contenido_19)
        (paralela contenido_19 contenido_32)
        (= (minutos_contenido contenido_55) 41)
        (= (minutos_contenido contenido_35) 15)
        (= (minutos_contenido contenido_32) 119)
        (= (minutos_contenido contenido_19) 179)
        (paralela contenido_97 contenido_96)
        (paralela contenido_96 contenido_97)
        (paralela contenido_97 contenido_125)
        (paralela contenido_125 contenido_97)
        (paralela contenido_97 contenido_37)
        (paralela contenido_37 contenido_97)
        (paralela contenido_96 contenido_125)
        (paralela contenido_125 contenido_96)
        (paralela contenido_96 contenido_37)
        (paralela contenido_37 contenido_96)
        (paralela contenido_125 contenido_37)
        (paralela contenido_37 contenido_125)
        (= (minutos_contenido contenido_97) 46)
        (= (minutos_contenido contenido_96) 93)
        (= (minutos_contenido contenido_125) 104)
        (= (minutos_contenido contenido_37) 66)
        (paralela contenido_59 contenido_56)
        (paralela contenido_56 contenido_59)
        (paralela contenido_59 contenido_146)
        (paralela contenido_146 contenido_59)
        (paralela contenido_59 contenido_137)
        (paralela contenido_137 contenido_59)
        (paralela contenido_56 contenido_146)
        (paralela contenido_146 contenido_56)
        (paralela contenido_56 contenido_137)
        (paralela contenido_137 contenido_56)
        (paralela contenido_146 contenido_137)
        (paralela contenido_137 contenido_146)
        (= (minutos_contenido contenido_59) 68)
        (= (minutos_contenido contenido_56) 186)
        (= (minutos_contenido contenido_146) 26)
        (= (minutos_contenido contenido_137) 74)
        (paralela contenido_41 contenido_85)
        (paralela contenido_85 contenido_41)
        (paralela contenido_41 contenido_23)
        (paralela contenido_23 contenido_41)
        (paralela contenido_41 contenido_126)
        (paralela contenido_126 contenido_41)
        (paralela contenido_85 contenido_23)
        (paralela contenido_23 contenido_85)
        (paralela contenido_85 contenido_126)
        (paralela contenido_126 contenido_85)
        (paralela contenido_23 contenido_126)
        (paralela contenido_126 contenido_23)
        (= (minutos_contenido contenido_41) 82)
        (= (minutos_contenido contenido_85) 53)
        (= (minutos_contenido contenido_23) 116)
        (= (minutos_contenido contenido_126) 101)
        (paralela contenido_61 contenido_5)
        (paralela contenido_5 contenido_61)
        (paralela contenido_61 contenido_70)
        (paralela contenido_70 contenido_61)
        (paralela contenido_61 contenido_118)
        (paralela contenido_118 contenido_61)
        (paralela contenido_5 contenido_70)
        (paralela contenido_70 contenido_5)
        (paralela contenido_5 contenido_118)
        (paralela contenido_118 contenido_5)
        (paralela contenido_70 contenido_118)
        (paralela contenido_118 contenido_70)
        (= (minutos_contenido contenido_61) 118)
        (= (minutos_contenido contenido_5) 21)
        (= (minutos_contenido contenido_70) 165)
        (= (minutos_contenido contenido_118) 13)
        (paralela contenido_141 contenido_124)
        (paralela contenido_124 contenido_141)
        (paralela contenido_141 contenido_103)
        (paralela contenido_103 contenido_141)
        (paralela contenido_141 contenido_98)
        (paralela contenido_98 contenido_141)
        (paralela contenido_124 contenido_103)
        (paralela contenido_103 contenido_124)
        (paralela contenido_124 contenido_98)
        (paralela contenido_98 contenido_124)
        (paralela contenido_103 contenido_98)
        (paralela contenido_98 contenido_103)
        (= (minutos_contenido contenido_141) 21)
        (= (minutos_contenido contenido_124) 78)
        (= (minutos_contenido contenido_103) 144)
        (= (minutos_contenido contenido_98) 52)
        (paralela contenido_147 contenido_131)
        (paralela contenido_131 contenido_147)
        (paralela contenido_147 contenido_139)
        (paralela contenido_139 contenido_147)
        (paralela contenido_147 contenido_78)
        (paralela contenido_78 contenido_147)
        (paralela contenido_131 contenido_139)
        (paralela contenido_139 contenido_131)
        (paralela contenido_131 contenido_78)
        (paralela contenido_78 contenido_131)
        (paralela contenido_139 contenido_78)
        (paralela contenido_78 contenido_139)
        (= (minutos_contenido contenido_147) 145)
        (= (minutos_contenido contenido_131) 33)
        (= (minutos_contenido contenido_139) 36)
        (= (minutos_contenido contenido_78) 123)
        (paralela contenido_10 contenido_1)
        (paralela contenido_1 contenido_10)
        (paralela contenido_10 contenido_33)
        (paralela contenido_33 contenido_10)
        (paralela contenido_10 contenido_123)
        (paralela contenido_123 contenido_10)
        (paralela contenido_1 contenido_33)
        (paralela contenido_33 contenido_1)
        (paralela contenido_1 contenido_123)
        (paralela contenido_123 contenido_1)
        (paralela contenido_33 contenido_123)
        (paralela contenido_123 contenido_33)
        (= (minutos_contenido contenido_10) 136)
        (= (minutos_contenido contenido_1) 44)
        (= (minutos_contenido contenido_33) 59)
        (= (minutos_contenido contenido_123) 64)
        (paralela contenido_25 contenido_9)
        (paralela contenido_9 contenido_25)
        (paralela contenido_25 contenido_127)
        (paralela contenido_127 contenido_25)
        (paralela contenido_25 contenido_81)
        (paralela contenido_81 contenido_25)
        (paralela contenido_9 contenido_127)
        (paralela contenido_127 contenido_9)
        (paralela contenido_9 contenido_81)
        (paralela contenido_81 contenido_9)
        (paralela contenido_127 contenido_81)
        (paralela contenido_81 contenido_127)
        (= (minutos_contenido contenido_25) 71)
        (= (minutos_contenido contenido_9) 19)
        (= (minutos_contenido contenido_127) 72)
        (= (minutos_contenido contenido_81) 63)
        (paralela contenido_120 contenido_42)
        (paralela contenido_42 contenido_120)
        (paralela contenido_120 contenido_128)
        (paralela contenido_128 contenido_120)
        (paralela contenido_120 contenido_53)
        (paralela contenido_53 contenido_120)
        (paralela contenido_42 contenido_128)
        (paralela contenido_128 contenido_42)
        (paralela contenido_42 contenido_53)
        (paralela contenido_53 contenido_42)
        (paralela contenido_128 contenido_53)
        (paralela contenido_53 contenido_128)
        (= (minutos_contenido contenido_120) 28)
        (= (minutos_contenido contenido_42) 113)
        (= (minutos_contenido contenido_128) 16)
        (= (minutos_contenido contenido_53) 12)
        (paralela contenido_46 contenido_17)
        (paralela contenido_17 contenido_46)
        (paralela contenido_46 contenido_145)
        (paralela contenido_145 contenido_46)
        (paralela contenido_46 contenido_130)
        (paralela contenido_130 contenido_46)
        (paralela contenido_17 contenido_145)
        (paralela contenido_145 contenido_17)
        (paralela contenido_17 contenido_130)
        (paralela contenido_130 contenido_17)
        (paralela contenido_145 contenido_130)
        (paralela contenido_130 contenido_145)
        (= (minutos_contenido contenido_46) 17)
        (= (minutos_contenido contenido_17) 20)
        (= (minutos_contenido contenido_145) 73)
        (= (minutos_contenido contenido_130) 197)
        (paralela contenido_68 contenido_69)
        (paralela contenido_69 contenido_68)
        (paralela contenido_68 contenido_7)
        (paralela contenido_7 contenido_68)
        (paralela contenido_68 contenido_136)
        (paralela contenido_136 contenido_68)
        (paralela contenido_69 contenido_7)
        (paralela contenido_7 contenido_69)
        (paralela contenido_69 contenido_136)
        (paralela contenido_136 contenido_69)
        (paralela contenido_7 contenido_136)
        (paralela contenido_136 contenido_7)
        (= (minutos_contenido contenido_68) 16)
        (= (minutos_contenido contenido_69) 102)
        (= (minutos_contenido contenido_7) 49)
        (= (minutos_contenido contenido_136) 129)
        (paralela contenido_150 contenido_66)
        (paralela contenido_66 contenido_150)
        (paralela contenido_150 contenido_107)
        (paralela contenido_107 contenido_150)
        (paralela contenido_150 contenido_27)
        (paralela contenido_27 contenido_150)
        (paralela contenido_66 contenido_107)
        (paralela contenido_107 contenido_66)
        (paralela contenido_66 contenido_27)
        (paralela contenido_27 contenido_66)
        (paralela contenido_107 contenido_27)
        (paralela contenido_27 contenido_107)
        (= (minutos_contenido contenido_150) 58)
        (= (minutos_contenido contenido_66) 109)
        (= (minutos_contenido contenido_107) 29)
        (= (minutos_contenido contenido_27) 137)
        (paralela contenido_54 contenido_149)
        (paralela contenido_149 contenido_54)
        (paralela contenido_54 contenido_65)
        (paralela contenido_65 contenido_54)
        (paralela contenido_54 contenido_62)
        (paralela contenido_62 contenido_54)
        (paralela contenido_149 contenido_65)
        (paralela contenido_65 contenido_149)
        (paralela contenido_149 contenido_62)
        (paralela contenido_62 contenido_149)
        (paralela contenido_65 contenido_62)
        (paralela contenido_62 contenido_65)
        (= (minutos_contenido contenido_54) 20)
        (= (minutos_contenido contenido_149) 83)
        (= (minutos_contenido contenido_65) 45)
        (= (minutos_contenido contenido_62) 131)
        (paralela contenido_82 contenido_30)
        (paralela contenido_30 contenido_82)
        (paralela contenido_82 contenido_110)
        (paralela contenido_110 contenido_82)
        (paralela contenido_82 contenido_117)
        (paralela contenido_117 contenido_82)
        (paralela contenido_30 contenido_110)
        (paralela contenido_110 contenido_30)
        (paralela contenido_30 contenido_117)
        (paralela contenido_117 contenido_30)
        (paralela contenido_110 contenido_117)
        (paralela contenido_117 contenido_110)
        (= (minutos_contenido contenido_82) 100)
        (= (minutos_contenido contenido_30) 83)
        (= (minutos_contenido contenido_110) 102)
        (= (minutos_contenido contenido_117) 64)
        (paralela contenido_21 contenido_132)
        (paralela contenido_132 contenido_21)
        (paralela contenido_21 contenido_80)
        (paralela contenido_80 contenido_21)
        (paralela contenido_21 contenido_63)
        (paralela contenido_63 contenido_21)
        (paralela contenido_132 contenido_80)
        (paralela contenido_80 contenido_132)
        (paralela contenido_132 contenido_63)
        (paralela contenido_63 contenido_132)
        (paralela contenido_80 contenido_63)
        (paralela contenido_63 contenido_80)
        (= (minutos_contenido contenido_21) 109)
        (= (minutos_contenido contenido_132) 22)
        (= (minutos_contenido contenido_80) 37)
        (= (minutos_contenido contenido_63) 140)
        (paralela contenido_4 contenido_2)
        (paralela contenido_2 contenido_4)
        (paralela contenido_4 contenido_12)
        (paralela contenido_12 contenido_4)
        (paralela contenido_4 contenido_31)
        (paralela contenido_31 contenido_4)
        (paralela contenido_2 contenido_12)
        (paralela contenido_12 contenido_2)
        (paralela contenido_2 contenido_31)
        (paralela contenido_31 contenido_2)
        (paralela contenido_12 contenido_31)
        (paralela contenido_31 contenido_12)
        (= (minutos_contenido contenido_4) 108)
        (= (minutos_contenido contenido_2) 56)
        (= (minutos_contenido contenido_12) 117)
        (= (minutos_contenido contenido_31) 42)
        (paralela contenido_89 contenido_77)
        (paralela contenido_77 contenido_89)
        (paralela contenido_89 contenido_106)
        (paralela contenido_106 contenido_89)
        (paralela contenido_89 contenido_20)
        (paralela contenido_20 contenido_89)
        (paralela contenido_77 contenido_106)
        (paralela contenido_106 contenido_77)
        (paralela contenido_77 contenido_20)
        (paralela contenido_20 contenido_77)
        (paralela contenido_106 contenido_20)
        (paralela contenido_20 contenido_106)
        (= (minutos_contenido contenido_89) 131)
        (= (minutos_contenido contenido_77) 45)
        (= (minutos_contenido contenido_106) 11)
        (= (minutos_contenido contenido_20) 51)
        (paralela contenido_140 contenido_40)
        (paralela contenido_40 contenido_140)
        (paralela contenido_140 contenido_44)
        (paralela contenido_44 contenido_140)
        (paralela contenido_140 contenido_116)
        (paralela contenido_116 contenido_140)
        (paralela contenido_40 contenido_44)
        (paralela contenido_44 contenido_40)
        (paralela contenido_40 contenido_116)
        (paralela contenido_116 contenido_40)
        (paralela contenido_44 contenido_116)
        (paralela contenido_116 contenido_44)
        (= (minutos_contenido contenido_140) 32)
        (= (minutos_contenido contenido_40) 94)
        (= (minutos_contenido contenido_44) 18)
        (= (minutos_contenido contenido_116) 35)
        (paralela contenido_148 contenido_113)
        (paralela contenido_113 contenido_148)
        (paralela contenido_148 contenido_92)
        (paralela contenido_92 contenido_148)
        (paralela contenido_148 contenido_134)
        (paralela contenido_134 contenido_148)
        (paralela contenido_113 contenido_92)
        (paralela contenido_92 contenido_113)
        (paralela contenido_113 contenido_134)
        (paralela contenido_134 contenido_113)
        (paralela contenido_92 contenido_134)
        (paralela contenido_134 contenido_92)
        (= (minutos_contenido contenido_148) 47)
        (= (minutos_contenido contenido_113) 66)
        (= (minutos_contenido contenido_92) 127)
        (= (minutos_contenido contenido_134) 120)
        (paralela contenido_111 contenido_114)
        (paralela contenido_114 contenido_111)
        (paralela contenido_111 contenido_74)
        (paralela contenido_74 contenido_111)
        (paralela contenido_111 contenido_135)
        (paralela contenido_135 contenido_111)
        (paralela contenido_114 contenido_74)
        (paralela contenido_74 contenido_114)
        (paralela contenido_114 contenido_135)
        (paralela contenido_135 contenido_114)
        (paralela contenido_74 contenido_135)
        (paralela contenido_135 contenido_74)
        (= (minutos_contenido contenido_111) 61)
        (= (minutos_contenido contenido_114) 179)
        (= (minutos_contenido contenido_74) 113)
        (= (minutos_contenido contenido_135) 25)
        (paralelas_vistas contenido_133)
        (no_paralela contenido_133)
        (paralelas_vistas contenido_87)
        (no_paralela contenido_87)
        (paralelas_vistas contenido_90)
        (no_paralela contenido_90)
        (paralelas_vistas contenido_129)
        (no_paralela contenido_129)
        (paralelas_vistas contenido_108)
        (no_paralela contenido_108)
        (paralelas_vistas contenido_48)
        (no_paralela contenido_48)
        (predecesores_vistos contenido_133)
        (predecesores_vistos contenido_87)
        (predecesores_vistos contenido_90)
        (predecesores_vistos contenido_108)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_129)
        (paralelas_ok)
        (= (minutos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
