(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125 contenido_126 contenido_127 contenido_128 contenido_129 contenido_130 contenido_131 contenido_132 contenido_133 contenido_134 contenido_135 contenido_136 contenido_137 contenido_138 contenido_139 contenido_140 contenido_141 contenido_142 contenido_143 contenido_144 contenido_145 contenido_146 contenido_147 contenido_148 contenido_149 contenido_150 contenido_151 contenido_152 contenido_153 contenido_154 contenido_155 contenido_156 contenido_157 contenido_158 contenido_159 contenido_160 contenido_161 contenido_162 contenido_163 contenido_164 contenido_165 contenido_166 contenido_167 contenido_168 contenido_169 contenido_170 contenido_171 contenido_172 contenido_173 contenido_174 contenido_175 contenido_176 contenido_177 contenido_178 contenido_179 contenido_180 contenido_181 contenido_182 contenido_183 contenido_184 contenido_185 contenido_186 contenido_187 contenido_188 contenido_189 contenido_190 contenido_191 contenido_192 contenido_193 contenido_194 contenido_195 contenido_196 contenido_197 contenido_198 contenido_199 contenido_200
    )

    (:init
        (predecesor contenido_72 contenido_106)
        (predecesor contenido_5 contenido_55)
        (predecesor contenido_9 contenido_60)
        (predecesor contenido_174 contenido_194)
        (predecesor contenido_125 contenido_149)
        (predecesor contenido_4 contenido_129)
        (predecesor contenido_103 contenido_145)
        (predecesor contenido_48 contenido_103)
        (predecesor contenido_123 contenido_132)
        (predecesor contenido_124 contenido_158)
        (predecesor contenido_18 contenido_184)
        (predecesor contenido_117 contenido_136)
        (predecesor contenido_53 contenido_78)
        (predecesor contenido_84 contenido_133)
        (predecesor contenido_1 contenido_19)
        (predecesor contenido_123 contenido_128)
        (predecesor contenido_81 contenido_133)
        (predecesor contenido_155 contenido_159)
        (predecesor contenido_107 contenido_129)
        (predecesor contenido_24 contenido_47)
        (predecesor contenido_61 contenido_178)
        (predecesor contenido_122 contenido_169)
        (predecesor contenido_63 contenido_66)
        (predecesor contenido_70 contenido_178)
        (predecesor contenido_138 contenido_162)
        (predecesor contenido_74 contenido_102)
        (predecesor contenido_52 contenido_68)
        (predecesor contenido_61 contenido_93)
        (predecesor contenido_17 contenido_171)
        (predecesor contenido_89 contenido_198)
        (predecesor contenido_26 contenido_197)
        (predecesor contenido_88 contenido_150)
        (predecesor contenido_1 contenido_140)
        (predecesor contenido_60 contenido_199)
        (predecesor contenido_77 contenido_110)
        (predecesor contenido_95 contenido_196)
        (predecesor contenido_12 contenido_155)
        (predecesor contenido_30 contenido_180)
        (predecesor contenido_98 contenido_151)
        (predecesor contenido_8 contenido_115)
        (predecesor contenido_36 contenido_137)
        (predecesor contenido_27 contenido_183)
        (predecesor contenido_29 contenido_136)
        (predecesor contenido_19 contenido_63)
        (predecesor contenido_25 contenido_126)
        (predecesor contenido_130 contenido_194)
        (predecesor contenido_93 contenido_154)
        (predecesor contenido_69 contenido_200)
        (predecesor contenido_2 contenido_86)
        (predecesor contenido_37 contenido_172)
        (predecesor contenido_77 contenido_175)
        (predecesor contenido_12 contenido_54)
        (predecesor contenido_97 contenido_102)
        (predecesor contenido_99 contenido_196)
        (predecesor contenido_107 contenido_112)
        (predecesor contenido_79 contenido_117)
        (predecesor contenido_10 contenido_56)
        (predecesor contenido_104 contenido_200)
        (predecesor contenido_97 contenido_110)
        (predecesor contenido_38 contenido_140)
        (predecesor contenido_20 contenido_164)
        (predecesor contenido_18 contenido_183)
        (predecesor contenido_66 contenido_167)
        (predecesor contenido_12 contenido_70)
        (predecesor contenido_37 contenido_182)
        (predecesor contenido_12 contenido_15)
        (predecesor contenido_83 contenido_115)
        (predecesor contenido_37 contenido_129)
        (predecesor contenido_62 contenido_179)
        (predecesor contenido_130 contenido_177)
        (predecesor contenido_140 contenido_154)
        (predecesor contenido_103 contenido_149)
        (predecesor contenido_169 contenido_175)
        (predecesor contenido_64 contenido_74)
        (predecesor contenido_23 contenido_180)
        (predecesor contenido_10 contenido_171)
        (predecesor contenido_36 contenido_78)
        (predecesor contenido_76 contenido_145)
        (predecesor contenido_54 contenido_173)
        (predecesor contenido_128 contenido_198)
        (predecesor contenido_89 contenido_134)
        (predecesor contenido_9 contenido_172)
        (predecesor contenido_19 contenido_177)
        (predecesor contenido_81 contenido_150)
        (predecesor contenido_111 contenido_114)
        (predecesor contenido_98 contenido_200)
        (predecesor contenido_16 contenido_91)
        (predecesor contenido_187 contenido_189)
        (predecesor contenido_82 contenido_176)
        (predecesor contenido_83 contenido_118)
        (predecesor contenido_12 contenido_121)
        (predecesor contenido_91 contenido_190)
        (predecesor contenido_41 contenido_73)
        (predecesor contenido_41 contenido_42)
        (predecesor contenido_85 contenido_90)
        (predecesor contenido_45 contenido_150)
        (predecesor contenido_71 contenido_170)
        (predecesor contenido_53 contenido_132)
        (predecesor contenido_69 contenido_112)
        (predecesor contenido_78 contenido_132)
        (predecesor contenido_137 contenido_147)
        (predecesor contenido_50 contenido_131)
        (predecesor contenido_21 contenido_76)
        (predecesor contenido_18 contenido_154)
        (predecesor contenido_7 contenido_141)
        (predecesor contenido_5 contenido_8)
        (predecesor contenido_36 contenido_151)
        (predecesor contenido_57 contenido_130)
        (predecesor contenido_25 contenido_140)
        (predecesor contenido_50 contenido_181)
        (predecesor contenido_26 contenido_102)
        (predecesor contenido_24 contenido_150)
        (predecesor contenido_40 contenido_50)
        (predecesor contenido_111 contenido_191)
        (predecesor contenido_118 contenido_129)
        (predecesor contenido_91 contenido_104)
        (predecesor contenido_121 contenido_125)
        (predecesor contenido_91 contenido_112)
        (predecesor contenido_19 contenido_86)
        (predecesor contenido_34 contenido_173)
        (predecesor contenido_7 contenido_94)
        (predecesor contenido_11 contenido_145)
        (predecesor contenido_8 contenido_41)
        (predecesor contenido_14 contenido_20)
        (predecesor contenido_78 contenido_109)
        (predecesor contenido_11 contenido_46)
        (predecesor contenido_67 contenido_179)
        (predecesor contenido_18 contenido_38)
        (predecesor contenido_55 contenido_77)
        (predecesor contenido_90 contenido_113)
        (predecesor contenido_38 contenido_125)
        (predecesor contenido_141 contenido_188)
        (predecesor contenido_37 contenido_38)
        (predecesor contenido_105 contenido_200)
        (predecesor contenido_17 contenido_78)
        (predecesor contenido_40 contenido_185)
        (predecesor contenido_44 contenido_133)
        (predecesor contenido_114 contenido_186)
        (predecesor contenido_132 contenido_149)
        (predecesor contenido_21 contenido_102)
        (predecesor contenido_53 contenido_87)
        (predecesor contenido_82 contenido_114)
        (predecesor contenido_8 contenido_102)
        (predecesor contenido_85 contenido_145)
        (predecesor contenido_120 contenido_122)
        (predecesor contenido_90 contenido_127)
        (predecesor contenido_96 contenido_159)
        (predecesor contenido_113 contenido_188)
        (predecesor contenido_5 contenido_89)
        (predecesor contenido_19 contenido_137)
        (predecesor contenido_71 contenido_135)
        (predecesor contenido_177 contenido_197)
        (predecesor contenido_11 contenido_107)
        (predecesor contenido_91 contenido_161)
        (predecesor contenido_87 contenido_134)
        (predecesor contenido_1 contenido_172)
        (predecesor contenido_3 contenido_75)
        (predecesor contenido_45 contenido_97)
        (predecesor contenido_46 contenido_136)
        (predecesor contenido_57 contenido_90)
        (paralela contenido_28 contenido_9)
        (paralela contenido_9 contenido_28)
        (paralela contenido_28 contenido_64)
        (paralela contenido_64 contenido_28)
        (paralela contenido_28 contenido_29)
        (paralela contenido_29 contenido_28)
        (paralela contenido_28 contenido_43)
        (paralela contenido_43 contenido_28)
        (paralela contenido_28 contenido_108)
        (paralela contenido_108 contenido_28)
        (paralela contenido_9 contenido_64)
        (paralela contenido_64 contenido_9)
        (paralela contenido_9 contenido_29)
        (paralela contenido_29 contenido_9)
        (paralela contenido_9 contenido_43)
        (paralela contenido_43 contenido_9)
        (paralela contenido_9 contenido_108)
        (paralela contenido_108 contenido_9)
        (paralela contenido_64 contenido_29)
        (paralela contenido_29 contenido_64)
        (paralela contenido_64 contenido_43)
        (paralela contenido_43 contenido_64)
        (paralela contenido_64 contenido_108)
        (paralela contenido_108 contenido_64)
        (paralela contenido_29 contenido_43)
        (paralela contenido_43 contenido_29)
        (paralela contenido_29 contenido_108)
        (paralela contenido_108 contenido_29)
        (paralela contenido_43 contenido_108)
        (paralela contenido_108 contenido_43)
        (paralela contenido_59 contenido_32)
        (paralela contenido_32 contenido_59)
        (paralela contenido_59 contenido_80)
        (paralela contenido_80 contenido_59)
        (paralela contenido_59 contenido_195)
        (paralela contenido_195 contenido_59)
        (paralela contenido_59 contenido_124)
        (paralela contenido_124 contenido_59)
        (paralela contenido_59 contenido_1)
        (paralela contenido_1 contenido_59)
        (paralela contenido_32 contenido_80)
        (paralela contenido_80 contenido_32)
        (paralela contenido_32 contenido_195)
        (paralela contenido_195 contenido_32)
        (paralela contenido_32 contenido_124)
        (paralela contenido_124 contenido_32)
        (paralela contenido_32 contenido_1)
        (paralela contenido_1 contenido_32)
        (paralela contenido_80 contenido_195)
        (paralela contenido_195 contenido_80)
        (paralela contenido_80 contenido_124)
        (paralela contenido_124 contenido_80)
        (paralela contenido_80 contenido_1)
        (paralela contenido_1 contenido_80)
        (paralela contenido_195 contenido_124)
        (paralela contenido_124 contenido_195)
        (paralela contenido_195 contenido_1)
        (paralela contenido_1 contenido_195)
        (paralela contenido_124 contenido_1)
        (paralela contenido_1 contenido_124)
        (paralela contenido_119 contenido_138)
        (paralela contenido_138 contenido_119)
        (paralela contenido_119 contenido_49)
        (paralela contenido_49 contenido_119)
        (paralela contenido_119 contenido_92)
        (paralela contenido_92 contenido_119)
        (paralela contenido_119 contenido_69)
        (paralela contenido_69 contenido_119)
        (paralela contenido_119 contenido_142)
        (paralela contenido_142 contenido_119)
        (paralela contenido_138 contenido_49)
        (paralela contenido_49 contenido_138)
        (paralela contenido_138 contenido_92)
        (paralela contenido_92 contenido_138)
        (paralela contenido_138 contenido_69)
        (paralela contenido_69 contenido_138)
        (paralela contenido_138 contenido_142)
        (paralela contenido_142 contenido_138)
        (paralela contenido_49 contenido_92)
        (paralela contenido_92 contenido_49)
        (paralela contenido_49 contenido_69)
        (paralela contenido_69 contenido_49)
        (paralela contenido_49 contenido_142)
        (paralela contenido_142 contenido_49)
        (paralela contenido_92 contenido_69)
        (paralela contenido_69 contenido_92)
        (paralela contenido_92 contenido_142)
        (paralela contenido_142 contenido_92)
        (paralela contenido_69 contenido_142)
        (paralela contenido_142 contenido_69)
        (paralela contenido_146 contenido_24)
        (paralela contenido_24 contenido_146)
        (paralela contenido_146 contenido_82)
        (paralela contenido_82 contenido_146)
        (paralela contenido_146 contenido_84)
        (paralela contenido_84 contenido_146)
        (paralela contenido_146 contenido_67)
        (paralela contenido_67 contenido_146)
        (paralela contenido_146 contenido_139)
        (paralela contenido_139 contenido_146)
        (paralela contenido_24 contenido_82)
        (paralela contenido_82 contenido_24)
        (paralela contenido_24 contenido_84)
        (paralela contenido_84 contenido_24)
        (paralela contenido_24 contenido_67)
        (paralela contenido_67 contenido_24)
        (paralela contenido_24 contenido_139)
        (paralela contenido_139 contenido_24)
        (paralela contenido_82 contenido_84)
        (paralela contenido_84 contenido_82)
        (paralela contenido_82 contenido_67)
        (paralela contenido_67 contenido_82)
        (paralela contenido_82 contenido_139)
        (paralela contenido_139 contenido_82)
        (paralela contenido_84 contenido_67)
        (paralela contenido_67 contenido_84)
        (paralela contenido_84 contenido_139)
        (paralela contenido_139 contenido_84)
        (paralela contenido_67 contenido_139)
        (paralela contenido_139 contenido_67)
        (paralela contenido_65 contenido_26)
        (paralela contenido_26 contenido_65)
        (paralela contenido_65 contenido_18)
        (paralela contenido_18 contenido_65)
        (paralela contenido_65 contenido_166)
        (paralela contenido_166 contenido_65)
        (paralela contenido_65 contenido_168)
        (paralela contenido_168 contenido_65)
        (paralela contenido_65 contenido_143)
        (paralela contenido_143 contenido_65)
        (paralela contenido_26 contenido_18)
        (paralela contenido_18 contenido_26)
        (paralela contenido_26 contenido_166)
        (paralela contenido_166 contenido_26)
        (paralela contenido_26 contenido_168)
        (paralela contenido_168 contenido_26)
        (paralela contenido_26 contenido_143)
        (paralela contenido_143 contenido_26)
        (paralela contenido_18 contenido_166)
        (paralela contenido_166 contenido_18)
        (paralela contenido_18 contenido_168)
        (paralela contenido_168 contenido_18)
        (paralela contenido_18 contenido_143)
        (paralela contenido_143 contenido_18)
        (paralela contenido_166 contenido_168)
        (paralela contenido_168 contenido_166)
        (paralela contenido_166 contenido_143)
        (paralela contenido_143 contenido_166)
        (paralela contenido_168 contenido_143)
        (paralela contenido_143 contenido_168)
        (paralela contenido_144 contenido_58)
        (paralela contenido_58 contenido_144)
        (paralela contenido_144 contenido_22)
        (paralela contenido_22 contenido_144)
        (paralela contenido_144 contenido_99)
        (paralela contenido_99 contenido_144)
        (paralela contenido_144 contenido_14)
        (paralela contenido_14 contenido_144)
        (paralela contenido_144 contenido_71)
        (paralela contenido_71 contenido_144)
        (paralela contenido_58 contenido_22)
        (paralela contenido_22 contenido_58)
        (paralela contenido_58 contenido_99)
        (paralela contenido_99 contenido_58)
        (paralela contenido_58 contenido_14)
        (paralela contenido_14 contenido_58)
        (paralela contenido_58 contenido_71)
        (paralela contenido_71 contenido_58)
        (paralela contenido_22 contenido_99)
        (paralela contenido_99 contenido_22)
        (paralela contenido_22 contenido_14)
        (paralela contenido_14 contenido_22)
        (paralela contenido_22 contenido_71)
        (paralela contenido_71 contenido_22)
        (paralela contenido_99 contenido_14)
        (paralela contenido_14 contenido_99)
        (paralela contenido_99 contenido_71)
        (paralela contenido_71 contenido_99)
        (paralela contenido_14 contenido_71)
        (paralela contenido_71 contenido_14)
        (paralela contenido_153 contenido_16)
        (paralela contenido_16 contenido_153)
        (paralela contenido_153 contenido_61)
        (paralela contenido_61 contenido_153)
        (paralela contenido_153 contenido_105)
        (paralela contenido_105 contenido_153)
        (paralela contenido_153 contenido_53)
        (paralela contenido_53 contenido_153)
        (paralela contenido_153 contenido_5)
        (paralela contenido_5 contenido_153)
        (paralela contenido_16 contenido_61)
        (paralela contenido_61 contenido_16)
        (paralela contenido_16 contenido_105)
        (paralela contenido_105 contenido_16)
        (paralela contenido_16 contenido_53)
        (paralela contenido_53 contenido_16)
        (paralela contenido_16 contenido_5)
        (paralela contenido_5 contenido_16)
        (paralela contenido_61 contenido_105)
        (paralela contenido_105 contenido_61)
        (paralela contenido_61 contenido_53)
        (paralela contenido_53 contenido_61)
        (paralela contenido_61 contenido_5)
        (paralela contenido_5 contenido_61)
        (paralela contenido_105 contenido_53)
        (paralela contenido_53 contenido_105)
        (paralela contenido_105 contenido_5)
        (paralela contenido_5 contenido_105)
        (paralela contenido_53 contenido_5)
        (paralela contenido_5 contenido_53)
        (paralela contenido_52 contenido_30)
        (paralela contenido_30 contenido_52)
        (paralela contenido_52 contenido_36)
        (paralela contenido_36 contenido_52)
        (paralela contenido_52 contenido_12)
        (paralela contenido_12 contenido_52)
        (paralela contenido_52 contenido_152)
        (paralela contenido_152 contenido_52)
        (paralela contenido_52 contenido_35)
        (paralela contenido_35 contenido_52)
        (paralela contenido_30 contenido_36)
        (paralela contenido_36 contenido_30)
        (paralela contenido_30 contenido_12)
        (paralela contenido_12 contenido_30)
        (paralela contenido_30 contenido_152)
        (paralela contenido_152 contenido_30)
        (paralela contenido_30 contenido_35)
        (paralela contenido_35 contenido_30)
        (paralela contenido_36 contenido_12)
        (paralela contenido_12 contenido_36)
        (paralela contenido_36 contenido_152)
        (paralela contenido_152 contenido_36)
        (paralela contenido_36 contenido_35)
        (paralela contenido_35 contenido_36)
        (paralela contenido_12 contenido_152)
        (paralela contenido_152 contenido_12)
        (paralela contenido_12 contenido_35)
        (paralela contenido_35 contenido_12)
        (paralela contenido_152 contenido_35)
        (paralela contenido_35 contenido_152)
        (paralela contenido_83 contenido_79)
        (paralela contenido_79 contenido_83)
        (paralela contenido_83 contenido_100)
        (paralela contenido_100 contenido_83)
        (paralela contenido_83 contenido_40)
        (paralela contenido_40 contenido_83)
        (paralela contenido_83 contenido_51)
        (paralela contenido_51 contenido_83)
        (paralela contenido_83 contenido_187)
        (paralela contenido_187 contenido_83)
        (paralela contenido_79 contenido_100)
        (paralela contenido_100 contenido_79)
        (paralela contenido_79 contenido_40)
        (paralela contenido_40 contenido_79)
        (paralela contenido_79 contenido_51)
        (paralela contenido_51 contenido_79)
        (paralela contenido_79 contenido_187)
        (paralela contenido_187 contenido_79)
        (paralela contenido_100 contenido_40)
        (paralela contenido_40 contenido_100)
        (paralela contenido_100 contenido_51)
        (paralela contenido_51 contenido_100)
        (paralela contenido_100 contenido_187)
        (paralela contenido_187 contenido_100)
        (paralela contenido_40 contenido_51)
        (paralela contenido_51 contenido_40)
        (paralela contenido_40 contenido_187)
        (paralela contenido_187 contenido_40)
        (paralela contenido_51 contenido_187)
        (paralela contenido_187 contenido_51)
        (paralela contenido_48 contenido_72)
        (paralela contenido_72 contenido_48)
        (paralela contenido_48 contenido_57)
        (paralela contenido_57 contenido_48)
        (paralela contenido_48 contenido_116)
        (paralela contenido_116 contenido_48)
        (paralela contenido_48 contenido_96)
        (paralela contenido_96 contenido_48)
        (paralela contenido_48 contenido_3)
        (paralela contenido_3 contenido_48)
        (paralela contenido_72 contenido_57)
        (paralela contenido_57 contenido_72)
        (paralela contenido_72 contenido_116)
        (paralela contenido_116 contenido_72)
        (paralela contenido_72 contenido_96)
        (paralela contenido_96 contenido_72)
        (paralela contenido_72 contenido_3)
        (paralela contenido_3 contenido_72)
        (paralela contenido_57 contenido_116)
        (paralela contenido_116 contenido_57)
        (paralela contenido_57 contenido_96)
        (paralela contenido_96 contenido_57)
        (paralela contenido_57 contenido_3)
        (paralela contenido_3 contenido_57)
        (paralela contenido_116 contenido_96)
        (paralela contenido_96 contenido_116)
        (paralela contenido_116 contenido_3)
        (paralela contenido_3 contenido_116)
        (paralela contenido_96 contenido_3)
        (paralela contenido_3 contenido_96)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_102)
        (paralelas_vistas contenido_39)
        (paralelas_vistas contenido_27)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_141)
        (paralelas_vistas contenido_56)
        (paralelas_vistas contenido_190)
        (paralelas_vistas contenido_160)
        (paralelas_vistas contenido_163)
        (paralelas_vistas contenido_164)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_115)
        (paralelas_vistas contenido_178)
        (paralelas_vistas contenido_192)
        (paralelas_vistas contenido_131)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_54)
        (paralelas_vistas contenido_145)
        (paralelas_vistas contenido_157)
        (paralelas_vistas contenido_11)
        (paralelas_vistas contenido_113)
        (paralelas_vistas contenido_90)
        (paralelas_vistas contenido_55)
        (paralelas_vistas contenido_19)
        (paralelas_vistas contenido_169)
        (paralelas_vistas contenido_151)
        (paralelas_vistas contenido_47)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_180)
        (paralelas_vistas contenido_179)
        (paralelas_vistas contenido_134)
        (paralelas_vistas contenido_172)
        (paralelas_vistas contenido_110)
        (paralelas_vistas contenido_98)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_62)
        (paralelas_vistas contenido_140)
        (paralelas_vistas contenido_130)
        (paralelas_vistas contenido_42)
        (paralelas_vistas contenido_129)
        (paralelas_vistas contenido_125)
        (paralelas_vistas contenido_150)
        (paralelas_vistas contenido_44)
        (paralelas_vistas contenido_156)
        (paralelas_vistas contenido_95)
        (paralelas_vistas contenido_176)
        (paralelas_vistas contenido_177)
        (paralelas_vistas contenido_87)
        (paralelas_vistas contenido_121)
        (paralelas_vistas contenido_70)
        (paralelas_vistas contenido_112)
        (paralelas_vistas contenido_162)
        (paralelas_vistas contenido_182)
        (paralelas_vistas contenido_184)
        (paralelas_vistas contenido_155)
        (paralelas_vistas contenido_194)
        (paralelas_vistas contenido_50)
        (paralelas_vistas contenido_109)
        (paralelas_vistas contenido_74)
        (paralelas_vistas contenido_149)
        (paralelas_vistas contenido_63)
        (paralelas_vistas contenido_183)
        (paralelas_vistas contenido_88)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_133)
        (paralelas_vistas contenido_120)
        (paralelas_vistas contenido_94)
        (paralelas_vistas contenido_127)
        (paralelas_vistas contenido_6)
        (paralelas_vistas contenido_114)
        (paralelas_vistas contenido_198)
        (paralelas_vistas contenido_193)
        (paralelas_vistas contenido_85)
        (paralelas_vistas contenido_78)
        (paralelas_vistas contenido_132)
        (paralelas_vistas contenido_189)
        (paralelas_vistas contenido_135)
        (paralelas_vistas contenido_196)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_148)
        (paralelas_vistas contenido_46)
        (paralelas_vistas contenido_66)
        (paralelas_vistas contenido_86)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_25)
        (paralelas_vistas contenido_147)
        (paralelas_vistas contenido_167)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_68)
        (paralelas_vistas contenido_104)
        (paralelas_vistas contenido_137)
        (paralelas_vistas contenido_174)
        (paralelas_vistas contenido_173)
        (paralelas_vistas contenido_128)
        (paralelas_vistas contenido_41)
        (paralelas_vistas contenido_154)
        (paralelas_vistas contenido_31)
        (paralelas_vistas contenido_165)
        (paralelas_vistas contenido_185)
        (paralelas_vistas contenido_106)
        (paralelas_vistas contenido_122)
        (paralelas_vistas contenido_191)
        (paralelas_vistas contenido_76)
        (paralelas_vistas contenido_75)
        (paralelas_vistas contenido_123)
        (paralelas_vistas contenido_197)
        (paralelas_vistas contenido_199)
        (paralelas_vistas contenido_111)
        (paralelas_vistas contenido_126)
        (paralelas_vistas contenido_38)
        (paralelas_vistas contenido_200)
        (paralelas_vistas contenido_103)
        (paralelas_vistas contenido_118)
        (paralelas_vistas contenido_89)
        (paralelas_vistas contenido_91)
        (paralelas_vistas contenido_60)
        (paralelas_vistas contenido_159)
        (paralelas_vistas contenido_186)
        (paralelas_vistas contenido_171)
        (paralelas_vistas contenido_170)
        (paralelas_vistas contenido_175)
        (paralelas_vistas contenido_136)
        (paralelas_vistas contenido_188)
        (paralelas_vistas contenido_81)
        (paralelas_vistas contenido_45)
        (paralelas_vistas contenido_101)
        (paralelas_vistas contenido_181)
        (paralelas_vistas contenido_97)
        (paralelas_vistas contenido_158)
        (paralelas_vistas contenido_117)
        (paralelas_vistas contenido_77)
        (paralelas_vistas contenido_107)
        (paralelas_vistas contenido_161)
        (paralelas_vistas contenido_34)
        (paralelas_vistas contenido_73)
        (paralelas_vistas contenido_93)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_37)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_39)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_160)
        (predecesores_vistos contenido_163)
        (predecesores_vistos contenido_192)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_157)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_98)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_62)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_156)
        (predecesores_vistos contenido_95)
        (predecesores_vistos contenido_88)
        (predecesores_vistos contenido_120)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_37)
        (predecesores_vistos contenido_193)
        (predecesores_vistos contenido_85)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_148)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_174)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_165)
        (predecesores_vistos contenido_123)
        (predecesores_vistos contenido_111)
        (predecesores_vistos contenido_81)
        (predecesores_vistos contenido_45)
        (predecesores_vistos contenido_101)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_23)
        (final contenido_6)
        (final contenido_13)
        (final contenido_15)
        (final contenido_31)
        (final contenido_33)
        (final contenido_39)
        (final contenido_42)
        (final contenido_47)
        (final contenido_56)
        (final contenido_68)
        (final contenido_73)
        (final contenido_75)
        (final contenido_86)
        (final contenido_94)
        (final contenido_101)
        (final contenido_102)
        (final contenido_106)
        (final contenido_109)
        (final contenido_110)
        (final contenido_112)
        (final contenido_115)
        (final contenido_126)
        (final contenido_127)
        (final contenido_129)
        (final contenido_131)
        (final contenido_133)
        (final contenido_134)
        (final contenido_135)
        (final contenido_136)
        (final contenido_145)
        (final contenido_147)
        (final contenido_148)
        (final contenido_149)
        (final contenido_150)
        (final contenido_151)
        (final contenido_154)
        (final contenido_156)
        (final contenido_157)
        (final contenido_158)
        (final contenido_159)
        (final contenido_160)
        (final contenido_161)
        (final contenido_162)
        (final contenido_163)
        (final contenido_164)
        (final contenido_165)
        (final contenido_167)
        (final contenido_170)
        (final contenido_171)
        (final contenido_172)
        (final contenido_173)
        (final contenido_175)
        (final contenido_176)
        (final contenido_178)
        (final contenido_179)
        (final contenido_180)
        (final contenido_181)
        (final contenido_182)
        (final contenido_183)
        (final contenido_184)
        (final contenido_185)
        (final contenido_186)
        (final contenido_188)
        (final contenido_189)
        (final contenido_190)
        (final contenido_191)
        (final contenido_192)
        (final contenido_193)
        (final contenido_194)
        (final contenido_196)
        (final contenido_197)
        (final contenido_198)
        (final contenido_199)
        (final contenido_200)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
