(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100
    )

    (:init
        (predecesor contenido_46 contenido_56)
        (predecesor contenido_1 contenido_10)
        (predecesor contenido_42 contenido_58)
        (predecesor contenido_66 contenido_75)
        (predecesor contenido_40 contenido_59)
        (predecesor contenido_69 contenido_81)
        (predecesor contenido_43 contenido_45)
        (predecesor contenido_41 contenido_67)
        (predecesor contenido_36 contenido_85)
        (predecesor contenido_27 contenido_87)
        (predecesor contenido_27 contenido_44)
        (predecesor contenido_12 contenido_90)
        (predecesor contenido_45 contenido_57)
        (predecesor contenido_9 contenido_77)
        (predecesor contenido_44 contenido_75)
        (predecesor contenido_54 contenido_56)
        (predecesor contenido_59 contenido_65)
        (predecesor contenido_30 contenido_100)
        (predecesor contenido_4 contenido_47)
        (predecesor contenido_57 contenido_94)
        (predecesor contenido_61 contenido_85)
        (predecesor contenido_22 contenido_67)
        (predecesor contenido_27 contenido_66)
        (predecesor contenido_10 contenido_89)
        (predecesor contenido_6 contenido_54)
        (predecesor contenido_25 contenido_66)
        (predecesor contenido_13 contenido_51)
        (predecesor contenido_62 contenido_79)
        (predecesor contenido_15 contenido_68)
        (predecesor contenido_41 contenido_88)
        (predecesor contenido_28 contenido_39)
        (predecesor contenido_7 contenido_10)
        (predecesor contenido_13 contenido_99)
        (predecesor contenido_38 contenido_73)
        (predecesor contenido_6 contenido_27)
        (predecesor contenido_1 contenido_86)
        (predecesor contenido_6 contenido_61)
        (predecesor contenido_43 contenido_73)
        (predecesor contenido_60 contenido_61)
        (predecesor contenido_39 contenido_88)
        (predecesor contenido_29 contenido_65)
        (predecesor contenido_8 contenido_46)
        (predecesor contenido_15 contenido_90)
        (predecesor contenido_36 contenido_53)
        (predecesor contenido_10 contenido_69)
        (predecesor contenido_23 contenido_75)
        (predecesor contenido_25 contenido_91)
        (predecesor contenido_9 contenido_92)
        (predecesor contenido_18 contenido_76)
        (predecesor contenido_27 contenido_39)
        (predecesor contenido_21 contenido_37)
        (predecesor contenido_12 contenido_75)
        (predecesor contenido_45 contenido_99)
        (predecesor contenido_9 contenido_86)
        (predecesor contenido_19 contenido_91)
        (predecesor contenido_36 contenido_68)
        (predecesor contenido_50 contenido_98)
        (predecesor contenido_3 contenido_4)
        (predecesor contenido_31 contenido_47)
        (predecesor contenido_12 contenido_24)
        (predecesor contenido_6 contenido_73)
        (predecesor contenido_3 contenido_45)
        (predecesor contenido_39 contenido_55)
        (predecesor contenido_24 contenido_52)
        (predecesor contenido_11 contenido_51)
        (predecesor contenido_19 contenido_70)
        (predecesor contenido_5 contenido_86)
        (predecesor contenido_4 contenido_51)
        (predecesor contenido_59 contenido_68)
        (predecesor contenido_20 contenido_93)
        (predecesor contenido_19 contenido_86)
        (predecesor contenido_1 contenido_43)
        (predecesor contenido_6 contenido_35)
        (predecesor contenido_6 contenido_23)
        (predecesor contenido_32 contenido_33)
        (predecesor contenido_42 contenido_59)
        (predecesor contenido_2 contenido_65)
        (predecesor contenido_45 contenido_64)
        (predecesor contenido_52 contenido_73)
        (predecesor contenido_64 contenido_99)
        (paralela contenido_13 contenido_31)
        (paralela contenido_31 contenido_13)
        (paralela contenido_13 contenido_32)
        (paralela contenido_32 contenido_13)
        (paralela contenido_13 contenido_17)
        (paralela contenido_17 contenido_13)
        (paralela contenido_13 contenido_16)
        (paralela contenido_16 contenido_13)
        (paralela contenido_13 contenido_41)
        (paralela contenido_41 contenido_13)
        (paralela contenido_31 contenido_32)
        (paralela contenido_32 contenido_31)
        (paralela contenido_31 contenido_17)
        (paralela contenido_17 contenido_31)
        (paralela contenido_31 contenido_16)
        (paralela contenido_16 contenido_31)
        (paralela contenido_31 contenido_41)
        (paralela contenido_41 contenido_31)
        (paralela contenido_32 contenido_17)
        (paralela contenido_17 contenido_32)
        (paralela contenido_32 contenido_16)
        (paralela contenido_16 contenido_32)
        (paralela contenido_32 contenido_41)
        (paralela contenido_41 contenido_32)
        (paralela contenido_17 contenido_16)
        (paralela contenido_16 contenido_17)
        (paralela contenido_17 contenido_41)
        (paralela contenido_41 contenido_17)
        (paralela contenido_16 contenido_41)
        (paralela contenido_41 contenido_16)
        (paralela contenido_9 contenido_26)
        (paralela contenido_26 contenido_9)
        (paralela contenido_9 contenido_12)
        (paralela contenido_12 contenido_9)
        (paralela contenido_9 contenido_6)
        (paralela contenido_6 contenido_9)
        (paralela contenido_9 contenido_25)
        (paralela contenido_25 contenido_9)
        (paralela contenido_9 contenido_1)
        (paralela contenido_1 contenido_9)
        (paralela contenido_26 contenido_12)
        (paralela contenido_12 contenido_26)
        (paralela contenido_26 contenido_6)
        (paralela contenido_6 contenido_26)
        (paralela contenido_26 contenido_25)
        (paralela contenido_25 contenido_26)
        (paralela contenido_26 contenido_1)
        (paralela contenido_1 contenido_26)
        (paralela contenido_12 contenido_6)
        (paralela contenido_6 contenido_12)
        (paralela contenido_12 contenido_25)
        (paralela contenido_25 contenido_12)
        (paralela contenido_12 contenido_1)
        (paralela contenido_1 contenido_12)
        (paralela contenido_6 contenido_25)
        (paralela contenido_25 contenido_6)
        (paralela contenido_6 contenido_1)
        (paralela contenido_1 contenido_6)
        (paralela contenido_25 contenido_1)
        (paralela contenido_1 contenido_25)
        (paralela contenido_3 contenido_74)
        (paralela contenido_74 contenido_3)
        (paralela contenido_3 contenido_49)
        (paralela contenido_49 contenido_3)
        (paralela contenido_3 contenido_80)
        (paralela contenido_80 contenido_3)
        (paralela contenido_3 contenido_21)
        (paralela contenido_21 contenido_3)
        (paralela contenido_3 contenido_71)
        (paralela contenido_71 contenido_3)
        (paralela contenido_74 contenido_49)
        (paralela contenido_49 contenido_74)
        (paralela contenido_74 contenido_80)
        (paralela contenido_80 contenido_74)
        (paralela contenido_74 contenido_21)
        (paralela contenido_21 contenido_74)
        (paralela contenido_74 contenido_71)
        (paralela contenido_71 contenido_74)
        (paralela contenido_49 contenido_80)
        (paralela contenido_80 contenido_49)
        (paralela contenido_49 contenido_21)
        (paralela contenido_21 contenido_49)
        (paralela contenido_49 contenido_71)
        (paralela contenido_71 contenido_49)
        (paralela contenido_80 contenido_21)
        (paralela contenido_21 contenido_80)
        (paralela contenido_80 contenido_71)
        (paralela contenido_71 contenido_80)
        (paralela contenido_21 contenido_71)
        (paralela contenido_71 contenido_21)
        (paralela contenido_36 contenido_82)
        (paralela contenido_82 contenido_36)
        (paralela contenido_36 contenido_14)
        (paralela contenido_14 contenido_36)
        (paralela contenido_36 contenido_96)
        (paralela contenido_96 contenido_36)
        (paralela contenido_36 contenido_18)
        (paralela contenido_18 contenido_36)
        (paralela contenido_36 contenido_84)
        (paralela contenido_84 contenido_36)
        (paralela contenido_82 contenido_14)
        (paralela contenido_14 contenido_82)
        (paralela contenido_82 contenido_96)
        (paralela contenido_96 contenido_82)
        (paralela contenido_82 contenido_18)
        (paralela contenido_18 contenido_82)
        (paralela contenido_82 contenido_84)
        (paralela contenido_84 contenido_82)
        (paralela contenido_14 contenido_96)
        (paralela contenido_96 contenido_14)
        (paralela contenido_14 contenido_18)
        (paralela contenido_18 contenido_14)
        (paralela contenido_14 contenido_84)
        (paralela contenido_84 contenido_14)
        (paralela contenido_96 contenido_18)
        (paralela contenido_18 contenido_96)
        (paralela contenido_96 contenido_84)
        (paralela contenido_84 contenido_96)
        (paralela contenido_18 contenido_84)
        (paralela contenido_84 contenido_18)
        (paralela contenido_83 contenido_40)
        (paralela contenido_40 contenido_83)
        (paralela contenido_83 contenido_48)
        (paralela contenido_48 contenido_83)
        (paralela contenido_83 contenido_60)
        (paralela contenido_60 contenido_83)
        (paralela contenido_83 contenido_34)
        (paralela contenido_34 contenido_83)
        (paralela contenido_83 contenido_97)
        (paralela contenido_97 contenido_83)
        (paralela contenido_40 contenido_48)
        (paralela contenido_48 contenido_40)
        (paralela contenido_40 contenido_60)
        (paralela contenido_60 contenido_40)
        (paralela contenido_40 contenido_34)
        (paralela contenido_34 contenido_40)
        (paralela contenido_40 contenido_97)
        (paralela contenido_97 contenido_40)
        (paralela contenido_48 contenido_60)
        (paralela contenido_60 contenido_48)
        (paralela contenido_48 contenido_34)
        (paralela contenido_34 contenido_48)
        (paralela contenido_48 contenido_97)
        (paralela contenido_97 contenido_48)
        (paralela contenido_60 contenido_34)
        (paralela contenido_34 contenido_60)
        (paralela contenido_60 contenido_97)
        (paralela contenido_97 contenido_60)
        (paralela contenido_34 contenido_97)
        (paralela contenido_97 contenido_34)
        (paralela contenido_19 contenido_50)
        (paralela contenido_50 contenido_19)
        (paralela contenido_19 contenido_11)
        (paralela contenido_11 contenido_19)
        (paralela contenido_19 contenido_7)
        (paralela contenido_7 contenido_19)
        (paralela contenido_19 contenido_20)
        (paralela contenido_20 contenido_19)
        (paralela contenido_19 contenido_38)
        (paralela contenido_38 contenido_19)
        (paralela contenido_50 contenido_11)
        (paralela contenido_11 contenido_50)
        (paralela contenido_50 contenido_7)
        (paralela contenido_7 contenido_50)
        (paralela contenido_50 contenido_20)
        (paralela contenido_20 contenido_50)
        (paralela contenido_50 contenido_38)
        (paralela contenido_38 contenido_50)
        (paralela contenido_11 contenido_7)
        (paralela contenido_7 contenido_11)
        (paralela contenido_11 contenido_20)
        (paralela contenido_20 contenido_11)
        (paralela contenido_11 contenido_38)
        (paralela contenido_38 contenido_11)
        (paralela contenido_7 contenido_20)
        (paralela contenido_20 contenido_7)
        (paralela contenido_7 contenido_38)
        (paralela contenido_38 contenido_7)
        (paralela contenido_20 contenido_38)
        (paralela contenido_38 contenido_20)
        (paralelas_vistas contenido_85)
        (paralelas_vistas contenido_39)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_73)
        (paralelas_vistas contenido_95)
        (paralelas_vistas contenido_93)
        (paralelas_vistas contenido_68)
        (paralelas_vistas contenido_75)
        (paralelas_vistas contenido_55)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_99)
        (paralelas_vistas contenido_52)
        (paralelas_vistas contenido_59)
        (paralelas_vistas contenido_69)
        (paralelas_vistas contenido_28)
        (paralelas_vistas contenido_30)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_44)
        (paralelas_vistas contenido_46)
        (paralelas_vistas contenido_53)
        (paralelas_vistas contenido_77)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_42)
        (paralelas_vistas contenido_62)
        (paralelas_vistas contenido_88)
        (paralelas_vistas contenido_47)
        (paralelas_vistas contenido_87)
        (paralelas_vistas contenido_29)
        (paralelas_vistas contenido_90)
        (paralelas_vistas contenido_54)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_98)
        (paralelas_vistas contenido_91)
        (paralelas_vistas contenido_100)
        (paralelas_vistas contenido_51)
        (paralelas_vistas contenido_45)
        (paralelas_vistas contenido_76)
        (paralelas_vistas contenido_67)
        (paralelas_vistas contenido_89)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_72)
        (paralelas_vistas contenido_65)
        (paralelas_vistas contenido_79)
        (paralelas_vistas contenido_58)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_70)
        (paralelas_vistas contenido_57)
        (paralelas_vistas contenido_43)
        (paralelas_vistas contenido_86)
        (paralelas_vistas contenido_5)
        (paralelas_vistas contenido_56)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_61)
        (paralelas_vistas contenido_35)
        (paralelas_vistas contenido_64)
        (paralelas_vistas contenido_63)
        (paralelas_vistas contenido_92)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_81)
        (paralelas_vistas contenido_78)
        (paralelas_vistas contenido_94)
        (paralelas_vistas contenido_27)
        (paralelas_vistas contenido_37)
        (paralelas_vistas contenido_66)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_95)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_62)
        (predecesores_vistos contenido_78)
        (predecesores_vistos contenido_29)
        (final contenido_33)
        (final contenido_35)
        (final contenido_37)
        (final contenido_47)
        (final contenido_51)
        (final contenido_53)
        (final contenido_55)
        (final contenido_56)
        (final contenido_58)
        (final contenido_63)
        (final contenido_65)
        (final contenido_67)
        (final contenido_68)
        (final contenido_70)
        (final contenido_72)
        (final contenido_73)
        (final contenido_75)
        (final contenido_76)
        (final contenido_77)
        (final contenido_78)
        (final contenido_79)
        (final contenido_81)
        (final contenido_85)
        (final contenido_86)
        (final contenido_87)
        (final contenido_88)
        (final contenido_89)
        (final contenido_90)
        (final contenido_91)
        (final contenido_92)
        (final contenido_93)
        (final contenido_94)
        (final contenido_95)
        (final contenido_98)
        (final contenido_99)
        (final contenido_100)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
