(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50
    )

    (:init
        (predecesor contenido_3 contenido_37)
        (predecesor contenido_1 contenido_22)
        (predecesor contenido_31 contenido_43)
        (predecesor contenido_30 contenido_34)
        (predecesor contenido_10 contenido_47)
        (predecesor contenido_22 contenido_38)
        (predecesor contenido_5 contenido_39)
        (predecesor contenido_10 contenido_46)
        (predecesor contenido_27 contenido_28)
        (predecesor contenido_13 contenido_46)
        (predecesor contenido_33 contenido_38)
        (predecesor contenido_25 contenido_49)
        (predecesor contenido_21 contenido_29)
        (predecesor contenido_1 contenido_33)
        (predecesor contenido_8 contenido_34)
        (predecesor contenido_30 contenido_31)
        (predecesor contenido_20 contenido_30)
        (predecesor contenido_30 contenido_33)
        (predecesor contenido_3 contenido_31)
        (predecesor contenido_7 contenido_26)
        (predecesor contenido_23 contenido_32)
        (predecesor contenido_3 contenido_18)
        (predecesor contenido_6 contenido_45)
        (predecesor contenido_29 contenido_47)
        (predecesor contenido_6 contenido_26)
        (predecesor contenido_6 contenido_12)
        (predecesor contenido_3 contenido_43)
        (predecesor contenido_5 contenido_43)
        (predecesor contenido_3 contenido_27)
        (predecesor contenido_7 contenido_50)
        (predecesor contenido_3 contenido_12)
        (predecesor contenido_4 contenido_5)
        (predecesor contenido_15 contenido_33)
        (predecesor contenido_5 contenido_45)
        (predecesor contenido_6 contenido_38)
        (predecesor contenido_18 contenido_43)
        (predecesor contenido_31 contenido_40)
        (predecesor contenido_10 contenido_43)
        (predecesor contenido_2 contenido_23)
        (predecesor contenido_23 contenido_50)
        (paralela contenido_11 contenido_15)
        (paralela contenido_15 contenido_11)
        (paralela contenido_11 contenido_21)
        (paralela contenido_21 contenido_11)
        (paralela contenido_11 contenido_44)
        (paralela contenido_44 contenido_11)
        (paralela contenido_11 contenido_7)
        (paralela contenido_7 contenido_11)
        (paralela contenido_11 contenido_2)
        (paralela contenido_2 contenido_11)
        (paralela contenido_15 contenido_21)
        (paralela contenido_21 contenido_15)
        (paralela contenido_15 contenido_44)
        (paralela contenido_44 contenido_15)
        (paralela contenido_15 contenido_7)
        (paralela contenido_7 contenido_15)
        (paralela contenido_15 contenido_2)
        (paralela contenido_2 contenido_15)
        (paralela contenido_21 contenido_44)
        (paralela contenido_44 contenido_21)
        (paralela contenido_21 contenido_7)
        (paralela contenido_7 contenido_21)
        (paralela contenido_21 contenido_2)
        (paralela contenido_2 contenido_21)
        (paralela contenido_44 contenido_7)
        (paralela contenido_7 contenido_44)
        (paralela contenido_44 contenido_2)
        (paralela contenido_2 contenido_44)
        (paralela contenido_7 contenido_2)
        (paralela contenido_2 contenido_7)
        (paralela contenido_19 contenido_48)
        (paralela contenido_48 contenido_19)
        (paralela contenido_19 contenido_24)
        (paralela contenido_24 contenido_19)
        (paralela contenido_19 contenido_35)
        (paralela contenido_35 contenido_19)
        (paralela contenido_19 contenido_3)
        (paralela contenido_3 contenido_19)
        (paralela contenido_19 contenido_4)
        (paralela contenido_4 contenido_19)
        (paralela contenido_48 contenido_24)
        (paralela contenido_24 contenido_48)
        (paralela contenido_48 contenido_35)
        (paralela contenido_35 contenido_48)
        (paralela contenido_48 contenido_3)
        (paralela contenido_3 contenido_48)
        (paralela contenido_48 contenido_4)
        (paralela contenido_4 contenido_48)
        (paralela contenido_24 contenido_35)
        (paralela contenido_35 contenido_24)
        (paralela contenido_24 contenido_3)
        (paralela contenido_3 contenido_24)
        (paralela contenido_24 contenido_4)
        (paralela contenido_4 contenido_24)
        (paralela contenido_35 contenido_3)
        (paralela contenido_3 contenido_35)
        (paralela contenido_35 contenido_4)
        (paralela contenido_4 contenido_35)
        (paralela contenido_3 contenido_4)
        (paralela contenido_4 contenido_3)
        (paralela contenido_42 contenido_14)
        (paralela contenido_14 contenido_42)
        (paralela contenido_42 contenido_1)
        (paralela contenido_1 contenido_42)
        (paralela contenido_42 contenido_8)
        (paralela contenido_8 contenido_42)
        (paralela contenido_42 contenido_10)
        (paralela contenido_10 contenido_42)
        (paralela contenido_42 contenido_16)
        (paralela contenido_16 contenido_42)
        (paralela contenido_14 contenido_1)
        (paralela contenido_1 contenido_14)
        (paralela contenido_14 contenido_8)
        (paralela contenido_8 contenido_14)
        (paralela contenido_14 contenido_10)
        (paralela contenido_10 contenido_14)
        (paralela contenido_14 contenido_16)
        (paralela contenido_16 contenido_14)
        (paralela contenido_1 contenido_8)
        (paralela contenido_8 contenido_1)
        (paralela contenido_1 contenido_10)
        (paralela contenido_10 contenido_1)
        (paralela contenido_1 contenido_16)
        (paralela contenido_16 contenido_1)
        (paralela contenido_8 contenido_10)
        (paralela contenido_10 contenido_8)
        (paralela contenido_8 contenido_16)
        (paralela contenido_16 contenido_8)
        (paralela contenido_10 contenido_16)
        (paralela contenido_16 contenido_10)
        (paralela contenido_20 contenido_9)
        (paralela contenido_9 contenido_20)
        (paralela contenido_20 contenido_41)
        (paralela contenido_41 contenido_20)
        (paralela contenido_20 contenido_36)
        (paralela contenido_36 contenido_20)
        (paralela contenido_20 contenido_13)
        (paralela contenido_13 contenido_20)
        (paralela contenido_20 contenido_6)
        (paralela contenido_6 contenido_20)
        (paralela contenido_9 contenido_41)
        (paralela contenido_41 contenido_9)
        (paralela contenido_9 contenido_36)
        (paralela contenido_36 contenido_9)
        (paralela contenido_9 contenido_13)
        (paralela contenido_13 contenido_9)
        (paralela contenido_9 contenido_6)
        (paralela contenido_6 contenido_9)
        (paralela contenido_41 contenido_36)
        (paralela contenido_36 contenido_41)
        (paralela contenido_41 contenido_13)
        (paralela contenido_13 contenido_41)
        (paralela contenido_41 contenido_6)
        (paralela contenido_6 contenido_41)
        (paralela contenido_36 contenido_13)
        (paralela contenido_13 contenido_36)
        (paralela contenido_36 contenido_6)
        (paralela contenido_6 contenido_36)
        (paralela contenido_13 contenido_6)
        (paralela contenido_6 contenido_13)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_34)
        (paralelas_vistas contenido_28)
        (paralelas_vistas contenido_25)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_5)
        (paralelas_vistas contenido_43)
        (paralelas_vistas contenido_37)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_27)
        (paralelas_vistas contenido_49)
        (paralelas_vistas contenido_46)
        (paralelas_vistas contenido_31)
        (paralelas_vistas contenido_38)
        (paralelas_vistas contenido_29)
        (paralelas_vistas contenido_45)
        (paralelas_vistas contenido_39)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_47)
        (paralelas_vistas contenido_26)
        (paralelas_vistas contenido_30)
        (paralelas_vistas contenido_50)
        (paralelas_vistas contenido_32)
        (paralelas_vistas contenido_40)
        (paralelas_vistas contenido_23)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_17)
        (final contenido_12)
        (final contenido_17)
        (final contenido_26)
        (final contenido_28)
        (final contenido_32)
        (final contenido_34)
        (final contenido_37)
        (final contenido_38)
        (final contenido_39)
        (final contenido_40)
        (final contenido_43)
        (final contenido_45)
        (final contenido_46)
        (final contenido_47)
        (final contenido_49)
        (final contenido_50)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
