(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75
    )

    (:init
        (predecesor contenido_23 contenido_75)
        (predecesor contenido_35 contenido_72)
        (predecesor contenido_19 contenido_61)
        (predecesor contenido_54 contenido_56)
        (predecesor contenido_3 contenido_4)
        (predecesor contenido_25 contenido_59)
        (predecesor contenido_1 contenido_10)
        (predecesor contenido_9 contenido_39)
        (predecesor contenido_19 contenido_70)
        (predecesor contenido_13 contenido_51)
        (predecesor contenido_11 contenido_13)
        (predecesor contenido_14 contenido_63)
        (predecesor contenido_14 contenido_21)
        (predecesor contenido_27 contenido_49)
        (predecesor contenido_9 contenido_70)
        (predecesor contenido_10 contenido_72)
        (predecesor contenido_20 contenido_42)
        (predecesor contenido_16 contenido_68)
        (predecesor contenido_27 contenido_39)
        (predecesor contenido_26 contenido_59)
        (predecesor contenido_1 contenido_12)
        (predecesor contenido_8 contenido_12)
        (predecesor contenido_15 contenido_68)
        (predecesor contenido_29 contenido_65)
        (predecesor contenido_7 contenido_22)
        (predecesor contenido_9 contenido_42)
        (predecesor contenido_19 contenido_28)
        (predecesor contenido_36 contenido_69)
        (predecesor contenido_12 contenido_34)
        (predecesor contenido_36 contenido_68)
        (predecesor contenido_15 contenido_49)
        (predecesor contenido_22 contenido_57)
        (predecesor contenido_40 contenido_59)
        (predecesor contenido_39 contenido_51)
        (predecesor contenido_6 contenido_56)
        (predecesor contenido_6 contenido_23)
        (predecesor contenido_4 contenido_45)
        (predecesor contenido_16 contenido_24)
        (predecesor contenido_9 contenido_75)
        (predecesor contenido_11 contenido_51)
        (predecesor contenido_3 contenido_45)
        (predecesor contenido_19 contenido_40)
        (predecesor contenido_41 contenido_74)
        (predecesor contenido_6 contenido_61)
        (predecesor contenido_8 contenido_46)
        (predecesor contenido_7 contenido_45)
        (predecesor contenido_39 contenido_55)
        (predecesor contenido_52 contenido_73)
        (predecesor contenido_20 contenido_69)
        (predecesor contenido_44 contenido_75)
        (predecesor contenido_12 contenido_41)
        (predecesor contenido_45 contenido_64)
        (predecesor contenido_12 contenido_66)
        (predecesor contenido_2 contenido_65)
        (predecesor contenido_1 contenido_43)
        (predecesor contenido_60 contenido_61)
        (predecesor contenido_25 contenido_45)
        (predecesor contenido_64 contenido_71)
        (predecesor contenido_36 contenido_53)
        (predecesor contenido_7 contenido_10)
        (paralela contenido_29 contenido_37)
        (paralela contenido_37 contenido_29)
        (paralela contenido_29 contenido_18)
        (paralela contenido_18 contenido_29)
        (paralela contenido_29 contenido_62)
        (paralela contenido_62 contenido_29)
        (paralela contenido_29 contenido_6)
        (paralela contenido_6 contenido_29)
        (paralela contenido_29 contenido_25)
        (paralela contenido_25 contenido_29)
        (paralela contenido_37 contenido_18)
        (paralela contenido_18 contenido_37)
        (paralela contenido_37 contenido_62)
        (paralela contenido_62 contenido_37)
        (paralela contenido_37 contenido_6)
        (paralela contenido_6 contenido_37)
        (paralela contenido_37 contenido_25)
        (paralela contenido_25 contenido_37)
        (paralela contenido_18 contenido_62)
        (paralela contenido_62 contenido_18)
        (paralela contenido_18 contenido_6)
        (paralela contenido_6 contenido_18)
        (paralela contenido_18 contenido_25)
        (paralela contenido_25 contenido_18)
        (paralela contenido_62 contenido_6)
        (paralela contenido_6 contenido_62)
        (paralela contenido_62 contenido_25)
        (paralela contenido_25 contenido_62)
        (paralela contenido_6 contenido_25)
        (paralela contenido_25 contenido_6)
        (paralela contenido_20 contenido_15)
        (paralela contenido_15 contenido_20)
        (paralela contenido_20 contenido_67)
        (paralela contenido_67 contenido_20)
        (paralela contenido_20 contenido_36)
        (paralela contenido_36 contenido_20)
        (paralela contenido_20 contenido_11)
        (paralela contenido_11 contenido_20)
        (paralela contenido_20 contenido_7)
        (paralela contenido_7 contenido_20)
        (paralela contenido_15 contenido_67)
        (paralela contenido_67 contenido_15)
        (paralela contenido_15 contenido_36)
        (paralela contenido_36 contenido_15)
        (paralela contenido_15 contenido_11)
        (paralela contenido_11 contenido_15)
        (paralela contenido_15 contenido_7)
        (paralela contenido_7 contenido_15)
        (paralela contenido_67 contenido_36)
        (paralela contenido_36 contenido_67)
        (paralela contenido_67 contenido_11)
        (paralela contenido_11 contenido_67)
        (paralela contenido_67 contenido_7)
        (paralela contenido_7 contenido_67)
        (paralela contenido_36 contenido_11)
        (paralela contenido_11 contenido_36)
        (paralela contenido_36 contenido_7)
        (paralela contenido_7 contenido_36)
        (paralela contenido_11 contenido_7)
        (paralela contenido_7 contenido_11)
        (paralela contenido_2 contenido_32)
        (paralela contenido_32 contenido_2)
        (paralela contenido_2 contenido_58)
        (paralela contenido_58 contenido_2)
        (paralela contenido_2 contenido_35)
        (paralela contenido_35 contenido_2)
        (paralela contenido_2 contenido_54)
        (paralela contenido_54 contenido_2)
        (paralela contenido_2 contenido_50)
        (paralela contenido_50 contenido_2)
        (paralela contenido_32 contenido_58)
        (paralela contenido_58 contenido_32)
        (paralela contenido_32 contenido_35)
        (paralela contenido_35 contenido_32)
        (paralela contenido_32 contenido_54)
        (paralela contenido_54 contenido_32)
        (paralela contenido_32 contenido_50)
        (paralela contenido_50 contenido_32)
        (paralela contenido_58 contenido_35)
        (paralela contenido_35 contenido_58)
        (paralela contenido_58 contenido_54)
        (paralela contenido_54 contenido_58)
        (paralela contenido_58 contenido_50)
        (paralela contenido_50 contenido_58)
        (paralela contenido_35 contenido_54)
        (paralela contenido_54 contenido_35)
        (paralela contenido_35 contenido_50)
        (paralela contenido_50 contenido_35)
        (paralela contenido_54 contenido_50)
        (paralela contenido_50 contenido_54)
        (paralela contenido_38 contenido_1)
        (paralela contenido_1 contenido_38)
        (paralela contenido_38 contenido_47)
        (paralela contenido_47 contenido_38)
        (paralela contenido_38 contenido_48)
        (paralela contenido_48 contenido_38)
        (paralela contenido_38 contenido_26)
        (paralela contenido_26 contenido_38)
        (paralela contenido_38 contenido_60)
        (paralela contenido_60 contenido_38)
        (paralela contenido_1 contenido_47)
        (paralela contenido_47 contenido_1)
        (paralela contenido_1 contenido_48)
        (paralela contenido_48 contenido_1)
        (paralela contenido_1 contenido_26)
        (paralela contenido_26 contenido_1)
        (paralela contenido_1 contenido_60)
        (paralela contenido_60 contenido_1)
        (paralela contenido_47 contenido_48)
        (paralela contenido_48 contenido_47)
        (paralela contenido_47 contenido_26)
        (paralela contenido_26 contenido_47)
        (paralela contenido_47 contenido_60)
        (paralela contenido_60 contenido_47)
        (paralela contenido_48 contenido_26)
        (paralela contenido_26 contenido_48)
        (paralela contenido_48 contenido_60)
        (paralela contenido_60 contenido_48)
        (paralela contenido_26 contenido_60)
        (paralela contenido_60 contenido_26)
        (paralela contenido_9 contenido_8)
        (paralela contenido_8 contenido_9)
        (paralela contenido_9 contenido_5)
        (paralela contenido_5 contenido_9)
        (paralela contenido_9 contenido_27)
        (paralela contenido_27 contenido_9)
        (paralela contenido_9 contenido_52)
        (paralela contenido_52 contenido_9)
        (paralela contenido_9 contenido_30)
        (paralela contenido_30 contenido_9)
        (paralela contenido_8 contenido_5)
        (paralela contenido_5 contenido_8)
        (paralela contenido_8 contenido_27)
        (paralela contenido_27 contenido_8)
        (paralela contenido_8 contenido_52)
        (paralela contenido_52 contenido_8)
        (paralela contenido_8 contenido_30)
        (paralela contenido_30 contenido_8)
        (paralela contenido_5 contenido_27)
        (paralela contenido_27 contenido_5)
        (paralela contenido_5 contenido_52)
        (paralela contenido_52 contenido_5)
        (paralela contenido_5 contenido_30)
        (paralela contenido_30 contenido_5)
        (paralela contenido_27 contenido_52)
        (paralela contenido_52 contenido_27)
        (paralela contenido_27 contenido_30)
        (paralela contenido_30 contenido_27)
        (paralela contenido_52 contenido_30)
        (paralela contenido_30 contenido_52)
        (paralelas_vistas contenido_53)
        (paralelas_vistas contenido_65)
        (paralelas_vistas contenido_39)
        (paralelas_vistas contenido_28)
        (paralelas_vistas contenido_44)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_57)
        (paralelas_vistas contenido_70)
        (paralelas_vistas contenido_59)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_42)
        (paralelas_vistas contenido_73)
        (paralelas_vistas contenido_16)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_56)
        (paralelas_vistas contenido_43)
        (paralelas_vistas contenido_66)
        (paralelas_vistas contenido_49)
        (paralelas_vistas contenido_74)
        (paralelas_vistas contenido_19)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_64)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_31)
        (paralelas_vistas contenido_41)
        (paralelas_vistas contenido_61)
        (paralelas_vistas contenido_55)
        (paralelas_vistas contenido_34)
        (paralelas_vistas contenido_40)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_51)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_46)
        (paralelas_vistas contenido_68)
        (paralelas_vistas contenido_63)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_69)
        (paralelas_vistas contenido_72)
        (paralelas_vistas contenido_71)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_75)
        (paralelas_vistas contenido_45)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_17)
        (final contenido_17)
        (final contenido_21)
        (final contenido_24)
        (final contenido_28)
        (final contenido_31)
        (final contenido_33)
        (final contenido_34)
        (final contenido_42)
        (final contenido_43)
        (final contenido_46)
        (final contenido_49)
        (final contenido_51)
        (final contenido_53)
        (final contenido_55)
        (final contenido_56)
        (final contenido_57)
        (final contenido_59)
        (final contenido_61)
        (final contenido_63)
        (final contenido_65)
        (final contenido_66)
        (final contenido_68)
        (final contenido_69)
        (final contenido_70)
        (final contenido_71)
        (final contenido_72)
        (final contenido_73)
        (final contenido_74)
        (final contenido_75)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
