(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125 contenido_126 contenido_127 contenido_128 contenido_129 contenido_130 contenido_131 contenido_132 contenido_133 contenido_134 contenido_135 contenido_136 contenido_137 contenido_138 contenido_139 contenido_140 contenido_141 contenido_142 contenido_143 contenido_144 contenido_145 contenido_146 contenido_147 contenido_148 contenido_149 contenido_150 contenido_151 contenido_152 contenido_153 contenido_154 contenido_155 contenido_156 contenido_157 contenido_158 contenido_159 contenido_160 contenido_161 contenido_162 contenido_163 contenido_164 contenido_165 contenido_166 contenido_167 contenido_168 contenido_169 contenido_170 contenido_171 contenido_172 contenido_173 contenido_174 contenido_175
    )

    (:init
        (predecesor contenido_77 contenido_175)
        (predecesor contenido_98 contenido_151)
        (predecesor contenido_50 contenido_114)
        (predecesor contenido_96 contenido_107)
        (predecesor contenido_8 contenido_115)
        (predecesor contenido_11 contenido_46)
        (predecesor contenido_93 contenido_154)
        (predecesor contenido_72 contenido_138)
        (predecesor contenido_132 contenido_149)
        (predecesor contenido_19 contenido_21)
        (predecesor contenido_117 contenido_136)
        (predecesor contenido_19 contenido_110)
        (predecesor contenido_7 contenido_129)
        (predecesor contenido_45 contenido_97)
        (predecesor contenido_18 contenido_69)
        (predecesor contenido_123 contenido_128)
        (predecesor contenido_116 contenido_156)
        (predecesor contenido_84 contenido_133)
        (predecesor contenido_35 contenido_69)
        (predecesor contenido_126 contenido_139)
        (predecesor contenido_20 contenido_143)
        (predecesor contenido_91 contenido_151)
        (predecesor contenido_67 contenido_109)
        (predecesor contenido_113 contenido_133)
        (predecesor contenido_67 contenido_72)
        (predecesor contenido_44 contenido_133)
        (predecesor contenido_102 contenido_105)
        (predecesor contenido_11 contenido_107)
        (predecesor contenido_89 contenido_134)
        (predecesor contenido_86 contenido_154)
        (predecesor contenido_40 contenido_128)
        (predecesor contenido_48 contenido_107)
        (predecesor contenido_22 contenido_135)
        (predecesor contenido_38 contenido_125)
        (predecesor contenido_19 contenido_137)
        (predecesor contenido_61 contenido_93)
        (predecesor contenido_20 contenido_151)
        (predecesor contenido_2 contenido_86)
        (predecesor contenido_91 contenido_112)
        (predecesor contenido_41 contenido_42)
        (predecesor contenido_81 contenido_155)
        (predecesor contenido_144 contenido_145)
        (predecesor contenido_12 contenido_70)
        (predecesor contenido_48 contenido_103)
        (predecesor contenido_18 contenido_95)
        (predecesor contenido_26 contenido_91)
        (predecesor contenido_172 contenido_173)
        (predecesor contenido_7 contenido_141)
        (predecesor contenido_89 contenido_166)
        (predecesor contenido_111 contenido_121)
        (predecesor contenido_55 contenido_77)
        (predecesor contenido_137 contenido_147)
        (predecesor contenido_97 contenido_102)
        (predecesor contenido_104 contenido_141)
        (predecesor contenido_3 contenido_75)
        (predecesor contenido_71 contenido_170)
        (predecesor contenido_38 contenido_97)
        (predecesor contenido_8 contenido_102)
        (predecesor contenido_111 contenido_114)
        (predecesor contenido_49 contenido_156)
        (predecesor contenido_82 contenido_157)
        (predecesor contenido_125 contenido_149)
        (predecesor contenido_78 contenido_132)
        (predecesor contenido_121 contenido_125)
        (predecesor contenido_83 contenido_88)
        (predecesor contenido_92 contenido_152)
        (predecesor contenido_9 contenido_60)
        (predecesor contenido_1 contenido_19)
        (predecesor contenido_85 contenido_145)
        (predecesor contenido_64 contenido_74)
        (predecesor contenido_17 contenido_78)
        (predecesor contenido_10 contenido_57)
        (predecesor contenido_11 contenido_96)
        (predecesor contenido_120 contenido_122)
        (predecesor contenido_41 contenido_170)
        (predecesor contenido_13 contenido_74)
        (predecesor contenido_88 contenido_150)
        (predecesor contenido_91 contenido_161)
        (predecesor contenido_112 contenido_148)
        (predecesor contenido_12 contenido_155)
        (predecesor contenido_63 contenido_66)
        (predecesor contenido_17 contenido_36)
        (predecesor contenido_90 contenido_127)
        (predecesor contenido_12 contenido_54)
        (predecesor contenido_137 contenido_160)
        (predecesor contenido_2 contenido_24)
        (predecesor contenido_10 contenido_171)
        (predecesor contenido_82 contenido_114)
        (predecesor contenido_137 contenido_157)
        (predecesor contenido_29 contenido_136)
        (predecesor contenido_25 contenido_140)
        (predecesor contenido_125 contenido_154)
        (predecesor contenido_120 contenido_170)
        (predecesor contenido_87 contenido_131)
        (predecesor contenido_67 contenido_148)
        (predecesor contenido_10 contenido_56)
        (predecesor contenido_18 contenido_84)
        (predecesor contenido_122 contenido_173)
        (predecesor contenido_77 contenido_110)
        (predecesor contenido_81 contenido_133)
        (predecesor contenido_105 contenido_136)
        (predecesor contenido_18 contenido_154)
        (predecesor contenido_40 contenido_162)
        (predecesor contenido_41 contenido_149)
        (predecesor contenido_14 contenido_90)
        (predecesor contenido_17 contenido_171)
        (predecesor contenido_12 contenido_121)
        (predecesor contenido_21 contenido_76)
        (predecesor contenido_53 contenido_132)
        (predecesor contenido_50 contenido_157)
        (predecesor contenido_37 contenido_122)
        (predecesor contenido_38 contenido_140)
        (predecesor contenido_83 contenido_115)
        (predecesor contenido_169 contenido_175)
        (predecesor contenido_72 contenido_81)
        (predecesor contenido_79 contenido_117)
        (predecesor contenido_7 contenido_89)
        (predecesor contenido_4 contenido_129)
        (predecesor contenido_38 contenido_137)
        (predecesor contenido_81 contenido_150)
        (predecesor contenido_155 contenido_159)
        (predecesor contenido_19 contenido_86)
        (predecesor contenido_17 contenido_19)
        (predecesor contenido_91 contenido_137)
        (predecesor contenido_1 contenido_140)
        (predecesor contenido_98 contenido_125)
        (predecesor contenido_37 contenido_172)
        (predecesor contenido_79 contenido_152)
        (predecesor contenido_41 contenido_73)
        (predecesor contenido_38 contenido_101)
        (predecesor contenido_118 contenido_129)
        (predecesor contenido_94 contenido_122)
        (predecesor contenido_63 contenido_166)
        (predecesor contenido_23 contenido_38)
        (predecesor contenido_57 contenido_90)
        (predecesor contenido_103 contenido_149)
        (predecesor contenido_140 contenido_154)
        (predecesor contenido_15 contenido_174)
        (predecesor contenido_123 contenido_132)
        (predecesor contenido_16 contenido_164)
        (paralela contenido_49 contenido_124)
        (paralela contenido_124 contenido_49)
        (paralela contenido_49 contenido_48)
        (paralela contenido_48 contenido_49)
        (paralela contenido_49 contenido_111)
        (paralela contenido_111 contenido_49)
        (paralela contenido_49 contenido_25)
        (paralela contenido_25 contenido_49)
        (paralela contenido_49 contenido_146)
        (paralela contenido_146 contenido_49)
        (paralela contenido_124 contenido_48)
        (paralela contenido_48 contenido_124)
        (paralela contenido_124 contenido_111)
        (paralela contenido_111 contenido_124)
        (paralela contenido_124 contenido_25)
        (paralela contenido_25 contenido_124)
        (paralela contenido_124 contenido_146)
        (paralela contenido_146 contenido_124)
        (paralela contenido_48 contenido_111)
        (paralela contenido_111 contenido_48)
        (paralela contenido_48 contenido_25)
        (paralela contenido_25 contenido_48)
        (paralela contenido_48 contenido_146)
        (paralela contenido_146 contenido_48)
        (paralela contenido_111 contenido_25)
        (paralela contenido_25 contenido_111)
        (paralela contenido_111 contenido_146)
        (paralela contenido_146 contenido_111)
        (paralela contenido_25 contenido_146)
        (paralela contenido_146 contenido_25)
        (paralela contenido_50 contenido_16)
        (paralela contenido_16 contenido_50)
        (paralela contenido_50 contenido_80)
        (paralela contenido_80 contenido_50)
        (paralela contenido_50 contenido_108)
        (paralela contenido_108 contenido_50)
        (paralela contenido_50 contenido_11)
        (paralela contenido_11 contenido_50)
        (paralela contenido_50 contenido_31)
        (paralela contenido_31 contenido_50)
        (paralela contenido_16 contenido_80)
        (paralela contenido_80 contenido_16)
        (paralela contenido_16 contenido_108)
        (paralela contenido_108 contenido_16)
        (paralela contenido_16 contenido_11)
        (paralela contenido_11 contenido_16)
        (paralela contenido_16 contenido_31)
        (paralela contenido_31 contenido_16)
        (paralela contenido_80 contenido_108)
        (paralela contenido_108 contenido_80)
        (paralela contenido_80 contenido_11)
        (paralela contenido_11 contenido_80)
        (paralela contenido_80 contenido_31)
        (paralela contenido_31 contenido_80)
        (paralela contenido_108 contenido_11)
        (paralela contenido_11 contenido_108)
        (paralela contenido_108 contenido_31)
        (paralela contenido_31 contenido_108)
        (paralela contenido_11 contenido_31)
        (paralela contenido_31 contenido_11)
        (paralela contenido_47 contenido_12)
        (paralela contenido_12 contenido_47)
        (paralela contenido_47 contenido_98)
        (paralela contenido_98 contenido_47)
        (paralela contenido_47 contenido_58)
        (paralela contenido_58 contenido_47)
        (paralela contenido_47 contenido_33)
        (paralela contenido_33 contenido_47)
        (paralela contenido_47 contenido_99)
        (paralela contenido_99 contenido_47)
        (paralela contenido_12 contenido_98)
        (paralela contenido_98 contenido_12)
        (paralela contenido_12 contenido_58)
        (paralela contenido_58 contenido_12)
        (paralela contenido_12 contenido_33)
        (paralela contenido_33 contenido_12)
        (paralela contenido_12 contenido_99)
        (paralela contenido_99 contenido_12)
        (paralela contenido_98 contenido_58)
        (paralela contenido_58 contenido_98)
        (paralela contenido_98 contenido_33)
        (paralela contenido_33 contenido_98)
        (paralela contenido_98 contenido_99)
        (paralela contenido_99 contenido_98)
        (paralela contenido_58 contenido_33)
        (paralela contenido_33 contenido_58)
        (paralela contenido_58 contenido_99)
        (paralela contenido_99 contenido_58)
        (paralela contenido_33 contenido_99)
        (paralela contenido_99 contenido_33)
        (paralela contenido_165 contenido_35)
        (paralela contenido_35 contenido_165)
        (paralela contenido_165 contenido_71)
        (paralela contenido_71 contenido_165)
        (paralela contenido_165 contenido_2)
        (paralela contenido_2 contenido_165)
        (paralela contenido_165 contenido_14)
        (paralela contenido_14 contenido_165)
        (paralela contenido_165 contenido_7)
        (paralela contenido_7 contenido_165)
        (paralela contenido_35 contenido_71)
        (paralela contenido_71 contenido_35)
        (paralela contenido_35 contenido_2)
        (paralela contenido_2 contenido_35)
        (paralela contenido_35 contenido_14)
        (paralela contenido_14 contenido_35)
        (paralela contenido_35 contenido_7)
        (paralela contenido_7 contenido_35)
        (paralela contenido_71 contenido_2)
        (paralela contenido_2 contenido_71)
        (paralela contenido_71 contenido_14)
        (paralela contenido_14 contenido_71)
        (paralela contenido_71 contenido_7)
        (paralela contenido_7 contenido_71)
        (paralela contenido_2 contenido_14)
        (paralela contenido_14 contenido_2)
        (paralela contenido_2 contenido_7)
        (paralela contenido_7 contenido_2)
        (paralela contenido_14 contenido_7)
        (paralela contenido_7 contenido_14)
        (paralela contenido_163 contenido_94)
        (paralela contenido_94 contenido_163)
        (paralela contenido_163 contenido_55)
        (paralela contenido_55 contenido_163)
        (paralela contenido_163 contenido_65)
        (paralela contenido_65 contenido_163)
        (paralela contenido_163 contenido_82)
        (paralela contenido_82 contenido_163)
        (paralela contenido_163 contenido_28)
        (paralela contenido_28 contenido_163)
        (paralela contenido_94 contenido_55)
        (paralela contenido_55 contenido_94)
        (paralela contenido_94 contenido_65)
        (paralela contenido_65 contenido_94)
        (paralela contenido_94 contenido_82)
        (paralela contenido_82 contenido_94)
        (paralela contenido_94 contenido_28)
        (paralela contenido_28 contenido_94)
        (paralela contenido_55 contenido_65)
        (paralela contenido_65 contenido_55)
        (paralela contenido_55 contenido_82)
        (paralela contenido_82 contenido_55)
        (paralela contenido_55 contenido_28)
        (paralela contenido_28 contenido_55)
        (paralela contenido_65 contenido_82)
        (paralela contenido_82 contenido_65)
        (paralela contenido_65 contenido_28)
        (paralela contenido_28 contenido_65)
        (paralela contenido_82 contenido_28)
        (paralela contenido_28 contenido_82)
        (paralela contenido_37 contenido_23)
        (paralela contenido_23 contenido_37)
        (paralela contenido_37 contenido_62)
        (paralela contenido_62 contenido_37)
        (paralela contenido_37 contenido_120)
        (paralela contenido_120 contenido_37)
        (paralela contenido_37 contenido_29)
        (paralela contenido_29 contenido_37)
        (paralela contenido_37 contenido_5)
        (paralela contenido_5 contenido_37)
        (paralela contenido_23 contenido_62)
        (paralela contenido_62 contenido_23)
        (paralela contenido_23 contenido_120)
        (paralela contenido_120 contenido_23)
        (paralela contenido_23 contenido_29)
        (paralela contenido_29 contenido_23)
        (paralela contenido_23 contenido_5)
        (paralela contenido_5 contenido_23)
        (paralela contenido_62 contenido_120)
        (paralela contenido_120 contenido_62)
        (paralela contenido_62 contenido_29)
        (paralela contenido_29 contenido_62)
        (paralela contenido_62 contenido_5)
        (paralela contenido_5 contenido_62)
        (paralela contenido_120 contenido_29)
        (paralela contenido_29 contenido_120)
        (paralela contenido_120 contenido_5)
        (paralela contenido_5 contenido_120)
        (paralela contenido_29 contenido_5)
        (paralela contenido_5 contenido_29)
        (paralela contenido_45 contenido_104)
        (paralela contenido_104 contenido_45)
        (paralela contenido_45 contenido_106)
        (paralela contenido_106 contenido_45)
        (paralela contenido_45 contenido_6)
        (paralela contenido_6 contenido_45)
        (paralela contenido_45 contenido_30)
        (paralela contenido_30 contenido_45)
        (paralela contenido_45 contenido_41)
        (paralela contenido_41 contenido_45)
        (paralela contenido_104 contenido_106)
        (paralela contenido_106 contenido_104)
        (paralela contenido_104 contenido_6)
        (paralela contenido_6 contenido_104)
        (paralela contenido_104 contenido_30)
        (paralela contenido_30 contenido_104)
        (paralela contenido_104 contenido_41)
        (paralela contenido_41 contenido_104)
        (paralela contenido_106 contenido_6)
        (paralela contenido_6 contenido_106)
        (paralela contenido_106 contenido_30)
        (paralela contenido_30 contenido_106)
        (paralela contenido_106 contenido_41)
        (paralela contenido_41 contenido_106)
        (paralela contenido_6 contenido_30)
        (paralela contenido_30 contenido_6)
        (paralela contenido_6 contenido_41)
        (paralela contenido_41 contenido_6)
        (paralela contenido_30 contenido_41)
        (paralela contenido_41 contenido_30)
        (paralela contenido_64 contenido_83)
        (paralela contenido_83 contenido_64)
        (paralela contenido_64 contenido_27)
        (paralela contenido_27 contenido_64)
        (paralela contenido_64 contenido_17)
        (paralela contenido_17 contenido_64)
        (paralela contenido_64 contenido_53)
        (paralela contenido_53 contenido_64)
        (paralela contenido_64 contenido_167)
        (paralela contenido_167 contenido_64)
        (paralela contenido_83 contenido_27)
        (paralela contenido_27 contenido_83)
        (paralela contenido_83 contenido_17)
        (paralela contenido_17 contenido_83)
        (paralela contenido_83 contenido_53)
        (paralela contenido_53 contenido_83)
        (paralela contenido_83 contenido_167)
        (paralela contenido_167 contenido_83)
        (paralela contenido_27 contenido_17)
        (paralela contenido_17 contenido_27)
        (paralela contenido_27 contenido_53)
        (paralela contenido_53 contenido_27)
        (paralela contenido_27 contenido_167)
        (paralela contenido_167 contenido_27)
        (paralela contenido_17 contenido_53)
        (paralela contenido_53 contenido_17)
        (paralela contenido_17 contenido_167)
        (paralela contenido_167 contenido_17)
        (paralela contenido_53 contenido_167)
        (paralela contenido_167 contenido_53)
        (paralela contenido_116 contenido_92)
        (paralela contenido_92 contenido_116)
        (paralela contenido_116 contenido_87)
        (paralela contenido_87 contenido_116)
        (paralela contenido_116 contenido_15)
        (paralela contenido_15 contenido_116)
        (paralela contenido_116 contenido_39)
        (paralela contenido_39 contenido_116)
        (paralela contenido_116 contenido_118)
        (paralela contenido_118 contenido_116)
        (paralela contenido_92 contenido_87)
        (paralela contenido_87 contenido_92)
        (paralela contenido_92 contenido_15)
        (paralela contenido_15 contenido_92)
        (paralela contenido_92 contenido_39)
        (paralela contenido_39 contenido_92)
        (paralela contenido_92 contenido_118)
        (paralela contenido_118 contenido_92)
        (paralela contenido_87 contenido_15)
        (paralela contenido_15 contenido_87)
        (paralela contenido_87 contenido_39)
        (paralela contenido_39 contenido_87)
        (paralela contenido_87 contenido_118)
        (paralela contenido_118 contenido_87)
        (paralela contenido_15 contenido_39)
        (paralela contenido_39 contenido_15)
        (paralela contenido_15 contenido_118)
        (paralela contenido_118 contenido_15)
        (paralela contenido_39 contenido_118)
        (paralela contenido_118 contenido_39)
        (paralelas_vistas contenido_103)
        (paralelas_vistas contenido_96)
        (paralelas_vistas contenido_125)
        (paralelas_vistas contenido_70)
        (paralelas_vistas contenido_169)
        (paralelas_vistas contenido_136)
        (paralelas_vistas contenido_140)
        (paralelas_vistas contenido_112)
        (paralelas_vistas contenido_166)
        (paralelas_vistas contenido_95)
        (paralelas_vistas contenido_121)
        (paralelas_vistas contenido_78)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_171)
        (paralelas_vistas contenido_133)
        (paralelas_vistas contenido_69)
        (paralelas_vistas contenido_59)
        (paralelas_vistas contenido_130)
        (paralelas_vistas contenido_88)
        (paralelas_vistas contenido_159)
        (paralelas_vistas contenido_72)
        (paralelas_vistas contenido_162)
        (paralelas_vistas contenido_134)
        (paralelas_vistas contenido_148)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_115)
        (paralelas_vistas contenido_149)
        (paralelas_vistas contenido_109)
        (paralelas_vistas contenido_100)
        (paralelas_vistas contenido_144)
        (paralelas_vistas contenido_56)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_152)
        (paralelas_vistas contenido_157)
        (paralelas_vistas contenido_36)
        (paralelas_vistas contenido_114)
        (paralelas_vistas contenido_79)
        (paralelas_vistas contenido_174)
        (paralelas_vistas contenido_46)
        (paralelas_vistas contenido_86)
        (paralelas_vistas contenido_123)
        (paralelas_vistas contenido_161)
        (paralelas_vistas contenido_131)
        (paralelas_vistas contenido_113)
        (paralelas_vistas contenido_61)
        (paralelas_vistas contenido_155)
        (paralelas_vistas contenido_168)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_89)
        (paralelas_vistas contenido_32)
        (paralelas_vistas contenido_26)
        (paralelas_vistas contenido_132)
        (paralelas_vistas contenido_93)
        (paralelas_vistas contenido_91)
        (paralelas_vistas contenido_153)
        (paralelas_vistas contenido_172)
        (paralelas_vistas contenido_77)
        (paralelas_vistas contenido_175)
        (paralelas_vistas contenido_128)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_101)
        (paralelas_vistas contenido_107)
        (paralelas_vistas contenido_40)
        (paralelas_vistas contenido_66)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_173)
        (paralelas_vistas contenido_145)
        (paralelas_vistas contenido_38)
        (paralelas_vistas contenido_117)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_105)
        (paralelas_vistas contenido_102)
        (paralelas_vistas contenido_74)
        (paralelas_vistas contenido_142)
        (paralelas_vistas contenido_19)
        (paralelas_vistas contenido_75)
        (paralelas_vistas contenido_44)
        (paralelas_vistas contenido_57)
        (paralelas_vistas contenido_143)
        (paralelas_vistas contenido_76)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_137)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_119)
        (paralelas_vistas contenido_158)
        (paralelas_vistas contenido_97)
        (paralelas_vistas contenido_34)
        (paralelas_vistas contenido_60)
        (paralelas_vistas contenido_170)
        (paralelas_vistas contenido_138)
        (paralelas_vistas contenido_129)
        (paralelas_vistas contenido_127)
        (paralelas_vistas contenido_150)
        (paralelas_vistas contenido_85)
        (paralelas_vistas contenido_135)
        (paralelas_vistas contenido_51)
        (paralelas_vistas contenido_139)
        (paralelas_vistas contenido_160)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_67)
        (paralelas_vistas contenido_147)
        (paralelas_vistas contenido_141)
        (paralelas_vistas contenido_9)
        (paralelas_vistas contenido_164)
        (paralelas_vistas contenido_52)
        (paralelas_vistas contenido_68)
        (paralelas_vistas contenido_63)
        (paralelas_vistas contenido_42)
        (paralelas_vistas contenido_90)
        (paralelas_vistas contenido_43)
        (paralelas_vistas contenido_154)
        (paralelas_vistas contenido_156)
        (paralelas_vistas contenido_81)
        (paralelas_vistas contenido_151)
        (paralelas_vistas contenido_122)
        (paralelas_vistas contenido_84)
        (paralelas_vistas contenido_126)
        (paralelas_vistas contenido_110)
        (paralelas_vistas contenido_54)
        (paralelas_vistas contenido_73)
        (predecesores_vistos contenido_169)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_59)
        (predecesores_vistos contenido_130)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_100)
        (predecesores_vistos contenido_144)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_79)
        (predecesores_vistos contenido_123)
        (predecesores_vistos contenido_113)
        (predecesores_vistos contenido_61)
        (predecesores_vistos contenido_168)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_153)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_142)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_119)
        (predecesores_vistos contenido_158)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_85)
        (predecesores_vistos contenido_51)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_67)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_52)
        (predecesores_vistos contenido_68)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_43)
        (predecesores_vistos contenido_126)
        (final contenido_24)
        (final contenido_32)
        (final contenido_34)
        (final contenido_36)
        (final contenido_42)
        (final contenido_43)
        (final contenido_46)
        (final contenido_51)
        (final contenido_52)
        (final contenido_54)
        (final contenido_56)
        (final contenido_59)
        (final contenido_60)
        (final contenido_66)
        (final contenido_68)
        (final contenido_69)
        (final contenido_70)
        (final contenido_73)
        (final contenido_74)
        (final contenido_75)
        (final contenido_76)
        (final contenido_95)
        (final contenido_100)
        (final contenido_101)
        (final contenido_107)
        (final contenido_109)
        (final contenido_110)
        (final contenido_114)
        (final contenido_115)
        (final contenido_119)
        (final contenido_127)
        (final contenido_128)
        (final contenido_129)
        (final contenido_130)
        (final contenido_131)
        (final contenido_133)
        (final contenido_134)
        (final contenido_135)
        (final contenido_136)
        (final contenido_138)
        (final contenido_139)
        (final contenido_141)
        (final contenido_142)
        (final contenido_143)
        (final contenido_145)
        (final contenido_147)
        (final contenido_148)
        (final contenido_149)
        (final contenido_150)
        (final contenido_151)
        (final contenido_152)
        (final contenido_153)
        (final contenido_154)
        (final contenido_156)
        (final contenido_157)
        (final contenido_158)
        (final contenido_159)
        (final contenido_160)
        (final contenido_161)
        (final contenido_162)
        (final contenido_164)
        (final contenido_166)
        (final contenido_168)
        (final contenido_170)
        (final contenido_171)
        (final contenido_173)
        (final contenido_174)
        (final contenido_175)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
