(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100
    )

    (:init
        (predecesor contenido_19 contenido_86)
        (predecesor contenido_59 contenido_68)
        (predecesor contenido_62 contenido_64)
        (predecesor contenido_5 contenido_86)
        (predecesor contenido_43 contenido_45)
        (predecesor contenido_43 contenido_73)
        (predecesor contenido_28 contenido_39)
        (predecesor contenido_27 contenido_66)
        (predecesor contenido_3 contenido_45)
        (predecesor contenido_41 contenido_88)
        (predecesor contenido_9 contenido_86)
        (predecesor contenido_29 contenido_65)
        (predecesor contenido_6 contenido_61)
        (predecesor contenido_54 contenido_56)
        (predecesor contenido_21 contenido_37)
        (predecesor contenido_19 contenido_91)
        (predecesor contenido_11 contenido_51)
        (predecesor contenido_34 contenido_90)
        (predecesor contenido_19 contenido_69)
        (predecesor contenido_32 contenido_33)
        (predecesor contenido_9 contenido_92)
        (predecesor contenido_17 contenido_91)
        (predecesor contenido_69 contenido_81)
        (predecesor contenido_27 contenido_87)
        (predecesor contenido_2 contenido_65)
        (predecesor contenido_62 contenido_79)
        (predecesor contenido_38 contenido_73)
        (predecesor contenido_1 contenido_10)
        (predecesor contenido_52 contenido_73)
        (predecesor contenido_66 contenido_75)
        (predecesor contenido_50 contenido_98)
        (predecesor contenido_10 contenido_69)
        (predecesor contenido_27 contenido_39)
        (predecesor contenido_64 contenido_99)
        (predecesor contenido_39 contenido_55)
        (predecesor contenido_25 contenido_91)
        (predecesor contenido_45 contenido_57)
        (predecesor contenido_4 contenido_51)
        (predecesor contenido_7 contenido_10)
        (predecesor contenido_36 contenido_53)
        (predecesor contenido_42 contenido_58)
        (predecesor contenido_23 contenido_75)
        (predecesor contenido_63 contenido_75)
        (predecesor contenido_59 contenido_65)
        (predecesor contenido_36 contenido_85)
        (predecesor contenido_6 contenido_27)
        (predecesor contenido_60 contenido_61)
        (predecesor contenido_30 contenido_100)
        (predecesor contenido_6 contenido_35)
        (predecesor contenido_6 contenido_73)
        (predecesor contenido_24 contenido_52)
        (predecesor contenido_18 contenido_69)
        (predecesor contenido_6 contenido_54)
        (predecesor contenido_29 contenido_45)
        (predecesor contenido_12 contenido_24)
        (predecesor contenido_1 contenido_43)
        (predecesor contenido_41 contenido_67)
        (predecesor contenido_13 contenido_51)
        (predecesor contenido_36 contenido_68)
        (predecesor contenido_10 contenido_89)
        (predecesor contenido_12 contenido_90)
        (predecesor contenido_1 contenido_86)
        (predecesor contenido_89 contenido_100)
        (predecesor contenido_22 contenido_65)
        (predecesor contenido_31 contenido_47)
        (predecesor contenido_18 contenido_76)
        (predecesor contenido_32 contenido_89)
        (predecesor contenido_39 contenido_88)
        (predecesor contenido_40 contenido_59)
        (predecesor contenido_22 contenido_67)
        (predecesor contenido_45 contenido_64)
        (predecesor contenido_15 contenido_90)
        (predecesor contenido_13 contenido_99)
        (predecesor contenido_3 contenido_4)
        (predecesor contenido_42 contenido_59)
        (predecesor contenido_61 contenido_85)
        (predecesor contenido_19 contenido_70)
        (predecesor contenido_15 contenido_68)
        (predecesor contenido_20 contenido_93)
        (predecesor contenido_12 contenido_75)
        (predecesor contenido_9 contenido_77)
        (predecesor contenido_4 contenido_47)
        (predecesor contenido_44 contenido_75)
        (predecesor contenido_57 contenido_94)
        (predecesor contenido_46 contenido_56)
        (predecesor contenido_8 contenido_46)
        (predecesor contenido_45 contenido_99)
        (predecesor contenido_6 contenido_23)
        (predecesor contenido_27 contenido_44)
        (predecesor contenido_25 contenido_66)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_9)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_66)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_37)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_84)
        (paralelas_vistas contenido_32)
        (paralelas_vistas contenido_56)
        (paralelas_vistas contenido_43)
        (paralelas_vistas contenido_98)
        (paralelas_vistas contenido_96)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_74)
        (paralelas_vistas contenido_73)
        (paralelas_vistas contenido_57)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_86)
        (paralelas_vistas contenido_70)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_35)
        (paralelas_vistas contenido_41)
        (paralelas_vistas contenido_61)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_88)
        (paralelas_vistas contenido_16)
        (paralelas_vistas contenido_87)
        (paralelas_vistas contenido_67)
        (paralelas_vistas contenido_77)
        (paralelas_vistas contenido_81)
        (paralelas_vistas contenido_30)
        (paralelas_vistas contenido_63)
        (paralelas_vistas contenido_89)
        (paralelas_vistas contenido_65)
        (paralelas_vistas contenido_5)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_39)
        (paralelas_vistas contenido_25)
        (paralelas_vistas contenido_26)
        (paralelas_vistas contenido_94)
        (paralelas_vistas contenido_46)
        (paralelas_vistas contenido_80)
        (paralelas_vistas contenido_76)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_82)
        (paralelas_vistas contenido_75)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_48)
        (paralelas_vistas contenido_92)
        (paralelas_vistas contenido_27)
        (paralelas_vistas contenido_59)
        (paralelas_vistas contenido_36)
        (paralelas_vistas contenido_68)
        (paralelas_vistas contenido_31)
        (paralelas_vistas contenido_42)
        (paralelas_vistas contenido_28)
        (paralelas_vistas contenido_71)
        (paralelas_vistas contenido_62)
        (paralelas_vistas contenido_60)
        (paralelas_vistas contenido_6)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_79)
        (paralelas_vistas contenido_72)
        (paralelas_vistas contenido_97)
        (paralelas_vistas contenido_45)
        (paralelas_vistas contenido_58)
        (paralelas_vistas contenido_34)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_11)
        (paralelas_vistas contenido_78)
        (paralelas_vistas contenido_40)
        (paralelas_vistas contenido_83)
        (paralelas_vistas contenido_85)
        (paralelas_vistas contenido_49)
        (paralelas_vistas contenido_64)
        (paralelas_vistas contenido_47)
        (paralelas_vistas contenido_91)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_100)
        (paralelas_vistas contenido_52)
        (paralelas_vistas contenido_29)
        (paralelas_vistas contenido_53)
        (paralelas_vistas contenido_54)
        (paralelas_vistas contenido_69)
        (paralelas_vistas contenido_93)
        (paralelas_vistas contenido_55)
        (paralelas_vistas contenido_99)
        (paralelas_vistas contenido_95)
        (paralelas_vistas contenido_50)
        (paralelas_vistas contenido_44)
        (paralelas_vistas contenido_51)
        (paralelas_vistas contenido_19)
        (paralelas_vistas contenido_38)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_90)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_78)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_41)
        (predecesores_vistos contenido_83)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_49)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_82)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_84)
        (predecesores_vistos contenido_36)
        (predecesores_vistos contenido_95)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_50)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_71)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_74)
        (predecesores_vistos contenido_62)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_60)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_96)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_38)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_80)
        (predecesores_vistos contenido_97)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_2)
        (final contenido_14)
        (final contenido_16)
        (final contenido_26)
        (final contenido_33)
        (final contenido_35)
        (final contenido_37)
        (final contenido_47)
        (final contenido_48)
        (final contenido_49)
        (final contenido_51)
        (final contenido_53)
        (final contenido_55)
        (final contenido_56)
        (final contenido_58)
        (final contenido_65)
        (final contenido_67)
        (final contenido_68)
        (final contenido_70)
        (final contenido_71)
        (final contenido_72)
        (final contenido_73)
        (final contenido_74)
        (final contenido_75)
        (final contenido_76)
        (final contenido_77)
        (final contenido_78)
        (final contenido_79)
        (final contenido_80)
        (final contenido_81)
        (final contenido_82)
        (final contenido_83)
        (final contenido_84)
        (final contenido_85)
        (final contenido_86)
        (final contenido_87)
        (final contenido_88)
        (final contenido_90)
        (final contenido_91)
        (final contenido_92)
        (final contenido_93)
        (final contenido_94)
        (final contenido_95)
        (final contenido_96)
        (final contenido_97)
        (final contenido_98)
        (final contenido_99)
        (final contenido_100)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
