(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125
    )

    (:init
        (predecesor contenido_6 contenido_35)
        (predecesor contenido_7 contenido_115)
        (predecesor contenido_100 contenido_107)
        (predecesor contenido_43 contenido_73)
        (predecesor contenido_37 contenido_76)
        (predecesor contenido_94 contenido_100)
        (predecesor contenido_69 contenido_80)
        (predecesor contenido_48 contenido_84)
        (predecesor contenido_12 contenido_98)
        (predecesor contenido_1 contenido_86)
        (predecesor contenido_36 contenido_68)
        (predecesor contenido_3 contenido_45)
        (predecesor contenido_117 contenido_121)
        (predecesor contenido_10 contenido_62)
        (predecesor contenido_19 contenido_69)
        (predecesor contenido_65 contenido_89)
        (predecesor contenido_37 contenido_103)
        (predecesor contenido_39 contenido_88)
        (predecesor contenido_99 contenido_122)
        (predecesor contenido_11 contenido_98)
        (predecesor contenido_39 contenido_123)
        (predecesor contenido_87 contenido_122)
        (predecesor contenido_113 contenido_124)
        (predecesor contenido_45 contenido_65)
        (predecesor contenido_22 contenido_49)
        (predecesor contenido_10 contenido_76)
        (predecesor contenido_69 contenido_81)
        (predecesor contenido_46 contenido_56)
        (predecesor contenido_66 contenido_114)
        (predecesor contenido_47 contenido_120)
        (predecesor contenido_64 contenido_117)
        (predecesor contenido_9 contenido_92)
        (predecesor contenido_4 contenido_120)
        (predecesor contenido_90 contenido_104)
        (predecesor contenido_19 contenido_118)
        (predecesor contenido_120 contenido_121)
        (predecesor contenido_85 contenido_104)
        (predecesor contenido_15 contenido_90)
        (predecesor contenido_40 contenido_121)
        (predecesor contenido_22 contenido_57)
        (predecesor contenido_75 contenido_117)
        (predecesor contenido_15 contenido_123)
        (predecesor contenido_4 contenido_47)
        (predecesor contenido_34 contenido_90)
        (predecesor contenido_60 contenido_61)
        (predecesor contenido_67 contenido_105)
        (predecesor contenido_3 contenido_88)
        (predecesor contenido_10 contenido_69)
        (predecesor contenido_45 contenido_99)
        (predecesor contenido_7 contenido_45)
        (predecesor contenido_22 contenido_117)
        (predecesor contenido_4 contenido_101)
        (predecesor contenido_112 contenido_118)
        (predecesor contenido_9 contenido_77)
        (predecesor contenido_114 contenido_116)
        (predecesor contenido_88 contenido_106)
        (predecesor contenido_65 contenido_107)
        (predecesor contenido_6 contenido_23)
        (predecesor contenido_67 contenido_119)
        (predecesor contenido_62 contenido_64)
        (predecesor contenido_75 contenido_105)
        (predecesor contenido_33 contenido_83)
        (predecesor contenido_27 contenido_125)
        (predecesor contenido_84 contenido_120)
        (predecesor contenido_65 contenido_97)
        (predecesor contenido_92 contenido_108)
        (predecesor contenido_12 contenido_24)
        (predecesor contenido_49 contenido_120)
        (predecesor contenido_41 contenido_67)
        (predecesor contenido_52 contenido_81)
        (predecesor contenido_58 contenido_93)
        (predecesor contenido_49 contenido_105)
        (predecesor contenido_10 contenido_72)
        (predecesor contenido_77 contenido_113)
        (predecesor contenido_14 contenido_107)
        (predecesor contenido_14 contenido_90)
        (predecesor contenido_10 contenido_11)
        (predecesor contenido_54 contenido_56)
        (predecesor contenido_23 contenido_122)
        (predecesor contenido_34 contenido_36)
        (predecesor contenido_55 contenido_108)
        (predecesor contenido_66 contenido_105)
        (predecesor contenido_39 contenido_62)
        (predecesor contenido_86 contenido_89)
        (predecesor contenido_1 contenido_12)
        (predecesor contenido_12 contenido_102)
        (predecesor contenido_18 contenido_113)
        (predecesor contenido_68 contenido_76)
        (predecesor contenido_13 contenido_51)
        (predecesor contenido_32 contenido_89)
        (predecesor contenido_63 contenido_117)
        (predecesor contenido_11 contenido_84)
        (predecesor contenido_28 contenido_39)
        (predecesor contenido_62 contenido_79)
        (predecesor contenido_25 contenido_45)
        (predecesor contenido_5 contenido_29)
        (predecesor contenido_98 contenido_102)
        (predecesor contenido_6 contenido_101)
        (predecesor contenido_32 contenido_33)
        (predecesor contenido_60 contenido_85)
        (predecesor contenido_88 contenido_121)
        (predecesor contenido_26 contenido_59)
        (predecesor contenido_9 contenido_83)
        (predecesor contenido_61 contenido_85)
        (predecesor contenido_25 contenido_91)
        (predecesor contenido_4 contenido_103)
        (predecesor contenido_66 contenido_75)
        (predecesor contenido_43 contenido_45)
        (predecesor contenido_16 contenido_106)
        (predecesor contenido_6 contenido_48)
        (predecesor contenido_27 contenido_44)
        (predecesor contenido_11 contenido_13)
        (paralelas_vistas contenido_28)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_95)
        (paralelas_vistas contenido_105)
        (paralelas_vistas contenido_101)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_112)
        (paralelas_vistas contenido_107)
        (paralelas_vistas contenido_6)
        (paralelas_vistas contenido_61)
        (paralelas_vistas contenido_113)
        (paralelas_vistas contenido_41)
        (paralelas_vistas contenido_38)
        (paralelas_vistas contenido_42)
        (paralelas_vistas contenido_56)
        (paralelas_vistas contenido_74)
        (paralelas_vistas contenido_19)
        (paralelas_vistas contenido_84)
        (paralelas_vistas contenido_32)
        (paralelas_vistas contenido_86)
        (paralelas_vistas contenido_26)
        (paralelas_vistas contenido_60)
        (paralelas_vistas contenido_117)
        (paralelas_vistas contenido_114)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_98)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_37)
        (paralelas_vistas contenido_109)
        (paralelas_vistas contenido_36)
        (paralelas_vistas contenido_123)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_125)
        (paralelas_vistas contenido_83)
        (paralelas_vistas contenido_52)
        (paralelas_vistas contenido_78)
        (paralelas_vistas contenido_88)
        (paralelas_vistas contenido_34)
        (paralelas_vistas contenido_104)
        (paralelas_vistas contenido_108)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_48)
        (paralelas_vistas contenido_65)
        (paralelas_vistas contenido_93)
        (paralelas_vistas contenido_63)
        (paralelas_vistas contenido_50)
        (paralelas_vistas contenido_25)
        (paralelas_vistas contenido_64)
        (paralelas_vistas contenido_96)
        (paralelas_vistas contenido_82)
        (paralelas_vistas contenido_76)
        (paralelas_vistas contenido_27)
        (paralelas_vistas contenido_81)
        (paralelas_vistas contenido_122)
        (paralelas_vistas contenido_80)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_70)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_16)
        (paralelas_vistas contenido_31)
        (paralelas_vistas contenido_90)
        (paralelas_vistas contenido_11)
        (paralelas_vistas contenido_47)
        (paralelas_vistas contenido_106)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_29)
        (paralelas_vistas contenido_30)
        (paralelas_vistas contenido_124)
        (paralelas_vistas contenido_77)
        (paralelas_vistas contenido_55)
        (paralelas_vistas contenido_39)
        (paralelas_vistas contenido_97)
        (paralelas_vistas contenido_100)
        (paralelas_vistas contenido_40)
        (paralelas_vistas contenido_62)
        (paralelas_vistas contenido_71)
        (paralelas_vistas contenido_92)
        (paralelas_vistas contenido_35)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_94)
        (paralelas_vistas contenido_121)
        (paralelas_vistas contenido_75)
        (paralelas_vistas contenido_111)
        (paralelas_vistas contenido_118)
        (paralelas_vistas contenido_53)
        (paralelas_vistas contenido_119)
        (paralelas_vistas contenido_89)
        (paralelas_vistas contenido_102)
        (paralelas_vistas contenido_49)
        (paralelas_vistas contenido_57)
        (paralelas_vistas contenido_44)
        (paralelas_vistas contenido_115)
        (paralelas_vistas contenido_43)
        (paralelas_vistas contenido_46)
        (paralelas_vistas contenido_9)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_5)
        (paralelas_vistas contenido_91)
        (paralelas_vistas contenido_103)
        (paralelas_vistas contenido_45)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_110)
        (paralelas_vistas contenido_79)
        (paralelas_vistas contenido_87)
        (paralelas_vistas contenido_69)
        (paralelas_vistas contenido_116)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_99)
        (paralelas_vistas contenido_68)
        (paralelas_vistas contenido_51)
        (paralelas_vistas contenido_59)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_66)
        (paralelas_vistas contenido_85)
        (paralelas_vistas contenido_58)
        (paralelas_vistas contenido_72)
        (paralelas_vistas contenido_73)
        (paralelas_vistas contenido_67)
        (paralelas_vistas contenido_54)
        (paralelas_vistas contenido_120)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_55)
        (predecesores_vistos contenido_95)
        (predecesores_vistos contenido_54)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_110)
        (predecesores_vistos contenido_87)
        (predecesores_vistos contenido_112)
        (predecesores_vistos contenido_109)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_52)
        (predecesores_vistos contenido_71)
        (predecesores_vistos contenido_78)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_41)
        (predecesores_vistos contenido_94)
        (predecesores_vistos contenido_38)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_74)
        (predecesores_vistos contenido_20)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_66)
        (predecesores_vistos contenido_111)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_50)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_53)
        (predecesores_vistos contenido_96)
        (predecesores_vistos contenido_26)
        (predecesores_vistos contenido_82)
        (predecesores_vistos contenido_58)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_60)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_70)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_43)
        (predecesores_vistos contenido_46)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_37)
        (final contenido_2)
        (final contenido_8)
        (final contenido_17)
        (final contenido_20)
        (final contenido_21)
        (final contenido_24)
        (final contenido_29)
        (final contenido_30)
        (final contenido_31)
        (final contenido_35)
        (final contenido_38)
        (final contenido_42)
        (final contenido_44)
        (final contenido_50)
        (final contenido_51)
        (final contenido_53)
        (final contenido_56)
        (final contenido_57)
        (final contenido_59)
        (final contenido_70)
        (final contenido_71)
        (final contenido_72)
        (final contenido_73)
        (final contenido_74)
        (final contenido_76)
        (final contenido_78)
        (final contenido_79)
        (final contenido_80)
        (final contenido_81)
        (final contenido_82)
        (final contenido_83)
        (final contenido_89)
        (final contenido_91)
        (final contenido_93)
        (final contenido_95)
        (final contenido_96)
        (final contenido_97)
        (final contenido_101)
        (final contenido_102)
        (final contenido_103)
        (final contenido_104)
        (final contenido_105)
        (final contenido_106)
        (final contenido_107)
        (final contenido_108)
        (final contenido_109)
        (final contenido_110)
        (final contenido_111)
        (final contenido_115)
        (final contenido_116)
        (final contenido_118)
        (final contenido_119)
        (final contenido_121)
        (final contenido_122)
        (final contenido_123)
        (final contenido_124)
        (final contenido_125)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
