(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50
    )

    (:init
        (predecesor contenido_23 contenido_32)
        (predecesor contenido_23 contenido_50)
        (predecesor contenido_10 contenido_47)
        (predecesor contenido_14 contenido_33)
        (predecesor contenido_15 contenido_33)
        (predecesor contenido_5 contenido_45)
        (predecesor contenido_3 contenido_12)
        (predecesor contenido_6 contenido_45)
        (predecesor contenido_6 contenido_12)
        (predecesor contenido_31 contenido_40)
        (predecesor contenido_6 contenido_26)
        (predecesor contenido_10 contenido_46)
        (predecesor contenido_3 contenido_27)
        (predecesor contenido_3 contenido_37)
        (predecesor contenido_1 contenido_33)
        (predecesor contenido_30 contenido_34)
        (predecesor contenido_29 contenido_47)
        (predecesor contenido_25 contenido_49)
        (predecesor contenido_16 contenido_24)
        (predecesor contenido_3 contenido_43)
        (predecesor contenido_5 contenido_43)
        (predecesor contenido_3 contenido_18)
        (predecesor contenido_27 contenido_28)
        (predecesor contenido_33 contenido_38)
        (predecesor contenido_5 contenido_39)
        (predecesor contenido_21 contenido_29)
        (predecesor contenido_10 contenido_43)
        (predecesor contenido_30 contenido_31)
        (predecesor contenido_7 contenido_26)
        (predecesor contenido_22 contenido_38)
        (predecesor contenido_20 contenido_30)
        (predecesor contenido_3 contenido_31)
        (predecesor contenido_12 contenido_38)
        (predecesor contenido_7 contenido_50)
        (predecesor contenido_4 contenido_5)
        (predecesor contenido_4 contenido_23)
        (predecesor contenido_30 contenido_33)
        (predecesor contenido_31 contenido_43)
        (predecesor contenido_14 contenido_20)
        (predecesor contenido_8 contenido_34)
        (predecesor contenido_6 contenido_38)
        (predecesor contenido_13 contenido_46)
        (predecesor contenido_2 contenido_23)
        (predecesor contenido_1 contenido_22)
        (predecesor contenido_18 contenido_43)
        (paralelas_vistas contenido_42)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_49)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_27)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_44)
        (paralelas_vistas contenido_50)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_32)
        (paralelas_vistas contenido_30)
        (paralelas_vistas contenido_36)
        (paralelas_vistas contenido_9)
        (paralelas_vistas contenido_40)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_46)
        (paralelas_vistas contenido_25)
        (paralelas_vistas contenido_48)
        (paralelas_vistas contenido_5)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_28)
        (paralelas_vistas contenido_34)
        (paralelas_vistas contenido_43)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_31)
        (paralelas_vistas contenido_47)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_16)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_41)
        (paralelas_vistas contenido_29)
        (paralelas_vistas contenido_45)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_6)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_35)
        (paralelas_vistas contenido_19)
        (paralelas_vistas contenido_38)
        (paralelas_vistas contenido_11)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_26)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_39)
        (paralelas_vistas contenido_37)
        (predecesores_vistos contenido_42)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_36)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_48)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_41)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_35)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_13)
        (final contenido_9)
        (final contenido_11)
        (final contenido_17)
        (final contenido_19)
        (final contenido_24)
        (final contenido_26)
        (final contenido_28)
        (final contenido_32)
        (final contenido_34)
        (final contenido_35)
        (final contenido_36)
        (final contenido_37)
        (final contenido_38)
        (final contenido_39)
        (final contenido_40)
        (final contenido_41)
        (final contenido_42)
        (final contenido_43)
        (final contenido_44)
        (final contenido_45)
        (final contenido_46)
        (final contenido_47)
        (final contenido_48)
        (final contenido_49)
        (final contenido_50)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
