(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25
    )

    (:init
        (predecesor contenido_3 contenido_22)
        (predecesor contenido_3 contenido_19)
        (predecesor contenido_1 contenido_17)
        (predecesor contenido_15 contenido_17)
        (predecesor contenido_4 contenido_25)
        (predecesor contenido_3 contenido_6)
        (predecesor contenido_17 contenido_19)
        (predecesor contenido_16 contenido_22)
        (predecesor contenido_2 contenido_9)
        (predecesor contenido_2 contenido_3)
        (predecesor contenido_1 contenido_12)
        (predecesor contenido_9 contenido_22)
        (predecesor contenido_4 contenido_17)
        (predecesor contenido_2 contenido_22)
        (predecesor contenido_3 contenido_20)
        (predecesor contenido_12 contenido_25)
        (predecesor contenido_1 contenido_11)
        (predecesor contenido_5 contenido_22)
        (predecesor contenido_2 contenido_14)
        (predecesor contenido_5 contenido_23)
        (predecesor contenido_10 contenido_15)
        (predecesor contenido_16 contenido_20)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_5)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_19)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_16)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_6)
        (paralelas_vistas contenido_9)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_25)
        (paralelas_vistas contenido_11)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_4)
        (final contenido_6)
        (final contenido_7)
        (final contenido_8)
        (final contenido_11)
        (final contenido_13)
        (final contenido_14)
        (final contenido_18)
        (final contenido_19)
        (final contenido_20)
        (final contenido_21)
        (final contenido_22)
        (final contenido_23)
        (final contenido_24)
        (final contenido_25)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
