(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35 contenido_36 contenido_37 contenido_38 contenido_39 contenido_40 contenido_41 contenido_42 contenido_43 contenido_44 contenido_45 contenido_46 contenido_47 contenido_48 contenido_49 contenido_50 contenido_51 contenido_52 contenido_53 contenido_54 contenido_55 contenido_56 contenido_57 contenido_58 contenido_59 contenido_60 contenido_61 contenido_62 contenido_63 contenido_64 contenido_65 contenido_66 contenido_67 contenido_68 contenido_69 contenido_70 contenido_71 contenido_72 contenido_73 contenido_74 contenido_75 contenido_76 contenido_77 contenido_78 contenido_79 contenido_80 contenido_81 contenido_82 contenido_83 contenido_84 contenido_85 contenido_86 contenido_87 contenido_88 contenido_89 contenido_90 contenido_91 contenido_92 contenido_93 contenido_94 contenido_95 contenido_96 contenido_97 contenido_98 contenido_99 contenido_100 contenido_101 contenido_102 contenido_103 contenido_104 contenido_105 contenido_106 contenido_107 contenido_108 contenido_109 contenido_110 contenido_111 contenido_112 contenido_113 contenido_114 contenido_115 contenido_116 contenido_117 contenido_118 contenido_119 contenido_120 contenido_121 contenido_122 contenido_123 contenido_124 contenido_125 contenido_126 contenido_127 contenido_128 contenido_129 contenido_130 contenido_131 contenido_132 contenido_133 contenido_134 contenido_135 contenido_136 contenido_137 contenido_138 contenido_139 contenido_140 contenido_141 contenido_142 contenido_143 contenido_144 contenido_145 contenido_146 contenido_147 contenido_148 contenido_149 contenido_150
    )

    (:init
        (predecesor contenido_18 contenido_38)
        (predecesor contenido_17 contenido_139)
        (predecesor contenido_135 contenido_150)
        (predecesor contenido_10 contenido_12)
        (predecesor contenido_83 contenido_118)
        (predecesor contenido_5 contenido_8)
        (predecesor contenido_2 contenido_24)
        (predecesor contenido_90 contenido_127)
        (predecesor contenido_57 contenido_90)
        (predecesor contenido_91 contenido_105)
        (predecesor contenido_77 contenido_110)
        (predecesor contenido_41 contenido_42)
        (predecesor contenido_5 contenido_150)
        (predecesor contenido_39 contenido_137)
        (predecesor contenido_10 contenido_56)
        (predecesor contenido_17 contenido_78)
        (predecesor contenido_67 contenido_148)
        (predecesor contenido_41 contenido_73)
        (predecesor contenido_37 contenido_129)
        (predecesor contenido_81 contenido_133)
        (predecesor contenido_48 contenido_83)
        (predecesor contenido_27 contenido_125)
        (predecesor contenido_23 contenido_132)
        (predecesor contenido_128 contenido_141)
        (predecesor contenido_37 contenido_79)
        (predecesor contenido_26 contenido_102)
        (predecesor contenido_137 contenido_147)
        (predecesor contenido_9 contenido_60)
        (predecesor contenido_74 contenido_102)
        (predecesor contenido_75 contenido_93)
        (predecesor contenido_120 contenido_122)
        (predecesor contenido_125 contenido_149)
        (predecesor contenido_18 contenido_95)
        (predecesor contenido_8 contenido_120)
        (predecesor contenido_11 contenido_111)
        (predecesor contenido_83 contenido_88)
        (predecesor contenido_50 contenido_89)
        (predecesor contenido_44 contenido_113)
        (predecesor contenido_72 contenido_106)
        (predecesor contenido_50 contenido_114)
        (predecesor contenido_13 contenido_120)
        (predecesor contenido_12 contenido_15)
        (predecesor contenido_76 contenido_134)
        (predecesor contenido_54 contenido_98)
        (predecesor contenido_78 contenido_109)
        (predecesor contenido_140 contenido_143)
        (predecesor contenido_12 contenido_121)
        (predecesor contenido_77 contenido_102)
        (predecesor contenido_1 contenido_140)
        (predecesor contenido_5 contenido_55)
        (predecesor contenido_144 contenido_145)
        (predecesor contenido_37 contenido_122)
        (predecesor contenido_94 contenido_122)
        (predecesor contenido_64 contenido_74)
        (predecesor contenido_31 contenido_136)
        (predecesor contenido_11 contenido_46)
        (predecesor contenido_76 contenido_110)
        (predecesor contenido_8 contenido_92)
        (predecesor contenido_51 contenido_141)
        (predecesor contenido_16 contenido_23)
        (predecesor contenido_91 contenido_112)
        (predecesor contenido_63 contenido_66)
        (predecesor contenido_96 contenido_107)
        (predecesor contenido_40 contenido_83)
        (predecesor contenido_8 contenido_102)
        (predecesor contenido_3 contenido_75)
        (predecesor contenido_91 contenido_140)
        (predecesor contenido_103 contenido_123)
        (predecesor contenido_82 contenido_148)
        (predecesor contenido_20 contenido_143)
        (predecesor contenido_31 contenido_140)
        (predecesor contenido_11 contenido_96)
        (predecesor contenido_7 contenido_89)
        (predecesor contenido_72 contenido_138)
        (predecesor contenido_86 contenido_101)
        (predecesor contenido_13 contenido_43)
        (predecesor contenido_53 contenido_78)
        (predecesor contenido_1 contenido_19)
        (predecesor contenido_50 contenido_116)
        (predecesor contenido_107 contenido_112)
        (predecesor contenido_38 contenido_140)
        (predecesor contenido_18 contenido_84)
        (predecesor contenido_17 contenido_36)
        (predecesor contenido_71 contenido_135)
        (predecesor contenido_43 contenido_130)
        (predecesor contenido_79 contenido_112)
        (predecesor contenido_89 contenido_134)
        (predecesor contenido_22 contenido_26)
        (predecesor contenido_60 contenido_74)
        (predecesor contenido_133 contenido_146)
        (predecesor contenido_4 contenido_129)
        (predecesor contenido_28 contenido_121)
        (predecesor contenido_30 contenido_97)
        (predecesor contenido_8 contenido_41)
        (predecesor contenido_23 contenido_82)
        (predecesor contenido_118 contenido_122)
        (predecesor contenido_38 contenido_56)
        (predecesor contenido_32 contenido_48)
        (predecesor contenido_16 contenido_91)
        (predecesor contenido_14 contenido_90)
        (predecesor contenido_45 contenido_150)
        (predecesor contenido_19 contenido_137)
        (predecesor contenido_28 contenido_41)
        (predecesor contenido_123 contenido_128)
        (predecesor contenido_95 contenido_138)
        (predecesor contenido_67 contenido_109)
        (predecesor contenido_3 contenido_81)
        (predecesor contenido_98 contenido_127)
        (predecesor contenido_17 contenido_150)
        (predecesor contenido_52 contenido_68)
        (predecesor contenido_24 contenido_67)
        (predecesor contenido_34 contenido_66)
        (predecesor contenido_29 contenido_136)
        (predecesor contenido_36 contenido_137)
        (predecesor contenido_53 contenido_87)
        (predecesor contenido_82 contenido_114)
        (predecesor contenido_2 contenido_86)
        (predecesor contenido_88 contenido_150)
        (predecesor contenido_70 contenido_143)
        (predecesor contenido_103 contenido_145)
        (predecesor contenido_5 contenido_89)
        (predecesor contenido_57 contenido_130)
        (predecesor contenido_93 contenido_96)
        (predecesor contenido_85 contenido_90)
        (predecesor contenido_50 contenido_118)
        (predecesor contenido_91 contenido_104)
        (predecesor contenido_85 contenido_145)
        (predecesor contenido_14 contenido_20)
        (predecesor contenido_21 contenido_102)
        (predecesor contenido_52 contenido_117)
        (predecesor contenido_19 contenido_81)
        (predecesor contenido_75 contenido_77)
        (predecesor contenido_97 contenido_102)
        (predecesor contenido_73 contenido_82)
        (predecesor contenido_79 contenido_118)
        (paralelas_vistas contenido_102)
        (paralelas_vistas contenido_106)
        (paralelas_vistas contenido_49)
        (paralelas_vistas contenido_136)
        (paralelas_vistas contenido_56)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_40)
        (paralelas_vistas contenido_122)
        (paralelas_vistas contenido_125)
        (paralelas_vistas contenido_139)
        (paralelas_vistas contenido_5)
        (paralelas_vistas contenido_65)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_84)
        (paralelas_vistas contenido_123)
        (paralelas_vistas contenido_19)
        (paralelas_vistas contenido_73)
        (paralelas_vistas contenido_76)
        (paralelas_vistas contenido_31)
        (paralelas_vistas contenido_42)
        (paralelas_vistas contenido_60)
        (paralelas_vistas contenido_94)
        (paralelas_vistas contenido_114)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_89)
        (paralelas_vistas contenido_99)
        (paralelas_vistas contenido_137)
        (paralelas_vistas contenido_117)
        (paralelas_vistas contenido_129)
        (paralelas_vistas contenido_145)
        (paralelas_vistas contenido_64)
        (paralelas_vistas contenido_105)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_74)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_143)
        (paralelas_vistas contenido_120)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_25)
        (paralelas_vistas contenido_52)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_92)
        (paralelas_vistas contenido_55)
        (paralelas_vistas contenido_30)
        (paralelas_vistas contenido_132)
        (paralelas_vistas contenido_142)
        (paralelas_vistas contenido_121)
        (paralelas_vistas contenido_35)
        (paralelas_vistas contenido_51)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_97)
        (paralelas_vistas contenido_135)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_101)
        (paralelas_vistas contenido_83)
        (paralelas_vistas contenido_116)
        (paralelas_vistas contenido_54)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_133)
        (paralelas_vistas contenido_37)
        (paralelas_vistas contenido_88)
        (paralelas_vistas contenido_131)
        (paralelas_vistas contenido_126)
        (paralelas_vistas contenido_109)
        (paralelas_vistas contenido_148)
        (paralelas_vistas contenido_9)
        (paralelas_vistas contenido_63)
        (paralelas_vistas contenido_86)
        (paralelas_vistas contenido_27)
        (paralelas_vistas contenido_91)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_93)
        (paralelas_vistas contenido_104)
        (paralelas_vistas contenido_96)
        (paralelas_vistas contenido_100)
        (paralelas_vistas contenido_144)
        (paralelas_vistas contenido_36)
        (paralelas_vistas contenido_68)
        (paralelas_vistas contenido_6)
        (paralelas_vistas contenido_69)
        (paralelas_vistas contenido_80)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_50)
        (paralelas_vistas contenido_124)
        (paralelas_vistas contenido_118)
        (paralelas_vistas contenido_59)
        (paralelas_vistas contenido_82)
        (paralelas_vistas contenido_11)
        (paralelas_vistas contenido_16)
        (paralelas_vistas contenido_48)
        (paralelas_vistas contenido_78)
        (paralelas_vistas contenido_95)
        (paralelas_vistas contenido_34)
        (paralelas_vistas contenido_149)
        (paralelas_vistas contenido_115)
        (paralelas_vistas contenido_28)
        (paralelas_vistas contenido_113)
        (paralelas_vistas contenido_79)
        (paralelas_vistas contenido_71)
        (paralelas_vistas contenido_67)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_57)
        (paralelas_vistas contenido_58)
        (paralelas_vistas contenido_130)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_41)
        (paralelas_vistas contenido_77)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_147)
        (paralelas_vistas contenido_141)
        (paralelas_vistas contenido_134)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_29)
        (paralelas_vistas contenido_146)
        (paralelas_vistas contenido_39)
        (paralelas_vistas contenido_138)
        (paralelas_vistas contenido_85)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_128)
        (paralelas_vistas contenido_47)
        (paralelas_vistas contenido_119)
        (paralelas_vistas contenido_140)
        (paralelas_vistas contenido_111)
        (paralelas_vistas contenido_72)
        (paralelas_vistas contenido_103)
        (paralelas_vistas contenido_108)
        (paralelas_vistas contenido_44)
        (paralelas_vistas contenido_110)
        (paralelas_vistas contenido_61)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_46)
        (paralelas_vistas contenido_107)
        (paralelas_vistas contenido_127)
        (paralelas_vistas contenido_70)
        (paralelas_vistas contenido_32)
        (paralelas_vistas contenido_62)
        (paralelas_vistas contenido_66)
        (paralelas_vistas contenido_75)
        (paralelas_vistas contenido_150)
        (paralelas_vistas contenido_87)
        (paralelas_vistas contenido_98)
        (paralelas_vistas contenido_38)
        (paralelas_vistas contenido_112)
        (paralelas_vistas contenido_53)
        (paralelas_vistas contenido_43)
        (paralelas_vistas contenido_81)
        (paralelas_vistas contenido_45)
        (paralelas_vistas contenido_90)
        (paralelas_vistas contenido_26)
        (predecesores_vistos contenido_72)
        (predecesores_vistos contenido_80)
        (predecesores_vistos contenido_103)
        (predecesores_vistos contenido_25)
        (predecesores_vistos contenido_49)
        (predecesores_vistos contenido_50)
        (predecesores_vistos contenido_52)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_108)
        (predecesores_vistos contenido_124)
        (predecesores_vistos contenido_59)
        (predecesores_vistos contenido_30)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_44)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_40)
        (predecesores_vistos contenido_34)
        (predecesores_vistos contenido_61)
        (predecesores_vistos contenido_142)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_5)
        (predecesores_vistos contenido_35)
        (predecesores_vistos contenido_51)
        (predecesores_vistos contenido_65)
        (predecesores_vistos contenido_115)
        (predecesores_vistos contenido_28)
        (predecesores_vistos contenido_70)
        (predecesores_vistos contenido_22)
        (predecesores_vistos contenido_32)
        (predecesores_vistos contenido_21)
        (predecesores_vistos contenido_71)
        (predecesores_vistos contenido_18)
        (predecesores_vistos contenido_17)
        (predecesores_vistos contenido_119)
        (predecesores_vistos contenido_62)
        (predecesores_vistos contenido_54)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_57)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_58)
        (predecesores_vistos contenido_33)
        (predecesores_vistos contenido_76)
        (predecesores_vistos contenido_31)
        (predecesores_vistos contenido_37)
        (predecesores_vistos contenido_131)
        (predecesores_vistos contenido_94)
        (predecesores_vistos contenido_126)
        (predecesores_vistos contenido_7)
        (predecesores_vistos contenido_99)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_63)
        (predecesores_vistos contenido_27)
        (predecesores_vistos contenido_39)
        (predecesores_vistos contenido_53)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_85)
        (predecesores_vistos contenido_100)
        (predecesores_vistos contenido_144)
        (predecesores_vistos contenido_64)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_47)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_45)
        (predecesores_vistos contenido_6)
        (predecesores_vistos contenido_69)
        (final contenido_6)
        (final contenido_15)
        (final contenido_25)
        (final contenido_33)
        (final contenido_35)
        (final contenido_42)
        (final contenido_46)
        (final contenido_47)
        (final contenido_49)
        (final contenido_55)
        (final contenido_56)
        (final contenido_58)
        (final contenido_59)
        (final contenido_61)
        (final contenido_62)
        (final contenido_65)
        (final contenido_66)
        (final contenido_68)
        (final contenido_69)
        (final contenido_80)
        (final contenido_84)
        (final contenido_87)
        (final contenido_92)
        (final contenido_99)
        (final contenido_100)
        (final contenido_101)
        (final contenido_102)
        (final contenido_104)
        (final contenido_105)
        (final contenido_106)
        (final contenido_108)
        (final contenido_109)
        (final contenido_110)
        (final contenido_111)
        (final contenido_112)
        (final contenido_113)
        (final contenido_114)
        (final contenido_115)
        (final contenido_116)
        (final contenido_117)
        (final contenido_119)
        (final contenido_121)
        (final contenido_122)
        (final contenido_124)
        (final contenido_126)
        (final contenido_127)
        (final contenido_129)
        (final contenido_130)
        (final contenido_131)
        (final contenido_132)
        (final contenido_134)
        (final contenido_136)
        (final contenido_138)
        (final contenido_139)
        (final contenido_141)
        (final contenido_142)
        (final contenido_143)
        (final contenido_145)
        (final contenido_146)
        (final contenido_147)
        (final contenido_148)
        (final contenido_149)
        (final contenido_150)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
