(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15 contenido_16 contenido_17 contenido_18 contenido_19 contenido_20 contenido_21 contenido_22 contenido_23 contenido_24 contenido_25 contenido_26 contenido_27 contenido_28 contenido_29 contenido_30 contenido_31 contenido_32 contenido_33 contenido_34 contenido_35
    )

    (:init
        (predecesor contenido_5 contenido_17)
        (predecesor contenido_4 contenido_5)
        (predecesor contenido_2 contenido_23)
        (predecesor contenido_3 contenido_25)
        (predecesor contenido_10 contenido_31)
        (predecesor contenido_11 contenido_18)
        (predecesor contenido_5 contenido_35)
        (predecesor contenido_23 contenido_32)
        (predecesor contenido_29 contenido_34)
        (predecesor contenido_10 contenido_30)
        (predecesor contenido_5 contenido_20)
        (predecesor contenido_3 contenido_18)
        (predecesor contenido_10 contenido_20)
        (predecesor contenido_6 contenido_33)
        (predecesor contenido_13 contenido_30)
        (predecesor contenido_7 contenido_23)
        (predecesor contenido_1 contenido_22)
        (predecesor contenido_1 contenido_33)
        (predecesor contenido_15 contenido_33)
        (predecesor contenido_3 contenido_27)
        (predecesor contenido_10 contenido_21)
        (predecesor contenido_12 contenido_18)
        (predecesor contenido_5 contenido_14)
        (predecesor contenido_5 contenido_28)
        (predecesor contenido_22 contenido_30)
        (predecesor contenido_6 contenido_21)
        (predecesor contenido_1 contenido_6)
        (predecesor contenido_12 contenido_27)
        (predecesor contenido_3 contenido_6)
        (predecesor contenido_20 contenido_30)
        (predecesor contenido_6 contenido_26)
        (paralelas_vistas contenido_26)
        (paralelas_vistas contenido_17)
        (paralelas_vistas contenido_11)
        (paralelas_vistas contenido_9)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_33)
        (paralelas_vistas contenido_29)
        (paralelas_vistas contenido_5)
        (paralelas_vistas contenido_32)
        (paralelas_vistas contenido_31)
        (paralelas_vistas contenido_34)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_23)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_25)
        (paralelas_vistas contenido_6)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_22)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_20)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_19)
        (paralelas_vistas contenido_27)
        (paralelas_vistas contenido_35)
        (paralelas_vistas contenido_24)
        (paralelas_vistas contenido_21)
        (paralelas_vistas contenido_7)
        (paralelas_vistas contenido_28)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_18)
        (paralelas_vistas contenido_30)
        (paralelas_vistas contenido_16)
        (predecesores_vistos contenido_29)
        (predecesores_vistos contenido_12)
        (predecesores_vistos contenido_10)
        (predecesores_vistos contenido_16)
        (predecesores_vistos contenido_8)
        (predecesores_vistos contenido_11)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_13)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_9)
        (predecesores_vistos contenido_19)
        (predecesores_vistos contenido_3)
        (predecesores_vistos contenido_15)
        (predecesores_vistos contenido_24)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_7)
        (final contenido_8)
        (final contenido_9)
        (final contenido_14)
        (final contenido_16)
        (final contenido_17)
        (final contenido_18)
        (final contenido_19)
        (final contenido_21)
        (final contenido_24)
        (final contenido_25)
        (final contenido_26)
        (final contenido_27)
        (final contenido_28)
        (final contenido_30)
        (final contenido_31)
        (final contenido_32)
        (final contenido_33)
        (final contenido_34)
        (final contenido_35)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
