(define (problem problema_generado)

    (:domain SeriesPelisExt3)

    (:objects
        contenido_1 contenido_2 contenido_3 contenido_4 contenido_5 contenido_6 contenido_7 contenido_8 contenido_9 contenido_10 contenido_11 contenido_12 contenido_13 contenido_14 contenido_15
    )

    (:init
        (predecesor contenido_1 contenido_13)
        (predecesor contenido_2 contenido_11)
        (predecesor contenido_9 contenido_10)
        (predecesor contenido_8 contenido_11)
        (predecesor contenido_8 contenido_9)
        (predecesor contenido_1 contenido_5)
        (predecesor contenido_11 contenido_12)
        (predecesor contenido_5 contenido_8)
        (predecesor contenido_2 contenido_3)
        (predecesor contenido_3 contenido_12)
        (predecesor contenido_2 contenido_15)
        (predecesor contenido_2 contenido_13)
        (predecesor contenido_2 contenido_10)
        (predecesor contenido_8 contenido_10)
        (predecesor contenido_1 contenido_6)
        (paralelas_vistas contenido_8)
        (paralelas_vistas contenido_15)
        (paralelas_vistas contenido_1)
        (paralelas_vistas contenido_4)
        (paralelas_vistas contenido_9)
        (paralelas_vistas contenido_10)
        (paralelas_vistas contenido_11)
        (paralelas_vistas contenido_5)
        (paralelas_vistas contenido_3)
        (paralelas_vistas contenido_6)
        (paralelas_vistas contenido_2)
        (paralelas_vistas contenido_12)
        (paralelas_vistas contenido_13)
        (paralelas_vistas contenido_14)
        (paralelas_vistas contenido_7)
        (predecesores_vistos contenido_1)
        (predecesores_vistos contenido_4)
        (predecesores_vistos contenido_2)
        (predecesores_vistos contenido_14)
        (predecesores_vistos contenido_7)
        (final contenido_4)
        (final contenido_6)
        (final contenido_7)
        (final contenido_10)
        (final contenido_12)
        (final contenido_13)
        (final contenido_14)
        (final contenido_15)
        (paralelas_ok)
        (= (contenidos_vistos) 0)
    )

    (:goal 
        (forall (?c) (visto ?c))
    )
)
